### ISSUE TITLE
Couldn't open file ubuntu-14.04.5-server-amd64 while adding app-server

### ISSUE THREAD

**Issue by melviii100** [hashicorp/vagrant#9132] opened 2017-11-02 04:35 UTC
I installed Virtulabox, packer and vagrant.
Now when I run below command I get error.
`$ vagrant box add ubuntu-14.04.5-server-amd64-appserver_virtualbox.box --name devops-appserver`

```
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'devops-appserver' (v0) for provider: 
    box: Downloading: ubuntu-14.04.5-server-amd64-appserver_virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
Couldn't open file ubuntu-14.04.5-server-amd64-appserver_virtualbox.box
```
I found a fix [here](https://github.com/udacity/devops-intro-project/issues/24), so I changed Ubuntu version to - ubuntu-14.04.5-server-amd64 . 

But not able to execute the command.

**Comment by briancain** [comment] 2017-11-02 15:38
Hi @melviii100 - It looks like you attempted to add a vagrant box that did not exist on your filesystem. Are you sure you have that box located on your computer?

**Comment by melviii100** [comment] 2017-11-03 05:28
No that is not in my system. First it failed to download the box then when it tried to access it again failed. 
I was following This tutorial : https://github.com/udacity/devops-intro-project

I thought vagrant simplifies the installation pain, but this gives me more head ache!!!!!!

**Comment by briancain** [comment] 2017-11-03 15:51
Hi @melviii100 - You are receiving that error message because you do not have that box on disk, and the box you are attempting to use does not exist on Vagrant Cloud, so there was an error trying to download a box that doesn't exist. I recommend re-reading part 1 which explains how to build a vagrant box with packer and add it to vagrant. Following those steps will fix your issue: https://github.com/udacity/devops-intro-project#part-i-building-a-box-with-packer

I'm going to go ahead and close this, since this is expected behavior of Vagrant.

**Closed by briancain** 2017-11-03 15:51 UTC
Labels: waiting-reply

**Comment by wowpavan** [comment] 2018-02-15 02:36
$ vagrant box add ubuntu-14.04.5-server-adm64-appserver_virtualbox.box --name devops-appserver
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): file:///C:/Users/wowpavan/devops/packer-templates/virtualbox/ubuntu-14.04.5-server-adm64-appserver_virtualbox.box (URI::InvalidURIError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:485:in `metadata_url?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:91:in `block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:89:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:89:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/commands/box/command/add.rb:78:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/commands/box/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/cli.rb:46:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:269:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:151:in `<main>'
