### ISSUE TITLE
Unexpected token error in ruby file on 'vagrant up'.

### ISSUE THREAD

**Issue by DonaldPeat** [hashicorp/vagrant#9057] opened 2017-10-13 18:09 UTC
**Vagrant version**
1.9.2

**Host operating system**
Windows 10

**Guest operating system**
Ubuntu 16.04.1 

**Vagrantfile**
```ruby
# -*- mode: ruby -*-

dir = File.dirname(File.expand_path(__FILE__))

require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"
require "#{dir}/puphpet/ruby/puppet.rb"

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end

if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']

Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end

```

**Debug output**
https://gist.github.com/DonaldPeat/f637afb781d4d3e8fb72e06465d664cd

**Expected behavior
What should have happened?**
vm starts up, runs & server accessible at awesome.dev

**Actual behavior
What actually happened?**
vm starts up & according to virtual box app is running but server not accessible at awesome.dev

**Comment by briancain** [comment] 2017-10-16 16:19
Hi @DonaldPeat - can you please provide the contents of `"#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}"`, I believe that is what actually contains the vagrant config causing the error. Thanks!

**Comment by DonaldPeat** [comment] 2017-10-17 17:27
A co-worker had the same issue when upgrading php versions.  I've since created a new vagrant server that is working but still curious what caused this error. 

Here is [/puphet/vagrant/Vagrantfile-local](https://gist.github.com/DonaldPeat/925cf2c7ff1a15b28b02cf705877ef65)

**Comment by briancain** [comment] 2017-10-17 18:17
@DonaldPeat From just looking at your Vagrantfile, it looks like at some point you're trying to create a synced_folder option that could be empty. I recommend trying to trim down your Vagrantfile to see if you can produce the error with the minimum configuration. Vagrant saves these options as a json file on disk, and since you're dynamically creating these synced_folders with various settings set as variables, I suspect at some point in one of your loops a variable is set to empty string.

**Comment by chrisroberts** [comment] 2017-10-25 21:28
Closing this as the issue is resolved. Cheers!

**Closed by chrisroberts** 2017-10-25 21:28 UTC
Labels: waiting-reply
