### ISSUE TITLE
vagrant up fails or doesn't boot up the VM on Virtual Box on Windows 10/11 (--type headless is causing the issue)

### ISSUE THREAD

**Issue by skeeith** [hashicorp/vagrant#12931] opened 2022-10-02 18:13 UTC
### Debug output
vagrant up --debug output
https://gist.github.com/skeeith/7a99c1308af668250e0523455798c403

VBoxSVC.log file
https://gist.github.com/skeeith/970c2245c1ad45726684fd45ca2391fa

### Expected behavior
Just boots the VM normally

### Actual behavior
Stuck on `Booting VM`

### Reproduction information
install Virtual Box v6.1.38 and Vagrant v2.3.0 on Windows 10/11

#### Vagrant version
Version 2.3.0

#### Host operating system
Windows 11

#### Guest operating system
Ubuntu 20.04 LTS

#### Steps to reproduce

1. vagrant up
2.
3.

#### Reference Issue
https://github.com/hashicorp/vagrant/issues/12897

**Comment by chrisroberts** [comment] 2022-10-03 17:28
Duplicate of #12897

**Closed by chrisroberts** 2022-10-03 17:28 UTC
Labels: bug, provider/virtualbox, needs-investigation
