### ISSUE TITLE
Cannot start linux OpenStack instance on Vagrant 2.2.15

### ISSUE THREAD

**Issue by mducle** [hashicorp/vagrant#12276] opened 2021-04-05 19:49 UTC
### Vagrant version

Vagrant 2.2.15

### Host operating system

Ubuntu 18.04 LTS

### Guest operating system

Ubuntu 18.04 LTS

### Vagrantfile

```ruby
require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|
    config.ssh.username = "vagrant"
    config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"
    config.vm.define "linux" do |linux|
        linux.vm.provider "openstack" do |os|
            os.openstack_auth_url = "https://<openstackserver>:5000/v3"
            os.identity_api_version = "3"
            os.project_name = "Project"
            os.project_domain_name = "default"
            os.user_domain_name = "domain"
            os.username = ENV['OS_USERNAME']
            os.password = ENV['OS_PASSWORD']
            os.region = "RegionOne"
            os.flavor = "m3.small"
            os.image = "linux_runner"
            os.availability_zone = "ceph"
            os.keypair_name = "vagrant_insecure"
        end
        # NFS folder syncing doesn't work on qemu and rsync can be slow
        linux.vm.synced_folder ".", "/vagrant", type: "rsync"
        linux.vm.provision :shell, path: 'bootstrap_linux.sh'
    end
end
```

### Debug output

https://gist.github.com/mducle/3e10e510a0ea7a86a2bb2d6d5cadc768

There are two gists there - a short version (bottom of the page) and one with `VAGRANT_OPENSTACK_LOG` set (very long, redacted and at top).

### Expected behavior

Instance starts and vagrant can provision it (works on 2.2.14)

### Actual behavior

Instance starts but vagrant fails to log in via ssh to provision it.
The error refers to Fedora, but the guest is Ubuntu - is there some new flag?

### Steps to reproduce

1. Create an Ubuntu image on OpenStack
2. Try to use Vagrant to start it up using the OpenStack plugin.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by soapy1** [comment] 2021-04-05 20:51
Hey there,
thanks for opening up an issue. This is a duplicate of https://github.com/hashicorp/vagrant/issues/12265, resolved by https://github.com/hashicorp/vagrant/pull/12275

**Closed by soapy1** 2021-04-05 20:51 UTC
