### ISSUE TITLE
Possible to vagrant powershell with new open source PowerShell client?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9476] opened 2018-02-16 18:21 UTC
Now that Microsoft has open sourced PowerShell, is it possible for non-Windows hosts to `vagrant powershell`, or does some part of the machinery still require a full Windows host?

https://github.com/PowerShell/PowerShell

**Comment by briancain** [comment] 2018-02-20 21:22
It might be possible in theory, however it does not work right now in Vagrant and would take some development and testing to make that functional.

**Comment by briancain** [comment] 2018-02-28 22:23
Duplicate of #7849

Closing.

**Closed by briancain** 2018-02-28 22:23 UTC
Labels: enhancement
