### ISSUE TITLE
Can't `vagrant reload` on Mojave + NFS

### ISSUE THREAD

**Issue by PapyDanone** [hashicorp/vagrant#10340] opened 2018-10-26 20:13 UTC
### Vagrant version
Vagrant 2.2.0

### Host operating system
MacOS Mojave 0.14

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 15672, host: 15672
  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "", "/vagrant", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook/local.yml"
    ansible.limit = 'all'
    ansible.inventory_path = "hosts"
    ansible.compatibility_mode = "2.0"
  end
end
```

### Debug output
https://gist.github.com/PapyDanone/a67defe135497039fb933094193d0bee

### Expected behavior
I should be able to `vagrant reload` or `vagrant up` when machine was shut down after `vagrant halt`

### Actual behavior

The initial `vagrant up` works perfectly (see success output in Gist), with SSH key properly injected in `authorized_keys`. On subsequent boot ups, SSH authentication seems to fail many times. Eventually it stops and the VM can be SSH'd into, but the local volume isn't mounted and the site can't be accessed.

The only way for me to keep working at this point is to `vagrant destroy + up` again. Also note that I have been working with this setup for months, but it stopped working right after I upgraded from High Sierra to Mojave.

### Steps to reproduce
1.  Fresh install of VirtualBox + Vagrant, 
2. `vagrant up` (works 👍 )
3. `vagrant reload` (fails 👎 )

### References
https://github.com/hashicorp/vagrant/issues/10234: I originally thought this was related, but I was able to give full access to the Terminal app as recommended in this thread. As a result I am not getting errors involving `/etc/exports` as seems to be the case in there.

**Comment by briancain** [comment] 2018-10-26 20:49
Hey there @PapyDanone - This is actually a duplicate of issue https://github.com/hashicorp/vagrant/issues/9981. Unfortunetly I think it's related to an issue in systemd-networkd. I haven't had an issue with ubuntu 16.04, so trying with that would resolve your issue. I'm going to close this as a duplicate though, thanks!

**Closed by briancain** 2018-10-26 20:49 UTC

**Comment by briancain** [comment] 2018-10-26 21:02
@PapyDanone - I forgot to mention, you should also be able to use Ubuntu 18.04 if you set a static IP rather than relying on DHCP.

**Comment by PapyDanone** [comment] 2018-10-27 16:55
Thanks so much @briancain, this was driving me crazy. Setting a static IP fixed it.
