### ISSUE TITLE
"Vagrant could not detect VirtualBox!" on Linux

### ISSUE THREAD

**Issue by Asuza** [hashicorp/vagrant#9121] opened 2017-10-29 06:00 UTC
The error is as follows:
```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

However, I can do `which VBoxManage` and the result is `/usr/bin/VBoxManage`. After echoing my `$PATH`, it shows `/usr/bin` listed (for both my own user, and root). I have no idea why vagrant can't find it.

I tried uninstalling VirtualBox and re-installing it with no change.

### Vagrant version
Vagrant 2.0.0
Vagrant 2.0.1

### Host operating system
Ubuntu 17.10

### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 8080, host: 4000
end
```

### Debug output
https://gist.github.com/Asuza/c5c7392d5f7292899231923acb2520b4

### Expected behavior
vagrant should find virtualbox and start up as usual

### Actual behavior
vagrant could not find virtualbox, or VBoxManage, despite it being in the path.

### Steps to reproduce
1. `vagrant up`

**Comment by MassiveHiggsField** [comment] 2017-10-30 21:25
See here for possible fix https://github.com/hashicorp/vagrant/issues/9090

**Comment by MassiveHiggsField** [comment] 2017-10-30 21:29
I think this can be closed as duplicate. The problem is already fixed, just waiting to be released. For now, one can fix this by editing one file in the package (see: https://github.com/hashicorp/vagrant/issues/9090#issuecomment-339935445 )

**Comment by briancain** [comment] 2017-10-30 21:34
Hi @MassiveHiggsField - I think this is a separate issue. the linked issue is about VirtualBox 5.2 support, where as this seems to be an issue with vagrant not being able to find the vboxmanage binary on the path.

**Comment by kikitux** [comment] 2017-10-30 21:47
@Asuza can you provide a bit more information.

Whats the outout of:

```
ls -al /usr/bin/VBox*
id
echo ${PATH}
echo $(which VBoxManage)
```

Thanks

**Comment by Asuza** [comment] 2017-10-30 23:47
@kikitux, here's the output:
```
~ ▶︎︎ ls -al /usr/bin/VBox*
lrwxrwxrwx 1 root root 27 Oct 17 01:50 /usr/bin/VBoxBalloonCtrl -> ../share/virtualbox/VBox.sh*
lrwxrwxrwx 1 root root 27 Oct 17 01:50 /usr/bin/VBoxHeadless -> ../share/virtualbox/VBox.sh*
lrwxrwxrwx 1 root root 27 Oct 17 01:50 /usr/bin/VBoxManage -> ../share/virtualbox/VBox.sh*
lrwxrwxrwx 1 root root 27 Oct 17 01:50 /usr/bin/VBoxSDL -> ../share/virtualbox/VBox.sh*
~ ▶︎︎ id
uid=1000(john) gid=1000(john) groups=1000(john),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare),136(docker)
~ ▶︎︎ echo $PATH
/home/john/bin /home/john/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /home/john/bin
~ ▶︎︎ echo (which VBoxManage)
/usr/bin/VBoxManage
```

**Comment by Asuza** [comment] 2017-11-04 00:31
I just downloaded Vagrant 2.0.1 and tried it again. The message remains the same.
```
~/d/j/ai-battle-website (riotjs) ▶︎︎ vagrant up
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

**Comment by briancain** [comment] 2017-11-06 16:28
Hello @Asuza - have you also tried re-installing virtualbox?

**Comment by Asuza** [comment] 2017-11-11 02:03
Just tried that, @briancain. No change. I purged it and reinstalled.

**Comment by Asuza** [comment] 2017-11-18 01:24
Is there anything else I can try in order to fix this? I'd really like to avoid having to use Docker for a development environment.

**Comment by Asuza** [comment] 2018-01-07 16:52
Still no clue why this isn't working. Is there no way to debug path issues?

I tried to create a new Vagrant box in a new test directory to see if I could get any more useful information. I don't know if this is useful, but here it is:

```
~/d/test ▶︎︎ vagrant init hashicorp/precise32
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
~/d/test ▶︎︎ vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

~/d/test ▶︎︎ vagrant up --provider=VirtualBox
The provider 'VirtualBox' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
~/d/test ▶︎︎ which virtualbox
/usr/bin/virtualbox
~/d/test ▶︎︎ VBoxManage --version
5.1.30_Ubuntur118389
```

**Comment by obfuscoder** [comment] 2018-01-31 09:16
I am having the exact same problem with Vagrant 1.7.3 on Ubuntu 17.10

**Comment by chrisroberts** [comment] 2018-01-31 17:03
@obfuscoder You most likely need to upgrade your version of Vagrant.

@Asuza I believe this may be something to do with your shell. Would you try running from a bash shell and see you experience the same behavior. Would you also provide the output of `echo $PATH` from your fish shell. Thanks!

**Comment by obfuscoder** [comment] 2018-01-31 17:09
Indeed, Vagrant 1.7.somethign was installed as it came with the Ubuntu distro, Downloading and installing latest version of Vagrant solved my issue.

**Comment by chrisroberts** [comment] 2018-03-27 14:42
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2018-03-27 14:42 UTC
Labels: needs info, needs-repro
