### ISSUE TITLE
OS X .dmg certificate expried

### ISSUE THREAD

**Issue by giovino** [hashicorp/vagrant#9240] opened 2017-12-02 23:21 UTC
### Vagrant version
2.0.1

### Host operating system
OS 10.12.6

It looks like the certificate for the OS X package is expired

<img width="622" alt="screen shot 2017-12-02 at 6 18 45 pm" src="https://user-images.githubusercontent.com/1413931/33520674-9ea87ae0-d78d-11e7-8f17-84cdf082ef23.png">

**Comment by splilly1987** [comment] 2017-12-04 14:02
Same issue:

```
brew cask install vagrant
==> Satisfying dependencies
==> Downloading https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.dmg
Already downloaded: /Users/paul.lilly@ibm.com/Library/Caches/Homebrew/Cask/vagrant--2.0.1.dmg
==> Verifying checksum for Cask vagrant
==> Installing Cask vagrant
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Vagrant
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/vagrant/2.0.1/vagrant.pkg -target /

==> Standard Output of failed command:
installer: Package name is Vagrant
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 77303 exit 1>
```

**Comment by damianlewis** [comment] 2017-12-04 14:36
Same problem here.

```
➜  ~ brew cask install vagrant
==> Satisfying dependencies
==> Downloading https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask vagrant
==> Installing Cask vagrant
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Vagrant
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/vagrant/2.0.1/vagrant.pkg -target /

==> Standard Output of failed command:
installer: Package name is Vagrant
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 4859 exit 1>
```

**Comment by lordgordon** [comment] 2017-12-04 15:06
Same issue here.

This issue is breaking automatic installation tools like brew.

**Comment by rockholla** [comment] 2017-12-04 17:09
Ran into this, too

**Comment by Grasshopper1234** [comment] 2017-12-04 17:24
was the Mac Vagrant 2.0.1 installer fixed? I am still seeing the certificate expired

**Comment by jtrinklein** [comment] 2017-12-04 19:45
not yet. I just downloaded it and have the same issue.

**Comment by geerlingguy** [comment] 2017-12-04 21:28
It's also breaking any CI builds that install vagrant using homebrew, e.g. https://travis-ci.org/geerlingguy/mac-dev-playbook/builds/311512428#L664 :(

Does a new release have to occur to get a fixed build, or can 2.0.1 be re-signed / re-released with a new cert?

**Comment by brownmike** [comment] 2017-12-04 21:31
> It's also breaking any CI builds that install vagrant using homebrew, e.g. https://travis-ci.org/geerlingguy/mac-dev-playbook/builds/311512428#L664 :(
> 
> Does a new release have to occur to get a fixed build, or can 2.0.1 be re-signed / re-released with a new cert?

I'm in this predicament as well.

**Comment by JPTeasdale** [comment] 2017-12-04 23:51
Can report that version `v1.8.7`from this url is expired as well: https://raw.githubusercontent.com/caskroom/homebrew-cask/8f731adc511c2fa553158dcc5544fda5c2237697/Casks/vagrant.rb

```
==> Downloading https://releases.hashicorp.com/vagrant/1.8.7/vagrant_1.8.7.dmg
Already downloaded: /Users/teasdale/Library/Caches/Homebrew/Cask/vagrant--1.8.7.dmg
==> Verifying checksum for Cask vagrant
==> Installing Cask vagrant
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:

==> installer: Package name is Vagrant
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Purging files for version 1.8.7 of Cask vagrant
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/vagrant/1.8.7/Vagrant.pkg -target /

==> Standard Output of failed command:
installer: Package name is Vagrant
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.

==> Exit status of failed command:
#<Process::Status: pid 15372 exit 1>
```

**Comment by jaux** [comment] 2017-12-05 04:26
Still no updates after 2 days?

**Comment by lordgordon** [comment] 2017-12-05 08:56
I think this should be escalated. This is blocking a lot of developments.

Also, it doesn't look good on Hashicorp to see a security warning while installing Vagrant with the manual installation.

**Comment by Muximize** [comment] 2017-12-05 13:38
https://github.com/hashicorp/vagrant-installers/issues/124

**Comment by ghaabor** [comment] 2017-12-05 15:27
Same error here with 1.9.1:
```
$ hdiutil attach vagrant.dmg
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $FBA7FE24
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $49CAD895
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $F0EC6B7D
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
          disk image (Apple_HFS : 4): verified   CRC32 $1684112C
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $F0EC6B7D
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $26EA3F76
verified   CRC32 $2D4CF9D0
/dev/disk1          	GUID_partition_scheme          	
/dev/disk1s1        	Apple_HFS                      	/Volumes/Vagrant
$ sudo installer -package /Volumes/Vagrant/Vagrant.pkg -target /
installer: Package name is Vagrant
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
```

**Comment by cesaruve** [comment] 2017-12-05 20:01
I think I have a workaround

copy the following in a file (normally a .rb file):
```
cask 'vagrant' do
	version '2.0.1'
	sha256 :no_check
	#sha256 '955fca5295be41a6a7dbb2a49f2ce0a8c14bc1fc598fcd196d1a8631932c1906'

  # hashicorp.com/vagrant was verified as official when first introduced to the cask
  url "https://releases.hashicorp.com/vagrant/#{version}/vagrant_#{version}_x86_64.dmg"
  appcast 'https://github.com/hashicorp/vagrant/releases.atom',
          checkpoint: 'e8da4166b284937d88fcddffa4aec661a6821521db9c679442f47dbf714b3a3b'
  name 'Vagrant'
  homepage 'https://www.vagrantup.com/'

	pkg 'vagrant.pkg'
	allow_untrusted true

  uninstall script:  {
                       executable: 'uninstall.tool',
                       input:      ['Yes'],
                       sudo:       true,
                     },
            pkgutil: 'com.vagrant.vagrant'

  zap trash: '~/.vagrant.d'
end
```

(you can specify the version as well, I turned off the checksum because I had problems, for me it was: '07f7be3a457a8422d576e6371c8499fbdea411b02aecc7ea3c5258494514c5f2')

then you might be able to install by running:

`brew cask install /path/to/the/above/file`

**Comment by asottile** [comment] 2017-12-05 21:06
turning off the `sha256` checking wasn't necessary for me (it shouldn't be? that's not actually the "verification" that's failing here)

Here's what I'm using: https://github.com/asottile/homebrew-cask/commit/055773fe8b55cb4fdaba8c299fe741ec9b2868a8

with:

```
brew cask install --force https://raw.githubusercontent.com/asottile/homebrew-cask/055773fe8b55cb4fdaba8c299fe741ec9b2868a8/Casks/vagrant.rb
```

(mine's obviously an old version, fork whatever file you actually need)

**Comment by asottile** [comment] 2017-12-05 21:37
fwiw, it seems a new dmg has been uploaded for 2.0.1 (brew has been updated with a fix):

https://github.com/caskroom/homebrew-cask/pull/41664

**Comment by cesaruve** [comment] 2017-12-05 21:48
no, my change is:
`allow_untrusted true`
But I think the new dmg has the new certificate then the checksum has changed and my change is bypass or it never has effect.

**Comment by splilly1987** [comment] 2017-12-05 23:22
I can confirm that after running a `brew update` and brew prompting me to remove the old dmg, I was able to `brew cask install vagrant` successfully.

**Comment by briancain** [comment] 2017-12-05 23:26
Hey everyone!

We have published updated packages today with a renewed signing cert for the latest version of Vagrant. Thank you everyone for reporting this and thank you for your patience!

**Closed by briancain** 2017-12-05 23:26 UTC
Labels: installer
