### ISSUE TITLE
Vagrant inoperable after `vagrant powershell`

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10086] opened 2018-08-02 23:49 UTC
After running `vagrant powershell`, vagrant commands no longer work.

### Vagrant version
Vagrant 2.1.2
Virtual Box 5.2.16r123759

### Host operating system
Windows 8.1

### Guest operating system
Windows 2016

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "my/windows2016"
end
```

### Expected behavior

Vagrant commands like `vagrant halt` would work.

### Actual behavior

Vagrant commands like `vagrant halt` no longer work after running `vagrant powershell`

### Steps to reproduce

1. `vagrant init my/windows2016`
2. `vagrant up`
3. `vagrant powershell`
4. In another Powershell session, navigate to directory, run `vagrant halt`

**Comment by briancain** [comment] 2018-08-06 15:53
Duplicate of #10087. I'm going to go ahead and close this since it looks very similar to the other issue you created. Thanks!

**Closed by briancain** 2018-08-06 15:53 UTC
