### ISSUE TITLE
VirtualBox NAT interface DHCP failures

### ISSUE THREAD

**Issue by balapuram** [hashicorp/vagrant#10362] opened 2018-11-02 13:12 UTC
I am trying to run vagrant up command , i am getting below error.

Vagrant Host Machine: CentOS7
Vagrant Guest Machine: CentOS7

The vagrant file as below

========================
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "10.10.10.20"
 end

========================

Looks like it is failing when it attempt for ssh authentication. Can you anyone please let me know what is missing here.

Thanks in Advance.

[root@jenkins2 ansible_provisioner]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/7' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
[root@jenkins2 ansible_provisioner]#

Regards,
Bhaskar.

**Comment by briancain** [comment] 2018-11-02 15:31
@balapuram - Can you bring up the machine using the virtualbox gui instead of Vagrant?

**Comment by robotpony** [comment] 2018-11-06 19:10
I'm seeing the same logs here (with Ubuntu 14.04) on previously tested/running images. When starting up via VirtualBox, networking devices are failing to start up:

![screen shot 2018-11-06 at 11 07 29 am](https://user-images.githubusercontent.com/163403/48087556-79492600-e1b4-11e8-8afa-e296ab3df126.png)

I'm nudging around the network config and will report back if I find a workaround.

**Comment by arion85** [comment] 2018-11-08 16:21
(Don't speak english) I have the same problem. I determined that this happens when port forwarding, after executing the "modifyvm uuid --natpf1" ssh, tcp, 127.0.0.1,2222,, 22 "" command. If I comment out the line with the launch of this command (in source code), the NAT adapter gets an IP address.

**Comment by chrisroberts** [comment] 2018-11-13 15:19
@arion85 Can you provide a gist of the debug output from the failure? (`vagrant up --debug`)

Thanks!

**Comment by vikman90** [comment] 2018-11-15 14:47
Hi team!

I have a similar issue with a _debian/stretch64_ box.

|Vagrant version|VirtualBox version|Host OS|Guest box|
|---|---|---|---|
|Vagrant 2.2.0|5.2.2.22 r126460|macOS Mojave 10.14.1|debian/stretch64|

Sometimes `vagrant up` runs OK, but most of the time, Vagrant hangs during the connection attempt, no matter whether the machine is new (after `vagrant destroy`) or used.

It seems that this problem only happens if I add a private network interface, no matter if it's a _virtio_ or a default network card.

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"
  config.vm.hostname = "stretch"
  config.vm.network "private_network", ip: "192.168.33.99", nic_type: "virtio"

end
```

### Command output

```
Vikmans-MacBook-Pro:Debian vikman$ vagrant destroy -f

==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...

Vikmans-MacBook-Pro:Debian vikman$ rm -r .vagrant

Vikmans-MacBook-Pro:Debian vikman$ vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/stretch64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/stretch64' is up to date...
==> default: Setting the name of the VM: Debian_default_1542187458153_80835
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### Command output (debug)

Please find attached the output of `vagrant up --debug`:
[vagrant-debug.log](https://github.com/hashicorp/vagrant/files/2585673/vagrant-debug.log)

### VirtualBox GUI

I tried to boot the virtual machine via VirtualBox GUI. It started OK but I found that the _eth0_ interface (for the NAT network) had no IP address:

<img width="832" alt="screen shot 2018-11-14 at 10 41 51 pm" src="https://user-images.githubusercontent.com/10536251/48559441-f6c71180-e8eb-11e8-9cf8-e2e36e9885f4.png">

On the other hand, both `ifdown` and `ifup` fail on DHCP:

![screen shot 2018-11-15 at 3 38 03 pm](https://user-images.githubusercontent.com/10536251/48559946-08f57f80-e8ed-11e8-8b28-9ddc269f8d73.png)

![screen shot 2018-11-15 at 3 42 15 pm](https://user-images.githubusercontent.com/10536251/48560060-435f1c80-e8ed-11e8-8337-951340f93aee.png)

I hope this helps you to find the cause of the problem.

Thank you in advance.
Cheers!

**Comment by chrisroberts** [comment] 2018-11-15 21:15
@vikman90 Hi, and thank you for providing all of these details! 

The end of your comment referencing the failure of eth0 to establish a connection to the DHCP server is certainly suspect. This interface should be receiving a lease from the DHCP server built into VirtualBox. Can you try fully stopping VirtualBox (all running guest VMs and all VirtualBox services/processes on the host), start VirtualBox back up, and see if the issue still persists. 

So far I have been unable reproduce the state locally, but will continue trying with different versions.

Thanks!

**Comment by arion85** [comment] 2018-11-16 07:02
> @arion85 Can you provide a gist of the debug output from the failure? (`vagrant up --debug`)
> 
> Thanks!
Vagrant up --debug
[vagrant.log](https://github.com/hashicorp/vagrant/files/2588233/vagrant.log)

**Comment by chrisroberts** [comment] 2018-11-16 15:54
@arion85 The file you have uploaded does not appear to be a log file

**Comment by chrisroberts** [comment] 2018-12-08 00:39
Just to drop a quick update here. I have one guest I have been able to reliably reproduce the error state of no address being provided, however even after waiting no address is ever offered. This seems to be an issue with the internal vbox DHCP server for the NAT interface, however I have not yet been able to generate enough logging information to confirm my suspicion.

**Comment by richard-scott** [comment] 2019-02-18 10:22
Add this to your Vagrantfile:

```
vb.customize ["modifyvm", :id, "--nictype1", "82540EM"]
```

I've found "virtio" causes this issue for me.

**Comment by chrisroberts** [comment] 2020-06-18 16:02
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2020-06-18 16:02 UTC
Labels: needs-repro, provider/virtualbox
