### ISSUE TITLE
dyld: Symbol not found: _iconv on vagrant 2.3.7 macOS intel

### ISSUE THREAD

**Issue by mike-code** [hashicorp/vagrant#13235] opened 2023-07-20 15:19 UTC
I have installed the latest version of Vagrant
```
Installed Version: 2.3.7
Latest Version: 2.3.7
```
running 11.5.2 macOS big sur @ intel

Any vagrant command is terminated with the following error

```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libarchive.2.dylib
  Expected in: /opt/vagrant/embedded/lib/libiconv.2.dylib
 in /usr/lib/libarchive.2.dylib
```

**Comment by danielmapar** [comment] 2023-08-06 00:22
My way out of it was to forcibly remove it: `sudo rm -rf /opt/vagrant/embedded/lib/libiconv.2.dylib`

**Comment by kaitlincart** [comment] 2023-08-17 20:23
This is a duplicate of #13220, please track it there.

**Closed by kaitlincart** 2023-08-17 20:23 UTC
Labels: waiting-intake
