### ISSUE TITLE
Unable to change permissions, or delete files in a shared directory

### ISSUE THREAD

**Issue by Pavel-Mukha** [hashicorp/vagrant#11278] opened 2019-12-21 18:55 UTC
### Vagrant version
Vagrant 2.2.6

### Host operating system
Windows 10 (ntfs)

### Guest operating system
Linux ubuntu 16

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "c:/vagrant/m4/www", "/var/www",
	owner: "vagrant",
	mount_options: ["dmode=777,fmode=777"]
end
```
### Actual behavior
When I try to change permissions for files that are located in the shared directory of the guest of the machine, I get an error rm: cannot remove '1.txt': Operation not permitted
Screenshot http://prntscr.com/qe20fe

Is it even possible to work with a vagrant from under the host machine of windows?

**Comment by jbonhag** [comment] 2020-01-06 14:50
Hi there,

Thank you for opening an issue. However, there is not quite enough information here to reproduce or provide a recommendation.  Would it be possible to run `vagrant up --debug` and post the output as a [Gist](https://gist.github.com)?  This will help us assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by briancain** [comment] 2020-01-07 21:57
Hi there @Pavel-Mukha - I just tried reproducing your issue and I could not. It is possible your box is not configured to give Vagrant the proper permissions to edit files in `/var`, as the error message states. Based on the image, it looks like Vagrant gave the files in that folder the proper permissions, at least. I would check to make sure your Vagrant user can edit files in that directory, or see if you can remove it using sudo.

Here's the ouput from my testing:

```
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-170-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


0 packages can be updated.
0 updates are security updates.

New release '18.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


vagrant@ubuntu-xenial:~$ cd /var/www/
vagrant@ubuntu-xenial:/var/www$ pwd
/var/www
vagrant@ubuntu-xenial:/var/www$ ls -lah
total 12K
drwxrwxrwx  1 vagrant vagrant 4.0K Jan  7 21:53 .
drwxr-xr-x 14 root    root    4.0K Jan  7 21:55 ..
drwxrwxrwx  1 vagrant vagrant 4.0K Jan  7 21:53 vagrant.local
vagrant@ubuntu-xenial:/var/www$ cd vagrant.local/
vagrant@ubuntu-xenial:/var/www/vagrant.local$ ls -lah
total 12K
drwxrwxrwx 1 vagrant vagrant 4.0K Jan  7 21:53 .
drwxrwxrwx 1 vagrant vagrant 4.0K Jan  7 21:53 ..
-rwxrwxrwx 1 vagrant vagrant    4 Jan  7 21:50 1.txt
vagrant@ubuntu-xenial:/var/www/vagrant.local$ rm 1.txt
vagrant@ubuntu-xenial:/var/www/vagrant.local$ ls -lah
total 8.0K
drwxrwxrwx 1 vagrant vagrant 4.0K Jan  7 21:56 .
drwxrwxrwx 1 vagrant vagrant 4.0K Jan  7 21:53 ..
```

```ruby
 config.vm.define "bork" do |b|
    b.vm.box = "ubuntu/xenial64"
    b.vm.synced_folder "www", "/var/www",
        owner: "vagrant", mount_options: ["dmode=777,fmode=777"]
  end
```

**Closed by briancain** 2020-01-07 21:57 UTC
Labels: needs-debug-gist
