### ISSUE TITLE
Virtualbox .vbox missing <HardDisk> section

### ISSUE THREAD

**Issue by alex-dewar** [hashicorp/vagrant#10839] opened 2019-05-08 20:25 UTC
### Vagrant version
Vagrant 2.2.4

### Host operating system
Windows 10 Pro

### Guest operating system
hashicorp/precise32

### Provider
Virtualbox 6.0.6 r130049

### Expected behavior
The .vbox file created should contain a <HardDisk> section that specifies the hard disk uuid, location, format, etc.

### Actual behavior
This section is missing from the created .vbox file

### Steps to reproduce
1. `vagrant init hashicorp/precise32`
1. `vagrant up`

This doesn't prevent the VM from being used, as Virtualbox seems to have the location of the hard disk stored somewhere else; however, it prevents the VM from being readded once removed.

**Comment by briancain** [comment] 2019-05-08 20:56
Hi @alex-dewar - What exactly do you mean by this?

> however, it prevents the VM from being readded once removed.

Does it prevent you from bringing up the virtual machine again after doing a Vagrant destroy? Can you not mount shared folders? A debug gist would be very helpful. Thanks!

**Comment by alex-dewar** [comment] 2019-05-09 13:32
Hi,

Sorry about not being more specific. Continuing to use the VM with Vagrant works fine. The issue is with removing the VM from within Virtualbox, then readding it again within Virtualbox. Attempting to add the VM causes the error: `Could not find an open hard disk with UUID {875efd89-e205-4675-b5a8-7dbb98da320b}`. 

I've found that the corresponding .vbox file does not contain the aforementioned <HardDisk> section, which is normally added when creating a new VM in Virtualbox, or when adding a hard disk via the VM's storage settings.

Let me know if you need any more info.

**Comment by alex-dewar** [comment] 2019-05-09 13:42
Here's a Gist of the `vagrant up` log: https://gist.github.com/alex-dewar/fc1b1585d7fa98e4b524a13535e916f0.

I'll retry this with a box that has a matching VirtualBox extensions version as well and see if that fixes it.

**Comment by briancain** [comment] 2019-05-09 15:15
Hey @alex-dewar - The log you posted shows no errors. Are you trying to add the unpacked box directly through the VirtualBox GUI? If so, I don't think that's intended behavior. Are you experiencing any errors while using Vagrant, specifically?

**Comment by alex-dewar** [comment] 2019-05-09 15:28
I'm not experiencing any errors with Vagrant specifically. I didn't realize that adding images created with Vagrant was unintended behaviour, since we've had it work in the past with images created with Vagrant on VirtualBox 5.

**Comment by briancain** [comment] 2019-11-04 23:25
Hi there, since there are no issues with Vagrant in this issue I'm going to close this. GitHub is meant for bugs with Vagrant, so if you have any further usage questions or virtualbox questions please direct them to the mailing list. Thanks!

**Closed by briancain** 2019-11-04 23:25 UTC
Labels: waiting-reply
