### ISSUE TITLE
quarkslab/debian-9.0.0-amd64 not found 

### ISSUE THREAD

**Issue by seantree** [hashicorp/vagrant#9589] opened 2018-03-19 05:48 UTC
Bringing machine 'brain.irma' up with 'virtualbox' provider...
==> brain.irma: Box 'quarkslab/debian-9.0.0-amd64' could not be found. Attempting to find and install...
    brain.irma: Box Provider: virtualbox
    brain.irma: Box Version: >= 0
The box 'quarkslab/debian-9.0.0-amd64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/quarkslab/debian-9.0.0-amd64"]
Error: The requested URL returned error: 404 Not Found

**Comment by briancain** [comment] 2018-03-19 16:08
@seantree - upgrade your version of Vagrant to 2.0.3. Duplicate of #9442. Thanks!

**Closed by briancain** 2018-03-19 16:08 UTC
