### ISSUE TITLE
Vagrant 32-bit trying to run mingw64/ruby and failing

### ISSUE THREAD

**Issue by cnkcb** [hashicorp/vagrant#10075] opened 2018-07-30 17:56 UTC
I'm trying to use a newly downloaded and installed 32-bit flavor of Vagrant v2.1.2 on a Win 7 Enterprise SP1 32-bit machine, but get this error when I try to run it

```
PS C:\Users\username> vagrant -v
Exec error: fork/exec C:\HashiCorp\Vagrant\embedded\mingw64\bin\ruby.exe: 
This version of %1 is not compatible with the version of Windows you're
running. Check your computer's system information to see whether you need
a x86 (32-bit) or x64 (64-bit) version of the program, and then contact 
the software publisher.
```
The installer has run correctly and not given any errors.

### Vagrant version
2.1.2 

### Host operating system
Win 7 Enterprise SP1 32-bit 

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
Vagrant should have used mingw32/ruby

### Actual behavior
Vagrant tried to use mingw64/ruby 

### Steps to reproduce
1.  Run installer
2.  `vagrant -v` in powershell

### References
N/A

**Comment by chrisroberts** [comment] 2018-07-30 21:25
Duplicate of #10026

**Closed by chrisroberts** 2018-07-30 21:25 UTC
