### ISSUE TITLE
NFS Sharing - Subfolders not exported properly on Mac OS (might affect others as well)

### ISSUE THREAD

**Issue by applike-ss** [hashicorp/vagrant#9218] opened 2017-11-24 13:55 UTC
### Vagrant version
1.9.8

### Host operating system
Mac OS X 10.12.6

### Guest operating system
debian 8.9

### Vagrantfile
can't provide

### Expected behavior
Vagrant should export any other mounted folder (like tmpfs) under a shared folder via nfs as well.

### Actual behavior
Vagrant only exports the root folder, making the guest unable to access the ramdisk.

### Steps to reproduce
1. Create a folder to share
2. create and mount a ramdisk in a subfolder of the shared folder
3. add the root share folder to the vagrantfile to share as nfs share
4. /etc/exports on the host will only show the root entry, while subfolders contain a mounted filesystem

### References
none

**Comment by briancain** [comment] 2017-11-27 22:18
Hello @applike-ss - can you give me a bit more information about what you mean with step 4? Do you just see the root folder, but the subfolders don't exist on the guest?

**Comment by applike-ss** [comment] 2017-11-28 07:32
@briancain i mean that in my hosts "/etc/exports" i do only see that the specified folder in the vagrantfile is exported, while as of what i thing it also should export subfolder that are mounted (like a ramdisk/tmpfs or something).
The current behaviour makes me see files and folders (in my guest) from my host that i created before mounting a ramdisk/tmpfs to that point in the filesystem.

**Comment by applike-ss** [comment] 2017-12-01 07:52
@briancain 
Just to clarify how it looks like.
Host:
- Shared Folder
  - /Folder_1
  - /cache (this is mounted as tmpfs)
   - /test.txt
   - end of listing

Guest:
- Shared Folder
  - /Folder_1
  - /cache
   - /some_symfony_cache_stuff_1
   - /some_symfony_cache_stuff_2
   - /some_symfony_cache_stuff_3
   - /some_symfony_cache_stuff_4
   - end of listing

**Comment by briancain** [comment] 2017-12-01 21:15
@applike-ss - Could provide a vagrantfile that reproduces this if you can't share your original? Thanks!

**Comment by applike-ss** [comment] 2017-12-04 07:29
Here is the Vagrantfile:
[Vagrantfile.txt](https://github.com/hashicorp/vagrant/files/1526027/Vagrantfile.txt)
Here's a Screenshot, please don't confuse because the folder on my mac is shown as "ram disk", thats just the label of the ramdisk, not the mountpoint.
![screenshot_04_12_17__08_23](https://user-images.githubusercontent.com/31846129/33540778-cfc591c2-d8cc-11e7-9e87-35000968c0a2.png)
Steps:
- create a cache folder
- put something into it
- create a ramdisk/tmpfs
- mount it to the cache folder
- vagrant up
- cat /etc/hosts
- see that the sub mount was not exported

**Comment by briancain** [comment] 2017-12-04 19:06
@applike-ss  Thanks, I'll try to reproduce this on my machine today!

**Comment by briancain** [comment] 2017-12-04 19:26
@applike-ss - actually I have one more request for you to try...could you try mounting the folder manually and see if you get the same result? Basically bring up the vm but without the nfs option in your vagrant file, and you should be able to run this command:

```
mount -o vers=3,rw,tcp,nolock,noacl,async <IP_OF_VM>:/Users/path/to/your/host/vagrantfile/folder /myshare
```

**Comment by applike-ss** [comment] 2017-12-05 07:16
@briancain since the /etc/exports entry in my host would not be created, this would fail.
Or do you mean, that i should create it manually, then vagrant up and afterwards try to mount it?
Also: IP_OF_VM should be IP_OF_HOST, right? Since the host executes the nfs server.

**Comment by briancain** [comment] 2017-12-05 16:22
@applike-ss yep exactly. I'm trying to see if it's perhaps an NFS bug if you run the same mount command vagrant would run. But yeah, you will need to create that /etc/exports entry. Also yep about the host IP. Was just doing some quick substitution and made a mistake :)

**Comment by applike-ss** [comment] 2017-12-06 07:35
@briancain well since vagrant creates those /etc/export entries on the host, it is obviously a vagrant bug when creating the exports file. It needs to be scanning for folder mounted under the shared folder and export those as well.

**Comment by kikitux** [comment] 2017-12-07 18:27
@applike-ss 

Hello

MAC OS have some security features around NFS that explain what you are seein.

1. you should not share your home dir
2. nested shares

If you share 2 separate shares it will be ok.

check macOS documentation around that, vagrant is trying to do the right thing, but the OS is not compatible with what you want to do.

If you can try manually (without vagrant) and you get something that work, please share with us for review.

Closing for now since we have got issues like this in the past.

Thanks
Alvaro.

**Closed by kikitux** 2017-12-07 18:27 UTC
Labels: needs info, waiting-reply

**Comment by applike-ss** [comment] 2017-12-08 08:24
@kikitux i am sharing a sub folder of my home folder, but i guess that would be the same case. Anyway, haven't got the time to figure that out and probably not coming to a solution for this.

best regards,
Sebastian
