### ISSUE TITLE
Issue with synced folders when using non-default providers

### ISSUE THREAD

**Issue by whiggs** [hashicorp/vagrant#10111] opened 2018-08-13 15:28 UTC
There seems to be something wrong with the synced folder feature when attempting to run spin up vms using external provisioners.  For example, I have tested and confirmed that this issue occurs using both the vagrant-vsphere provider as well as the vagrant-azure provider.  Essentially, vagrant will always attempt to configure synced folders via smb, even when the guest operating system does not support smb (eg linux), even when I specifically leave out any sync folder configurations, even when I specifically configure a different sync folder option (in which case, the sync method I had configured will run after the smb sync process either fails or goes through), no matter what I do, no matter what I try, vagrant's automation always breaks when I am prompted to enter my credentials to set up smb shares, which is extremely annoying when I am trying to spin up a guest vm that doesn't even support smb shares.  Funny thing is, in cases where os does not support smb shares, even if I specifically configure all of the smb share information (including user name and password) into the vagrantfile, **I am still prompted to enter my credentials when vagrant tries to set up the smb share, completely breaking vagrant's automation.**  And before someone tries to reflect the blame to the external providers, I have looked into this a bit myself (as I thought it was the provisioners that were the problem), but the all the "action.rb" file in the provisioner's plugin does is call the "SyncedFolders" gem (sorry, not familiar with Ruby termonology, so that may be wrong) which is built into the main Vagrant application.  Therefore, one can only come to the conclusion that this is an issue with the main vagrant application. 

### Vagrant version
Vagrant 2.1.2

### Host operating system
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134

### Guest operating system
Both linux and windows guest operating systems are affected, but Ubuntu server 18.04 LTS displays all of the issues

### Vagrantfile
```ruby

$script = <<-SCRIPT
	apt update
	apt upgrade
	apt install -y curl
	curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
	curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list
	apt-get update
	apt-get install -y powershell-preview
	apt install -y wget
	apt install -y make
	SCRIPT
Vagrant.configure("2") do |config|
	config.vm.box = "atlas_shrugged/vsphere_dummy"
	config.vm.box_check_update = true
	config.vm.communicator = "ssh"
	config.vm.guest = :linux
	config.ssh.username = "vagrant"
	config.ssh.password = "vagrant"
	config.ssh.keep_alive = true

	config.vm.synced_folder "packages", "/packages", type: "rsync"
	config.vm.provision "shell", inline: $script, privileged: true
	config.vm.provider :vsphere do |vsphere, override|
		vsphere.host = 'ahost.somewhere.com'
		vsphere.insecure = true
		vsphere.cpu_count = 4
		vsphere.memory_mb = 12288
		vsphere.compute_resource_name = 'Test Environment'

		vsphere.template_name = '/Templates/vagubuntu'
		vsphere.vm_base_path = "B.Local/Hyperion"
		vsphere.name = 'ubuvagr'
		vsphere.user = 'something'
		vsphere.password = 'here'
	end
  end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
vagrant should sync the indicated folder using rsync.

### Actual behavior
Vagrant attempts to sync the indicated folder via smb and prompts for the credentials to use.  After the smb connection fails, it is then and only then that vagrant will attempt to sync the folder using the sync option I specified and want to use.

### Steps to reproduce
1. run vagrant up with one of the two vagrant providers I mentioned (vagrant-vsphere or vagrant-azure) or just run the vagrantfile included in this issue.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment] 2018-08-13 21:43
Hi there @whiggs - Are you able to reproduce this with the VirtualBox provider? Can you also provide the full output of bringing up a machine with the `--debug` flag? I tried to reproduce this on Windows 10 with VirtualBox, Vagrant 2.1.2, and a Ubuntu guest and I did not get any prompt for entering SMB credentials:

![screen shot 2018-08-13 at 2 36 38 pm](https://user-images.githubusercontent.com/810277/44059527-89265bba-9f06-11e8-8d02-ec12ed5f1a39.png)

Have you tried a different box? Vagrant boxes often ship with their own Vagrantfile, which Vagrant takes into account when bringing up your machine. You can find it here and see if there are any SMB configurations:

```
~/.vagrant.d/boxes/your-box-here
```

For example, here is the box I used to try to reproduce this issue:

```
brian@localghost:bento-VAGRANTSLASH-ubuntu-18.04 % tree 201807.12.0
201807.12.0
└── virtualbox
    ├── Vagrantfile
    ├── box.ovf
    ├── metadata.json
    └── ubuntu-18.04-amd64-disk001.vmdk

1 directories, 4 files
brian@localghost:bento-VAGRANTSLASH-ubuntu-18.04 % cat 201807.12.0/virtualbox/Vagrantfile

# The contents below were provided by the Packer Vagrant post-processor

Vagrant.configure("2") do |config|
  config.vm.base_mac = "0800270C010D"
end


# The contents below (if any) are custom contents provided by the
# Packer template during image build.
```

Thanks!

**Comment by briancain** [comment] 2018-08-13 21:58
Also, perhaps the providers you are using default to using SMB to sync the current working dir. If you add this config entry to your Vagrantfile, does the SMB prompt go away?

```ruby
config.vm.synced_folder ".", "/vagrant", disabled: true
```

By default Vagrant will attempt to sync your working dir to `/vagrant` on your guest unless its told not to, so there's a good chance those plugins are trying to use SMB to share your current dir with the remote guest.

**Comment by whiggs** [comment] 2018-08-15 15:13
debug gist url below.  The gist ends at the point where it asks for the username for the smb share, as, being a linux machine and the fact that I have not configured synced folders to use smb, I should not be prompted for this.  Yet, it continues to, time and time and time again:
https://gist.github.com/whiggs/e79cf01e3902944386d0ecfb5e72337a

**Comment by whiggs** [comment] 2018-08-15 15:36
@briancain Thank you for your reply.  Your solution resolved my issue.  You guys might want to consider modifying vagrants default behavior so that if there is no "synced_folder" configuration in the vagrantfile, vagrant will not share the project directory, as this does nothing but, like I mentioned earlier, break the automation flow when users are forced to type in smb credentials that could potentially result in the premature termination of vagrants execution of the vagrantfile.  As for me, the part that confused me was that I could have sworn I read somewhere (of course I can't find it now) that vagrant would connect to the guest machine using the method that was most compatible with the guest machine, so it confused me as to why it would always use smb.  Further, is there a way to automate the input of the smb credentials without hard coding it into the vagrantfile?

**Comment by briancain** [comment] 2018-08-15 21:46
Hi @whiggs - yes, you could export your smb settings as environment variables, or store them in a file on disk and read them in your Vagrantfile. I'm going to go ahead and close this issue since it's not a Vagrant bug, thanks!

**Closed by briancain** 2018-08-15 21:46 UTC
Labels: needs-debug-gist, waiting-reply
