### ISSUE TITLE
Can't Vagrant Up Provider hyperv on WSL

### ISSUE THREAD

**Issue by Crisfole** [hashicorp/vagrant#9494] opened 2018-02-20 15:58 UTC
`vagrant up --provider=hyperv` fails because, "The Hyper-V provider only works on Windows. Please try to use another provider."

However, the WSL _is_ windows, and many other parts of vagrant work fine even though they use windows specifics.

### Vagrant version
2.0.2

### Host operating system
Windows

### Guest operating system
Ubuntu, but N/A

### Vagrantfile
N/A, relevant pieces:

```
Vagrant.configure("2") do |config|
    # config.vm.box = "https://s3-us-west-2.amazonaws.com/CLIENT/clientstuff.box"
    config.vm.box = "https://s3-us-west-2.amazonaws.com/CLIENT/clientstuff.box"
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |virtualbox|
        virtualbox.memory = 2048
        virtualbox.cpus = 2
    end

    config.vm.provider "hyperv" do |h, override|
      override.vm.box ='CLIENT/ubuntu-14.04--hyperv'
    end

  # ... my provisioners here
end
```

### Debug output
https://gist.github.com/Crisfole/57f20996fec0d80f2dc766a224c12921

### Expected behavior
Vagrant should have noticed that it was running under WSL and deferred the execution to the Windows executable.

### Actual behavior
Vagrant *failed* to notice it was running under WSL and tried to run it as if it was actually on linux, thus failing.

### Steps to reproduce
1. Try and use a hyper-v provider on WSL.

**Comment by briancain** [comment] 2018-02-20 19:27
Closing this because it's a duplicate of https://github.com/hashicorp/vagrant/issues/8700

Thanks!

**Comment by Crisfole** [comment] 2018-02-20 19:28
Oh man, sorry! I totally failed to search there.

**Closed by briancain** 2018-02-20 19:27 UTC
