### ISSUE TITLE
Connection reset. Retrying.

### ISSUE THREAD

**Issue by glenshappy** [hashicorp/vagrant#12380] opened 2021-05-20 09:03 UTC
Hi, there , when i execute "vagrant up" or "vagrant reload", i get the error below:
Bringing machine 'aaaa' up with 'virtualbox' provider...
Bringing machine 'bbb' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 3: hostonly
    default: Adapter 4: hostonly
    default: Adapter 5: hostonly
==> default: Forwarding ports...
    default: 3000 (guest) => 3000 (host) (adapter 1)
    default: 3001 (guest) => 3001 (host) (adapter 1)
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 35729 (guest) => 35729 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ki
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
But when i look the virtualbox, it stay like below. when i input something ,such as "cls", it will go on,wha't the case? thanks

**Comment by grappler** [comment] 2021-05-21 14:40
Is this the same issue as https://github.com/hashicorp/vagrant/issues/12344

**Comment by soapy1** [comment] 2021-05-24 15:27
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by soapy1** [comment] 2021-06-01 14:59
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by soapy1** 2021-06-01 14:59 UTC
