### ISSUE TITLE
Update from v2.3.4 to v2.3.6 and Broken Plugins

### ISSUE THREAD

**Issue by StephenPooley** [hashicorp/vagrant#13177] opened 2023-05-24 13:13 UTC
### Debug output

Just updated from vagrant v2.3.4 to v2.3.6 in an attenpt to resolve an issue with the ansible provisioner. Unfortunately this appears to have caused plugins to stop working. 

It appears to be a certificate error of some kind. 

  SSL_connect SYSCALL returned=5 errno=0 peeraddr=13.224.132.74:443 state=error: certificate verify failed (https://gems.hashicorp.com/specs.4.8.gz)

However, the https website is reachable and I can download https://gems.hashicorp.com/specs.4.8.gz manually. So there doesn't appear to be any issue with proxies etc.

Possibly related to https://github.com/hashicorp/vagrant-installers/pull/270 and https://github.com/hashicorp/vagrant/issues/13156

See steps below...

> vagrant
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-hostmanager (= 1.8.9)'

> vagrant plugin repair
Repairing currently installed global plugins. This may take a few minutes...
ERROR:  SSL verification error at depth 3: unable to get local issuer certificate (20)
ERROR:  You must add /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority to your local trusted store
Failed to automatically repair installed Vagrant plugins. To fix this
problem remove all user installed plugins and reinstall. Vagrant can
do this for you automatically by running the following command:

  vagrant plugin expunge --reinstall

Failure message received during repair:

Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  SSL_connect SYSCALL returned=5 errno=0 peeraddr=13.224.132.74:443 state=error: certificate verify failed (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

> vagrant plugin expunge --reinstall

This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: y

All user installed plugins have been removed from this Vagrant environment!

Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
ERROR:  SSL verification error at depth 3: unable to get local issuer certificate (20)
ERROR:  You must add /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority to your local trusted store
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  SSL_connect SYSCALL returned=5 errno=0 peeraddr=13.224.132.74:443 state=error: certificate verify failed (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

> vagrant plugin list
No plugins installed.

> vagrant plugin install vmware_desktop
Installing the 'vmware_desktop' plugin. This can take a few minutes...
ERROR:  SSL verification error at depth 3: unable to get local issuer certificate (20)
ERROR:  You must add /C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority to your local trusted store
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  SSL_connect SYSCALL returned=5 errno=0 peeraddr=13.224.132.66:443 state=error: certificate verify failed (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

### Expected behavior

Vagrant to successfuly update plugins following update from vagrant v2.3.4 to v2.3.6

### Actual behavior

See above.

### Reproduction information 

See above.

#### Vagrant version

v2.3.6

#### Host operating system

Windows 

#### Guest operating system

Doens' get that far.

#### Steps to reproduce

1. See above.

#### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here. Remove any sensitive information such as passwords, authentication tokens, or email addresses.
```

Not relavant. Issue is with the management of plugins.

**Comment by StephenPooley** [comment] 2023-05-24 14:22
Probably also related to https://github.com/hashicorp/vagrant/issues/13167

**Comment by chrisroberts** [comment] 2023-05-24 22:45
Closing this as a duplicate of #13167. Please refer to that issue. Cheers!

**Closed by chrisroberts** 2023-05-24 22:45 UTC
Labels: duplicate

**Comment by StephenPooley** [comment] 2023-05-25 09:19
@chrisroberts Thanks for your help. Agree, based on comments from @mloskot in https://github.com/hashicorp/vagrant/issues/13167 then this does appear to be a duplicate. I'll track https://github.com/hashicorp/vagrant/issues/13167 instead. Thanks again.
