### ISSUE TITLE
Vagrant enhancement request:  add -f option to specify Vagrantfile.*

### ISSUE THREAD

**Issue by denchang** [hashicorp/vagrant#10853] opened 2019-05-11 14:11 UTC
### Vagrant version
2.2.4

### Host operating system
Mac OS X

### Guest operating system
Slackware 3.2

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-14.04-i386"
  config.vm.hostname = "slack-builder"

  config.vm.provider :virtualbox do |resources|
    resources.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
  end
end
```

Feature Request
1. Add '-f Vagrantfile.X' option. One Vagrantfile per directory is limiting. Instead I am proposing an '-f' option so that users can define any filename they want to describe an environment (and choose not to store the environment description files, i.e. Vagrantfile, in specific directories.

2. Requesting that a command, like 'vagrant up --box ol76' will create a new vagrant machine from the box named 'ol76'. Here, I'm requesting that spinning up a vagrant machine does not require a Vagrantfile. Vagrantfiles are useful but I'm asking that they should not be a requirement.

3. I don't understand the use of "default" as a name for a machine. 'vagrant global-status' displays machine names as "default" which I think isn't very useful. I like docker's CLI. Therefore, I would request that 'vagrant ps -a' provide a listing of machines (instead of global-status). That the user can name their machines (to something other than "default").

- ...

**Comment by secret104278** [comment] 2019-05-12 10:47
For the first point of feature request, vagrant currently have `VAGRANT_VAGRANTFILE` that allow you to specify Vagrantfile name. See https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_vagrantfile

**Comment by secret104278** [comment] 2019-05-12 11:11
For the third point, you can define the machine name in `Vagrantfile` like this
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.default "MACHINE NAME"
end
```
I guess vagrant use "default" because you can chose to define multiple machine in one file.
See https://www.vagrantup.com/docs/vagrantfile/tips.html

**Comment by denchang** [comment] 2019-05-12 21:37
Can you explain VAGRANT_VAGRANTFILE with an example? I don't see how it is used.
E.g.
VAGRANT_VAGRANTFILE=abcd

"This environmental variable is commonly used in scripting environments where a single folder may contain multiple Vagrantfiles representing different configurations."

Does this mean that if there are a lot of Vagrantfiles in a directory, this env variable would select

Vagrantfile.abcd ?

**Comment by secret104278** [comment] 2019-05-13 02:14
`VAGRANT_VAGRANTFILE` should be the path to your vagrantfile

Example
```bash
VAGRANT_VAGRANTFILE=~/tmp/Vagrantfile.abcd vagrant up
```

**Comment by briancain** [comment] 2019-05-13 15:56
Hey there @denchang -

> Add '-f Vagrantfile.X' option. One Vagrantfile per directory is limiting. Instead I am proposing an '-f' option so that users can define any filename they want to describe an environment (and choose not to store the environment description files, i.e. Vagrantfile, in specific directories.

As mentioned above by @secret104278 - this exists today through the use of an environment variable and should be how to use this.

That being said, how is one Vagrantfile per directory limiting? You can define as many guests as you want in a Vagrantfile. What could you require that needs multiple Vagrantfiles per directory? Unless (like the docs were saying) you are trying to use Vagrant in an automated way, I wouldn't recommend using multiple Vagrantfiles for your environment.

> Does this mean that if there are a lot of Vagrantfiles in a directory, this env variable would select Vagrantfile.abcd ?

The docs here are simply giving an example as to _why_ someone might want to use the environment variable. It means that whatever you set that environment variable to, that is the name of the file. So in this example they named the file `abcd`. You _could_ name your Vagrantfile that, I think. But in reality it will be named something else.

> Requesting that a command, like 'vagrant up --box ol76' will create a new vagrant machine from the box named 'ol76'. Here, I'm requesting that spinning up a vagrant machine does not require a Vagrantfile. Vagrantfiles are useful but I'm asking that they should not be a requirement.

Bringing up boxes like this is not really what Vagrant is for. If you just want to bring up a vm with no provisioning or any network setup that Vagrant offers it would likely just be easier to use the `vboxmanage` CLI tool. Using Vagrant and Vagrantfiles gives you repeatability when bringing up and provisioning a guest. The idea is you run `vagrant up`, and Vagrant sets up all of the networking interfaces and other software you would need for your project. And giving that Vagrantfile to others will reproduce the exact same virtual machine.

> I don't understand the use of "default" as a name for a machine. 'vagrant global-status' displays machine names as "default" which I think isn't very useful. I like docker's CLI. Therefore, I would request that 'vagrant ps -a' provide a listing of machines (instead of global-status). That the user can name their machines (to something other than "default").

Vagrant is giving your guest name "default" because you haven't named it. You need to give your guest a name inside your Vagrantfile. It sounds like these docs might be useful to you: https://www.vagrantup.com/docs/multi-machine/

You can define multiple machines with which ever name you want:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "apache"
  end

  config.vm.define "db" do |db|
    db.vm.box = "mysql"
  end
end
```

I'm going to go ahead and close this issue as it seems like the feature requests are covered. Feel free to open a new one or comment on here if you have any more questions or other requests! Thanks.

**Closed by briancain** 2019-05-13 15:56 UTC

**Comment by cbdchang** [comment] 2019-05-13 17:30
Ok, so I didn't see that link.
So a Vagrantfile is a project file. Define multiple machines per project.
One directory per project.

I was thinking of one Vagrantfile per machine.
