### ISSUE TITLE
Unable to interrupt vagrant with CtrlC from a cygwin terminal

### ISSUE THREAD

**Issue by rossengeorgiev** [hashicorp/vagrant#9387] opened 2018-01-19 14:28 UTC
### Vagrant version
```bash
$ vagrant -v
Vagrant 2.0.0
```

### Host operating system
Windows 10 + Cygwin

### Expected behavior
Press `Ctrl+C` and vagrant process gets interrupted

### Actual behavior
I get my prompt back, but the vagrant process continues to run and output to the terminal.
Essentially, I'm unable to cancel any command.

### Steps to reproduce
1. `vagrant up` inside cygwin terminal (mintty)
2. Press `Ctrl+C`

**Comment by eknoes** [comment] 2018-01-22 10:03
Can confirm this for Windows 7 with cygwin using Vagrant 2.0.1

**Comment by bizxta** [comment] 2019-08-05 11:11
Same issue here on Windows 7 and vagrant 2.2.4.

**Comment by briancain** [comment] 2020-05-04 18:42
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I just tried to reproduce this with the latest Vagrant and Cygwin on windows 10 and I was able to interrupt Vagrant without issue. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!

**Closed by briancain** 2020-05-04 18:42 UTC
Labels: core, host/windows

**Comment by rossengeorgiev** [comment] 2020-05-04 18:47
hi @briancain, what version of cygwin and vagrant did you use to test?

**Comment by rossengeorgiev** [comment] 2020-05-04 18:51
@briancain Issue still exists on `2.2.7`:

![image](https://user-images.githubusercontent.com/2720787/81002091-9958b480-8e40-11ea-99f5-7b72f7d255ce.png)

**Comment by briancain** [comment] 2020-05-04 19:49
![Peek 2020-05-04 12-47](https://user-images.githubusercontent.com/810277/81007111-8248a100-8e05-11ea-9c41-fe6e61572d3a.gif)

Freshly installed cygwin on a new image of Windows 10

**Comment by rossengeorgiev** [comment] 2020-05-04 20:00
Latest cygwin, windows, and vagrant. Did you check whether the ruby process is still running in task manager?

**Comment by briancain** [comment] 2020-05-04 20:07
Yep, there's nothing running:

![Peek 2020-05-04 13-06](https://user-images.githubusercontent.com/810277/81008631-1d427a80-8e08-11ea-852b-94b923df29fc.gif)

**Comment by rossengeorgiev** [comment] 2020-05-04 20:31
Ok interesting. I don't see what could be causing the difference. I've not done anything special, and the same issue exist on multiple machines.

**Comment by briancain** [comment] 2020-05-04 20:43
@rossengeorgiev It's possible there's something in your cygwin environment that's maybe messing things up? Have you tried uninstalling and reinstalling cygin and Vagrant maybe? :thinking:

**Comment by hoshsadiq** [comment] 2020-05-04 20:47
Note `ps aux` might not report windows processes correctly. Check use the `-W` (might be lowercase).

I also still had this issue a few weeks ago. Have left the company now though so I'm unable to check.

**Comment by briancain** [comment] 2020-05-04 21:18
@hoshsadiq - Maybe...however `ps` showed Vagrant when it was running, and it did not show up after I had ctrl-c 'd Vagrant. If Vagrant was still running, I would suspect it would show up like it did prior to me ctrl-cing the process.

**Comment by hoshsadiq** [comment] 2020-05-04 21:35
Pardon me, I don't know why I didn't see that.
