### ISSUE TITLE
Vagrant failed to initialize at a very early stage

### ISSUE THREAD

**Issue by amankaushik1988** [hashicorp/vagrant#12479] opened 2021-07-29 07:50 UTC
Hello Team,
While doing Vagrant up i am getting below error, Earlier it was working fine but suddenly it stopped working.

D:\VM\Images\u64-18-04-jenkins>vagrant up
Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3

I am using Window 10 and power shell version is 5.

PFB content of vagrant file.

Vagrant.configure("2") do |config|
  config.vm.define "v", primary: true do |v|
    v.vm.box = "bento/ubuntu-18.04"
    v.vm.hostname = 'u64-18-04-jenkins'
    v.vm.network :private_network, ip: "192.168.56.101"    
	
	v.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--name", "u64-18-04-jenkins"]
	  v.customize ["modifyvm", :id, "--memory", 1024]
	  v.customize ["modifyvm", :id, "--cpus", 1]
    end	 
 end
end

**Comment by chrisroberts** [comment] 2021-08-03 15:08
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2021-08-13 22:33
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2021-08-13 22:33 UTC
Labels: needs info, host/windows
