### ISSUE TITLE
vagrant up ignores --provider parameter (when non-admin)

### ISSUE THREAD

**Issue by skrysmanski** [hashicorp/vagrant#7853] opened 2016-10-02 10:14 UTC
It seems that Vagrant 1.8.6 ignores the `--provider` parameter.

On my Windows 10 box I have Hyper-V installed but no VirtualBox.

So when trying to run even the simplest Vagrant box, I get this output:

```
λ vagrant up --provider=hyperv                                          
No usable default provider could be found for your system.              

Vagrant relies on interactions with 3rd party systems, known as         
"providers", to provide Vagrant with resources to run development       
environments. Examples are VirtualBox, VMware, Hyper-V.                 

The easiest solution to this message is to install VirtualBox, which    
is available for free on all major platforms.                           

If you believe you already have a provider available, make sure it      
is properly installed and configured. You can see more details about    
why a particular provider isn't working by forcing usage with           
`vagrant up --provider=PROVIDER`, which should give you a more specific 
error message for that particular provider.                             
```

Note that I've explicitly specified `hyperv` as provider and according to [this documentation](https://www.vagrantup.com/docs/providers/basic_usage.html) (section: Default Provider) this should be sufficient.

~~The behavior doesn't differ no matter whether I execute this on an Admin console or a regular user console.~~ See update below.

If I set the env variable `VAGRANT_DEFAULT_PROVIDER` to `hyperv`, Vagrant picks up the provider as expected.

**Update:** Actually, it works _only_ on an Admin console. Cmder didn't actually switch to an Admin console when I asked it too.

**Comment by irab** [comment] 2016-10-03 05:12
+1 Same issue here

**Comment by chrisroberts** [comment] 2016-10-03 15:46
This is expected behavior when running from a non-admin origin. Adding more explicit information when known (as in requiring admin) should help make this a bit clearer.

**Comment by chrisroberts** [comment] 2020-03-27 20:20
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2020-03-27 20:20 UTC
Labels: documentation, enhancement, provider/hyperv
