### ISSUE TITLE
vagrant does nothing when running vagrant up

### ISSUE THREAD

**Issue by ElectronicaXAB3** [hashicorp/vagrant#9003] opened 2017-09-27 11:31 UTC
### Vagrant versions
vagrant 2.0.0

### Host operating system
windows 7 x86

### Guest operating system
ubuntu/trusty64

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
end

### Debug output
nothing

### Expected behavior
vagrant start

### Actual behavior
cursor blinking at vagrant up

### Steps to reproduce
1.navigate into desired directory with (git bash or cmd)
2.vagrant init hashicorp/precise64
3.vagrant up

I have read numerous tutorials (official docs, laracasts, etc) and nothing worked. when vagrant up command is issued, it does nothing, the cursor keeps blinking forever.
I even tried using "ubuntu/trusty64" box. Same output.

**Comment by coeki** [comment] 2017-09-28 23:29
Hi @ElectronicaXAB3 

Run into the same thing and did some debug. Turns out for me it was powershell 2.0 that was installed. Updating powershell to the newest version did for me.

**Comment by chrisroberts** [comment] 2017-10-02 19:01
@ElectronicaXAB3 Would you please confirm if you are using powershell 2.0 and if upgrading resolves this issue. Thanks!

**Comment by coeki** [comment] 2017-10-06 16:52
@ElectronicaXAB3 @chrisroberts,

I think we should close this, and open a bug for documentation, to explicitly mention a supported version of powershell (I think > 4.0) for ansible 2.x.

my 2 cents,

Greetz ;)

**Comment by ElectronicaXAB3** [comment] 2017-10-27 08:20
@chrisroberts I will try your suggestion. However, right now I cannot update powershell because of a [dependency error](https://github.com/PowerShell/PowerShell/issues/5254).

**Comment by briancain** [comment] 2017-12-07 18:08
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2017-12-07 18:08 UTC
Labels: host/windows, waiting-reply
