### ISSUE TITLE
VAGRANT BOX ADD UBUNTU/FOCAL64 ERROR

### ISSUE THREAD

**Issue by Tonnamiacart** [hashicorp/vagrant#13255] opened 2023-09-02 19:05 UTC
I am getting this any time I try to add my 'vagrant box add ubuntu/focal64' , Is there a way I can resolve this?

The box 'ubuntu/focal64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/ubuntu/focal64"]
Error: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

I am getting this any time I try to add my 'vagrant box add ubuntu/focal64' , Is there a way I can resolve this?

**Comment by branzoo77** [comment] 2023-09-07 09:46
We experienced the exact same problem, and it turned out to be caused by a firewall blocking the connection to vagrant's online servers. After whitelisting:
https://vagrantcloud.com
cloud-images.ubuntu.com
the box could be added by 'vagrant box add ubuntu/focal64' without issue (although with some waiting time)

**Comment by kaitlincart** [comment] 2023-09-21 16:59
Hi @Tonnamiacart were you able to resolve the issue? Is Vagrant Cloud on your allowlist?

**Comment by chrisroberts** [comment] 2023-10-02 22:59
Hi there,

This has been fixed via #13214 and will be included in the next release. The [following workaround](https://github.com/hashicorp/vagrant/issues/13102#issuecomment-1603083270) can be used if this error is encountered.

Cheers!

**Closed by chrisroberts** 2023-10-02 22:59 UTC
