### ISSUE TITLE
Vagrant up fail with Hyper-V

### ISSUE THREAD

**Issue by Max84** [hashicorp/vagrant#8794] opened 2017-07-19 07:00 UTC
### Vagrant version
1.9.7

### Host operating system
Windows 10 (french version)

### Guest operating system
gusztavvargadr/w10e

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
	Vagrant.require_version ">= 1.9.7"
	config.vm.provider "hyperv"
	config.vm.box = "gusztavvargadr/w10e"
end
```

### Expected behavior
I expect a new VM.

### Actual behavior
I get this error:

F:\>vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured startup memory is 1024
==> default: Configured cpus number is 1
==> default: Importing a Hyper-V instance
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Connect-VMNetworkAdapter : Hyper-V n'a trouvé aucun commutateur virtuel
portant le nom « Pour AccÃ¨s Externe ».
Au caractère C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.7\plugins\prov
iders\hyperv\scripts\import_vm_vmcx.ps1:96 : 1
+ Connect-VMNetworkAdapter -VMNetworkAdapter $vmNetworkAdapter -SwitchN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Connect-VMNetworkAdapter]
   , VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Com
   mands.ConnectVMNetworkAdapter

But i get this commutator "Pour Accès Externe", into Hyper-V.
I suspect, it's due to "è" (seen like this into Hyper-V), but become "Ã¨" with Vagrant.

### Steps to reproduce
1. Vagrant up (only), maybe onto a French Windows Host.

### References
No

**Comment by sylv704** [comment] 2017-11-30 20:02
Hello,
I confirm this issue relates to the accentuated e: if we create a new commutator with no special character it works.

**Comment by LeoColomb** [comment] 2017-12-28 13:15
Confirmed. Seems to be an encoding issue.

```
> vagrant up
Bringing machine 'homestead-7' up with 'hyperv' provider...
==> homestead-7: Verifying Hyper-V is enabled...
==> homestead-7: Importing a Hyper-V instance
    homestead-7: Please choose a switch to attach to your Hyper-V instance.
    homestead-7: If none of these are appropriate, please open the Hyper-V manager
    homestead-7: to create a new virtual switch.
    homestead-7:
    homestead-7: 1) DockerNAT
    homestead-7: 2) Commutateur par défaut
    homestead-7:
    homestead-7: What switch would you like to use? 2
    homestead-7: Cloning virtual hard drive...
    homestead-7: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Connect-VMNetworkAdapter : Hyper-V n'a trouvé aucun commutateur virtuel portant le nom « Commutateur par dÃ©faut ».
Au caractère C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.1\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:96 : 1
+ Connect-VMNetworkAdapter -VMNetworkAdapter $vmNetworkAdapter -SwitchN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Connect-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.ConnectVMNetworkAdapter
```

**Comment by AlexRadch** [comment] 2018-01-12 11:44
I have the same issue with `laravel/homestead` guest OS on Russian Windows 10 Host 
```
Bringing machine 'homestead-7' up with 'hyperv' provider...
==> homestead-7: Verifying Hyper-V is enabled...
==> homestead-7: Importing a Hyper-V instance
    homestead-7: Cloning virtual hard drive...
    homestead-7: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Connect-VMNetworkAdapter : Hyper-V не удалось найти виртуальный коммутатор с именем "Р?Р?Р?Р?С?С".
C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.1\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:96 знак:1
+ Connect-VMNetworkAdapter -VMNetworkAdapter $vmNetworkAdapter -SwitchN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.ConnectVMNetworkAdapter
```

How to workaround this?

**Comment by Prometee** [comment] 2018-01-23 19:50
@AlexRadch Create a new "virtual switch" (виртуальный коммутатор) in Hyper-V Manager with an english name like "Default Virtual Switch" with the same options then retry `vagrant up`

**Comment by AlexRadch** [comment] 2018-01-24 09:20
@Prometee yes it works.

**Comment by jbonhag** [comment] 2020-04-03 20:44
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by jbonhag** 2020-04-03 20:44 UTC
Labels: encoding, host/windows, provider/hyperv

**Comment by jospradlin** [comment] 2020-04-22 21:42
I'm on 2.2.7 and I still get this error:

==> slave2: Starting the machine...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: start_vm.ps1
Error:

**Comment by jbonhag** [comment] 2020-04-23 14:33
Hi @jospradlin,

Sorry that you're seeing this error when bringing up a VM. I see that your error is in the `start_vm.ps1` script, and the original issue mentioned the `import_vm_vmcx.ps1` script. Would you be willing to open up a new issue and fill out the issue template so we can investigate?

Cheers! 😄
