### ISSUE TITLE
bash errors every time when running vagrant commands 

### ISSUE THREAD

**Issue by kylix3511** [hashicorp/vagrant#10023] opened 2018-07-13 19:26 UTC
Following error in running vagrant command every time :  

```
bash: _scp: line 38: syntax error near unexpected token `('
bash: _scp: line 38: ` !(*:*)/* | [.~]*)'
bash: error importing function definition for `_scp'
```

### Vagrant version

```
$vagrant -v
bash: _scp: line 38: syntax error near unexpected token `('
bash: _scp: line 38: ` !(*:*)/* | [.~]*)'
bash: error importing function definition for `_scp'
Vagrant 2.1.2
$
```

### Host operating system

```
$uname -a 
Linux server1 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$
```

### Guest operating system
```
[vagrant@dockernode1 ~]$ uname -a 
Linux dockernode1 4.1.12-112.16.4.el7uek.x86_64 #2 SMP Mon Mar 12 23:57:12 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@dockernode1 ~]$ 
```

Vagrant File is attached in this case.

**Comment by briancain** [comment] 2018-07-13 19:47
Hi @kylix3511 - could you please provide a debug log when you're seeing the bash error? I cannot reproduce it the Vagrantfile provided:

```
brian@localghost:debug % mv Vagrantfile.txt Vagrantfile
brian@localghost:debug % vagrant status
Current machine states:

testnode1                 not created (virtualbox)
testnode2                 not created (virtualbox)
testnode3                 not created (virtualbox)
testnode4                 not created (virtualbox)
testnode5                 not created (virtualbox)
testnode6                 not created (virtualbox)
testnode7                 not created (virtualbox)
testnode8                 not created (virtualbox)
testnode9                 not created (virtualbox)
ansiblec                  not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
brian@localghost:debug % vagrant -v
Vagrant 2.1.2
```

**Comment by briancain** [comment] 2018-07-13 19:50
Also worth asking: How did you install Vagrant? Are you doing something special with your environment? Try getting a "fresh" shell and rerun the vagrant command:

```
bash --norc --noprofile
vagrant -v
```

**Comment by kylix3511** [comment] 2018-07-13 19:58
Hi Brian, 

I install vagrant (like in the older versions)  via command like this 

`
$sudo apt-get remove vagrant
$ wget -c https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb
$ sudo dpkg -i vagrant_2.0.3_x86_64.deb
$
`

Nothing changed or update before and after installation. 


As you mention, i run the in a new terminal as follows : 

`
$bash --norc --noprofile
bash: _scp: line 38: syntax error near unexpected token `('
bash: _scp: line 38: ` !(*:*)/* | [.~]*)'
bash: error importing function definition for `_scp'
$vagrant -v
bash: _scp: line 38: syntax error near unexpected token `('
bash: _scp: line 38: ` !(*:*)/* | [.~]*)'
bash: error importing function definition for `_scp'
Vagrant 2.1.2
$
`

I dont know which 38 line the error referring too ...

**Comment by briancain** [comment] 2018-07-13 20:08
Hm ok. Unfortunately this is not a Vagrant issue. The fact that you see the bash error when you create a new profile means there is something wrong with your environment. You might want to check and see if you are loading up any scripts when you create a new shell some where? I'm going to go ahead and close this issue though since it is not a Vagrant bug. Sorry I couldn't help!

**Closed by briancain** 2018-07-13 20:08 UTC
Labels: waiting-reply
