### ISSUE TITLE
Continuation of #9820

### ISSUE THREAD

**Issue by whiggs** [hashicorp/vagrant#9828] opened 2018-05-11 13:54 UTC
This is a continuation of #9820.  Rather than close the ticket without waiting for a reply (as I am paying attention), which is going to result in a lot of these chained tickets, that can **stop** so that we can participate in an actual **dialog** to ensure things are done properly, rather than this current open/close, open/close, which really only makes it more difficult for you by 1) increasing the amount of tickets further, and 2) creating a long chain of tickets that you will have to go back through to find and look at the original issue (which wouldn't have had to happen if these tickets were being treated as actual tickets.  If there are a surplus of tickets, then you only shoot yourselves in the foot in closing my tickets without any resolution, because I can promise (and do promise) that I will create as many as I need to.  I have no problem producing a more simplistic vagrantfile, even though I specifically mentioned in the ticket that "vagrant up master" was the command generating the problem, so I am just going to copy/paste everything under the "master" section in the vagrantfile (if you are not going to read all of the info, why ask for it?).  I was under the impression that, as the developers, it would simple to pick out the relevant portion of the vagrantfile, so I apologize that I assumed incorrectly.  As for being able to reproduce the issue, as I stated in the original ticket (going to have to hop back a couple of tickets), the issue **only occurs on vms that are joined to a domain but works fine when using the standard "vagrant" username and password on a non-domain joined machine?**  As far as the vagrantfile is concerned, the main difference between the working method and the non-working method is the winrm username and password used to authenticate to winrm on the remote machine, which is why I included the entire vagrant file, so that you could see the difference between the domain configured machines and the non-domain configured machines, but since there seems to be a crippling, ticket closing fear of large vagrant files, I will just include a separate, copy/paste example for you out of the original vagrantfile).  And finally, I don't believe that I am being treated unfairly at all.  What I think (as irrelevant as my thoughts are to you) is that the people who answered the previous tickets (and maybe just the developers of vagrant in general, but I hope not) don't really care if the application works for their end users or not, or about vagrant in general, seeing as how quick you are to close tickets that couldn't even remotely be considered resolved.  Attached are the minimalistic vagrantfiles for your convenience.  Please let me know **IN THIS TICKET, WITHOUT CLOSING IT** if there is anything else you need from me.
[works.txt](https://github.com/hashicorp/vagrant/files/1995530/works.txt)
[trouble.txt](https://github.com/hashicorp/vagrant/files/1995531/trouble.txt)

**Comment by chrisroberts** [comment] 2018-05-11 21:12
Hi there,

I'm sorry that you are frustrated with the responses that you have received on this issue. However, the content of this issue is not acceptable and I ask that you refrain from making disparaging remarks about the developers (myself included) in this issue or any future issues which you may open or participate. I would also ask that you read the [HashiCorp community guidelines](https://www.hashicorp.com/community-guidelines) as well. We are all here to actively work on and make Vagrant better. The inclusion of hostile, belittling, or threatening comments neither helps to move work forward nor in identifying and resolving bugs.  

As it was stated in the last issue (#9820), if you wanted to open a new issue with a minimal Vagrantfile that produced the unexpected errors encountered we would be happy to have a look. This is because the new issue template requests the entirety of the items we would need, including the minimal Vagrantfile and the debug output. We request minimal Vagrantfiles (as were used as examples for reproduction in #9820) because it reduces the scope of things that may be causing unexpected problems (like scripts not behaving correctly). We will commonly close issues that do not follow the issue template, include third party plugins, or are overly complex for local reproduction. This is always done with the request of providing either a cleaner environment (no plugins) and/or a minimal Vagrantfile in a new issue. 

I have taken the time this morning to get a local reproduction of this issue and have created a new issue for tracking it #9830 . The `powershell_elevated_interactive` option is what is causing the issue as it requires the configured user to have an active session running on the machine. When the user does not have an active session, a false success behavior is observed.

Cheers!

**Closed by chrisroberts** 2018-05-11 21:12 UTC
