### ISSUE TITLE
Unable to install vagrant plugins on v2.4.2

### ISSUE THREAD

**Issue by lockefox** [hashicorp/vagrant#13534] opened 2024-11-05 19:05 UTC
### Debug output

```Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0
```

### Expected behavior

on v2.4.1, plugins install without issue.  Both from online repository and local .gem

### Actual behavior

vagrant cannot install plugins

#### Vagrant version
2.4.2

#### Host operating system
MacOS 14.  Both M1 and Intel 

#### Guest operating system
N/A cannot boot machine

#### Steps to reproduce

`vagrant plugin install vagrant-parallels` or `vagrant plugin install vagrant-bindfs`

#### Vagrantfile

Issue is not related to vagrant file

**Comment by zarinfam** [comment] 2024-11-05 21:35
I had this issue on macOS Intel.

The only way I could find to rollback to the previous version was to uninstall the "2.4.2" version and reinstall the "2.4.1" version from the HashiCorp releases page: https://releases.hashicorp.com/

**Comment by maxpdx** [comment] 2024-11-06 03:41
same issue after reboot (and I think updates were installed?).
```
$ uname -a
Linux pine 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
```

**Comment by rick-at-loanbridge-ai** [comment] 2024-11-06 16:48
This worked for me on an M3Pro mac.
 
> 
> It seems that [disabling strict dependency enforcement](https://github.com/hashicorp/vagrant/issues/13510#issuecomment-2431163553) offered a temporary work-around in similar cases in the past, but I haven't tried in this case.

**Comment by Ustimov** [comment] 2024-11-07 12:19
Please search before creating an issue. It's duplicate of: https://github.com/hashicorp/vagrant/issues/13527

**Comment by naikdevendra452** [comment] 2024-11-08 15:14
Downgrade vagrant_2.4.1-1 it will fix the issue.

https://releases.hashicorp.com/vagrant/2.4.1/

**Comment by aparedero** [comment] 2024-11-11 16:04
Same error in Windows 10/Windows 11 when executing 

```
vagrant plugin install vagrant-vbguest
vagrant plugin install vagrant-winnfsd
vagrant plugin install vagrant-hosts
```

Reverting to version 2.4.1 works again

**Comment by Codewithteju** [comment] 2024-11-11 22:02
Hello all, 

For Windows 11 users, you don't need to downgrade the vagrant to 2.4.1 version to resolve the conflicting logger dependency issue, you can setup a environment variable in the system like this below :

- Set Env variable in the Path like this : 
![image](https://github.com/user-attachments/assets/dc5457e8-f915-4d82-aad8-b81898bc758b)
- Reload the terminals or bash shells to reflect the changes 
- That's it!.. You are good to go with installing any plugins with vagrant just like before

**Comment by darkn3rd** [comment] 2024-11-12 01:46
This version should never have been release. It looks like inadequate (if any) quality assurance testing was performed.  The version should be pulled, and release beta or release candidates.

**Comment by trinitronx** [comment] 2024-11-12 02:23
> This version should never have been release. It looks like inadequate (if any) quality assurance testing was performed. The version should be pulled, and release beta or release candidates for 2.4.3.

Similar to #13537, this is a sub-dependency version constraint issue.  Such is the nature of the way that Ruby + Bundler manage gem dependency resolution & version constraints.  Unless Bundler & Ruby adopt a sub-dependency isolation model (e.g. [similar to NPM](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/)), Vagrant + plugins will need to match compatible version constraints for their dependencies across the ecosystem.

Further explanation of the similar issue with `vagrant-libvirt -> excon` dependency [here][1].

While some basic smoke tests of `vagrant plugin install ...` for the most popular plugins would be prudent, it may not be feasible to perform testing across the entire ecosystem of ~`673`[^1] plugins.

[^1]: According to: `gem search vagrant | grep -Ev 'REMOTE GEMS\|^$' | wc -l`, there are currently `673` gems with `vagrant` in the name.

[1]: https://github.com/hashicorp/vagrant/issues/13537#issuecomment-2469416772

**Comment by smdsysadmin** [comment] 2024-11-12 14:05
For those on Windows 11 working inside WSL2 like me, I can confirm that just exporting the environment variable in your .profile or .bashrc works to enable loading plugins as well.

**Comment by chrisroberts** [comment] 2024-11-12 22:14
Vagrant v2.4.3 has been published which includes the fix for this issue. 

Cheers!

**Closed by chrisroberts** 2024-11-12 22:14 UTC
Labels: waiting-intake
