### ISSUE TITLE
basic ubuntu recipes go into guru meditation state, in virtualbox 7.0, vagrant 2.3.4,and 2.3.6... ubuntu jammy (22) LTS.

### ISSUE THREAD

**Issue by jayunit100** [hashicorp/vagrant#13170] opened 2023-05-22 13:06 UTC
Hi folks ! It appears that there are some fundamental issues with simple Vagrantfiles on 2.3.4 and vbox 7... where the machines go into some state called "Guru Meditation".

I whittled this down to a very small vagrant recipe which is unopinionated, and found that the problem still persists....

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
require 'fileutils'

Vagrant.configure(2) do |config|

  ############ Linux Control Plane node ############
  config.vm.define :controlplane do |controlplane|
    controlplane.vm.host_name = "controlplane"
    controlplane.vm.box = "ubuntu/trusty64"

    controlplane.vm.network :private_network, ip:"10.20.30.10"
    controlplane.vm.provider :virtualbox do |vb|
    end
    
end
end
~    
```

Here's the rest of the info: 

### Debug output
```
==> controlplane: Booting VM...               
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "startvm", "b6f5eb56-e7e7-4744-81d9-8593e892a715", "--type", "headless"]                                                       
 INFO subprocess: Command not in installer, restoring original environment...                
DEBUG subprocess: Selecting on IO             
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000                   
DEBUG subprocess: Exit status: 0              
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Customize:0x000000000367c188>                                                                               
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::WaitForCommunicator:0x000000000367c0c0>                                                                                       
 INFO interface: output: Waiting for machine to boot. This may take a few minutes...                                                                                                       
 INFO interface: output: ==> controlplane: Waiting for machine to boot. This may take a few minutes...                                                                                     
==> controlplane: Waiting for machine to boot. This may take a few minutes...                
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "b6f5eb56-e7e7-4744-81d9-8593e892a715", "--machinereadable"]                                                     
 INFO subprocess: Command not in installer, restoring original environment...                
DEBUG subprocess: Selecting on IO             
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "b6f5eb56-e7e7-4744-81d9-8593e892a715", "--machinereadable"]                                                     
 INFO subprocess: Command not in installer, restoring original environment...                
DEBUG subprocess: Selecting on IO             
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000                   
DEBUG subprocess: Exit status: 0              
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000                   
DEBUG subprocess: Exit status: 0              
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "b6f5eb56-e7e7-4744-81d9-8593e892a715", "--machinereadable"]                                                     
 INFO subprocess: Command not in installer, restoring original environment...                
DEBUG subprocess: Selecting on IO             
```

### Expected behavior
Vagrant up with work for a linux VM on a Virtualbox with version 7.x and 2.3.x... 

```
➜ sig-windows-dev-tools git:(82c99bc) ✗ VBoxManage -v
7.0.8r156879
➜ sig-windows-dev-tools git:(82c99bc) ✗ vagrant version
[Vagrantfile] Loading default settings from settings.yaml
Installed Version: 2.3.4
Latest Version: 2.3.6
```

### Actual behavior

Something happens related to the Vagrant created VM where it goes into gururemediation state

#### Vagrant version

Installed Version: 2.3.4

#### Host operating system

Ubuntu 22 LTS

#### Guest operating system

Ubuntu 

#### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
require 'fileutils'

Vagrant.configure(2) do |config|

  ############ Linux Control Plane node ############
  config.vm.define :controlplane do |controlplane|
    controlplane.vm.host_name = "controlplane"
    controlplane.vm.box = "ubuntu/trusty64"

    controlplane.vm.network :private_network, ip:"10.20.30.10"
    controlplane.vm.provider :virtualbox do |vb|
    end
    
end

end
```

**Comment by jayunit100** [comment] 2023-05-22 16:43
any relation to #8878 ? not sure

**Comment by jayunit100** [comment] 2023-05-24 00:42
hi ! so the debug output is 

```
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::IsEnvSet:0x00007fa7223b5cb0>                                                                                                                                                                                                                                                                                                   
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Warden:0x00007fa71d9c36e8>                                                                                                                                                                                                                                                                                                
 INFO warden: Calling IN action: #<Proc:0x00007fa71d929598 /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:126 (lambda)>                                                                                                                                                                                                                                          
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::CloudInitSetup:0x00007fa71d9c3468>                                                                                                                                                                                                                                                                                              
 INFO warden: Calling IN action: #<Proc:0x00007fa71d9a3280 /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:126 (lambda)>                                                                                                                                                                                                                                          
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::CleanupDisks:0x00007fa71e012ff8>                                                                                                                                                                                                                                                                                                
 INFO disk: No previous disk_meta file defined for guest controlplane                                                                                                                                                                                                                                                                                                                        
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Disk:0x00007fa71e445b48>                                                                                                                                                                                                                                                                                                        
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Customize:0x00007fa722a9c538>                                                                                                                                                                                                                                                                                 
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Boot:0x00007fa722aa19e8>                                                                                                                                                                                                                                                                                      
 INFO interface: info: Booting VM...                                                                                                                                                                                                                                                                                                                                                         
 INFO interface: info: ==> controlplane: Booting VM...                                                                                                                                                                                                                                                                                                                                       
==> controlplane: Booting VM...                                                                                                                                                                                                                                                                                                                                                              
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "startvm", "a5dfcac2-6b6a-4e70-aea5-9a3c6355431f", "--type", "headless"]                                                                                                                                                                                                                                                         
 INFO subprocess: Command not in installer, restoring original environment...                                                                                                                                                                                                                                                                                                                
DEBUG subprocess: Selecting on IO                                                                                                                                                                                                                                                                                                                                                            
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000                                                                                                                                                                                                                                                                                                                   
DEBUG subprocess: Exit status: 0                                                                                                                                                                                                                                                                                                                                                             
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Customize:0x00007fa722aabf88>                                                                                                                                                                                                                                                                                 
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::WaitForCommunicator:0x00007fa722aa91c0>                                                                                                                                                                                                                                                                                         
 INFO interface: output: Waiting for machine to boot. This may take a few minutes...                                                                                                                                                                                                                                                                                                         
 INFO interface: output: ==> controlplane: Waiting for machine to boot. This may take a few minutes...                                                                                                                                                                                                                                                                                       
==> controlplane: Waiting for machine to boot. This may take a few minutes...                                                                                                                                                                                                                                                                                                                
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "a5dfcac2-6b6a-4e70-aea5-9a3c6355431f", "--machinereadable"]                                                                                                                                                                                                                                                       
 INFO subprocess: Command not in installer, restoring original environment...                                                                                                                                                                                                                                                                                                                
DEBUG subprocess: Selecting on IO                                                                                                                                                                                                                                                                                                                                                            
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "a5dfcac2-6b6a-4e70-aea5-9a3c6355431f", "--machinereadable"]                                                                                                                                                                                                                                                       
 INFO subprocess: Command not in installer, restoring original environment...                                                                                                                                                                                                                                                                                                                
DEBUG subprocess: Selecting on IO                                                                                                                                                                                                                                                                                                                                                            
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999                                                                                                                                                                                                                                                                                                                   
DEBUG subprocess: Exit status: 0                                                                                                                                                                                                                                                                                                                                                             
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000                                                                                                                                                                                                                                                                                                                   
DEBUG subprocess: Exit status: 0                                                                                                                                                                                                                                                                                                                                                             
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "a5dfcac2-6b6a-4e70-aea5-9a3c6355431f", "--machinereadable"]                                                                                                                                                                                                                                                       
 INFO subprocess: Command not in installer, restoring original environment...                                                                                                                                                                                                                                                                                                                
DEBUG subprocess: Selecting on IO                                                                                                                                                                                                                                                                                                                                                            
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000                                                                                                                                                                                                                                                                                                                   
DEBUG subprocess: Exit status: 0                                                                                                                                                                                                                                                                                                                                                             
ERROR warden: Error occurred: The guest machine entered an invalid state while waiting for it                                                                                                                                                                                                                                                                                                
to boot. Valid states are 'starting, running'. The machine is in the                                                                                                                                                                                                                                                                                                                         
'gurumeditation' state. Please verify everything is configured                                                                                                                                                                                                                                                                                                                               
properly and try again.                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                             
If the provider you're using has a GUI that comes with it,                     
```

and VirtualBox, the gui itself , sais its in the guru mediation state, which is quite opaque....  Any idea what could cause that?  thanks!

**Comment by jayunit100** [comment] 2023-05-24 00:46
not sure if useful but... here are the vbox logs:

```

00:00:00.182226 PIC0:
00:00:00.182227  IMR :00 ISR   :00 IRR   :01 LIRR:01
00:00:00.182229  Base:00 PriAdd:00 RegSel:00
00:00:00.182230  Poll:00 SpMask:00 IState:00
00:00:00.182232  AEOI:00 Rotate:00 FNest :00 Ini4:00
00:00:00.182233  ELCR:00 ELMask:f8
00:00:00.182234 PIC1:
00:00:00.182235  IMR :00 ISR   :00 IRR   :00 LIRR:00
00:00:00.182236  Base:00 PriAdd:00 RegSel:00
00:00:00.182238  Poll:00 SpMask:00 IState:00
00:00:00.182240  AEOI:00 Rotate:00 FNest :00 Ini4:00
00:00:00.182242  ELCR:00 ELMask:de
00:00:00.182243 !!
00:00:00.182244 !! {pirq}
00:00:00.182244 !!
00:00:00.182245 PCI IRQ levels:
00:00:00.182246   IRQA: 0
00:00:00.182247   IRQB: 0
00:00:00.182248   IRQC: 0
00:00:00.182249   IRQD: 0
00:00:00.182250 !!
00:00:00.182250 !! {pit}
00:00:00.182251 !!
00:00:00.182252 PIT (i8254) channel 0 status: irq=0x0
00:00:00.182253       count=00010000  latched_count=0000  count_latched=00
00:00:00.182254            status=00   status_latched=00     read_state=00
00:00:00.182255       write_state=00      write_latch=00        rw_mode=00
00:00:00.182256              mode=03              bcd=00           gate=01
00:00:00.182257   count_load_time=0000000000000000 next_transition_time=0000000001a30c2d
00:00:00.182259       u64ReloadTS=0000000000000000            u64NextTS=0000000001a30c2d
00:00:00.182265 PIT (i8254) channel 1 status: irq=0x0
00:00:00.182266       count=00010000  latched_count=0000  count_latched=00
00:00:00.182267            status=00   status_latched=00     read_state=00
00:00:00.182268       write_state=00      write_latch=00        rw_mode=00
00:00:00.182268              mode=03              bcd=00           gate=01
00:00:00.182269   count_load_time=0000000000000000 next_transition_time=0000000000000000
00:00:00.182270       u64ReloadTS=0000000000000000            u64NextTS=ffffffffffffffff
00:00:00.182276 PIT (i8254) channel 2 status: irq=0x0
00:00:00.182276       count=00010000  latched_count=0000  count_latched=00
00:00:00.182277            status=00   status_latched=00     read_state=00
00:00:00.182278       write_state=00      write_latch=00        rw_mode=00
00:00:00.182279              mode=03              bcd=00           gate=00
00:00:00.182280   count_load_time=0000000000000000 next_transition_time=0000000000000000
00:00:00.182281       u64ReloadTS=0000000000000000            u64NextTS=ffffffffffffffff
00:00:00.182286 speaker_data_on=0x0
00:00:00.182287 !!
00:00:00.182288 !! {plugins}
00:00:00.182288 !!
00:00:00.182289 No plug-ins loaded
00:00:00.182290 !!
00:00:00.182291 !! {ps2c}
00:00:00.182291 !!
00:00:00.182292 Keyboard controller: Active command 00, DBB out 00, translation off
00:00:00.182294 Mode: 03 ( KBD_INT AUX_INT  )
00:00:00.182297 Status: 18 ( CMD UNLOCKED  )
00:00:00.182299 !!
00:00:00.182301 !! {ps2k}
00:00:00.182301 !!
00:00:00.182302 PS/2 Keyboard: scan set 2, scanning enabled, serial line enabled
00:00:00.182304 Active command 00
00:00:00.182305 LED state 00, Num Lock off
00:00:00.182306 Typematic delay 500ms, repeat period 91ms
00:00:00.182308 Command queue: 0 items (4 max)
00:00:00.182310 Input queue  : 0 items (64 max)
00:00:00.182311 !!
00:00:00.182312 !! {ps2m}
00:00:00.182312 !!
00:00:00.182313 PS/2 mouse state: normal, stream mode, reporting disabled, serial line enabled
00:00:00.182315 Protocol: PS/2, scaling 1:1
00:00:00.182317 Active command 00
00:00:00.182318 Sampling rate 100 reports/sec, resolution 4 counts/mm
00:00:00.182320 Command queue: 0 items (8 max)
00:00:00.182321 Event queue  : 0 items (256 max)
00:00:00.182324 !!
00:00:00.182325 !! {rtc}
00:00:00.182326 !!
00:00:00.182327 Time: 00:40:33  Date: 23-05-24
00:00:00.182331 REG A=26 B=02 C=00 D=80
00:00:00.182335 !!
00:00:00.182336 !! {svmvmcbcache}
00:00:00.182336 !!
00:00:00.182344 HM SVM is not enabled for this VM!
00:00:00.182348 !!
00:00:00.182348 !! {tasks}
00:00:00.182348 !!
00:00:00.182350 Task set #0 - handle base 0, pending 0x0 RZ-enabled, running 255, 2 of 64 allocated:
00:00:00.182353  Hnd:   State     Type   pfnCallback      pvUser           Flags  Name
00:00:00.182355    0:   idle     device  00007fb9d9569130 0000000000000000 0x0003 E1000-Xmit
00:00:00.182362    1:   idle     device  00007fb9d9569130 0000000000000000 0x0003 E1000-Xmit
00:00:00.182367 !!
00:00:00.182367 !! {tracebuf}
00:00:00.182368 !!
00:00:00.182369 Tracing is disabled
00:00:00.182370 !!
00:00:00.182370 !! {trpmevent}
00:00:00.182371 !!
00:00:00.182377 CPU[0]: TRPM event (None)
00:00:00.182378 !!
00:00:00.182379 !! {vbe}
00:00:00.182379 !!
00:00:00.182380 LFB at 0000000000000000
00:00:00.182382 VBE disabled
00:00:00.182383 !!
00:00:00.182383 !! {vga}
00:00:00.182383 !!
00:00:00.182384 decoding memory at A000-BFFF
00:00:00.182385 Misc status reg. MSR:00
00:00:00.182386 pixel clock: 25.175 MHz
00:00:00.182387 double scanning off
00:00:00.182388 double clocking off
00:00:00.182389 htotal: 45 px (5 cclk)
00:00:00.182390 vtotal: 2 px
00:00:00.182391 hdisp : 9 px (1 cclk)
00:00:00.182393 vdisp : 1 px
00:00:00.182393 split : 0 ln
00:00:00.182394 start : 0x0
00:00:00.182395 char height 1
00:00:00.182396 text mode 1x1
00:00:00.182397 cbLine:   0x280
00:00:00.182399 offStart: 0x0 (line 0x0)
00:00:00.182400 offCursr: 0x0
00:00:00.182401 display refresh interval: 20 ms
00:00:00.182403 !!
00:00:00.182403 !! {vgaar}
00:00:00.182404 !!
00:00:00.182405 VGA Attribute Controller (3C0): index reg 00, flip-flop: 0 (index)
00:00:00.182407  Palette: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00:00:00.182413  AR10:00 AR11:00 AR12:00 AR13:00 AR14:00
00:00:00.182417 !!
00:00:00.182417 !! {vgacr}
00:00:00.182418 !!
00:00:00.182419 VGA CRTC (3D5): CRTC index 3D4:00
00:00:00.182420  CR00:00 CR01:00 CR02:00 CR03:00 CR04:00 CR05:00 CR06:00 CR07:00 CR08:00 CR09:00
00:00:00.182427  CR0A:00 CR0B:00 CR0C:00 CR0D:00 CR0E:00 CR0F:00 CR10:00 CR11:00 CR12:00 CR13:00
00:00:00.182433  CR14:00 CR15:00 CR16:00 CR17:00 CR18:00
00:00:00.182437 !!
00:00:00.182437 !! {vgadac}
00:00:00.182437 !!
00:00:00.182438 VGA DAC contents:
00:00:00.182439  00: 00 00 00
00:00:00.182440  01: 00 00 00
00:00:00.182442  02: 00 00 00
00:00:00.182444  03: 00 00 00
00:00:00.182447  04: 00 00 00
00:00:00.182449  05: 00 00 00
00:00:00.182451  06: 00 00 00
00:00:00.182453  07: 00 00 00
00:00:00.182455  08: 00 00 00
00:00:00.182457  09: 00 00 00
00:00:00.182459  0A: 00 00 00
00:00:00.182461  0B: 00 00 00
00:00:00.182464  0C: 00 00 00
00:00:00.182466  0D: 00 00 00
00:00:00.182468  0E: 00 00 00
00:00:00.182470  0F: 00 00 00
00:00:00.182472  10: 00 00 00
00:00:00.182473  11: 00 00 00
00:00:00.182475  12: 00 00 00
00:00:00.182476  13: 00 00 00
00:00:00.182477  14: 00 00 00
00:00:00.182478  15: 00 00 00
00:00:00.182480  16: 00 00 00
00:00:00.182483  17: 00 00 00
00:00:00.182484  18: 00 00 00
00:00:00.182485  19: 00 00 00
00:00:00.182487  1A: 00 00 00
00:00:00.182488  1B: 00 00 00
00:00:00.182490  1C: 00 00 00
00:00:00.182493  1D: 00 00 00
00:00:00.182495  1E: 00 00 00
00:00:00.182497  1F: 00 00 00
00:00:00.182499  20: 00 00 00
00:00:00.182501  21: 00 00 00
00:00:00.182503  22: 00 00 00
00:00:00.182505  23: 00 00 00
00:00:00.182507  24: 00 00 00
00:00:00.182510  25: 00 00 00
00:00:00.182512  26: 00 00 00
00:00:00.182514  27: 00 00 00
00:00:00.182517  28: 00 00 00
00:00:00.182519  29: 00 00 00
00:00:00.182521  2A: 00 00 00
00:00:00.182523  2B: 00 00 00
00:00:00.182525  2C: 00 00 00
00:00:00.182526  2D: 00 00 00
00:00:00.182527  2E: 00 00 00
00:00:00.182528  2F: 00 00 00
00:00:00.182530  30: 00 00 00
00:00:00.182531  31: 00 00 00
00:00:00.182532  32: 00 00 00
00:00:00.182534  33: 00 00 00
00:00:00.182535  34: 00 00 00
00:00:00.182536  35: 00 00 00
00:00:00.182537  36: 00 00 00
00:00:00.182539  37: 00 00 00
00:00:00.182540  38: 00 00 00
00:00:00.182541  39: 00 00 00
00:00:00.182545  3A: 00 00 00
00:00:00.182546  3B: 00 00 00
00:00:00.182547  3C: 00 00 00
00:00:00.182548  3D: 00 00 00
00:00:00.182550  3E: 00 00 00
00:00:00.182551  3F: 00 00 00
00:00:00.182552  40: 00 00 00
00:00:00.182554  41: 00 00 00
00:00:00.182555  42: 00 00 00
00:00:00.182556  43: 00 00 00
00:00:00.182557  44: 00 00 00
00:00:00.182559  45: 00 00 00
00:00:00.182560  46: 00 00 00
00:00:00.182561  47: 00 00 00
00:00:00.182562  48: 00 00 00
00:00:00.182564  49: 00 00 00
00:00:00.182565  4A: 00 00 00
00:00:00.182566  4B: 00 00 00
00:00:00.182567  4C: 00 00 00
00:00:00.182569  4D: 00 00 00
00:00:00.182570  4E: 00 00 00
00:00:00.182571  4F: 00 00 00
00:00:00.182572  50: 00 00 00
00:00:00.182574  51: 00 00 00
00:00:00.182575  52: 00 00 00
00:00:00.182576  53: 00 00 00
00:00:00.182577  54: 00 00 00
00:00:00.182579  55: 00 00 00
00:00:00.182580  56: 00 00 00
00:00:00.182581  57: 00 00 00
00:00:00.182582  58: 00 00 00
00:00:00.182584  59: 00 00 00
00:00:00.182585  5A: 00 00 00
00:00:00.182586  5B: 00 00 00
00:00:00.182587  5C: 00 00 00
00:00:00.182589  5D: 00 00 00
00:00:00.182590  5E: 00 00 00
00:00:00.182591  5F: 00 00 00
00:00:00.182593  60: 00 00 00
00:00:00.182594  61: 00 00 00
00:00:00.182595  62: 00 00 00
00:00:00.182596  63: 00 00 00
00:00:00.182598  64: 00 00 00
00:00:00.182599  65: 00 00 00
00:00:00.182600  66: 00 00 00
00:00:00.182601  67: 00 00 00
00:00:00.182604  68: 00 00 00
00:00:00.182605  69: 00 00 00
00:00:00.182607  6A: 00 00 00
00:00:00.182608  6B: 00 00 00
00:00:00.182609  6C: 00 00 00
00:00:00.182610  6D: 00 00 00
00:00:00.182612  6E: 00 00 00
00:00:00.182613  6F: 00 00 00
00:00:00.182614  70: 00 00 00
00:00:00.182615  71: 00 00 00
00:00:00.182617  72: 00 00 00
00:00:00.182618  73: 00 00 00
00:00:00.182619  74: 00 00 00
00:00:00.182620  75: 00 00 00
00:00:00.182622  76: 00 00 00
00:00:00.182623  77: 00 00 00
00:00:00.182624  78: 00 00 00
00:00:00.182625  79: 00 00 00
00:00:00.182627  7A: 00 00 00
00:00:00.182628  7B: 00 00 00
00:00:00.182629  7C: 00 00 00
00:00:00.182630  7D: 00 00 00
00:00:00.182632  7E: 00 00 00
00:00:00.182633  7F: 00 00 00
00:00:00.182634  80: 00 00 00
00:00:00.182635  81: 00 00 00
00:00:00.182637  82: 00 00 00
00:00:00.182638  83: 00 00 00
00:00:00.182639  84: 00 00 00
00:00:00.182640  85: 00 00 00
00:00:00.182642  86: 00 00 00
00:00:00.182643  87: 00 00 00
00:00:00.182644  88: 00 00 00
00:00:00.182646  89: 00 00 00
00:00:00.182647  8A: 00 00 00
00:00:00.182648  8B: 00 00 00
00:00:00.182649  8C: 00 00 00
00:00:00.182651  8D: 00 00 00
00:00:00.182652  8E: 00 00 00
00:00:00.182653  8F: 00 00 00
00:00:00.182654  90: 00 00 00
00:00:00.182656  91: 00 00 00
00:00:00.182657  92: 00 00 00
00:00:00.182658  93: 00 00 00
00:00:00.182659  94: 00 00 00
00:00:00.182661  95: 00 00 00
00:00:00.182662  96: 00 00 00
00:00:00.182665  97: 00 00 00
00:00:00.182666  98: 00 00 00
00:00:00.182667  99: 00 00 00
00:00:00.182669  9A: 00 00 00
00:00:00.182670  9B: 00 00 00
00:00:00.182671  9C: 00 00 00
00:00:00.182672  9D: 00 00 00
00:00:00.182674  9E: 00 00 00
00:00:00.182675  9F: 00 00 00
00:00:00.182676  A0: 00 00 00
00:00:00.182678  A1: 00 00 00
00:00:00.182679  A2: 00 00 00
00:00:00.182680  A3: 00 00 00
00:00:00.182681  A4: 00 00 00
00:00:00.182683  A5: 00 00 00
00:00:00.182684  A6: 00 00 00
00:00:00.182685  A7: 00 00 00
00:00:00.182687  A8: 00 00 00
00:00:00.182688  A9: 00 00 00
00:00:00.182689  AA: 00 00 00
00:00:00.182690  AB: 00 00 00
00:00:00.182692  AC: 00 00 00
00:00:00.182693  AD: 00 00 00
00:00:00.182694  AE: 00 00 00
00:00:00.182695  AF: 00 00 00
00:00:00.182697  B0: 00 00 00
00:00:00.182698  B1: 00 00 00
00:00:00.182699  B2: 00 00 00
00:00:00.182700  B3: 00 00 00
00:00:00.182702  B4: 00 00 00
00:00:00.182703  B5: 00 00 00
00:00:00.182704  B6: 00 00 00
00:00:00.182705  B7: 00 00 00
00:00:00.182707  B8: 00 00 00
00:00:00.182708  B9: 00 00 00
00:00:00.182709  BA: 00 00 00
00:00:00.182710  BB: 00 00 00
00:00:00.182712  BC: 00 00 00
00:00:00.182713  BD: 00 00 00
00:00:00.182714  BE: 00 00 00
00:00:00.182716  BF: 00 00 00
00:00:00.182718  C0: 00 00 00
00:00:00.182720  C1: 00 00 00
00:00:00.182722  C2: 00 00 00
00:00:00.182727  C3: 00 00 00
00:00:00.182729  C4: 00 00 00
00:00:00.182731  C5: 00 00 00
00:00:00.182733  C6: 00 00 00
00:00:00.182735  C7: 00 00 00
00:00:00.182737  C8: 00 00 00
00:00:00.182740  C9: 00 00 00
00:00:00.182742  CA: 00 00 00
00:00:00.182744  CB: 00 00 00
00:00:00.182746  CC: 00 00 00
00:00:00.182747  CD: 00 00 00
00:00:00.182748  CE: 00 00 00
00:00:00.182750  CF: 00 00 00
00:00:00.182751  D0: 00 00 00
00:00:00.182752  D1: 00 00 00
00:00:00.182754  D2: 00 00 00
00:00:00.182755  D3: 00 00 00
00:00:00.182756  D4: 00 00 00
00:00:00.182757  D5: 00 00 00
00:00:00.182759  D6: 00 00 00
00:00:00.182760  D7: 00 00 00
00:00:00.182761  D8: 00 00 00
00:00:00.182762  D9: 00 00 00
00:00:00.182764  DA: 00 00 00
00:00:00.182765  DB: 00 00 00
00:00:00.182766  DC: 00 00 00
00:00:00.182768  DD: 00 00 00
00:00:00.182769  DE: 00 00 00
00:00:00.182770  DF: 00 00 00
00:00:00.182771  E0: 00 00 00
00:00:00.182773  E1: 00 00 00
00:00:00.182774  E2: 00 00 00
00:00:00.182775  E3: 00 00 00
00:00:00.182778  E4: 00 00 00
00:00:00.182779  E5: 00 00 00
00:00:00.182781  E6: 00 00 00
00:00:00.182782  E7: 00 00 00
00:00:00.182783  E8: 00 00 00
00:00:00.182786  E9: 00 00 00
00:00:00.182788  EA: 00 00 00
00:00:00.182789  EB: 00 00 00
00:00:00.182790  EC: 00 00 00
00:00:00.182791  ED: 00 00 00
00:00:00.182793  EE: 00 00 00
00:00:00.182794  EF: 00 00 00
00:00:00.182795  F0: 00 00 00
00:00:00.182796  F1: 00 00 00
00:00:00.182798  F2: 00 00 00
00:00:00.182799  F3: 00 00 00
00:00:00.182800  F4: 00 00 00
00:00:00.182802  F5: 00 00 00
00:00:00.182803  F6: 00 00 00
00:00:00.182804  F7: 00 00 00
00:00:00.182805  F8: 00 00 00
00:00:00.182807  F9: 00 00 00
00:00:00.182808  FA: 00 00 00
00:00:00.182809  FB: 00 00 00
00:00:00.182810  FC: 00 00 00
00:00:00.182812  FD: 00 00 00
00:00:00.182813  FE: 00 00 00
00:00:00.182814  FF: 00 00 00
00:00:00.182816 !!
00:00:00.182816 !! {vgagr}
00:00:00.182817 !!
00:00:00.182818 VGA Graphics Controller (3CF): GR index 3CE:00
00:00:00.182819  GR00:00 GR01:00 GR02:00 GR03:00 GR04:00 GR05:00 GR06:00 GR07:00 GR08:00
00:00:00.182825 !!
00:00:00.182826 !! {vgapl}
00:00:00.182826 !!
00:00:00.182827 read mode     : 0     write mode: 0
00:00:00.182830 set/reset data: 00    S/R enable: 00
00:00:00.182832 color compare : 00    read map  : 0
00:00:00.182833 rotate        : 0     function  : 0
00:00:00.182835 don't care    : 00    bit mask  : 00
00:00:00.182837 seq plane mask: 00    chain-4   : off
00:00:00.182839 !!
00:00:00.182840 !! {vgasr}
00:00:00.182840 !!
00:00:00.182842 VGA Sequencer (3C5): SR index 3C4:00
00:00:00.182843  SR00:00 SR01:00 SR02:00 SR03:00 SR04:00 SR05:00 SR06:00 SR07:00
00:00:00.182854 !!
00:00:00.182854 !! {vgatext}
00:00:00.182855 !!
00:00:00.182865 ------------------------------------ 80x25 -------------------------------------
00:00:00.182880 ................................................................................
00:00:00.182903 ................................................................................
00:00:00.182924 ................................................................................
00:00:00.182938 ................................................................................
00:00:00.182953 ................................................................................
00:00:00.182969 ................................................................................
00:00:00.182984 ................................................................................
00:00:00.182999 ................................................................................
00:00:00.183013 ................................................................................
00:00:00.183029 ................................................................................
00:00:00.183044 ................................................................................
00:00:00.183059 ................................................................................
00:00:00.183073 ................................................................................
00:00:00.183095 ................................................................................
00:00:00.183115 ................................................................................
00:00:00.183135 ................................................................................
00:00:00.183157 ................................................................................
00:00:00.183177 ................................................................................
00:00:00.183197 ................................................................................
00:00:00.183218 ................................................................................
00:00:00.183238 ................................................................................
00:00:00.183258 ................................................................................
00:00:00.183279 ................................................................................
00:00:00.183299 ................................................................................
00:00:00.183319 ................................................................................
00:00:00.183341 --------------------------------------------------------------------------------
00:00:00.183362 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by jayunit100** [comment] 2023-05-24 01:09
hi ! So i did an experiment, removing the private network, and still see the same error, and i posted this in the virtualbox forum , here https://forums.virtualbox.org/viewtopic.php?f=7&t=109382 ...... We can wait to see what they say

**Comment by chrisroberts** [comment] 2023-05-25 15:59
Do you have KVM installed and enabled on this system?

**Comment by jayunit100** [comment] 2023-05-27 11:01
Hi! In general does kvm conflict with virtualbox ? I will double check

**Comment by chrisroberts** [comment] 2023-06-16 21:19
Hi there,

Given that this is most likely a local configuration issue or a VirtualBox related problem, I'm going to close this issue. If you feel that it is an issue being caused by Vagrant please feel free to open a new issue and we can investigate further. 

Cheers!

**Closed by chrisroberts** 2023-06-16 21:19 UTC
Labels: waiting-reply, provider/virtualbox, host/ubuntu
