### ISSUE TITLE
mount.nfs: requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by nextgenthemes** [hashicorp/vagrant#11666] opened 2020-06-03 16:16 UTC
Assuming still the same as #9666 

This was working in the past but it came up after some update. I have it working by having 3 nfs related packages hold back, they also hold a bunch of dependencies back. I am rolling like this for over 6 months I think, gave it another try today and still not working with the latest versions.

I roll back now and tell you the packages I locked.

```bash
$ sudo zypper locks

# | Name              | Typ     | Repository
--+-------------------+---------+-----------
1 | nfs-client        | package | (beliebig)
2 | nfs-kernel-server | package | (beliebig)
3 | nfsidmap          | package | (beliebig)
```
With this packages locked from a long time ago it works. I noticed during upgrade that `vfsidmap` gets removed and replaced by `nfidmap1` or something like that. I do not know how to show all the deps that also get hold back but this are the root packages, not sure what package it is exactly that triggered the bug.

### Vagrant version

Vagrant 2.2.9

### Host operating system

Open Suse Tumbleweed

### Guest operating system

Ubuntu 18.04

### Vagrantfile

```ruby
ANSIBLE_PATH = __dir__ # absolute path to Ansible directory on host machine
ANSIBLE_PATH_ON_VM = '/home/vagrant/trellis'.freeze # absolute path to Ansible directory on virtual machine

require File.join(ANSIBLE_PATH, 'lib', 'trellis', 'vagrant')
require File.join(ANSIBLE_PATH, 'lib', 'trellis', 'config')
require 'yaml'

vconfig = YAML.load_file("#{ANSIBLE_PATH}/vagrant.default.yml")

if File.exist?("#{ANSIBLE_PATH}/vagrant.local.yml")
  local_config = YAML.load_file("#{ANSIBLE_PATH}/vagrant.local.yml")
  vconfig.merge!(local_config) if local_config
end

ensure_plugins(vconfig.fetch('vagrant_plugins')) if vconfig.fetch('vagrant_install_plugins')

trellis_config = Trellis::Config.new(root_path: ANSIBLE_PATH)

Vagrant.require_version '>= 2.1.0'

Vagrant.configure('2') do |config|

  # NICO
  config.vm.network "public_network"

  config.vm.box = vconfig.fetch('vagrant_box')
  config.vm.box_version = vconfig.fetch('vagrant_box_version')
  config.ssh.forward_agent = true
  config.vm.post_up_message = post_up_message

  # Fix for: "stdin: is not a tty"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = %(bash -c 'BASH_ENV=/etc/profile exec bash')

  # Required for NFS to work
  if vconfig.fetch('vagrant_ip') == 'dhcp'
    config.vm.network :private_network, type: 'dhcp', hostsupdater: 'skip'

    cached_addresses = {}
    config.hostmanager.ip_resolver = proc do |vm|
      if cached_addresses[vm.name].nil?
        if vm.communicate.ready?
          vm.communicate.execute("hostname -I | cut -d ' ' -f 2") do |_type, contents|
            cached_addresses[vm.name] = contents.split("\n").first[/(\d+\.\d+\.\d+\.\d+)/, 1]
          end
        end
      end
      cached_addresses[vm.name]
    end
  else
    config.vm.network :private_network, ip: vconfig.fetch('vagrant_ip'), hostsupdater: 'skip'
  end

  main_hostname, *hostnames = trellis_config.site_hosts_canonical
  config.vm.hostname = main_hostname

  if Vagrant.has_plugin?('vagrant-hostmanager') && !trellis_config.multisite_subdomains?
    redirects = trellis_config.site_hosts_redirects

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.aliases = hostnames + redirects
  elsif Vagrant.has_plugin?('landrush') && trellis_config.multisite_subdomains?
    config.landrush.enabled = true
    config.landrush.tld = trellis_config.site_hosts_canonical.reject { |host| host.end_with?(".#{main_hostname}") }
    hostnames.each { |host| config.landrush.host host, vconfig.fetch('vagrant_ip') }
  else
    fail_with_message "vagrant-hostmanager missing, please install the plugin with this command:\nvagrant plugin install vagrant-hostmanager\n\nOr install landrush for multisite subdomains:\nvagrant plugin install landrush"
  end

  bin_path = File.join(ANSIBLE_PATH_ON_VM, 'bin')

  vagrant_mount_type = vconfig.fetch('vagrant_mount_type')

  extra_options = if vagrant_mount_type == 'smb'
    {
      smb_username: vconfig.fetch('vagrant_smb_username', 'vagrant'),
      smb_password: vconfig.fetch('vagrant_smb_password', 'vagrant'),
    }
  else
    {}
  end

  if vagrant_mount_type != 'nfs' || Vagrant::Util::Platform.wsl? || (Vagrant::Util::Platform.windows? && !Vagrant.has_plugin?('vagrant-winnfsd'))
    vagrant_mount_type = nil if vagrant_mount_type == 'nfs'
    trellis_config.wordpress_sites.each_pair do |name, site|
      config.vm.synced_folder local_site_path(site), remote_site_path(name, site), owner: 'vagrant', group: 'www-data', mount_options: mount_options(vagrant_mount_type, dmode: 776, fmode: 775), type: vagrant_mount_type, **extra_options
    end

    config.vm.synced_folder ANSIBLE_PATH, ANSIBLE_PATH_ON_VM, mount_options: mount_options(vagrant_mount_type, dmode: 755, fmode: 644), type: vagrant_mount_type, **extra_options
    config.vm.synced_folder File.join(ANSIBLE_PATH, 'bin'), bin_path, mount_options: mount_options(vagrant_mount_type, dmode: 755, fmode: 755), type: vagrant_mount_type, **extra_options
  elsif !Vagrant.has_plugin?('vagrant-bindfs')
    fail_with_message "vagrant-bindfs missing, please install the plugin with this command:\nvagrant plugin install vagrant-bindfs"
  else
    trellis_config.wordpress_sites.each_pair do |name, site|
      config.vm.synced_folder local_site_path(site), nfs_path(name), type: 'nfs'
      config.bindfs.bind_folder nfs_path(name), remote_site_path(name, site), u: 'vagrant', g: 'www-data', o: 'nonempty'
    end

    config.vm.synced_folder ANSIBLE_PATH, '/ansible-nfs', type: 'nfs'
    config.bindfs.bind_folder '/ansible-nfs', ANSIBLE_PATH_ON_VM, o: 'nonempty', p: '0644,a+D'
    config.bindfs.bind_folder bin_path, bin_path, perms: '0755'
  end

  vconfig.fetch('vagrant_synced_folders', []).each do |folder|
    options = {
      type: folder.fetch('type', 'nfs'),
      create: folder.fetch('create', false),
      mount_options: folder.fetch('mount_options', [])
    }

    destination_folder = folder.fetch('bindfs', true) ? nfs_path(folder['destination']) : folder['destination']

    config.vm.synced_folder folder['local_path'], destination_folder, options

    if folder.fetch('bindfs', true)
      config.bindfs.bind_folder destination_folder, folder['destination'], folder.fetch('bindfs_options', {})
    end
  end

  provisioner = local_provisioning? ? :ansible_local : :ansible
  provisioning_path = local_provisioning? ? ANSIBLE_PATH_ON_VM : ANSIBLE_PATH

  # Fix for https://github.com/hashicorp/vagrant/issues/10914
  if local_provisioning?
    config.vm.provision 'shell', inline: <<~SHELL
      sudo apt-get update -y -qq &&
      sudo dpkg-reconfigure libc6 &&
      export DEBIAN_FRONTEND=noninteractive &&
      sudo -E apt-get -q --option \"Dpkg::Options::=--force-confold\" --assume-yes install libssl1.1
    SHELL
  end

  config.vm.provision provisioner do |ansible|
    if local_provisioning?
      ansible.install_mode = 'pip'
      if Vagrant::VERSION >= '2.2.5'
        # Fix for https://github.com/hashicorp/vagrant/issues/10950
        ansible.pip_install_cmd = 'curl https://bootstrap.pypa.io/get-pip.py | sudo python'
      end
      ansible.provisioning_path = provisioning_path
      ansible.version = vconfig.fetch('vagrant_ansible_version')
    end

    ansible.compatibility_mode = '2.0'
    ansible.playbook = File.join(provisioning_path, 'dev.yml')
    ansible.galaxy_role_file = File.join(provisioning_path, 'galaxy.yml') unless vconfig.fetch('vagrant_skip_galaxy') || ENV['SKIP_GALAXY']
    ansible.galaxy_roles_path = File.join(provisioning_path, 'vendor/roles')

    ansible.groups = {
      'web' => ['default'],
      'development' => ['default']
    }

    ansible.tags = ENV['ANSIBLE_TAGS']
    ansible.extra_vars = { 'vagrant_version' => Vagrant::VERSION }

    if (vars = ENV['ANSIBLE_VARS'])
      extra_vars = Hash[vars.split(',').map { |pair| pair.split('=') }]
      ansible.extra_vars.merge!(extra_vars)
    end

    if !Vagrant::Util::Platform.windows?
      config.trigger.after :up do |trigger|
        # Add Vagrant ssh-config to ~/.ssh/config
        trigger.info = "Adding vagrant ssh-config for #{main_hostname } to ~/.ssh/config"
        trigger.ruby do
          update_ssh_config(main_hostname)
        end
      end
    end
  end

  # VirtualBox settings
  config.vm.provider 'virtualbox' do |vb|
    vb.name = config.vm.hostname
    vb.customize ['modifyvm', :id, '--cpus', vconfig.fetch('vagrant_cpus')]
    vb.customize ['modifyvm', :id, '--memory', vconfig.fetch('vagrant_memory')]
    vb.customize ['modifyvm', :id, '--ioapic', vconfig.fetch('vagrant_ioapic', 'on')]

    # Fix for slow external network connections
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', vconfig.fetch('vagrant_natdnshostresolver', 'on')]
    vb.customize ['modifyvm', :id, '--natdnsproxy1', vconfig.fetch('vagrant_natdnsproxy', 'on')]
  end

  # VMware Workstation/Fusion settings
  %w(vmware_fusion vmware_workstation).each do |provider|
    config.vm.provider provider do |vmw|
      vmw.vmx['displayName'] = config.vm.hostname
      vmw.vmx['numvcpus'] = vconfig.fetch('vagrant_cpus')
      vmw.vmx['memsize'] = vconfig.fetch('vagrant_memory')
    end
  end

  # Parallels settings
  config.vm.provider 'parallels' do |prl|
    prl.name = config.vm.hostname
    prl.cpus = vconfig.fetch('vagrant_cpus')
    prl.memory = vconfig.fetch('vagrant_memory')
    prl.update_guest_tools = true
  end

  # Hyper-V settings
  config.vm.provider 'hyperv' do |h|
    h.vmname = config.vm.hostname
    h.cpus = vconfig.fetch('vagrant_cpus')
    h.memory = vconfig.fetch('vagrant_memory')
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output

https://gist.github.com/nextgenthemes/8103365b796a91f2e6b8dd473a33495b

### Steps to reproduce

1. vagrant up

### References

- #9666

**Comment by briancain** [comment] 2020-06-29 20:38
@nextgenthemes - Can you confirm that your nfs server is properly running when running Vagrant? And that you also have the right client installed, and that neither process is frozen? Are you able to manually run the mount command outside of Vagrant, and do you get the same result?

**Comment by nextgenthemes** [comment] 2020-06-29 20:49
What is "the right client"?

I am running those mentioned packages without any other configuration done. As soon as they are updated it fails. Did you actually try to reproduce this? I do not know what exact commands vagrant runs and I do not think my NFS server was not running. Does vagrant not start it when needed? Is it not autostarted when installed?

Sound like you are shooting in the dark. You just close the other issue that had multiple people having this issue without any resolution.

**Comment by briancain** [comment] 2020-06-29 20:58
@nextgenthemes I'm not shooting in the dark, I'm trying to help you solve _your_ problem. I would like to remind you to please be respectful when interacting with people on GitHub.

Vagrant does not start or manage your nfs clients or server tools. If they aren't installed or running, then Vagrant can't use them. Vagrant invokes a mount command, which you can find in your debug log. The error you received is an error from the mount command. Looking up that error you received  indicates that it's an issue with the nfs tools that you are using. So I'm asking you to please do some due diligence and make sure the tools you are trying to use are working properly. I can't do this for you, because I don't have access to your machine and there isn't any info in the logs about NFS running, so this is why I asked the question. Since you said you "think" it's running, please actually check this like I had originally requested. The error you received can be pointed back to NFS server not running. There are also plenty of proposed solutions in that original issue which you have yet to mention trying, so I recommend going through that issue to see if it resolves your problem. Thanks.

**Comment by nextgenthemes** [comment] 2020-06-29 21:27
> I'm not shooting in the dark, I'm trying to help you solve your problem. I would like to remind you to please be respectful when interacting with people on GitHub.

It's _your_ software, you just rudely close issues off for absolutely no reason because it **might** no longer be an issue. But hey I am respectful for stating facts.

So guessing by the fact that you did not answer my question if you tried to reproduce that you did **not** try to reproduce this. So yes to me is seems you just making wild guesses instead if actually trying to reproduce it.

> If they aren't installed or running, then Vagrant can't use them.

Again my question why should it not be running? When it runs now why should it suddenly stop running when I update the packages?

> Vagrant invokes a mount command

What mount command, again question not answered.

> The error you received is an error from the mount command. Looking up that error you received indicates that it's an issue with the nfs tools that you are using.

"The NFS tools" are the original untouched tumbleweed packages. Still, no clue what your "the right client" is supposed to tell me.

> I can't do this for you, because I don't have access to your machine

Correct, what you can do is to actually install the latest tumbleweed and try to reproduce it with the latest packages. Seems like you rather make wild (or not so wild) guesses. But if my not so wild guess is wrong then sorry.

> Since you said you "think" it's running, please actually check this like I had originally requested.

> There are also plenty of proposed solutions in that original issue which you have yet to mention trying, 

So you just throw accusations around that I never tried anything. But hey I am the respectful one. I already spend hours trail and erroring, trying all kinds of things people suggested there and nothing helped. I watched the issue being ignored and then rudely close off ... I think I commented on the other issue about trying something but you did not read it did you. Because closing issue off is so helpful.

So the error does 100% come from NFS not running? I am skeptical about this and I feel not really like going down some tail and error hell again when you are not even willing to try to reproduce it. Maybe for some strange reason the updated package no longer autostarts automatically. Maybe all it needs is a `sudo systemctl enable nfs-server` or something like that, but I am skeptical. Why should it be like that? I am actually expecting something that makes it crash on start or actually that its actually not about it not running at all. Maybe I try at some point but currently it works for me with the old packages and I do not feel like spending more time doing __your__ job.

**Comment by nextgenthemes** [comment] 2020-06-29 21:42
This is on my current setup with the outdated packages. Is shows as active but exited. So it's not running? I am not sure what this means but `Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; vendor preset: disabled)` exited, disabled, disabled and still vagrant works ...

I guess I compare this with the updated packages if I every try again.

```
sudo systemctl status nfs-server
[sudo] Passwort für root: 
● nfs-server.service - NFS server and services
     Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; vendor preset: disabled)
    Drop-In: /usr/lib/systemd/system/nfs-server.service.d
             └─nfsserver.conf, options.conf
             /run/systemd/generator/nfs-server.service.d
             └─order-with-mounts.conf
     Active: active (exited) since Mon 2020-06-29 13:35:20 CEST; 10h ago
    Process: 3643 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
    Process: 3644 ExecStart=/usr/sbin/rpc.nfsd $NFSD_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 3644 (code=exited, status=0/SUCCESS)

Jun 29 13:35:19 linux-hbls systemd[1]: Starting NFS server and services...
Jun 29 13:35:20 linux-hbls systemd[1]: Finished NFS server and services.
```

**Comment by briancain** [comment] 2020-06-29 23:07
I'm sorry that you think that I'm taking wild guesses. I can promise you this is not the case. The questions I ask are for specific reasons. I'm asking you to tell me the status of your nfs server. A lot of time could be saved going back and forth trying to solve your problem here. I am trying to ask very specific and pointed questions so that we can figure out the source of the problem on your machine.

- Asking about the status of nfs-server will let us know if its an issue with nfs-server not running, which would cause an error like the one you received.
- Running the `mount` command manually on your guest would also give us an idea if it's an issue outside of Vagrant. Vagrant simply runs the mount.nfs command that was printed in your debug log. It's a common debug strategy since all Vagrant is doing is running the mount command. If the mount command fails in the same way, then that narrows your issue down.

> Again my question why should it not be running? When it runs now why should it suddenly stop running when I update the packages? (and I always tried with rebooting)

Services can halt for any number of reasons. I don't know why yours might be stopped. And as of your last comment, it looks like it has been stopped and exited, which is probably why you got the error you received. Your NFS server needs to be running to use NFS with synced folders. You can configure services to autostart so that nfs-server is always running. Something like this:

```
sudo systemctl enable nfs-server
```

> What mount command, again question not answered.

The command is in the error you shared:

```
mount -o vers=3,udp 192.168.50.1:/u/w/nn /vagrant-nfs-nn
```

> "The NFS tools" are the original untouched tumbleweed packages. Still, no clue what your "the right client" is supposed to tell me.

There was no hidden meaning behind "correct". You need an NFS server and client installed. That's all I meant.

> So you just throw accusations around that I never tried anything. But hey I am the disrespectful one. I already spend hours trail and erroring, trying all kinds of things people suggested there and nothing helped. I watched the issue being ignored and then rudely close off ... I think I commented on the other issue about trying something but you did not read it did you. Because closing issue off is so helpful.

I'm sorry you think closing issues is rude, but it doesn't prevent anyone from opening a new one, as you just did. The problem with these kinds of commonly run into issues is they get off topic. That issue has a large range of people posing with different environments and setups. And this kind of issue is usually a result of a misconfiguration on the users machine, rather than a Vagrant bug. This repository is specifically for bugs with Vagrant. Given that the issue has _multiple_ working solutions for folks that have multiple positive emojis, we closed it. Again, that doesn't mean the issue is over forever just because it's closed. Closing it encourages people who are still encountering the issue to open new ones.

> 
> So the error does 100% come from NFS not running? I am skeptical about this and I feel not really like going down some tail and error hell again when you are not even willing to try to reproduce it. Maybe for some strange reason the updated package no longer autostarts automatically. Maybe all it needs is a `sudo systemctl enable nfs-server` or something like that, but I am skeptical. Why should it be like that? I am actually expecting something that makes it crash on start or actually that its actually not about it not running at all. Maybe I try at some point but currently it works for me with the old packages and I do not feel like spending more time doing **your** job.

I can't do my job if you aren't willing to give me more information about your environment and go through the steps I'm asking for triage. But since you shared the status of your nfs-server, it looks like it had exited and isn't running. Which, as mentioned in the issue you linked to, is a root cause for `mount.nfs` failing to mount a shared folder. NFS Sever needs to be running/active for NFS to work. So if that's the case, please close this issue.

Finally, I'm going to remind you again about our [Community Guidelines](https://www.hashicorp.com/community-guidelines). Please read them and understand before interacting again.

**Comment by chrisroberts** [comment] 2020-07-06 21:33
Closing as this issue has been resolved.

**Closed by chrisroberts** 2020-07-06 21:33 UTC
Labels: waiting-reply
