### ISSUE TITLE
2.2.13 breaks landrush plugin to take effect

### ISSUE THREAD

**Issue by otto802** [hashicorp/vagrant#12040] opened 2020-11-12 13:38 UTC
### Vagrant version

2.2.13

### Host operating system

Mac OS 10.15.7

### Guest operating system

Centos 7

### Vagrantfile

```ruby
  config.vm.define 'competition-dev' do |res|
    res.vm.box = 'centos/7'
    res.vm.hostname = 'competition-dev.mtlocal'
    res.landrush.enabled = true
    res.landrush.tld = 'mtlocal'
    res.landrush.guest_redirect_dns = false
    res.vm.synced_folder '../../', '/ansible', type: 'virtualbox', mount_options: ['dmode=700,fmode=700']
    res.vm.synced_folder ENV['COMPETITION_APP_PATH'], '/www/competition/develop/', type: 'virtualbox', create: true, mount_options: ['dmode=777,fmode=777$
    res.vm.provision 'ansible_local' do |ansible|
      ansible.playbook = 'product.yml'
      ansible.provisioning_path = '/ansible/products/competition'
    end
    res.vm.provider "virtualbox" do |v|
      v.name = 'competition-dev'
      v.memory = 512
      v.cpus = 1
    end
  end
```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

https://gist.github.com/otto802/ff5ba9214786809e7a9c944a69913265

### Expected behavior

Output with vagrant 2.2.10: https://gist.github.com/otto802/56ee096eede040229d928b57fc3bd596

- second adaptor (hostonly) seems to be added
- landrush log outputs are visible/landrush actually working

### Actual behavior

landrush plugin seems not to work (does not add the IP address to the dns hostname). I've tried to add a hostonly interface explicitly via config by adding: "config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2". Creating that additional interface succeed however landrush seems still not detecting it. 

### Steps to reproduce

1. running the machine mit vagrant 2.2.10: landrush integration works
2. running the machine mit vagrant 2.2.13 landrush integration does not work

**Comment by soapy1** [comment] 2020-11-12 14:57
This seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/12035. While the plugin in question is different, the root cause seems to be the same. As mentioned in the referenced issue, there is a test package with a fix available https://github.com/hashicorp/vagrant-installers/releases/tag/v2.2.14.dev%2B157db399.

I'm going to go ahead and close this issue as a duplicate so as to consolidate discussion related to this bug to one open issue. Please feel free to reopen if it seems fit.

**Closed by soapy1** 2020-11-12 14:57 UTC
