### ISSUE TITLE
win11 + vagrant2.3.4 + virtualbox 6.1.44 has error：Failed to create the host-only adapter

### ISSUE THREAD

**Issue by cnzxc** [hashicorp/vagrant#13130] opened 2023-04-24 14:46 UTC
An error occurred while I was executing 'vagrant up'. as follows:

`PS D:\software\Vagrant\machine\Centos7> vagrant up node1
Bringing machine 'node1' up with 'virtualbox' provider...
==> node1: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aInterfaceName.isEmpty()] at 'F:\tinderbox\win-6.1\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (76) in long __cdecl HostNetworkInterface::init(class com::Utf8Str,class com::Utf8Str,class com::Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0046).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp
PS D:\software\Vagrant\machine\Centos7>`

pelease help me. thanks！

**Comment by cnzxc** [comment] 2023-04-25 02:33
please🥺

**Comment by chrisroberts** [comment] 2023-05-03 20:58
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2023-06-02 21:09
Hey there,

I am closing this due to lack of response. If this is still an issue, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!

**Closed by chrisroberts** 2023-06-02 21:09 UTC
Labels: waiting-reply, provider/virtualbox, host/windows
