### ISSUE TITLE
Trying to install metasploitable3, I had this issues trynig to run vagrant up: 

### ISSUE THREAD

**Issue by AliEsme** [hashicorp/vagrant#13135] opened 2023-04-29 22:43 UTC
PS C:\WINDOWS\system32> .\notepad.exe .\Vagrantfile
PS C:\WINDOWS\system32> vagrant up
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Importing base box 'rapid7/metasploitable3-ub1404'...
==> ub1404: Matching MAC address for NAT networking...
==> ub1404: Checking if box 'rapid7/metasploitable3-ub1404' version '0.1.12-weekly' is up to date...
==> ub1404: Setting the name of the VM: Metasploitable3-ub1404
==> ub1404: Clearing any previously set network interfaces...
==> ub1404: Preparing network interfaces based on configuration...
    ub1404: Adapter 1: nat
    ub1404: Adapter 2: hostonly
==> ub1404: Forwarding ports...
    ub1404: 22 (guest) => 2222 (host) (adapter 1)
==> ub1404: Running 'pre-boot' VM customizations...
==> ub1404: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "556a1377-232b-4eb5-af27-d73eb187fbd4", "--type", "headless"]

Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Any help ?!

**Comment by chrisroberts** [comment] 2023-05-05 18:15
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2023-06-02 21:06
Hey there,

I am closing this due to lack of response. If this is still an issue, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!

**Closed by chrisroberts** 2023-06-02 21:06 UTC
Labels: waiting-reply, provider/virtualbox, host/windows
