### ISSUE TITLE
mount.nfs: requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by valjar** [hashicorp/vagrant#9666] opened 2018-04-09 07:59 UTC
Lately me and my coworkers are sharing same problems when we try to vagrant up our virtual machines. Some times is working, sometimes not (totally random behaviour). Sometimes it doesn't work for whole day and next day starts magically working again, even thought no changes where made on host machine (no update, nothing).
Maybe this has something to do with macOS version, since my coworker (which hasn't updated maxOS to high sierra), haven't faced that issue for now.

### Vagrant version
Vagrant 2.0.3

### Host operating system
macOS High Sierra
Version: 10.13.3 (17D102)

### Guest operating system
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-143-generic x86_64)

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.provider :virtualbox do |vb|
	    vb.name = "myapp platform"
	    vb.customize ["modifyvm", :id, "--memory", 8288, "--cpus", "1"]
	end
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "myapp-dev"
	config.vm.synced_folder "/Users/<username>/workspace/myapp", "/home/vagrant", create: true, type: "nfs", nfs_udp: false

	config.hostmanager.enabled = true
	config.vbguest.auto_update = true
	config.hostmanager.manage_host = true
	config.hostmanager.manage_guest = false
	config.hostmanager.ignore_private_ip = false
	config.hostmanager.include_offline = false
	config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
      if vm.communicate.ready?
        result = ""
        vm.communicate.execute("ifconfig eth1") do |type, data|
          result << data if type == :stdout
        end
      end
      (ip = /inet addr:(\d+\.\d+\.\d+\.\d+)/.match(result)) && ip[1]
    end
    config.vm.define "myapp" do |node|
		node.vm.hostname = "myapp-dev"
		node.vm.network :private_network, type: 'dhcp'
		node.hostmanager.aliases = %w(myapp.test)
	end
end
```

### Debug output
https://gist.github.com/valjar/a93744ec2e78cf4ab925ba1c36fdc0b8

### Expected behaviour
Vagrant should boot and mount nfs shared folders

### Actual behaviour
Vagrant boots but it doesn't mount nfs shared folders

### Steps to reproduce
1. vagrant up

To me it looks like the same problems as #7646, but:
- I have deleted exports file
- I have deleted and recreated hosts file
- Firewall is turned OFF
- I have restarted Nfsd service and its running
Still not working...

Is this known bug on macOS High Sierra? Can you help me figure out why is this happening and how to solve a problem. If you need any additional informations please let me know and I will provide. Thank you!

*UPDATE*
Users with Ubuntu OS are also experiencing same problem from time to time.

**Comment by DenizTemizer** [comment] 2018-05-01 07:44
Check your `/etc/hosts` if `127.0.0.1       localhost` is missing.
I don't know how that happened on my system but it was removed somehow.
Adding this line made it work for me again.

**Comment by valjar** [comment] 2018-05-02 10:03
@DenizTemizer no sorry, this is not the case. We already checked that and this host entire is there

**Comment by danielBingham** [comment] 2018-05-16 16:30
I'm also seeing this issue.  ``vagrant up`` fails every time.  I'm also on macOs High Sierra.    At this point, I'm completely blocked and unable to bring up my vm development environment.

Vagrant and plugins versions:
```
 $ vagrant --version
Vagrant 2.1.1
$ vagrant plugin list
vagrant-hostmanager (1.8.8)
vagrant-s3auth (1.3.2)
vagrant-vmware-fusion (5.0.4)
```

The error I see:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 172.16.251.1:/path/to/repo/censored /path/to/mount/on/vm/censored

Stdout from the command:

Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by rdonkin** [comment] 2018-05-21 12:27
@sandstrom - interesting, what Vagrant version were you using?

**Comment by sandstrom** [comment] 2018-05-21 12:29
@rdonkin 2.1.1

**Comment by valjar** [comment] 2018-05-21 13:37
@sandstrom I agree with you! If I hard code my private_network config, then it's working.
But I must say, when I was trying to vagrant up, non other virtual machine were running...

**Comment by npacker** [comment] 2018-06-21 18:41
Reproduced:

Host: macOS 10.13.5 (17F77) High Sierra
Guest: ubuntu 18.04 LTS Bionic Beaver
Vagrant: 2.1.1
VirtualBox: 5.2.12 r122591

### Vagrant Up
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 172.28.128.1:/Users/packern/Desktop/wwu-vagrant-nfs /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```
### Manual via SSH
```
$ sudo mount -o vers=3,udp 172.28.128.1:/Users/packern/Desktop/wwu-vagrant-nfs /vagrant --verbose
mount.nfs: timeout set for Thu Jun 21 11:39:44 2018
mount.nfs: trying text-based options 'vers=3,udp,addr=172.28.128.1'
mount.nfs: prog 100003, trying vers=3, prot=17
mount.nfs: portmap query failed: RPC: Program not registered
mount.nfs: requested NFS version or transport protocol is not supported
```

### Host Configuration
```
vboxnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00
	inet 172.28.128.1 netmask 0xffffff00 broadcast 172.28.128.255
```
```
# VAGRANT-BEGIN: 436613281 1d2237d1-0e08-45dd-b534-f9e6482e3b8f                                                                                                                                                                             
"/Users/packern/Desktop/wwu-vagrant-nfs" 172.28.128.1 -alldirs -mapall=436613281:1835270042
# VAGRANT-END: 436613281 1d2237d1-0e08-45dd-b534-f9e6482e3b8f
```
```
Exports list on localhost:
/Users/packern/Desktop/wwu-vagrant-nfs 172.28.128.1
```

### Guest Configuration
```
enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:30:b7:1e brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.1/24 brd 172.28.128.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe30:b71e/64 scope link 
       valid_lft forever preferred_lft forever
```

## Workaround
As suggested above, setting a static IP for the VM on the private network resolves the issue:
```
config.vm.network 'private_network', ip: '172.28.128.2'
```

**Comment by npacker** [comment] 2018-06-21 19:25
Another datapoint from a VM that works with NFS (same host):

Host: macOS 10.13.5 (17F77) High Sierra
Guest: ubuntu 14.04 LTS Trusty Tahir
Vagrant: 2.1.1
VirtualBox: 5.2.12 r122591

```
vagrant@vagrant:~$ showmount -e 172.28.128.1
Export list for 172.28.128.1:
/Users/packern/dev 172.28.128.3
```
```
eth1      Link encap:Ethernet  HWaddr 08:00:27:19:a1:b3  
          inet addr:172.28.128.3  Bcast:172.28.128.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe19:a1b3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3380 (3.3 KB)  TX bytes:4216 (4.2 KB)
```
```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet dhcp
    post-up ip route del default dev $IFACE || true
#VAGRANT-END
```

Clearly DHCP correctly assigns an IP for the VM without any issues.

**Comment by npacker** [comment] 2018-06-21 19:38
Okay, did a little more research in the issue queue and it looks like this is fixed in #9855. Just need to wait for the 2.1.2 release. Disregard my posts above.

**Comment by 128keaton** [comment] 2018-06-27 14:09
@npacker for me, at least, the issue is still present in 2.1.2

**Comment by sandstrom** [comment] 2018-06-27 14:15
@128keaton Did anything in https://github.com/hashicorp/vagrant/issues/9666#issuecomment-390601602 help?

**Comment by npacker** [comment] 2018-06-27 15:46
This is fixed for me in 2.1.2.

**Comment by 128keaton** [comment] 2018-06-27 18:19
@sandstrom funny thing. I destroyed my VM completely--started working. I guess its fixed then. Awesome! Thanks @npacker @sandstrom

**Comment by karmux** [comment] 2018-07-02 20:51
This is still problem in 2.1.2 in Manjaro Linux.

Using CoreOS as a guest.
`git clone https://github.com/coreos/coreos-vagrant`
`cd coreos-vagrant`
Uncomment this line in Vagrantfile:
```
config.vm.synced_folder ".", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']
```
Run `vagrant up`

Error happens:
```
==> core-01: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,nolock,vers=3,udp 172.17.8.1:/home/karmo/coreos-vagrant /home/core/share

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by valjar** [comment] 2018-07-05 06:47
Yep, problem still appears in vagrant 2.1.2 version
`Bringing machine 'dg1' up with 'virtualbox' provider...
/Users/<user>/.vagrant.d/gems/2.4.4/gems/vagrant-notify-0.5.6/lib/vagrant-notify/config.rb:31: warning: constant ::Fixnum is deprecated
==> dg1: Clearing any previously set forwarded ports...
==> dg1: Clearing any previously set network interfaces...
==> dg1: Preparing network interfaces based on configuration...
    dg1: Adapter 1: nat
    dg1: Adapter 2: hostonly
==> dg1: Forwarding ports...
    dg1: 22 (guest) => 2222 (host) (adapter 1)
==> dg1: Running 'pre-boot' VM customizations...
==> dg1: Booting VM...
==> dg1: Waiting for machine to boot. This may take a few minutes...
    dg1: SSH address: 127.0.0.1:2222
    dg1: SSH username: vagrant
    dg1: SSH auth method: private key
==> dg1: Machine booted and ready!
==> dg1: vagrant-notify-server pid: 1438
==> dg1: Checking for guest additions in VM...
==> dg1: Setting hostname...
==> dg1: Configuring and enabling network interfaces...
==> dg1: Exporting NFS shared folders...
==> dg1: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> dg1: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 172.28.128.1:/Users/<user>/workspace/myApp /home/vagrant/myApp/..

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
`

**Comment by valjar** [comment] 2018-07-05 07:18
But now even setting static IP doesn't help any more
`config.vm.network "private_network", ip: "172.28.128.1"`

**Comment by sandstrom** [comment] 2018-07-05 08:39
@valjar Why did you close this issue? Can you please re-open, since it doesn't seem to be solved.

Also, have you tried the workaround [outlined here](https://github.com/hashicorp/vagrant/issues/9666#issuecomment-390601602), curious to hear if it works?

**Comment by valjar** [comment] 2018-07-05 09:13
Hi @sandstrom ! 
No i haven't closed that issue. Some one else did.

I have tried setting static IP and this workaround isn't working for me any more (in previous versions of vagrat did)
`config.vm.network "private_network", type: "dhcp", ip: "172.28.128.12"`

Another thing, which my cose  a problem??
I have also added an option `config.vbguest.auto_update = true` because i was wondering if there is a problem with vbguest, since i have updated vagrant to 2.1.2
This is the output

```
==> dg1: Clearing any previously set forwarded ports...
==> dg1: Clearing any previously set network interfaces...
==> dg1: Preparing network interfaces based on configuration...
    dg1: Adapter 1: nat
    dg1: Adapter 2: hostonly
==> dg1: Forwarding ports...
    dg1: 22 (guest) => 2222 (host) (adapter 1)
==> dg1: Running 'pre-boot' VM customizations...
==> dg1: Booting VM...
==> dg1: Waiting for machine to boot. This may take a few minutes...
    dg1: SSH address: 127.0.0.1:2222
    dg1: SSH username: vagrant
    dg1: SSH auth method: private key
==> dg1: Machine booted and ready!
==> dg1: vagrant-notify-server pid: 1913
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.2.14
Going on, assuming VBoxService is correct...
[dg1] GuestAdditions 5.2.14 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.2.14
Going on, assuming VBoxService is correct...
==> dg1: Checking for guest additions in VM...
    dg1: The guest additions on this VM do not match the installed version of
    dg1: VirtualBox! In most cases this is fine, but in rare cases it can
    dg1: prevent things such as shared folders from working properly. If you see
    dg1: shared folder errors, please make sure the guest additions within the
    dg1: virtual machine match the version of VirtualBox you have installed on
    dg1: your host and reload your VM.
    dg1: 
    dg1: Guest Additions Version: 4.3.36
    dg1: VirtualBox Version: 5.2

How to properly sync Guest Additions between host and virtual machine, so it will work properly?

```

**Comment by valjar** [comment] 2018-07-06 06:20
Funny observation...

When ever I get at home and i try to vagrant up, nfs starts working.
Always when this happens and I get home, nfs sync starts working and then its also working at my job.  At my job I tried to vagrant up without internet connection, with internet connection via my phone and all other sort of thing and it was not working.

I have no other explanation, except that my home has good energy for nfs sync :D 

So the real question is: Does vagrant have any thing to do with network you are connected? Can network be a problem?

**Comment by npacker** [comment] 2018-07-06 07:01
Would be helpful if you can post the contents of your network config files from inside the vm.

**Comment by valjar** [comment] 2018-07-06 07:03
@npacker  Just tell me which files do you need and I will provide

**Comment by npacker** [comment] 2018-07-06 07:45
@valjar If you're on ubuntu they should be in the file /etc/network/interfaces, or in a directory called interfaces.d.

**Comment by valjar** [comment] 2018-07-06 08:32
There you go
```
dg1-dev-default: ~/proplatform/balthazar/Dg1 $ cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# Source interfaces
# Please check /etc/network/interfaces.d before changing this file
# as interfaces may have been defined in /etc/network/interfaces.d
# NOTE: the primary ethernet device is defined in
# /etc/network/interfaces.d/eth0
# See LP: #1262951
source /etc/network/interfaces.d/*.cfg

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet dhcp
    post-up ip route del default dev $IFACE || true
#VAGRANT-END
```

```
dg1-dev-default: ~/proplatform/balthazar/Dg1 $ cat /etc/network/interfaces.d/eth0.cfg 
# The primary network interface
auto eth0
iface eth0 inet dhcp
```

**Comment by G89Angel** [comment] 2018-07-21 15:09
@karmux suggestion worked for me on Linux Antergos.

**Comment by ekkode** [comment] 2018-08-02 12:43
The same problem on vagrant version 2.1.1

**Comment by sandstrom** [comment] 2018-08-02 13:38
@ekkode Can you try if the workaround [outlined here](https://github.com/hashicorp/vagrant/issues/9666#issuecomment-390601602) works?

**Comment by The1andONLYdave** [comment] 2018-08-09 10:01
Same Problem after upgrading host from ubuntu xenial to bionic.
Guest is Debian Wheezy.
Vagrant tried: 2.0.1 and 2.1.2
Vbox tried: 5.2.6 and 5.2.16
Workaroung suggested form sandstrom above don't work.

**Comment by bizzr3** [comment] 2018-09-04 03:33
@wallsfantasy it was my case as well, thanks buddy.

**Comment by The1andONLYdave** [comment] 2018-09-05 07:33
Wallsfantasy 's Solution also worked on latest Linux Mint. Thanks.

**Comment by thirdriver** [comment] 2018-09-20 01:57
> Check your `/etc/hosts` if `127.0.0.1 localhost` is missing.
> I don't know how that happened on my system but it was removed somehow.
> Adding this line made it work for me again.

it works to me. thanks

**Comment by shurikdima** [comment] 2018-09-23 22:11
> It was still a problem for me in 2.1.2 in Manjaro Linux with a static IP.
> 
> This fixed it for me:
> 
> In `/etc/nfs.conf` I had to uncomment two lines:
> 
> ```
> [nfsd]
> udp=y
> ```
> and then had to restart nfs:
> `sudo systemctl restart nfs-server.service`
> 
> Related to #9361.

Thanks, that worked for me. i've been having this issue for the last 3 months but only on fedora and centos. ubuntu/mac didn't have any issues. if i'm not mistaken, the last time i've managed to solve the problem by randomly changing the versions of Virtual box/vagrant until i managed to find the versions which seemed to work. anyway, now, running vagrant 2.1.5 and virtualbox 5.1.38, i uncommented the lines you said and everything seems to work for now.

**Comment by molund** [comment] 2018-10-01 21:27
I was getting this error on an ubuntu 18.04 host .  I resolved it with this command...

`sudo apt install nfs-kernel-server`

**Comment by faahim** [comment] 2018-11-05 06:15
Okay, I've noticed something very interesting today.

I had this same problem several times before and solved it by trying out fixes randomly, but never really understood what was causing it. Today when I was having this issue again, I tried re-starting `nfs-server.service` (I'm on a Arch Linux system) and realized it was failing. So I checked its status with the command `systemctl status nfs-server.service` and the output I got was:
```
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled; vendor preset>
   Active: failed (Result: exit-code) since Mon 2018-11-05 11:35:17 +06; 1min 14s ago
  Process: 7105 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)
  Process: 7104 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
  Process: 7103 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=1/FAILURE)

Nov 05 11:35:17 archbox systemd[1]: Starting NFS server and services...
Nov 05 11:35:17 archbox exportfs[7103]: exportfs: Failed to stat /home/faahim/sites/client-ncl/trellis: No such file or directory
Nov 05 11:35:17 archbox exportfs[7103]: exportfs: Failed to stat /home/faahim/sites/client-ncl/site: No such file or directory
Nov 05 11:35:17 archbox systemd[1]: nfs-server.service: Control process exited, code=exited status=1
Nov 05 11:35:17 archbox systemd[1]: nfs-server.service: Failed with result 'exit-code'.
Nov 05 11:35:17 archbox systemd[1]: Stopped NFS server and services.
```

So you see, one of the 3 processes, process 7103 was failing. And those log messages at the bottom indicates that process 7103 is failing because it can't find a directory specified there. That's because I renamed that directory yesterday.

What I figured from this is, even though I was trying to run a vagrant machine in a completely different directory, It was checking NFS export configuration for all of the machine configured with NFS export. It seems that each machine has their location info located in that `/usr/sbin/exportfs` file, which of course, fails if you rename/delete the folder. So I simply went into the folder where the actual failing vagrant machine was and ran `vagrant destroy`. I noticed this was within the output of the destroy command:
`default: Pruning invalid NFS exports. Administrator privileges will be required...`
That probably means vagrant has removed NFS export information for that machine. Then I went into the folder of the machine I want to run, did `vagrant up` and for sure, It ran just fine!

Lesson learned: Always destroy vagrant before renaming/deleting folder that contains vagrant machine.

Not sure whether this is whether it's the same case with other OS/systems, but hopefully this will help someone. :slightly_smiling_face:

**Comment by andreanironi** [comment] 2018-12-06 08:19
> I faced the similar problem on my ubuntu 18.04 host but in my case I found vagrant generated duplicate record in `/etc/exports`. I delete one of it and reload the box then the problem solved.
> 
> Might be helpful for ubuntu users as mentioned by OP. Not sure about mac as OP deleted exports file.

brilliant, thanks a lot! in my case the error was due to an old VM (with a different static IP) using the same shared directory of the VM throwing the error.

**Comment by Namone** [comment] 2018-12-19 14:57
In my case molund's solution worked (Ubuntu 18.04.) Also had to run `vagrant reload.`

**Comment by rca0** [comment] 2019-01-04 20:30
> /etc/nfs.conf

T

> It was still a problem for me in 2.1.2 in Manjaro Linux with a static IP.
> 
> This fixed it for me:
> 
> In `/etc/nfs.conf` I had to uncomment two lines:
> 
> ```
> [nfsd]
> udp=y
> ```
> and then had to restart nfs:
> `sudo systemctl restart nfs-server.service`
> 
> Related to #9361.

Thanks @karmux
This solution worked to me...

**Comment by schnerring** [comment] 2019-01-29 21:15
Thanks @karmux, same for me

**Comment by faahim** [comment] 2019-02-01 10:11
Update to my previous comment here: https://github.com/hashicorp/vagrant/issues/9666#issuecomment-435765957

It turns out there's a vagrant command to remove the invalid exports automatically! :smile: 
Try: `vagrant global-status --prune`

**Comment by Bilge** [comment] 2019-02-19 10:24
I did not have a duplicate record in `/etc/exports`, but Vagrant had decided to stop updating it since doing a `vagrant destroy`. Razing the file and starting again fixed it.

**Comment by zyx954** [comment] 2019-03-03 07:06
Solved by reinstall Vagrant,  but next time maybe it better to try [#9666(comment)](https://github.com/hashicorp/vagrant/issues/9666#issuecomment-459672832) first

**Comment by isca0** [comment] 2019-04-15 21:24
> It was still a problem for me in 2.1.2 in Manjaro Linux with a static IP.
> 
> This fixed it for me:
> 
> In `/etc/nfs.conf` I had to uncomment two lines:
> 
> ```
> [nfsd]
> udp=y
> ```
> 
> and then had to restart nfs:
> `sudo systemctl restart nfs-server.service`
> 
> Related to #9361.

This is exactly the same case on Arch Linux, since vagrant is trying to mount the default shared folder with mount options ```vers=3,udp``` by default. If someone doesn't want to use the default NFS settings and also want to solve this issue directly from the vagrant file, you can disable the default mount or try to change mount options with something like:

```
config.vm.synced_folder ".", "/vagrant", mount_options: ["vers=3,tcp"]
```

**Comment by codekandis** [comment] 2019-05-27 12:10
> Update to my previous comment here: [#9666 (comment)](https://github.com/hashicorp/vagrant/issues/9666#issuecomment-435765957)
> 
> It turns out there's a vagrant command to remove the invalid exports automatically! smile
> Try: `vagrant global-status --prune`

I discovered my `nfs-server.service` on Debian didn't start due an unresolvable export in `/etc/exports`.

```
$ sudo systemctl status nfs-server.service
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-05-27 13:53:48 CEST; 25s ago
  Process: 911 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=1/FAILURE)

Mai 27 13:53:48 myhostname systemd[1]: Starting NFS server and services...
Mai 27 13:53:48 myhostname exportfs[911]: exportfs: Failed to stat /path/to/deleted/but/still/exported/mount/source: No such file or directory
Mai 27 13:53:48 myhostname systemd[1]: nfs-server.service: Control process exited, code=exited status=1
Mai 27 13:53:48 myhostname systemd[1]: Failed to start NFS server and services.
Mai 27 13:53:48 myhostname systemd[1]: nfs-server.service: Unit entered failed state.
Mai 27 13:53:48 myhostname systemd[1]: nfs-server.service: Failed with result 'exit-code'.
```

`nfs-server` uses `exportfs` to provide the mount source. If one doesn't properly halt the VM the export remains and after deleting the mount source cannot be resolved.

I deleted the export manually. But it seems `vagrant global-status --prune` should like mentioned in
[#9666(comment)](https://github.com/hashicorp/vagrant/issues/9666#issuecomment-459672832).

**Comment by tstrijdhorst** [comment] 2019-06-18 09:12
FYI: If you try to export directories from eCryptfs with NFS you will get the same error from vagrant. See: https://github.com/hashicorp/vagrant/issues/4987

**Comment by codekandis** [comment] 2019-07-26 14:27
> I deleted the export manually. But it seems `vagrant global-status --prune` should help.

I had that issue again today. I cannot confirm `vagrant global-status --prune` is working here. I had to remove the export manually again.

**Comment by nextgenthemes** [comment] 2019-09-18 20:44
> It was still a problem for me in 2.1.2 in Manjaro Linux with a static IP.
> 
> This fixed it for me:
> 
> In `/etc/nfs.conf` I had to uncomment two lines:
> 
> ```
> [nfsd]
> udp=y
> ```
> 
> and then had to restart nfs:
> `sudo systemctl restart nfs-server.service`
> 
> Related to #9361.

On the latest openSUSE tumbleweed `nfs-kernel-server` and related lib upgrades my vagrant project (roots/trellis based) stopped working. And this also solved it for me.

**Comment by HugoPoi** [comment] 2019-10-06 21:03
This is very weird because some box have synced folder by nfs tcp by default and some by udp.

**Comment by danepowell** [comment] 2019-11-13 18:53
One potential gotcha: the root cause for me turned out to be duplicate `/etc/exports` entries as mentioned above, but it took me quite a while to diagnose because Vagrant had injected an _insane_ number of newlines into that file, so when I first looked at it there appeared to be no Vagrant entries. Until I scrolled down a few hundred lines...

A better way to diagnose this is to check your syslog for an entry like this: `exportfs: duplicated export entries:`

A bit frustrating that Vagrant doesn't surface that more visibly, and actively obfuscates the exports file...

**Comment by radixs** [comment] 2019-12-09 10:51
I have Ububtu 18.04 as host and Debian vagrant boxes (various versions) and stumbled upon the same problem, there were duplicated entries in `/etc/exports`. Deleting the duplicates (same IP address for the same entry) helped and my vagrant box booted properly.

**Comment by Faisal-Zulfiqar510** [comment] 2020-05-04 07:42
This will work for me

- sudo rm /etc/exports
- sudo touch /etc/exports
- vagrant halt
- vagrant up --provision

**Comment by briancain** [comment] 2020-05-21 20:45
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!

**Closed by briancain** 2020-05-21 20:45 UTC
Labels: needs-repro, synced-folders/nfs

**Comment by codekandis** [comment] 2020-05-25 21:33
Ack! I'll do so. I'm on it.
