### ISSUE TITLE
@hashibot needs correct calculation... 

### ISSUE THREAD

**Issue by Reiner030** [hashicorp/vagrant#11344] opened 2020-01-28 03:54 UTC
https://github.com/hashicorp/vagrant/issues/8434

> @chrisroberts chrisroberts closed this on 4 May 2018

... whyever it was closed **because issue is still active all over the time...**
Last week I had to download an image over 5 hours!

https://github.com/hashicorp/vagrant/issues/8434#issuecomment-579043095

> hashibot bot commented 2 hours ago
> I'm going to lock this issue because it has been closed for 30 days ⏳. 
> This helps our maintainers find and focus on the active issues.
> If you have found a problem that seems similar to this, please open a 
> new issue and complete the issue template so we can capture all the 
> details necessary to investigate further.

4 May 2018 ... 28 Jan 2020 ... that looks for me than more then 1,5 years ;)

**Comment by briancain** [comment] 2020-01-28 16:16
Duplicate of https://github.com/hashicorp/vagrant/issues/11342

**Closed by briancain** 2020-01-28 16:16 UTC
