### ISSUE TITLE
Guest machine default name too long with VirtualBox 5.2.8 (VERR_CFGM_NOT_ENOUGH_SPACE)

### ISSUE THREAD

**Issue by gael-ian** [hashicorp/vagrant#9524] opened 2018-02-28 11:25 UTC
Hello,

After upgrading to VirtualBox 5.2.8 today, some of my Vagrant-managed virtual machines simply refused to boot, with the `VBoxManage start-vm` command returning this error:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "af3e1b26-bc41-407e-847f-2f520ca237e6", "--type", "headless"]

Stderr: VBoxManage: error: The specified string / bytes buffer was to small. Specify a larger one and retry. (VERR_CFGM_NOT_ENOUGH_SPACE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

After some research, I found the problem was the default name build by Vagrant for the impacted virtual machines was too long. Internal buffer size for this name may have been shortened in VirtualBox 5.2.8, as everything worked fine before upgrade.

It's an easy problem to fix, as you only need to [manually set the name of your VM](https://www.vagrantup.com/docs/virtualbox/configuration.html#virtual-machine-name), but maybe Vagrant can handle this in a better way, either with a more understandable error message or by building default names that will not exceed the limit.

For information, my impacted default machines names were 78 and 79 chars long.

Thanks

**Comment by ruzickap** [comment] 2018-03-05 07:35
Thanks for sharing it... I got a same issue...

**Comment by cheeseplus** [comment] 2018-04-24 00:10
What research led you to the name length issue? 

I've attempted to reproduce this one by forcing names of 90+ characters with VirtualBox 5.2.8 and 5.2.10 and can't get the failure.

**Comment by gael-ian** [comment] 2018-04-24 05:58
In my browser history, I can still find tracks to the [VirtualBox OSE Changelog](https://www.virtualbox.org/wiki/Changelog) and some [really old code excerpts](http://virtualbox-ose.sourcearchive.com/documentation/3.1.2-dfsg-1/include_2VBox_2err_8h-source.html) but, reading it again today, I don't remembr how a [name length error on module loading](http://virtualbox-ose.sourcearchive.com/documentation/3.1.2-dfsg-1/PDMDevice_8cpp-source.html#l00452) leads me to shorten my VM name.

Sorry, that was a while ago so I can't be more precise.

**Comment by cheeseplus** [comment] 2018-04-24 10:48
No worries, this issue was opened on a related repo of mine and when I went to test 5.2.8 and 5.2.10 I couldn't force the error based on the length of the automatically name from 

https://github.com/hashicorp/vagrant/blob/c31f87d434eba736840ada97d88207ca663f43db/plugins/providers/virtualbox/action/set_name.rb#L23-L30

Or when setting that value manually. Mostly wanted to follow up here for the Vagrant folks as I am unable to reproduce and thinking the nature of the error might be slightly different than name length.

**Comment by briancain** [comment] 2018-05-01 16:47
Hey everyone! I also just attempted to reproduce this, but could not based on the information in this thread. I tried both virtualbox 5.2.8 and 5.2.10 on macOS high sierra and ubuntu 16.04 with both a folder name and guest name above 150 characters. I'm guessing there is likely something missing beyond the name here that's triggering this error.

For whoever is running into this problem, please provide us with a *full* debug log from Vagrant, as well as your Vagrantfile. It might also be worth listing how much RAM your machine has? If you can reproduce the error with vboxmanage maybe you could run the  startvm command with debug on too?

**Comment by ravn** [comment] 2018-05-02 08:05
[vagrant.log](https://github.com/hashicorp/vagrant/files/1966315/vagrant.log)

[Vagrantfile.zip](https://github.com/hashicorp/vagrant/files/1966316/Vagrantfile.zip)

Machine has 32 GB RAM.
[digital-pligtaflevering-aviser-tools_default_1525247039605_35180-2018-05-02-10-04-36.log](https://github.com/hashicorp/vagrant/files/1966389/digital-pligtaflevering-aviser-tools_default_1525247039605_35180-2018-05-02-10-04-36.log)

**Comment by chrisroberts** [comment] 2018-05-02 13:50
@ravn That information is perfect, thanks!

**Comment by chrisroberts** [comment] 2018-05-02 14:09
@ravn Could you try adding this to the virtualbox provider block in your Vagrantfile:

```ruby
v.customize ["modifyvm", :id, "--audio", "none"]
```

ensure the guest is fully destroyed and then run a `vagrant up` and see if the error persists.

Thanks!

**Comment by chrisroberts** [comment] 2018-05-15 15:00
@kosch Awesome, thanks for the confirmation! I had tracked it down to mostly likely being the cause in the vbox source, but wasn't able to reproduce it locally.

**Comment by chrisroberts** [comment] 2018-05-15 18:36
@cheeseplus I'm not entirely sure. It can definitely be added in the embedded Vagrantfile to always disable audio, and users could override it locally if it's something that they want. It looks to be an issue with vbox itself, though I haven't dug hard enough to find the original cause for the change in behavior. It has to do with the allocated size for the variable to hold the path internally, which is not long enough for the actual path (which results in the some what misleading error message).

**Comment by chrisroberts** [comment] 2018-05-17 20:40
Closing this as an upstream issue.

@ravn I didn't find anything in the virtualbox bug tracker and have so far been unable to reproduce the issue locally to create a new issue with the required debug logs and the like.

**Closed by chrisroberts** 2018-05-17 20:40 UTC
Labels: confirmed, provider/virtualbox, upstream
