### ISSUE TITLE
After Update to 2.2.18 -> "ruby": executable file not found in %PATH%

### ISSUE THREAD

**Issue by localhorst-org** [hashicorp/vagrant#12476] opened 2021-07-28 15:07 UTC
**Host operating system**
Windows 10

Im came from

PS> vagrant -v
Vagrant 2.2.17

PS> vagrant box outdated --global --debug
 INFO global: Vagrant version: 2.2.17
 INFO global: Ruby version: 3.0.1
 INFO global: RubyGems version: 3.2.15
 INFO global: VAGRANT_EXECUTABLE="C:\\HashiCorp\\Vagrant\\embedded\\gems\\2.2.17\\gems\\vagrant-2.2.17\\bin\\vagrant"
 [...]

and everything worked as expected.
 
After update to 2.2.18 with vagrant_2.2.18_x86_64.msi and Reboot i got

PS> vagrant -v
Exec error: exec: "ruby": executable file not found in %PATH%

inside 

C:\HashiCorp\Vagrant\embedded\mingw64\bin\

No ruby.exe and rubyw.exe like the prior Version. I saved these both files away from 2.2.17 and tried to copy them in the folder with no luck, after that

PS> vagrant -v

Hase no output. My be there are more files missing.

Uninstall 2.2.18 and go back to 2.2.17 solved the Problem. Found ruby.exe, rubyw.exe inside the folder. I tried this several times.

Regards Horst

**Comment by breisig** [comment] 2021-07-28 16:09
Getting the EXACT same issue and could not find ruby.exe

**Comment by PaulNeumann** [comment] 2021-07-28 16:12
I had the same issue (Windows 10 Pro Version 21H1, OS Build 19043.1110).  Repairing the installation via Control Panel resolved it.

**Comment by chrisroberts** [comment] 2021-07-28 16:15
Hi there,

This issue is most likely being caused by a virus scanner flagging and quarantining the executable files. Restoring the files from quarantine and/or adding the install directory to an allow list within the scanner should resolve the issue. 

Cheers

**Comment by PaulNeumann** [comment] 2021-07-28 16:22
> This issue is most likely being caused by a virus scanner flagging and quarantining the executable files.

I'm not so sure. There was nothing relevant in the virus scanner logs, and if the issue were due to a virus scanner, then I don't think the Control Panel repair would have worked.

**Comment by localhorst-org** [comment] 2021-07-28 16:25
strange... i have only microsoft defender and i saw no hint by the installation from 2.2.18. in the changelog from 2.2.18 there is no hint to a different ruby version. this is comming in 2.2.17 and that version i can install with no problems.

**Comment by localhorst-org** [comment] 2021-07-28 17:35
Repairing worked also for me thx PaulNeumann

**Comment by chrisroberts** [comment] 2021-07-28 17:43
Thanks for replies. I tested an install on win10 and everything works as expected. Ran win defender and found no issues, checked if any contents of the installer had been flagged by scanners, and found nothing. In the majority of cases where executable files go missing, it's due to a virus scanner quarantining the files.

With the bouncing back and forth between versions (and working / not working installations) I tossed in a 2.2.17 install and then upgraded it to 2.2.18. _That_ got me the same error message being encountered. 

I'm not sure why the files are missing on upgrade. I'll work through the installer to figure out what is causing the issue on upgrade. Until then, @PaulNeumann 's recommendation for running the repair will get things working (thanks @PaulNeumann !).

**Comment by pedrofurtado** [comment] 2021-07-28 20:19
Any news about it? 2.2.18 not works in windows 10, only 2.2.17 👍

**Comment by chrisroberts** [comment] 2021-07-28 20:35
@pedrofurtado Going to the list of installed applications in the control panel, selecting vagrant, and repairing the install will fix the installation. I'm currently testing different configuration modifications when building packages.

**Comment by dannmartens** [comment] 2021-07-29 09:14
Kudos to @PaulNeumann.

Note that this only works via **Control Panel\Programs\Programs and Features**
![image](https://user-images.githubusercontent.com/263133/127465503-adf691be-b567-4ed8-8896-3619b0d0941f.png)

The Windows 10 "Apps & features" in Settings does not have a repair.
![image](https://user-images.githubusercontent.com/263133/127465636-e1370db1-5278-4897-8a9a-1024b660b1c7.png)

**Comment by gebailey** [comment] 2021-07-29 15:15
I also had this issue, and in my case it was resolved by uninstalling 2.2.18 and then reinstalling 2.2.18.  I'm not running any virus scanner (other than Windows Defender).

**Comment by chrisroberts** [comment] 2021-08-02 23:13
Hi everyone,

hashicorp/vagrant-installers#218 includes the packaging fix for upgrade installations. I've updated the Windows packages for the 2.2.18 release to include this modification and Ruby is no longer missing from the installation after upgrade. Thank you all for the report. This was an unexpected behavior with the Windows Installer I had not encountered in the past. My apologies for the inconvenience it may have caused. With the packaging update now in place, this kind of situation won't happen in future releases where embedded libs/tools may be downgraded.

Cheers!

**Closed by chrisroberts** 2021-08-02 23:13 UTC
Labels: host/windows

**Comment by pedrofurtado** [comment] 2021-08-02 23:20
@chrisroberts Is better wait the release of 2.2.19, right? Just to confirm 🤝 

Thanks a lot for your hard work on it 🎉 🍻

**Comment by chrisroberts** [comment] 2021-08-02 23:24
@pedrofurtado There is no need to wait for the 2.2.19 release. The Windows installers for the current release (2.2.18) have been updated and the upgrade installation works as expected. You can download the updated installer from the [downloads page](https://www.vagrantup.com/downloads).

**Comment by PaulNeumann** [comment] 2021-08-03 01:42
@chrisroberts Thank you! Much appreciated.
