### ISSUE TITLE
openssl mismatch 

### ISSUE THREAD

**Issue by ketan985** [hashicorp/vagrant#9937] opened 2018-06-15 15:42 UTC
Whille vagrant ssh. I am getting following error. 

```
ketan@ketan-pc:$ vagrant ssh --plain
OpenSSL version mismatch. Built against 100020ef, you have 1000106f
```

### Vagrant version
Vagrant 2.1.1

### Host operating system
Ubuntu 18.04 LTS 
Kernel 4.15.0-20-generic 

### Guest operating system
Ubuntu 18.04 , Ubuntu 16.04

### Vagrantfile
`Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
end`

### Expected behavior
User able to login in vm

### Actual behavior
Can't login in vm

### Steps to reproduce
1.  vagrant up with given config file. 
2.  vagrant ssh

**Comment by chrisroberts** [comment] 2018-06-19 18:09
Hi there,

Would you please provide a gist of the debug output when running the command. 

Thanks!

**Comment by chrisroberts** [comment] 2018-06-20 18:38
Thanks for providing the debug log. This is a duplicate of #9875 and it will be fixed in the next release. Until the release is available the deb package can be used.

Cheers!

**Closed by chrisroberts** 2018-06-20 18:38 UTC
Labels: duplicate
