### ISSUE TITLE
Port forwarding collisions using VMWare Fusion provider for Vagrant 

### ISSUE THREAD

**Issue by iamlittle** [hashicorp/vagrant#9624] opened 2018-03-27 18:07 UTC
### Vagrant version
Vagrant 2.0.3
Fusion 10.1.1
Vagrant VMware Utility 1.0.0
vagrant-vmware-desktop (1.0.0) 

### Host operating system
OSX High Sierra

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'
require 'open-uri'
require 'tempfile'
require 'yaml'

Vagrant.require_version ">= 1.6.0"

Vagrant.configure(2) do |config|

  # always use Vagrant's insecure key
  config.ssh.insert_key = false

  config.vm.box="bento/ubuntu-16.04"

  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  # Base box
  config.vm.define :project do |project_config|
    project_config.vm.synced_folder ".", "/opt/project"
    project_config.vm.network :forwarded_port, host: 80, guest: 4000  

    project_config.vm.provision :shell, :inline => "apt-get update && apt-get -y install ruby ruby-dev g++ libffi-dev", :privileged => true
    project_config.vm.provision :shell, :inline => "gem install jekyll bundle", :privileged => true
  end

end
```

### Debug output
```
Bringing machine 'project' up with 'vmware_fusion' provider...
==> project: Checking if box 'bento/ubuntu-16.04' is up to date...
==> project: Verifying vmnet devices are healthy...
==> project: Preparing network adapters...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 80 is already in use
on the host machine.

To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 4000, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding. You could
try 'vagrant reload' (equivalent of running a halt followed by an up)
so vagrant can attempt to auto-correct this upon booting. Be warned
that any unsaved work might be lost.
```

### Expected behavior
See Reference tickets

### Actual behavior
See Reference tickets

### Steps to reproduce
See Reference tickets

### References
- #8642
- #8554

### Workarounds
Clearing out the offending entries in `/Library/Preferences/VMware\ Fusion/vmnet8/nat.conf` and `/Library/Preferences/VMware\ Fusion/networking` files

**Comment by iamlittle** [comment] 2018-03-27 18:08
### Workaround 2
1. Open the VMWare Fusion GUI. 
1. vagrant up. 
1. No collision.

**Comment by chrisroberts** [comment] 2018-03-27 22:23
@iamlittle Did you upgrade from vagrant-vmware-fusion to vagrant-vmware-desktop? If so, are you seeing this error happening continually, or just on the initial up?

**Comment by iamlittle** [comment] 2018-03-27 22:46
> Did you upgrade from vagrant-vmware-fusion to vagrant-vmware-desktop?

I did.

> If so, are you seeing this error happening continually, or just on the initial up?

Continually. However, if I open the VMware GUI before running any vagrant ups, it seems to behave properly. As best I can tell, anyways.

**Comment by chrisroberts** [comment] 2018-03-27 22:50
@iamlittle Thanks, I'm setting up a repro environment now and will drop a note in here with what I find.

**Comment by onlyhavecans** [comment] 2018-03-28 22:15
I also am having this issue. when using this with [kitchen-vagrant](https://github.com/test-kitchen/kitchen-vagrant)

```
-----> Starting Kitchen (v1.20.0)
-----> Creating <default-ubuntu-1604>...
       Bringing machine 'default' up with 'vmware_fusion' provider...
       ==> default: Cloning VMware VM: 'bento/ubuntu-16.04'. This can take some time...
       ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
       ==> default: Verifying vmnet devices are healthy...
       ==> default: Preparing network adapters...
       ==> default: Starting the VMware VM...
       ==> default: Waiting for the VM to receive an address...
       Some of the defined forwarded ports would collide with existing
       forwarded ports on VMware network devices. This can be due to
       existing Vagrant-managed VMware machines, or due to manually
       configured port forwarding with VMware. Please fix the following
       port collisions and try again:

       2222
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider vmware_fusion ----
STDOUT: Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'bento/ubuntu-16.04'. This can take some time...
==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
STDERR: Some of the defined forwarded ports would collide with existing
forwarded ports on VMware network devices. This can be due to
existing Vagrant-managed VMware machines, or due to manually
configured port forwarding with VMware. Please fix the following
port collisions and try again:

2222
---- End output of vagrant up --no-provision --provider vmware_fusion ----
Ran vagrant up --no-provision --provider vmware_fusion returned 1] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

vagrantfile

```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-16.04"
  c.vm.hostname = "default-ubuntu-1604.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.96.31"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/dos/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :vmware_fusion do |p|
    p.vmx["numvcpus"] = "2"
    p.vmx["memsize"] = "2048"
  end
end
```

**Comment by chrisroberts** [comment] 2018-03-29 13:57
Just wanted to drop a note that I have been able to reproduce the behavior in a local environment and am working on a fix that should be released next week. Thanks for reporting the issue!

**Comment by Kier** [comment] 2018-04-09 10:53
Just a note to say that since Vagrant 2.0.3 and vmware_desktop, to which I upgraded from Vagrant 2.0.3 and provider: vmware_fusion at the weekend, my system is *utterly* wrecked.

If you have a fix for this port forwarding issue, and hopefully the

> Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

issue that seems to have arrived with it, please post it soon!

**Comment by Kier** [comment] 2018-04-10 18:06
Seriously, endless, endless problems since 2.0.3 and vmware_desktop - I am completely unable to use Vagrant right now.

`==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 80 => 80
    default: -- 3306 => 3307
    default: -- 22 => 2222
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.`

**Comment by chrisroberts** [comment] 2018-04-11 14:25
@Kier Hi! Would you let me know what platform you are on, and provide a debug gist. Thanks!

**Comment by Kier** [comment] 2018-04-13 14:17
@chrisroberts I've been away for a few days, and today I haven't encountered the 'Guest-specific operations' error message - but I have had to clear out the port forwarding entries in `/Library/Preferences/VMware fusion/networking` and `/Library/Preferences/VMware fusion/vmnet8/nat.conf` **every time** I've wanted to start a Vagrant box.

I'm running on OS X 10.13.4 with VMware Fusion 10.1.1, Vagrant 2.0.3 and the latest vmware_desktop.

This VM is basically the Bento Ubuntu 17.10 with PHP, Apache and MySQL added:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "xf-dev"
    config.vm.hostname = "xf-dev"

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 3306, host: 3307

    config.vm.synced_folder "../", "/var/www", :mount_options => ["umask=000"]
    config.vm.synced_folder "/Volumes/LaCie", "/Volumes/LaCie", :nfs => { :mount_options => ["umask=000"] }

end
```

Startup logs:
https://gist.github.com/Kier/6886394e9b9b9b75cb50ca1ecec99720

**Comment by tweiand** [comment] 2018-04-13 16:42
+1 on being able to reproduce on OS X 10.13.4, VMware Fusion 10.1.1, Vagrant 2.0.3 and the latest vmware_desktop. Acts identical to @Kier.

Please let me know if I can help with logs and such.

**Comment by tweiand** [comment] 2018-04-13 16:44
Oh, one more note: it seems to get worse if I have NFS going to my guest and try port forwarding. I am unable to get a guest started with both these configurations.

**Comment by allanchau** [comment] 2018-04-17 23:01
Seeing the same issue here too:
OS X 10.13.4
VMware Fusion 10.1.1
Vagrant 2.0.3

@iamlittle workaround seemed to work for me.

**Comment by Kier** [comment] 2018-04-18 10:13
Unfortunately, the @iamlittle workaround of starting the VMware app prior to loading the vagrant box does **not** reliably work for me.

This morning, I've had to completely reboot my workstation to get my VM up and running, after endless port forwarding errors.

After I finally got it running, I quit it again and tried to reload, but after a few instances of the 
> Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

problem, I had a successful boot that took over two minutes.

I hope the gist here might help get this resolved in a speedy fashion.

https://gist.github.com/Kier/c24b6bccbfb951211569d8b248159958

**Comment by chrisroberts** [comment] 2018-04-20 23:34
Hi everyone,

The collisions end up being highly dependent on the version of Fusion in use. The networking file ends up being rewritten under different conditions and removes all tagging data. I am prepping an update to the vmware-utility (which manages the port forwarding) that extracts this forward tracking to an isolated global settings location. It will be released shortly and I will post an update here once it is live. My apologies that this has cropped up again as I understand the annoyance it invokes. 

Cheers!

**Comment by Kier** [comment] 2018-04-22 19:42
Just updated to Vagrant 2.0.4 and updated plugins - and I'm still waiting for my VM to boot. It seems stuck in a loop - here is the gist:

https://gist.github.com/Kier/1d255d03d03f145bb7176ad634484839

Note that the machine hasn't finished booting - it's just stuck.

**Comment by Kier** [comment] 2018-04-22 19:44
I ctrl+c'd that boot and ran `vagrant up` again, with the following (successful) result:

https://gist.github.com/Kier/99b91091314e8a74fbbc7884c7555650

**Comment by Kier** [comment] 2018-04-22 19:47
Oh... so not quite successful then:

> kier@Big-Tasty [~/Sites/xf-dev] $ vagrant ssh
> The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

**Comment by Kier** [comment] 2018-04-23 08:37
Still trying to get up and running:

https://gist.github.com/Kier/640c417bed3f8f598e083d19f44496f5

**Comment by Kier** [comment] 2018-04-23 08:46
...and we're back to collisions again.

https://gist.github.com/Kier/fc3888bf5f1ae88b166e4411af6a3f76

**Comment by Kier** [comment] 2018-04-23 08:58
And here's a debug log showing the 

> Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

error:

https://gist.github.com/Kier/44a1c250e97f116b13226e8f93976ad1

**Comment by Kier** [comment] 2018-04-23 09:29
I guess I'll just keep posting gists each time I get a new error - this time it's `Failed to start NAT service`

https://gist.github.com/Kier/1c17c908a8aedc44dbc6bc2c2727df6c

**Comment by Kier** [comment] 2018-04-24 11:12
I've updated to the latest vmware utility, and thus far I have been *unable* to get a failed boot. Thanks, @chrisroberts !

**Comment by chrisroberts** [comment] 2018-04-24 14:12
@Kier Fantastic, thanks for the confirmation it fixed things up for you. 

For everyone on this issue, the new version of the Vagrant VMware Utility I referenced [here](https://github.com/hashicorp/vagrant/issues/9624#issuecomment-383247682) has been released. You can download it from the downloads page:

https://www.vagrantup.com/vmware/downloads.html

Cheers!

**Closed by chrisroberts** 2018-04-24 14:12 UTC
Labels: confirmed, host/darwin, provider/vmware

**Comment by allanchau** [comment] 2018-04-26 00:15
@chrisroberts After updating `vagrant-vmware-utility` and `vagrant-vmware-desktop` to the latest versions I get stuck at `==> default: Waiting for the VM to receive an address...`. If I open VMWare Fusion it shows `a start job is running for the raise network` before eventually getting to the login prompt after 5min.

**Comment by WizBangCrash** [comment] 2018-05-18 19:58
Are others still seeing this issue? I still regularly get the "Vagrant cannot forward the specified ports on this VM" message when bringing up and down vagrant machines.
I'm running:
- macOS 10.13.4
- vagrant 2.1.1 (installed using homebrew)
- vagrant-share 1.1.9
- vagrant-vmware-desktop 1.0.3
- vagrant-vmware-utility 1.0.1

The only way I can get the vagrant machine to boot after experiencing this is to edit the `/Library/Preferences/VMware fusion/networking` and `/Library/Preferences/VMware fusion/vmnet8/nat.conf`

**Comment by allanchau** [comment] 2018-05-20 23:04
@WizBangCrash yeah, vmware is pretty much unusable for me right now 😢 .

**Comment by WizBangCrash** [comment] 2018-05-21 07:34
@allanchau I've been wasting hours on trying to get to the bottom of this issue over the weekend and I have found that if I run the following with the VMware Fusion GUI app closed:
```
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --configure
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --stop
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --start
```
then it keep it closed, vagrant does seem to manage the port forwarding a lot better.
If I open the app at all or leave it open when I run vagrant then I get port forwarding errors.

Give it a try and see if you have the same results.
By Sunday evening I was almost spending more time on the software I am developing than looking into vagrant/VMware bugs :tired_face:

**Comment by Kier** [comment] 2018-06-11 07:07
Unfortunately, the issue is back for me this morning after an unrelated system crash.

**Comment by Kier** [comment] 2018-06-12 11:45
```kier@Big-Tasty [~/Sites/xf-sbp] $ vagrant reload
==> default: Verifying vmnet devices are healthy...
==> default: Pruning invalid NFS exports. Administrator privileges will be required...
Password:
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 80 => 80
    default: -- 3306 => 3307
    default: -- 22 => 2222
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
==> default: Machine booted and ready!
==> default: Setting hostname...
==> default: Configuring network adapters within the VM...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
kier@Big-Tasty [~/Sites/xf-sbp] $ vagrant reload
==> default: Attempting graceful shutdown of VM...
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
==> default: Stopping the VMware VM...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 80 is already in use
on the host machine.

To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 80, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding. You could
try 'vagrant reload' (equivalent of running a halt followed by an up)
so vagrant can attempt to auto-correct this upon booting. Be warned
that any unsaved work might be lost.
```

**Comment by bidadh** [comment] 2018-08-28 13:31
I have installed 
Vagrant 2.1.2
vagrant-vmware-desktop (1.0.4)
VMWare 10.1.3

Had issues with port forwarding and finally got it worked using this [solution](https://github.com/hashicorp/vagrant/issues/5444#issuecomment-182359926)

Adding random port resolves the issue for me

**Comment by tmpkn** [comment] 2019-02-26 16:26
Having the same problem on 2.2.3 + 2.0.3 and latest macOS & fusion pro. Very annoying.

**Comment by damoclark** [comment] 2019-03-05 07:32
Likewise, I too am having the same issue.

macOS 10.13.6
vmware fusion professional version 11.0.2
vagrant 2.2.4
vagrant-vmware-desktop 2.0.3
vagrant-vmware-utility 1.0.7

I believe these all to be the latest vagrant versions.

```
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Checking if box 'bento/centos-7.6' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
Some of the defined forwarded ports would collide with existing
forwarded ports on VMware network devices. This can be due to
existing Vagrant-managed VMware machines, or due to manually
configured port forwarding with VMware. Please fix the following
port collisions and try again:

2222
Finished
```
If I ssh into the guest, there is no hgfs mounts configured when there should be.

This issue has persisted for almost 12 months.  Could hashicorp technical support raise the priority on resolving this?

Regards,
Damien.
