### ISSUE TITLE
Vagrant 2.1.1 +   VMWare Workstation 14.1.2 + vagrant-vmware-desktop 1.0.3 = error during vagrant up

### ISSUE THREAD

**Issue by anemitoff** [hashicorp/vagrant#9915] opened 2018-06-11 14:18 UTC
### Vagrant version
2.1.1

### Host operating system
Windows 10 1803

### Guest operating system
bento/centos-7.4

### Provider
VMWare Workstation 14.1.2

### Vagrant file
```
Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.4"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 9200, host: 9200
    config.vm.provision "shell", path: "provision-server.sh"
end
```

### Debug output
`DEBUG vagrant_utility: request METHOD=GET PATH=/vmnet/vmnet8/dhcplease/00:0c:29:4f:3b:b1 RESPONSE=400`

### Expected behavior
vagrant up process to complete successfully

### Actual behavior
During vagrant up, the process gets stuck "**Waiting for the VM to receive an address...**" and it seems from the debug output that the process repeatedly tries to get the dhcp lease by issuing an HTTP request to some service which returns a 400 code (Bad request).

### Steps to reproduce
1. Install VMWare Workstation 14.1.2
2. Install Vagrant 2.1.1
3. Install Vagrant VMWare utility 1.0.1
4. Install vagrant-vmware-desktop plugin (version 1.0.3)
5. License the plugin
6. Try vagrant up --provider vmware_workstation

**Comment by kikitux** [comment] 2018-06-12 10:33
this is a duplicate of a support ticket.

**Closed by kikitux** 2018-06-12 10:33 UTC
Labels: provider/vmware
