### ISSUE TITLE
vbox GuestAdditions `setup` not found error

### ISSUE THREAD

**Issue by FirEarly** [hashicorp/vagrant#10827] opened 2019-05-06 06:50 UTC
### Vagrant version
Vagrant 2.2.2

### Host operating system
macOS Mojave 10.14.4

### Guest operating system
Ubuntu 14.04 LTS

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "mhdev"
  config.vm.network "forwarded_port", guest: 80, host: 8888 ,id: 'nginx'
  config.vm.network "forwarded_port", guest: 8888, host: 8889 ,id: 'apache'
  config.vm.network "forwarded_port", guest: 3306, host: 3306 ,id: 'mysql'
  config.vm.network "private_network", ip: "192.168.199.101"
  config.vm.synced_folder "/Users/qin/Downloads/hm_ERP/php/", "/home/www",:nfs => true

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

```

### Debug output
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8888 (host) (adapter 1)
    default: 8888 (guest) => 8889 (host) (adapter 1)
    default: 3306 (guest) => 3306 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
vboxadd: unrecognized service
vboxadd-service: unrecognized service
bash: line 4: setup: command not found
==> default: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:

Stderr from the command:

bash: line 4: setup: command not found

### Expected behavior
What should have happened?

### Actual behavior
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
 setup
Stdout from the command:
Stderr from the command:
bash: line 4: setup: command not found

### Steps to reproduce
1.When i use "vagrant up" in the shell.
2.no
3.no

**Comment by briancain** [comment] 2019-05-06 15:09
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by calvin-ryan** [comment] 2019-05-17 18:52
> Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

Hello, I'm having the same issue as the initial poster. I'm not positive what you are asking to see, the results from running: $ vagrant up --debug ?

**Comment by briancain** [comment] 2019-05-17 20:16
@calvin-ryan - yep, exactly!

**Comment by calvin-ryan** [comment] 2019-05-17 21:17
> @calvin-ryan - yep, exactly!
It seems I received that error on a second attempt at running: vagrant up. You can find the debug info in this link: https://gist.github.com/calvin-ryan/342f43c36755af7a167a0e50363fb440

After running: vagrant destroy "OSEHRA VistA - Ubuntu" then: vagrant box remove "OSEHRA Ubuntu 16.04 Image" I believe I had myself back where I began. On the initial run I am receiving an error that states:

"Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant"

This seems to be addressed in an already closed topic https://github.com/hashicorp/vagrant/issues/8303 but I don't understand what it is a person was supposed to change.

I grabbed as much of the debug from the initial run of vagrant up which can be found here: https://gist.github.com/calvin-ryan/ce5b5c5c87e7555b4e8cb274a60492b7

Hopefully something here is useful, let me know if there was something else you were looking for.

**Comment by briancain** [comment] 2019-05-17 21:20
Hey @calvin-ryan - This looks to be a different issue. Your box needs to have virtualbox guest additions installed on it for Vagrant to properly mount vboxsf. If it's a custom box, you need to rebuild it with virtualbox additions. If it's not a custom box, I recommend using a different one that has the virtualbox additions installed, or installing them yourself and repackaging the box. Thanks!

**Comment by calvin-ryan** [comment] 2019-05-17 21:23
> Hey @calvin-ryan - This looks to be a different issue. Your box needs to have virtualbox guest additions installed on it for Vagrant to properly mount vboxsf. If it's a custom box, you need to rebuild it with virtualbox additions. If it's not a custom box, I recommend using a different one that has the virtualbox additions installed, or installing them yourself and repackaging the box. Thanks!

I ran the step below per the instructions, that doesn't suffice?

Install Vagrant VirtualBox Guest Additions Plugin. With the latest versions of VirtualBox and Vagrant the mounting of the shared folders may fail. By adding a plugin to Vagrant the Virtualbox Guest Additions will be automatically installed when a VM is brought up. To install the plugin perform the following:
~$ cd ~
~$ Vagrant plugin install vagrant-vbguest

**Comment by briancain** [comment] 2019-05-17 21:26
@calvin-ryan - We don't officially support that plugin, but it looks like you might be able to just install it and it will set up virtualbox guest additions for you? Either way this doesn't look related to the original issue! If you have an issue that is different from the original, please open a new one. Thanks!

**Comment by calvin-ryan** [comment] 2019-05-17 21:27
> @calvin-ryan - We don't officially support that plugin, but it looks like you might be able to just install it and it will set up virtualbox guest additions for you? Either way this doesn't look related to the original issue! If you have an issue that is different from the original, please open a new one. Thanks!

I see, thanks.

**Comment by briancain** [comment] 2019-05-20 20:47
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2019-05-20 20:47 UTC
Labels: needs-debug-gist, waiting-reply
