### ISSUE TITLE
Backspace is displaying a character on interactive commands bash shell

### ISSUE THREAD

**Issue by julienkosinski** [hashicorp/vagrant#8836] opened 2017-07-31 13:14 UTC
Hello,

### Vagrant version
1.9.7

### Host operating system
Windows 10 Creator's Update

### Guest operating system
Linux based systems, reproduced with Ubuntu 16.04 and Archlinux latest.

### Expected behavior
When we are connected through `vagrant ssh` Linux bash interactive command should handle correctly backspaces.

### Actual behavior
With `vagrant ssh`, interactive command only displays a character as follows with backspace input: ![Character bug with backspace in interactive shell](https://i.imgur.com/Su7gXuT_d.jpg)

### Steps to reproduce
1. Use CMD or Powershell on Windows 10 host, set up a linux guest through Virtualbox (I did not test other provider).
2. In `vagrant ssh` execute any interactive command in the bash shell.
3. Backspace is displaying the character but not the correct behavior.

### References
- 

Thank you very much!

**Comment by chrisroberts** [comment] 2017-08-10 16:04
Hi there,

I have been unable to reproduce this behavior on my Windows 10 host. Can you provide a bigger screenshot of the behavior you are encountering? Thanks!

**Comment by julienkosinski** [comment] 2017-08-10 20:10
Hi!
Thank you very much for your response.

Please find details below :).

I use `Windows Creator’s Update version 10.0.15063`.

I am using `Virtualbox 5.1.26` with `Vagrant 1.9.7`.

I use `Git 2.14.0.2`.

All is installed with `Chocolatey 0.10.5`.

Powershell is as below:
```
$PsVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Here is the screenshot in an interactive command in Ubuntu in both Powershell and CMD. 
![Powershell bug backspace](http://i.imgur.com/Wl9w0n9.png)
![CMD bug backspace](http://i.imgur.com/MJijnM6.png)

PS:
I tested with my laptop this time and it is the same result than with my desktop except that in my desktop the symbol displayed is the same as in Powershell. I suppose it is a font matter, I have the default font of CMD with my laptop and a TrueType with my Desktop. I don’t know why because on both computer I installed git the same way with chocolatey. I don’t think it matter here. 

Thank you very much for your help!

**Comment by chrisroberts** [comment] 2017-08-28 21:01
@julienkosinski Is this issue still present with the latest release of Vagrant (1.9.8) ?

**Comment by julienkosinski** [comment] 2017-08-28 22:09
@chrisroberts Unfortunately yes... :/

**Comment by julienkosinski** [comment] 2017-09-04 07:23
@chrisroberts Also, there's no bug with PuTTY. It seems to be a vagrant ssh bug.

**Comment by julienkosinski** [comment] 2017-09-10 14:14
@chrisroberts Do you need something else to be able to reproduce that?
I tried on two other computer running Windows 10 latest as host and reproduced that.

**Comment by theduke** [comment] 2018-01-20 19:36
Same issue on linux host with docker provider.

Let me know what info I can provide to narrow this down.

**Comment by chrisroberts** [comment] 2018-04-24 23:36
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2018-04-24 23:36 UTC
Labels: host/windows, waiting-reply
