### ISSUE TITLE
action_hook on machine_action_provision not executed

### ISSUE THREAD

**Issue by Mte90** [hashicorp/vagrant#12334] opened 2021-04-28 16:18 UTC
### Vagrant version

2.2.15

### Host operating system

Windows/Linux

# What is happening

So we have a plugin that is a fork of https://github.com/agiledivider/vagrant-hostsupdater/
This plugin has this code:

```
      action_hook(:goodhosts, :machine_action_provision) do |hook|
        hook.before(Vagrant::Action::Builtin::Provision, Action::UpdateHosts)
      end
```

The problem is that the method on `vagrant reload --provision` is not executed. I tried with append/prepend and it is the same.
I don't know if during the years the Vagrant behavior changed.

Ticket: https://github.com/goodhosts/vagrant/issues/35

**Comment by soapy1** [comment] 2021-06-16 20:26
As pointed out in https://github.com/goodhosts/vagrant/pull/39 this issue is caused by the goodhost plugin being too strict about which actions are executed in the [`BaseAction`](https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/Action/BaseAction.rb#L29). That PR resolves the issue, or a similar diff

```
diff --git a/lib/vagrant-goodhosts/Action/BaseAction.rb b/lib/vagrant-goodhosts/Action/BaseAction.rb
index 9567634..0e25c50 100644
--- a/lib/vagrant-goodhosts/Action/BaseAction.rb
+++ b/lib/vagrant-goodhosts/Action/BaseAction.rb
@@ -26,9 +26,9 @@ module VagrantPlugins
           # machines and having a static flag will result in a plugin being
           # executed just once.
           # https://github.com/goodhosts/vagrant/issues/30
-          if not @@completed.key?(@machine.name)
+          if not @@completed.key?("#{@machine.name}-#{self.class.to_s}")
             run(env)
-            @@completed[@machine.name] = true
+            @@completed["#{@machine.name}-#{self.class.to_s}"] = true
           end
 
           @app.call(env)
@@ -42,3 +42,4 @@ module VagrantPlugins
     end
   end
 end
+
```

So, I'm going to go ahead and close this. Thanks!

**Closed by soapy1** 2021-06-16 20:26 UTC
Labels: bug, core
