### ISSUE TITLE
“vagrant” will damage your computer. | Macos monterey

### ISSUE THREAD

**Issue by jigarhalani** [hashicorp/vagrant#13132] opened 2023-04-26 06:58 UTC
Today morning suddenly I started getting this popup whenever I ran Vagrant up in my Mac.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/15965253/234492648-1a3db085-8a18-492f-baa0-ced0ac28a7a8.png">

Virtualbox Version 7.0.4 r154605 (Qt5.15.2)
Macos Monterey, MacBook Pro (Retina, 15-inch, Mid 2015)

| Ubuntu LTS | Settler Version | Homestead Version | Branch      | Status
| -----------| -----------     | -----------       | ----------- | -----------
| 20.04      | 11.x            | 12.x              | `main`      | Development/Unstable
| 20.04      | 11.x            | 12.x              | `release`   | Stable

Do any one have idea whats the issue here?

**Comment by tomvvegchel** [comment] 2023-04-26 07:43
My colleagues and I ran into this problem this morning, we have ended up being able to fix this by updating our vagrant.
Not sure if this is the intended way of fixing this, as this will probably still be a problem on the "older" versions. However, updating vagrant does fix it.

macOS Ventura 13.3.1

**Comment by thirdgen88** [comment] 2023-04-26 13:35
I also got this this morning but from `vagrant-vmware-desktop`, of which I currently have the latest version installed (1.0.21).

**Comment by pentatonicfunk** [comment] 2023-04-26 14:30
i got this instead all of sudden
> “ruby” will damage your computer.

vagrant already latest 2.3.4. installed using homebrew long time ago
show in finder went to this path
```
/opt/vagrant/embedded/bin/ruby
```
![image](https://user-images.githubusercontent.com/831674/234607809-5dc23918-444f-4266-a0b0-65dce5d18322.png)

**Comment by pentatonicfunk** [comment] 2023-04-26 14:34
update: i tried to restart mac, in hope it fixes it self, now i got same issue as other
![image](https://user-images.githubusercontent.com/831674/234609521-fac63695-4cf4-4b74-809a-b0c822ce8b82.png)

**Comment by pentatonicfunk** [comment] 2023-04-26 14:44
update part 2:
so i've reinstalled vagrant
```
❯ vagrant status
[1]    947 killed     vagrant status
  ~/Green/vvv-docker-wpmudev    main !8 ?4                KILL ✘  14s 
❯ brew reinstall --cask vagrant
==> Downloading https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4_darwi
######################################################################## 100.0%
==> Uninstalling Cask vagrant
==> Running uninstall script uninstall.tool
Password:
The following files and directories will be removed:
    /opt/vagrant
    /usr/local/bin/vagrant

Do you wish to uninstall Vagrant (Yes/No)?
The uninstallation process requires administrative privileges
because some of the installed files cannot be removed by a
normal user. You may now be prompted for a password...


Successfully uninstalled Vagrant.
Done.
Press any key to exit.
==> Uninstalling packages; your password may be necessary:
com.vagrant.vagrant
==> Purging files for version 2.3.4 of Cask vagrant
==> Installing Cask vagrant
==> Running installer for vagrant; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is Vagrant
installer: Installing at base path /
installer: The install was successful.
🍺  vagrant was successfully installed!
  ~/Green/vvv-docker-wpmudev    main !8 ?4                                                      1m 20s 
❯ vagrant status
__ __ __ __
\ V\ V\ V / v3.10.0 Ruby:2.7.6, Path:"/Users/hendrawan/Green/vvv-docker-wpmudev"
 \_/\_/\_/  git::main(0d2e0e10)

Platform: darwin19 shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.3.4, docker: v??

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

The provider 'docker' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "version", {:notify=>[:stdout, :stderr]}]

Stderr: Cannot connect to the Docker daemon at unix:///Users/hendrawan/.docker/run/docker.sock. Is the docker daemon running?


Stdout: Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:21:21 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true
```
and now it doesn't throw that warning message anymore. 
man is my mac getting malware inject from somewhere

**Comment by chrisroberts** [comment] 2023-04-26 14:57
Hi there,

This is due to a certificate revocation which is [detailed here](https://support.hashicorp.com/hc/en-us/articles/13177506317203). Re-downloading and installing Vagrant will resolve the issue.

Cheers!

**Comment by akasophistikat** [comment] 2023-04-26 15:29
Thanks for the background @chrisroberts, updating Vagrant to the latest version worked.

**Comment by scott-vick** [comment] 2023-04-28 20:35
I started having the same issue. I re-installed and Vagrant began working again for a short period of time and then I start getting the "Vagrant" will damage your compute message again. I'm installing the latest version of Vagrant via HomeBrew.

**Comment by acornett21** [comment] 2023-04-28 20:38
@scott-vick I experience the same, re-install works for a few minuets/hour tops, then I get the error message...Have uninstalled/reinstalled 4-5 times in the last 2 days.

**Comment by chrisroberts** [comment] 2023-04-28 21:07
@scott-vick is your homebrew currently up to date (have you run `brew update` recently)? 

@acornett21 is your install also via homebrew?

**Comment by scott-vick** [comment] 2023-04-28 21:13
@chrisroberts I did indeed update my brew and all of its installed packages to make sure everything was up to date.

**Comment by chrisroberts** [comment] 2023-04-28 22:20
I'm working on getting a reproduction locally, but in the meantime perhaps try this: 

* uninstall vagrant via `brew`
* check the `/opt/vagrant` directory is gone
* if the directory still exists, delete it
* install vagrant again via `brew`

**Comment by Jos-de-Boss** [comment] 2023-05-01 12:40
For me a simple reinstall did the trick:

```shell
brew reinstall vagrant
```

**Comment by acornett21** [comment] 2023-05-01 14:17
@chrisroberts Yes I was installing/uninstalling via homebrew and making sure that all vagrant related files were deleted. My mac os is `Version 13.3.1 ` is that helps.

**Comment by BilalAslim** [comment] 2023-05-02 11:35
I ran this and it worked for me

```shell
brew reinstall --cask hashicorp-vagrant
 ```

**Comment by paulortvalle** [comment] 2023-05-03 21:43
Reinstalling from binary fixed the issue!

```
vagrant -v
Vagrant 2.3.4
```

**Comment by swateek** [comment] 2023-05-04 03:32
I followed this gist to reinstall vagrant.. [link here](https://gist.github.com/ejlp12/059373f1785c52114d778a4ee7277ccb)

tl; dr

`brew reinstall vagrant --cask`

**Comment by mubbashar** [comment] 2023-05-05 10:26
https://developer.hashicorp.com/vagrant/downloads?product_intent=vagrant

`brew install hashicorp/tap/hashicorp-vagrant`

this fixed my issue

**Comment by remotedevelopment-info** [comment] 2023-06-03 06:23
Maybe there is something awry. Macos kept interrupted, as I am no longer using vagrant, I have simply removed the file in finder and the naggin stopped.  

But...

❯ brew reinstall --cask vagrant
==> Downloading https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4_darwin_amd64.dmg
######################################################################## 100.0%
**Error: SHA256 mismatch
Expected: 8fd27ac9b6faa7a42fcf4b74b25150301f957e9251a1f193d1195b31464fe054
  Actual: 0015f971c20cce4cd3c97ed758f1e0b528bffe0dc02f0ab55da4b216cb5748b8**
    File: ~/Library/Caches/Homebrew/downloads/42e309b6a372ee35af42017a677ef41507b8d183dcbd7b4f1af172c9070e4dee--vagrant_2.3.4_darwin_amd64.dmg
To retry an incomplete download, remove the file above.

**Comment by chrisroberts** [comment] 2023-06-16 21:23
Hi everyone,

As we have had multiple new releases since this issue was first reported I'm going to close this now as it should not be something commonly encountered any longer.

Cheers!

**Closed by chrisroberts** 2023-06-16 21:23 UTC
Labels: installer

**Comment by maniankara** [comment] 2023-06-20 16:55
Just for others coming here to check this, I was having the same problem when I downloaded the prebuilt binary and placed in path.
After downloading/installing the dmg file, it worked.
versions:
vagrant: 2.3.7
macOS: 12.2.1
