### ISSUE TITLE
'vagrant up' triggered by jenkins can not startup virtual machine with gui 

### ISSUE THREAD

**Issue by cppbitman** [hashicorp/vagrant#9911] opened 2018-06-08 09:40 UTC
### Vagrant version
Vagrant 2.1.1

### Host operating system
Ubuntu 18.04 amd64 desktop 

### Guest operating system
Windows 7 x64 , Ubuntu 18.04 amd64 desktop

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "Win7x64"
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network "forwarded_port", host: 33389, guest: 3389, auto_correct:true
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
```

### Jenkinsfile

```
//'vagrant up ' is triggered by Jenkinsfile pipeline
pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'vagrant box list'
        //sh 'vagrant box add Ubuntu /home/devops/vagrant/ubuntu18.04x64-desktop.box'
        sh 'vagrant box list'
        sh 'cd $WORKSPACE && mkdir $BUILD_TAG'
        sh 'cp -f /home/devops/vagrant/Vagrantfile $WORKSPACE/$BUILD_TAG'
        sh 'cd $WORKSPACE/$BUILD_TAG && vagrant up'
        sh 'cd $WORKSPACE/$BUILD_TAG && vagrant halt --force'
      }
    }
  }
}
```

### Debug output

```
[devops_master-OOMAGDYF2IJUOOOTAEZNIXFC4DT42ELOGBKKSSMDFWMVJDAYD3EQ] Running shell script
+ cd /var/lib/jenkins/workspace/devops_master-OOMAGDYF2IJUOOOTAEZNIXFC4DT42ELOGBKKSSMDFWMVJDAYD3EQ/jenkins-devops-master-20

+ vagrant up

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Importing base box 'Ubuntu'...


Progress: 30%
Progress: 40%
Progress: 50%
Progress: 60%
Progress: 70%
Progress: 80%
Progress: 90%
==> default: Matching MAC address for NAT networking...

==> default: Setting the name of the VM: jenkins-devops-master-20_default_1528448151833_26639

==> default: Clearing any previously set network interfaces...

==> default: Preparing network interfaces based on configuration...

    default: Adapter 1: nat

==> default: Forwarding ports...

    default: 22 (guest) => 2222 (host) (adapter 1)

==> default: Booting VM...

There was an error while executing `VBoxManage`, a CLI used by Vagrant

for controlling VirtualBox. The command and stderr is shown below.


Command: ["startvm", "66cc1915-19cb-4407-8299-c59c01bc2835", "--type", "gui"]


Stderr: VBoxManage: error: The virtual machine 'jenkins-devops-master-20_default_1528448151833_26639' has terminated unexpectedly during startup with exit code 1 (0x1)

VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

script returned exit code 1
```

### Expected behavior
Virtual machine startup by virtualbox with gui

### Actual behavior
Virtual machine does not startup

### Steps to reproduce
1. Install Jenkins 2.121.1 on Host with Ubuntu 18.04 amd64 desktop
2. Install vagrant  2.1.1
3. Install virtualbox 5.2.10-dfsg-6 by "apt-get install virtualbox"
4. Build jenkins pipeline

**Comment by briancain** [comment] 2018-06-08 15:55
Hi there,

This is generally caused by a failure to allocate resources on the host machine required by the defined guest. You can inspect the VirtualBox logs to find more information which should help resolve your issue. The following link can help you determine where your log files may be:

https://blogs.oracle.com/fatbloke/virtualbox-log-files

I'll go ahead and close this, but if you think you've found a bug with Vagrant feel free to comment on this issue and it can be reopened! Or if you have any more questions feel free to write an email to the Vagrant up mailing list. Thanks!

**Closed by briancain** 2018-06-08 15:55 UTC

**Comment by briancain** [comment] 2018-06-08 15:57
I also recommend checking out this issue...it seems related to your problem: https://github.com/hashicorp/vagrant/issues/8687

**Comment by jamestylerwarren** [comment] 2018-08-20 22:00
I'm still getting this error after trying just about everything.

Vagrant Version
----------------------
2.12

Virtualbox Version
-------------------------
5.2.10_Ubuntu r121806

Host OS
----------------
ubuntu 18.04 amd64 desktop

Guest OS
------------------
fedora 25
 
I have systemd service (located in /etc/systemd/system/) that watches for changes in /vagrant/Vagrantfile on an ubuntu 18 host machine. If it sees changes, it calls a shell script (also located in /etc/systemd/system/) that 'vagrant up' 's a fedora 25 guest VM. This starts the vagrant machine, but it errors out with the same Virtualbox error as the one posted above: 
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant

for controlling VirtualBox. The command and stderr is shown below.


Command: ["startvm", "xxxxxxxxxx", "--type", "gui"]
```

Expected Behavior
---------------------
VM startup with Virtualbox Gui

Actual Behavior
---------------------
VM errors out with above error code

???
--------------------
Could this be a permissions problem? I can chdir into /vagrant and start the machine with 'vagrant up', and the service I've created is working correctly, they just aren't working in tandom

Maybe related -- I also use Ansible to provision this environment to multiple machines in hopes of using vagrant to spin up a VM, including the gui. However, even using the Ansible 'command' and 'shell' modules I receive this same error.....

THANKS!!
----------------
