### ISSUE TITLE
Cannot install vagrant-vmware-desktop plugin, only stub

### ISSUE THREAD

**Issue by kmoe** [hashicorp/vagrant#9712] opened 2018-04-20 16:54 UTC
### Vagrant version
2.0.3

### Host operating system
Arch Linux 4.15.15 x86_64

### Steps to reproduce
Follow instructions on https://www.vagrantup.com/docs/vmware/installation.html to attempt to install `vagrant-vmware-desktop` plugin.

0. install Vagrant VMWare Utility
1. run `vagrant plugin install vagrant-vmware-desktop`
2. run `vagrant plugin license vagrant-vmware-desktop license.lic`

### Debug output
```
$ vagrant plugin install vagrant-vmware-desktop

Installing the 'vagrant-vmware-desktop' plugin. This can take a few minutes...
Thank you for installing the Vagrant VMware Desktop gem. This
is a placeholder gem for the RubyGems server. The real gem is in
the HashiCorp gem servers. For more information, please visit
the page below.

  https://www.vagrantup.com/vmware
Installed the plugin 'vagrant-vmware-desktop (0.0.1)'!
Post install message from the 'vagrant-vmware-desktop' plugin:

Thank you for installing the Vagrant VMware Desktop gem. This
is a placeholder gem for the RubyGems server. The real gem is in
the HashiCorp gem servers. For more information, please visit
the page below.

  https://www.vagrantup.com/vmware

$ vagrant plugin license vagrant-vmware-desktop license.lic

Installing license for 'vagrant-vmware-desktop'...
The license for 'vagrant-vmware-desktop' was successfully installed
```

### Expected behavior
Either: the real plugin should be downloaded and installed from the HashiCorp gem servers, or: the webpage mentioned in the debug message (https://www.vagrantup.com/vmware) should describe how to obtain the real plugin.

### Actual behavior
The plugin installed is a stub, with version 0.0.1.

The webpage mentioned in the debug message has no information about the HashiCorp gem servers or how to access them.

**Comment by kmoe** [comment] 2018-04-23 10:39
Yes, I can access http://gems.hashicorp.com. I am not behind a proxy.

```
❤@libr ➜  ~  ping gems.hashicorp.com
PING d3bqwsh65659ed.cloudfront.net (54.192.197.158) 56(84) bytes of data.
64 bytes from server-54-192-197-158.lhr50.r.cloudfront.net (54.192.197.158): icmp_seq=1 ttl=247 time=19.5 ms
64 bytes from server-54-192-197-158.lhr50.r.cloudfront.net (54.192.197.158): icmp_seq=2 ttl=247 time=19.6 ms
64 bytes from server-54-192-197-158.lhr50.r.cloudfront.net (54.192.197.158): icmp_seq=3 ttl=247 time=19.7 ms
^C
```

When I visit http://gems.hashicorp.com in the browser, it redirects to https://www.hashicorp.com.

I am aware that the latest version of the gem is located at http://gems.hashicorp.com/. However, I would appreciate further instructions as to how to actually obtain this gem, since they are not in the command output or your documentation.

**Comment by chrisroberts** [comment] 2018-04-23 14:32
It seems as though the gem sources from the gems.hashicorp.com gem store are not being pulled in properly when you attempt to install the gem. Can you please provide a gist of the output from running:

```
$ vagrant plugin install vagrant-vmware-desktop --debug
```

This should help provide some information to find the root cause of the issue. Thanks!

**Comment by kmoe** [comment] 2018-04-23 14:57
Thank you. Here is the gist:

https://gist.github.com/kmoe/3f68d0a091fcead7c37130e14fa842a0

**Comment by jcorme** [comment] 2018-05-21 05:26
I had the same problem today after installing Arch Linux, and it looks like this an issue with Ruby 2.5 and/or RubyGems 2.7.

The plugin installed correctly after I downgraded to Ruby 2.4.3 (https://archive.archlinux.org/packages/r/ruby/ruby-2.4.3-1-x86_64.pkg.tar.xz).

**Comment by guillaumededrie** [comment] 2018-06-11 14:52
When you downgrade to Ruby 2.4.3 (as mentionned by @jcorme), the installation of `vagrant-vmware-desktop` works, but the `vagrant rsync-auto` command doesn't work anymore…

**Comment by DominikSchlecht** [comment] 2018-07-15 06:51
Issue sadly is still present but at least the fix by @jcorme keeps working. Hurts having to downgrade ruby by 7 versions to get this to run.

Btw., for easier downgrading, on Arch you can use the tool downgrader :)

**Comment by kilmister** [comment] 2018-09-14 14:47
Issue still present as of 9/13/2018.  Fix by @jcorme continues to work as long as Ruby is downgraded after every pacman update.

**Comment by briancain** [comment] 2018-11-06 23:11
Closing this issue via https://github.com/hashicorp/vagrant/pull/10364. It should be fixed in the next release, thanks!

**Closed by briancain** 2018-11-06 23:11 UTC
Labels: bug, bundler
