### ISSUE TITLE
Vagrant crashes with a space in my lastname.

### ISSUE THREAD

**Issue by trollmad3** [hashicorp/vagrant#10157] opened 2018-08-30 19:21 UTC
Whenever I type `vagrant up` in the folder it crashes with a space in my last name. 

![image](https://user-images.githubusercontent.com/7843719/44874182-9236d780-ac57-11e8-990f-cf438b9438d6.png)

The only thing censored in the photo is my last name and the repo I'm working on. 

I am using Windows 10.

**Comment by chrisroberts** [comment] 2018-08-30 19:47
@trollmad3 Does the path contain any non-ascii characters?

**Comment by trollmad3** [comment] 2018-08-30 20:07
@chrisroberts  No.

**Comment by chrisroberts** [comment] 2018-08-30 20:10
@trollmad3 Is the path on onedrive?

**Comment by trollmad3** [comment] 2018-08-30 20:10
@chrisroberts No. It is on my local C:\ Drive.

**Comment by chrisroberts** [comment] 2018-08-30 20:17
@trollmad3 Can you create a directory (`C:\Users\YOUR USERNAME\test`) and in that directory run:

```
> vagrant init -m BOX_NAME
> vagrant up
```

where BOX_NAME is just the name of a box you have locally available. Would like to see if you get the same error here as I'm unable to reproduce the error you are experiencing with a space in the path.

Thanks!

**Comment by trollmad3** [comment] 2018-08-30 20:30
@chrisroberts  This happens now. 

<img width="398" alt="cmd_2018-08-30_14-29-51" src="https://user-images.githubusercontent.com/7843719/44877448-3f621d80-ac61-11e8-87fe-0cb9d0b591cc.png">

**Comment by briancain** [comment] 2018-08-30 20:34
@trollmad3 - do you have virtualbox installed on your system?

**Comment by trollmad3** [comment] 2018-08-31 01:03
@briancain No I do not.

**Comment by briancain** [comment] 2018-08-31 15:43
Hi @trollmad3 - you need to install a provider to use to bring up a virtual machine with Vagrant https://www.vagrantup.com/docs/providers/basic_usage.html#boxes.

Your original error was likely because that file was on onedrive, since it seems like Vagrant didn't have any issues with the space in your name with this folder. Currently that is not supported with Vagrant. I'm going to go ahead and close this issue. Thanks!

**Closed by briancain** 2018-08-31 15:43 UTC
Labels: host/windows, waiting-reply

**Comment by trollmad3** [comment] 2018-08-31 20:50
It turns out vagrant no longer crashes with a space in my name. I had ransomware protection on with my windows defender and as soon as I turned it off everything works. 
<img width="385" alt="applicationframehost_2018-08-31_14-43-30" src="https://user-images.githubusercontent.com/7843719/44935240-1f982b80-ad2d-11e8-93b9-49b9a680747c.png">

**Comment by briancain** [comment] 2018-08-31 20:52
@trollmad3 - Ahh, that's interesting. Thanks for letting us know!

**Comment by trollmad3** [comment] 2018-08-31 20:54
@briancain No problem. This caused a lot of issues just not with vagrant.
