### ISSUE TITLE
Can't download any vagrant box hosted by Vagrant Cloud

### ISSUE THREAD

**Issue by CodingMadeEasy** [hashicorp/vagrant#9379] opened 2018-01-16 22:58 UTC
### Vagrant version
2.0.0 and 2.0.1

### Host operating system
OSX and Windows

### Guest operating system
Centos 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "c9s/centos-stack"
end
```

### Debug output
An error occurred while download the remote file. The error message, if any, is reproduced below. Please fix this error and try again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

(Sometimes on OSX it says LIBRESSL instead of OPENSSL)

### Expected behavior
It should download the vagrant box from vagrant cloud, but it fails due to an SSL error. When I try to download an externally hosted box such as ubuntu/trusty64 everything works fine.

### Actual behavior
I get an SSL error

### Steps to reproduce

Method 1: Vagrant up

Method 2: `vagrant box add c9s/centos-stack`

Method 3: `vagrant box add --insecure -c c9s/centos-stack http://atlas.hashicorp.com/c9s/boxes/centos-stack

I've also tried with laravel/homstead and it still fails to download, but when I try ubuntu/trusty64 everything works fine. The difference between them is that trusty64 is externally hosted and c9s/centos-stack + laravel/homestead are not.

**Comment by mycool0943** [comment] 2018-01-18 18:59
I can also confirm after starting a download of a windows box, the above error appears.

**Comment by CodingMadeEasy** [comment] 2018-01-18 19:02
Update: I was able to download the vagrant box at a friends house using their internet. So it seems like it's a network related issue. Does anyone have any idea what could cause vagrant cloud to not work on certain networks?

**Comment by Barami** [comment] 2018-02-04 03:17
It seems repository of hashicorp has been doen or removed.
When you access https://atlas.hashicorp.com/debian/stretch64 on browser.
It returned 404 page with following message.

"The Packer, Artifact Registry and Terraform Enterprise (Legacy) features of Atlas will no longer be actively developed or maintained and will be fully decommissioned on Friday, March 30, 2018. Please see our guide on building immutable infrastructure with Packer on CI/CD for ideas on implementing Packer and Artifact Registry features yourself and the Upgrading From Terraform Enterprise (Legacy) guide to migrate to the new Terraform Enterprise."

https://stackoverflow.com/questions/10155708/where-does-vagrant-download-its-box-files-to

**Comment by chrisroberts** [comment] 2018-02-05 16:18
I am unable to reproduce this behavior. I'm going to close this and chalk it up to an intermittent network issue. If you continue to encounter this behavior and can provide a way to reliable reproduce it, please open a new issue and I will investigate further. Thanks!

**Closed by chrisroberts** 2018-02-05 16:18 UTC

**Comment by PranjalGohain** [comment] 2018-02-14 08:05
I am having this same issue. And i tried with multiple network connections . It was working with the previous domain but since the images had been moved to some other location its not working.

**Comment by briancain** [comment] 2018-02-14 16:37
Hi @PranjalGohain - please look at this issue for more information #9442. Thanks!

**Comment by robertoschuh** [comment] 2019-03-25 09:34
I had the same issue, but same when I tried to download docker images with my 4G phone connection. If I use a broadband conex it is OK, why? No idea.
