### ISSUE TITLE
Warning: Connection reset. Retrying...  Mac OS host

### ISSUE THREAD

**Issue by svstartuplab** [hashicorp/vagrant#10608] opened 2019-01-21 01:10 UTC
I'm running the latest versions of Mac OS, VirtualBox, Vagrant, Ubuntu, and probably everything else.

The problem may be with the private_key file permissions but sometimes it isn't.  I've tried every diagnostic procedure I've found online.

The vagrantfile has been in use in my host environment for years.  A recent VirtualBox or vagrant box upgrade seems to have started causing this problem.

### Vagrant version

Vagrant 2.2.3, same problem with 2.2.0.

### Host operating system

Mac OS Mojave 10.14.2

### Guest operating system

Ubuntu 18.04.1  after upgrade in box ubuntu/xenial64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = "true"
  config.vm.hostname = "myProject"
  config.vm.network "forwarded_port", host: 8084, guest: 80
  config.vm.network "forwarded_port", host: 8080, guest: 8080
  config.vm.network "forwarded_port", host: 8079, guest: 8079
  config.vm.network "forwarded_port", host: 3000, guest: 3000
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network"
  config.vm.define "mybox"
  config.vm.provision :shell, path: ".provision/bootstrap.sh"
  config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"
  config.vm.synced_folder "ubuntu", "/home/vagrant"
  config.ssh.insert_key = true

# VirtualBox
  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.name = "pfserver" # friendly name that shows up in Oracle VM VirtualBox Manager
    vb.memory = 2048 # memory in megabytes 2.0 GB
    vb.cpus = 1 # cpu cores, can't be more than the host actually has.
  end
end
```
My original working vagrantfile used: ```config.ssh.insert_key = true```  I've tried both true and false and commenting the line out and no change in the problem.  I don't care about security on my dev computer.  This worked on reload once but failed after that.  I'm reloading because after upgrading the box from a previous version to 0115 last week and a day or so later this:

```vagrant box list  =  ubuntu/xenial64 (virtualbox, 20190118.0.0)```

Virtualbox 5.2.24

### Debug output

This time it was looping and I had to CTL C to get out of it:
https://gist.github.com/svstartuplab/fe0d282c1d7e6e0221cd8352672adebc
I halted the box and tried up and I used vagrant reload.

### Expected behavior
I should be able to ssh into the box from Webstorm terminal and have been doing this with this Vagrant file for years.  I've destroyed several boxes working on this issue.  That doesn't help.

### Actual behavior

With vagrant up, reload, or resume on an existing box I get this in terminal:
```
mybox: SSH username: vagrant
mybox: SSH auth method: private key
mybox: Warning: Connection reset. Retrying...
mybox: Warning: Remote connection disconnect. Retrying...
```
This goes on for minutes and finishes booting, as comments on similar issues have said.  However, I still can't ssh into Ubuntu.

I```sudo chmod 644 private_key``` in .vagrant/machines/mybox/virtualbox before, during boot-up, and after.  Under some circumstances this works, not clear which circumstances yet, but mostly it doesn't - the attempts at connection are changing the private_key file permissions continuously during boot.  This seems to be the problem but it has worked with the restricted permissions.

```-rw-------   1 username  staff  1675 Jan 18 13:16 private_key```

Should be? ```  -rw-r--r--```

However, when I ran VAGRANT_LOG=info vagrant up the first time I could log in and the the permissions were set at  ```-rw-------````  After that it never worked again with maybe a dozen tries with various ways to boot Vagrant.  So the issue is hit or miss.

### Steps to reproduce

1.  After vagrant destroy and then vagrant up everything works on a new box.
2.  After upgrading Vagrant to 2.2.3 I vagrant up and it goes well and I can ssh into the box.
3.  However, my synced files aren't loading, as they have for years with this vagrantfile.  They don't show as loading in the boot up.  I don't know if this problem is related to the private_key issue.  Both /vagrant and /home/vagrant from my vagrant config aren't loading.  I vagrant suspend then vagrant resume and the retrying messages pile up in terminal until it times out. This is when I try vagrant up --provision, vagrant up, and vagrant reload.  Same problem, lots of retrying.  Eventually it finishes booting and I can't ssh into the box.
 
This process is too sensitive to something.  It has been a problem for many others for years.  Maybe a rethink needed?

### References

9416, 9834, 9900

**Comment by svstartuplab** [comment] 2019-01-24 21:32
This problem may have to do with upgrading Ubuntu from 16.04 to 18.04.  While I was able to log in with an rsa key pair when I initially setup the box I'm not able to after the upgrade.  I have no clue why this could be a problem.

**Comment by svstartuplab** [comment] 2019-01-25 18:56
If I'm patient then after six minutes VirtualBox displays the login view and I can SSH into the box.  I have to CTL C when the warning messages are streaming because rarely will it complete.  Usually I get a time out message and the boot up stops.  Attached is the VirtualBox screen view when it halts for 6 minutes.  Whatever is happening at this point needs to be fixed.  I hope this helps!

![vagrant_box_boot_stuck](https://user-images.githubusercontent.com/5234493/51766496-955fb380-208f-11e9-8b23-82b653c8050d.png)

**Comment by chrisroberts** [comment] 2019-01-30 23:21
Duplicate of #10578 

See https://github.com/hashicorp/vagrant/issues/10578#issuecomment-459081990 for more information

Cheers!

**Closed by chrisroberts** 2019-01-30 23:21 UTC

**Comment by svstartuplab** [comment] 2019-02-07 20:06
chrisroberts, I don't completely understand that fix but I solved the problem by manually copying the public key info from this file where I used `ssh-keygen -t ecdsa -b 521` to make `~/.ssh/id_ecdsa.pub` and pasting into this file:   `/home/vagrant/.ssh/authorized_keys`.  This line in my vagrantfile didn't work but should have:  `pfbox.vm.provision "file", source: "~/.ssh/id_ecdsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"`  Also, for diagnostics this is useful: `vagrant ssh -- -vv` = verbose diagnostics.
