### ISSUE TITLE
Snapshot Save: No Default Machine

### ISSUE THREAD

**Issue by harmonyharmo** [hashicorp/vagrant#11215] opened 2019-11-22 18:58 UTC
### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
2.6

### Host operating system
This is the operating system that you run locally.
Windows 10

### Expected behavior
What should have happened?
When I run `vagrant snapshot save nov22`, a snapshot named "nov22" should be created. See https://www.vagrantup.com/docs/cli/snapshot.html#snapshot-save

### Actual behavior
What actually happened?
It's looking for a machine called "nov22": `The machine with the name 'nov22' was not found configured for Vagrant environment.`

### Steps to reproduce
1. run `vagrant snapshot save nov22`

**Comment by jbonhag** [comment] 2019-11-22 20:01
Hi there,

Thanks for opening an issue with Vagrant! We recently merged in a PR https://github.com/hashicorp/vagrant/pull/11152 which fixes a regression caused by an earlier PR.  This regression incorrectly treated the snapshot name as the machine name (see https://github.com/hashicorp/vagrant/issues/11139).

As a temporary workaround, you can either roll back to Vagrant 2.2.5 or specify the default VM name in the `snapshot` command:

```
vagrant snapshot save default nov22
```

Hope this clears things up!  Cheers.

**Comment by harmonyharmo** [comment] 2019-11-22 20:16
Cool, thanks.

**Closed** 2019-11-22 20:21 UTC
Labels: duplicate, waiting-reply
