### ISSUE TITLE
vagrant unsetting Promiscuous mode on linux host (resetting linux permissions)

### ISSUE THREAD

**Issue by riotejas** [hashicorp/vagrant#10233] opened 2018-09-24 19:43 UTC
### Vagrant version
```
$ vagrant --version
Vagrant 2.1.5
$ vagrant plugin list
vagrant-vmware-desktop (1.0.4, global)
$ vmware --version
VMware Workstation 14.1.3 build-9474260
```
### Host operating system
Ubuntu 16.04.5
```
$ uname -a
Linux fragfly7 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "vmware_workstation" do |v|
     v.gui = false
  end

  config.vm.box_check_update = false

  # uncomment below to disable the default share
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
```
### Debug output
https://gist.github.com/riotejas/5fae0a9a9acd536dead75b7a61526848

### Expected behavior
My VMs need the ability to inspect all traffic on the vmnet, this is called Promiscuous Mode. On linux, this is enabled by chmod’ing the /dev/vmnet* devices to ‘rw’ for everyone.  On startup, VMware creates the devices and they are chmod’ed to ‘rw’ privileges for group and world.  

### Actual behavior
The problem is that when Vagrant  is up-ing  (or destroy-ing) the VM, it is resetting the vmnets and erasing the device group/privileges that VMware set.  

Starting a VM using vmrun does not exhibit this behavior.  We have been using this method for many months (on an older 1.8.5 & 2.0.2 vagrant) but I upgraded to latest vmware and vagrant last week which has now broken my VMs.

### Steps to reproduce
1.  With VMware Network Editor, create several new host-only vmnet’s, say vmnet21 and vmnet23
2. Start VMware Workstation
3. confirm that vmnet devices are created
```
$ ls -l /dev/vmnet2?
crw------- 1 root root 119,  21 Sep 20 16:14 /dev/vmnet21
crw------- 1 root root 119,  23 Sep 20 16:14 /dev/vmnet23
```
2. Set devices to Promiscuous Mode https://kb.vmware.com/s/article/287
`sudo chgrp vmuser /dev/vmnet2?`
`sudo chmod a+rw /dev/vmnet2?`

Here's how I set it to be persistent across reboots:
```
$ cat /etc/init.d/vmware
<snip>
# Start the virtual ethernet kernel service
vmwareStartVmnet() {
   vmwareLoadModule $vnet
   "$BINDIR"/vmware-networks --start >> $VNETLIB_LOG 2>&1
   chmod a+rw /dev/vmnet2?
}
<snip>
```
3. Confirm that Promiscuous Mode is set:
(Note group and world permissions)
```
$ ls -l /dev/vmnet2?
crw-rw-rw- 1 root vmuser 119, 21 Sep 24 09:56 /dev/vmnet21
crw-rw-rw- 1 root vmuser 119, 23 Sep 24 09:56 /dev/vmnet23
```
4. `vagrant up` using simple Vagrantfile above.
5. Once vm is up, the  vmnets have been reset, or removed and recreated during the 'up' (destroy also does this) group-name has also be reset.
```
$ ls -l /dev/vmnet2?
crw------- 1 root root 119, 21 Sep 24 12:55 /dev/vmnet21
crw------- 1 root root 119, 23 Sep 24 12:55 /dev/vmnet23
```
My VMs no longer function as needed.

**Comment by chrisroberts** [comment] 2018-10-03 14:38
@riotejas Yep, this is confirmed. The underlying cause is due to the method used for applying networking related modifications. I'm working on a fix for the issue and it will be included in the next release of the utility.

**Comment by riotejas** [comment] 2018-10-03 18:33
Great ! Do you have any guess on date?  Anything I can test for you?  I installed 10 servers then found the bug.  I’ve back-rev’d 4 of them to use old OS and old Vagrant&VMware, therefore I have several servers setup ready.



On October 3, 2018 at 9:39:22 AM, Chris Roberts (notifications@github.com) wrote:

@riotejas Yep, this is confirmed. The underlying cause is due to the method used for applying networking related modifications. I'm working on a fix for the issue and it will be included in the next release of the utility.

**Comment by chrisroberts** [comment] 2018-10-04 14:33
@riotejas Should be early next week.

**Comment by riotejas** [comment] 2018-10-19 15:54
I Downloaded the new vagrant 2.2.0 and still getting device permissions
reset on a vagrant up/destroy
russell@fragfly7:ff$ vagrant --version
Vagrant 2.2.0
russell@fragfly7:ff$ vagrant plugin list
vagrant-vmware-desktop (2.0.0, global)
  - Version Constraint: > 0




On October 4, 2018 at 4:35:10 AM, Chris Roberts (notifications@github.com)
wrote:

@riotejas <https://github.com/riotejas> Should be early next week.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashicorp/vagrant/issues/10233#issuecomment-427042309>,
or mute the thread

**Comment by riotejas** [comment] 2018-10-25 20:06
@chrisroberts Any update on a fix for this?

**Comment by chrisroberts** [comment] 2018-10-25 22:29
@riotejas Yep, another update that is included in this release has taken a bit longer to wrap than expected. However, everything is completed and I'll be cutting releases before the EOD today. I'll be closing this issue as soon as it's available.

**Comment by chrisroberts** [comment] 2018-10-27 00:12
The updates are released. The fix for the network device permissions/ownership is within the update to the vagrant-vmware-utility: https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-utility-changelog.md#105

Cheers!

**Closed by chrisroberts** 2018-10-27 00:12 UTC
Labels: confirmed, provider/vmware
