### ISSUE TITLE
Receive Permission denied error (Error::EACCES) when other VMs are running

### ISSUE THREAD

**Issue by onedsc** [hashicorp/vagrant#9072] opened 2017-10-18 17:17 UTC
### Vagrant version
2.0.0.0 with vmware fusion plugin 5.0

### Host operating system
MacOS High Sierra 

### Guest operating system
CentOS 7.4

### Debug output
/Users/dcook/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-fusion-5.0.0/lib/vagrant-vmware-fusion/helper/nat_conf.rb:169:in `initialize': Permission denied @ rb_sysopen - /Users/dcook/.vagrant.d/data/vmware/vmware-nat.json.lock (Errno::EACCES)

### Expected behavior
Bringup up the VM as normal

### Actual behavior
Ruby exception

### Steps to reproduce
Start some of VMs using VMWare UI
Try to bring up an existing 8.0 vagrant box using vagrant up command

### References:
https://github.com/hashicorp/vagrant/issues/9047

**Comment by onedsc** [comment] 2017-10-18 17:21
Seems to be a dup of https://github.com/hashicorp/vagrant/issues/9047

**Comment by briancain** [comment] 2017-10-18 18:33
Hi! Thanks for opening an issue, as you mentioned, this seems to be a duplicate of #9047 so I'm going to go ahead and close this.

**Closed by briancain** 2017-10-18 18:33 UTC
