### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication.

### ISSUE THREAD

**Issue by robinportigliatti** [hashicorp/vagrant#13083] opened 2023-02-13 11:31 UTC
### Debug output

[vagrant.log](https://gist.github.com/robinportigliatti/f73b1c697e1f73ac9f2d73a4a7b1983a)

### Expected behavior

Provisionning with ansible can be run a numerous times.

### Actual behavior

An error happens when executing a second time `vagrant provision`.

#### Vagrant version

```
Vagrant 2.3.4
```

#### Host operating system

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### Guest operating system

```
generic/rocky8
```

#### Steps to reproduce

1. vagrant up --no-provision
2. vagrant provision
3. vagrant provision

#### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
BOX_BASE = "generic/rocky8"

LIMIT = "all"
if BOX_BASE == "generic/rocky8" or BOX_BASE == "generic/centos8" then
  SHELL = true
else
  SHELL = false
end

Vagrant.configure("2") do |config|
  # Configuration du primary
  
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
  config.ssh.forward_agent = false
  config.vm.box = BOX_BASE
  if BOX_BASE == "generic/ubuntu2204" then
    config.vm.box_version = "4.1.20"
  end
  if SHELL then
    if BOX_BASE == "generic/rocky8" or BOX_BASE == "generic/centos8" then
      config.vm.provision "shell",
        inline: "sudo yum install python3.9 nano git -y && sudo systemctl stop firewalld && sudo systemctl disable firewalld"
    end
  end

  srv_hostname="srv1"
  config.vm.define srv_hostname do |host_config|
    host_config.vm.hostname = srv_hostname
    host_config.vm.network :private_network, ip: "192.168.60.31"

    # Libvirt settings
    host_config.vm.provider "libvirt" do |hv|
      # VM Shape
      hv.cpus = "1"
      hv.memory = "1024"
    end
    host_config.vm.provision "ansible" do |ansible|
      ansible.limit = LIMIT
      ansible.playbook = "./playbook.yml"
      ansible.inventory_path = "./inventory"
      ansible.compatibility_mode = "2.0"
    end

  end
end # Vagrant.configure("2") do |config|
```

#### Playbook

```
# playbook.yml
- hosts: "all"
  gather_facts: yes
  become: yes
  tasks:
    - name: "Remove SElinux"
      ansible.builtin.shell: "setenforce 0"
      when: 'ansible_os_family == "RedHat"'
```

#### Inventory

```
[servers]
srv1 ansible_host=192.168.60.31
```

#### Ansible configuration

```
[defaults]
stdout_callback=yaml
stderr_callback=yaml

[privilege_escalation]
become_flags=-i
```

**Comment by soapy1** [comment] 2023-02-13 19:23
Hey there,

it looks like the root cause is an SSH authentication failure https://gist.github.com/robinportigliatti/f73b1c697e1f73ac9f2d73a4a7b1983a#file-vagrant-log-L632 - vagrant is unable establish an ssh connection with the guest. It seems like this is probably happening because of these lines in your Vagranfile which replace some keys and authorized hosts lists. If you want to change the ssh keys that Vagrant uses to connect to the guest you should use the `private_key_path` option. You can read more about it in the docs https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings#config-ssh-private_key_path. 

Since this isn't a bug with Vagrant, I'm going to go ahead and close this issue. If you have further questions about configuring your guest with different ssh settings please open up a thread on the Vagrant discuss forum https://discuss.hashicorp.com/c/vagrant/24. Thanks!

**Closed by soapy1** 2023-02-13 19:23 UTC
Labels: waiting-intake
