### ISSUE TITLE
Plugin cannot hook after specific action

### ISSUE THREAD

**Issue by fnordfish** [hashicorp/vagrant#12046] opened 2020-11-14 14:16 UTC
While investigating dotless-de/vagrant-vbguest#387 and dotless-de/vagrant-vbguest#391 I've found, that vagrant 2.2.11 somehow changed the way plugin can hook before other actions.

I didn't noticed this earlier since my local dev bundle still pointed to the old "master" branch (v2.2.11.dev).

Here's whats going on:

For historic, backwards compatibility reasons vbguest has those 7 year old lines in it's plugin definitions:

```ruby
module VagrantVbguest
  class Plugin < Vagrant.plugin("2")
    # ...
    action_hook('vbguest') do |hook|
      if defined?(VagrantPlugins::ProviderVirtualBox::Action::CheckGuestAdditions)
        hook.before(VagrantPlugins::ProviderVirtualBox::Action::CheckGuestAdditions, VagrantVbguest::Middleware)
      else
        hook.after(VagrantPlugins::ProviderVirtualBox::Action::Boot, VagrantVbguest::Middleware)
      end
    end
  end
end
```

So, I can change to hook like this:

```
action_hook('vbguest', :machine_action_up) do |hook|
  require 'vagrant-vbguest/middleware'
  hook.append(VagrantVbguest::Middleware)
end
```

In a small sample, this seems to be working. Although it will now run after Vagrants own `CheckGuestAdditions`.
I'm not sure if using the `machine_action_up` hook makes sure, that vbguest runs before anything else tries to run which would require working guest additions.

What's your take on this?

**Comment by soapy1** [comment] 2020-11-16 15:21
This seems to be a duplicate of #12035. While the plugin in question is different, the root cause seems to be the same. As mentioned in the referenced issue, there is a test package with a fix available https://github.com/hashicorp/vagrant-installers/releases/tag/v2.2.14.dev%2B157db399.

I'm going to go ahead and close this issue as a duplicate so as to consolidate discussion related to this bug to one open issue. Please feel free to reopen if it seems fit.

**Closed by soapy1** 2020-11-16 15:21 UTC
