### ISSUE TITLE
Unable to create a Centos virtual box

### ISSUE THREAD

**Issue by saumik8763** [hashicorp/vagrant#9853] opened 2018-05-19 14:46 UTC
Bringing machine 'vm1' up with 'virtualbox' provider...
==> vm1: Box 'centos/7' could not be found. Attempting to find and install...
    vm1: Box Provider: virtualbox
    vm1: Box Version: 1611.01
The box 'centos/7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/centos/7"]
Error: The requested URL returned error: 404 Not Found

**Comment by jackteoh** [comment] 2018-05-19 20:11
The correct url should be "/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1804_02.VirtualBox.box" . There is an extra character "1" in link

**Comment by saumik8763** [comment] 2018-05-20 06:04
Where can I edit that?

**Comment by chrisroberts** [comment] 2018-05-21 22:17
Closing as duplicate of #9852.

Cheers!

**Closed by chrisroberts** 2018-05-21 22:17 UTC
Labels: duplicate
