### ISSUE TITLE
Vagrant backed by docker on Windows 10

### ISSUE THREAD

**Issue by JeremyMarshall** [hashicorp/vagrant#8512] opened 2017-04-23 22:25 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
1.9.3 - installed by choco

### Host operating system
This is the operating system that you run locally.
windows 10 on surface pro

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.vm.provider "docker" do |d|
    d.image = "jboss/wildfly:latest"
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/JeremyMarshall/6a87a99d4c78479f85ab40d2d9c29d76

### Expected behavior
Spin up a VM on docker on windows (docker-toolbox)

### Actual behavior
What actually happened?

```
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Docker host VM is already ready.
==> default: Syncing folders to the host VM...
    default: The machine you're rsyncing folders to is configured to use
    default: password-based authentication. Vagrant can't script rsync to automatically
    default: enter this password, so you'll likely be prompted for a password
    default: shortly.
    default:
    default: If you don't want to have to do this, please enable automatic
    default: key insertion using `config.ssh.insert_key`.
    default: Rsyncing folder: /c/Users/jerem/vagrant/docker-test/ => /var/lib/docker/docker_1492939889_18367
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /c/Users/jerem/vagrant/docker-test/
Guest path: /var/lib/docker/docker_1492939889_18367
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" "--exclude" ".vagrant/" "/c/Users/jerem/vagrant/docker-test/" "docker@127.0.0.1:/var/lib/docker/docker_1492939889_18367"
Error: Permission denied (publickey,password,keyboard-interactive).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

```

### Steps to reproduce
1. install choco
2. choco install vagrant
3. choco install git
4. choco install rsync
5. Vagrantfile as above
6. vagrant up --provider=docker

**Comment by osher** [comment] 2017-08-14 08:12
+1

**Comment by osher** [comment] 2017-08-14 08:16
I'm not sure it's related - however - on `windows 10 pro` - the boot2docker thing over virtual box does not work.
The recommended solution is not to use docker-tookbox, but to use the docker msi which recognizes win10 pro and directs it's effort to Hyper-V.
(and currently, the Kitematics is still installed manually from a zip)

Im not aware of the low level details except for using Hiper-V over VBox - but it does feel *essentially* different: more stable and better integrated to the windows shell on one hand - but yet in a bubble out of the ecosystem on the other hand...

**Comment by snfnwgi** [comment] 2017-09-30 07:50
Who can answer my question
https://github.com/hashicorp/vagrant/issues/9010

**Comment by AndrewSav** [comment] 2017-09-30 22:56
@snfnwgi linking your problem in a dozen of other people threads is not a very good etiquette, it's rude. You should not be doing this.

**Comment by daveneeley** [comment] 2017-11-09 00:29
I've found that vagrant doesn't work correctly with the regular windows rsync that you get via chocolatey. It does work for me from cygwin with cygwin's rsync package installed. Ultimately though the debug output says 'Permission Denied', so it looks the issue is that the ssh environment that is set up by rsync is invalid. This happens with other providers besides docker as well.

``` INFO subprocess: Starting process: ["C:\\ProgramData\\chocolatey\\bin/rsync.EXE", "--verbose", "--archive", "--delete", "-z", "--copy-links", "--chmod=ugo=rwX", "--no-perms", "--no-owner", "--no-group", "--rsync-path", "sudo rsync", "-e", "ssh -p 2200 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null", "--exclude", ".vagrant/", "/c/Users/jerem/vagrant/docker-test/", "docker@127.0.0.1:/var/lib/docker/docker_1492940095_47344"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Permission denied (publickey,password,keyboard-interactive).

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 12
ERROR warden: Error occurred: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /c/Users/jerem/vagrant/docker-test/
Guest path: /var/lib/docker/docker_1492940095_47344
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" "--exclude" ".vagrant/" "/c/Users/jerem/vagrant/docker-test/" "docker@127.0.0.1:/var/lib/docker/docker_1492940095_47344"
Error: Permission denied (publickey,password,keyboard-interactive).

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.```

**Comment by chrisroberts** [comment] 2018-12-21 23:54
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2018-12-21 23:54 UTC
Labels: host/windows, synced-folders/rsync
