### ISSUE TITLE
Stderr: VBoxManage.exe: error: A NAT rule of this name already exists

### ISSUE THREAD

**Issue by fendo8888** [hashicorp/vagrant#9842] opened 2018-05-16 12:37 UTC
Environment:
VirtualBox version:  VirtualBox-5.2.12-122591-Win.exe
Vagrant version:  vagrant_2.1.1_x86_64.msi

C:\OS>vagrant up
Bringing machine 'test' up with 'virtualbox' provider...
==> test: Clearing any previously set forwarded ports...
==> test: Clearing any previously set network interfaces...
==> test: Preparing network interfaces based on configuration...
    test: Adapter 1: nat
    test: Adapter 2: hostonly
==> test: Forwarding ports...
    test: 22 (guest) => 2222 (host) (adapter 1)
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "d015291e-a235-40ef-bdcc-115ed437559f", "--natpf1", "ssh,tcp,127.0.0.1,2222,,22"]

Stderr: VBoxManage.exe: error: A NAT rule of this name already exists
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component NATEngineWrap, interface INATEngine, callee IUnknown
VBoxManage.exe: error: Context: "AddRedirect(Bstr(strName).raw(), proto, Bstr(strHostIp).raw(), RTStrToUInt16(strHostPort), Bstr(strGuestIp).raw(), RTStrToUInt16(strGuestPort))" at line 1851 of file VBoxManageModifyVM.cpp

**Comment by briancain** [comment] 2018-05-16 20:18
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by chrisroberts** [comment] 2018-06-26 22:30
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2018-06-26 22:30 UTC
Labels: waiting-reply
