### ISSUE TITLE
Windows 10: Unable to upgrade from 2.2.0 to 2.2.1

### ISSUE THREAD

**Issue by MrFlutters** [hashicorp/vagrant#10427] opened 2018-11-17 18:54 UTC
### Vagrant version
Current version: 2.2.0
Updating to 2.2.1

### Host operating system
Windows 10 Pro
Version: 1809
Build 17763.134

### Expected behavior
Updated to Vagrant 2.2.1

### Actual behavior
Installer errors, "The feature you are trying to use is on a network resource that is unavalable".

Pressing ok prompts saying that the vagrant_2.1.5_x86_64.msi cannot be found.
Pressing cancel opens a prompt saying "The older version of Vagrant cannot be removed" and closes the installer

Vagrant 2.2.0 stays installed.
### Steps to reproduce
1. Download installer from https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_x86_64.msi
2. Running installer with vagrant 2.2.0 installed.
###
![image](https://user-images.githubusercontent.com/17028801/48664688-6844c280-ea9a-11e8-9a4b-e52266d0c538.png)

**Comment by chrisroberts** [comment] 2018-11-19 15:47
Hi there. It looks like this may be due to Vagrant having been installed to a non-standard location. If you are unable to proceed past this point during the upgrade you can uninstall Vagrant from the control panel, and then run the installer again.

**Comment by MrFlutters** [comment] 2018-11-19 16:05
Hi, Vagrant was installed to the default location on C, only my downloads, desktop, documents etc are stored on another drive.

**Comment by MrFlutters** [comment] 2018-11-19 16:10
I have also never had v2.1.5 on this machine, if that helps.

**Comment by briancain** [comment] 2018-12-14 22:44
Hi there @MrFlutters - I was able to install a new version of Vagrant over the 2.2.0 package when it was installed to the default location. If this still isn't working, you can always uninstall your old version of Vagrant prior to installing a new package. Since there hasn't been a response in a while and I could not reproduce the issue, I'm going to go ahead and close this one. If you have more troubles please feel free to mail the Vagrant up mailing list, thanks!

![screenshot from 2018-12-14 14-42-15](https://user-images.githubusercontent.com/810277/50033695-7ceb7c00-ffae-11e8-997b-56018af38971.png)

**Closed by briancain** 2018-12-14 22:44 UTC
Labels: host/windows, installer, waiting-reply
