### ISSUE TITLE
Vagrant creating duplicate entries in /etc/exports

### ISSUE THREAD

**Issue by brianV** [hashicorp/vagrant#11418] opened 2020-02-26 19:40 UTC
Vagrant is creating duplicate entries in `/etc/exports` when I try to bring up a project on my localhost.

````
# VAGRANT-BEGIN: 1000 b942511b-1c04-4c66-91e4-83a76daa4d31
"/home/brian/Workspace/client_project" 10.20.1.2(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3632416851)
"/home/brian/Workspace/client_project" 10.20.1.2(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3632416851)
# VAGRANT-END: 1000 b942511b-1c04-4c66-91e4-83a76daa4d31
````
As a result, `vagrant up` errors out with:

````
==> client_project: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 10.20.1.1:/home/brian/Workspace/client_project /var/www/client_project.local

Stdout from the command:

Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
````

I've tried removing one of the `/etc/exports` entries, then performing `vagrant up --provision`, however, the NFS mounts aren't present on the resulting box. 

I've also tried doing a `vagrant halt`, removing one up the entries, then a `vagrant up`, but in this scenario, Vagrant recreates the duplicate entries, after which presents the above error when it attempts to create the NFS mounts again.

### Vagrant version
2.2.6

### Host operating system
Linux Mint 19.1

### Guest operating system
Ubuntu 16.04
https://app.vagrantup.com/palantir/boxes/drupalbox/versions/1.4.0

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.1.0"

%w{ vagrant-hostmanager vagrant-auto_network }.each do |plugin|
    unless Vagrant.has_plugin?(plugin)
        raise "#{plugin} plugin is not installed. Please install with: vagrant plugin install #{plugin}"
    end
end

# tunables
project     = 'clientsite'
hostname    = "#{project}.local"
extra_hostnames = []

ansible_solr_enabled = true
ansible_https_enabled = true
ansible_project_web_root = "docroot"
ansible_timezone = "America/Chicago"
ansible_system_packages = []
ansible_custom_playbook = ""
# end tunables

Vagrant.configure(2) do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.define "#{project}" do |box|

        box.vm.box = "palantir/drupalbox"
        box.vm.box_version = ">= 1.2.0, < 2.0"

        box.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end

        box.vm.hostname = "#{hostname}"
        box.vm.network :private_network, :auto_network => true

        box.hostmanager.aliases = extra_hostnames

        box.vm.synced_folder ".", "/vagrant", :disabled => true
        box.vm.synced_folder ".", "/var/www/#{hostname}", :nfs => true

        box.ssh.forward_agent = true
    end

    config.vm.provision "the-vagrant", type: "ansible" do |ansible|
        ansible.playbook = "vendor/palantirnet/the-vagrant/conf/vagrant/provisioning/drupal8-skeleton.yml"

        ansible.groups = {
            "all:children" => ["#{project}"]
        }

        ansible.extra_vars = {
            "project" => project,
            "hostname" => hostname,
            "extra_hostnames" => extra_hostnames,
            "solr_enabled" => ansible_solr_enabled,
            "https_enabled" => ansible_https_enabled,
            "project_web_root" => ansible_project_web_root,
            "timezone" => ansible_timezone,
            "system_packages" => ansible_system_packages,
            "php_ini_memory_limit" => "512M",
        }
    end

    if (defined?(ansible_custom_playbook) && !ansible_custom_playbook.empty?)
        config.vm.provision "clientsite-provision", type: "ansible" do |ansible|
            ansible.playbook = ansible_custom_playbook
        end
    end

    config.trigger.before [:up, :reload] do |trigger|
        trigger.name = "Composer Install"
        trigger.run = {
            inline: "composer install --ignore-platform-reqs"
        }
    end

end
```

### Debug output

https://gist.github.com/brianV/983ec5198cb0d3e3033417561f032184

### Expected behavior
Environment should come up.

### Steps to reproduce
Unfortunately, not able to give reproduction steps without access to a codebase.

**Comment by briancain** [comment] 2020-03-03 21:35
Hey there @brianV - Do you get duplicate entries if you remove all third party plugins and just run a simple Vagrantfile like this inside a different folder? Or if you try with a different box like `hashicorp/bionic64`? Also please share the result of that in a debug log, thanks!

```ruby
Vagrant.configure(2) do |config|
  config.vm.define "test" do |box|
        box.vm.box = "palantir/drupalbox"
        box.vm.box_version = ">= 1.2.0, < 2.0"

        box.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end

        box.vm.synced_folder ".", "/var/www/test-folder", :nfs => true
    end
end
```

**Comment by brianV** [comment] 2020-03-03 22:02
@briancain:

Thanks. I get the same issue with the `palantir/drupalbox` box as per the example you pasted, as well as with the `hashicorp/bionic64` box, with a slightly modified Vagrantfile to remove `box.vm.box_version` and add `config.vm.network:

````
Vagrant.configure(2) do |config|
  config.vm.define "test" do |box|
        box.vm.box = "hashicorp/bionic64"

        box.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end

        config.vm.network "private_network", type: "dhcp"

        box.vm.synced_folder ".", "/var/www/test-folder", :nfs => true
    end
end
````

Here's a gist with the debug log using the `hasicorp/bionic64` box: https://gist.github.com/brianV/eda6f99d691ef2fc5418f85bb19f53f2

**Comment by briancain** [comment] 2020-03-03 23:14
@brianV Hey, thanks for checking with that. Can you confirm that nfs-server is running on your host prior to running Vagrant up too? And either way, perhaps try reloading the NFS service and try Vagrant again? :pray:

**Comment by brianV** [comment] 2020-03-04 02:59
@briancain So, I want to take back my previous comment, because I hadn't removed an earlier the original entries from `/etc/exports` that had the duplicated entries from my original Vagrantfile. Once I removed the duplicate entries and tested your sample `Vagrantfile`, it worked.

In https://github.com/hashicorp/vagrant/issues/4666, it seems to be tied to having the same folder synced into two places, but that specific issue was supposedly fixed in Sept. 2017.

**Comment by briancain** [comment] 2020-03-05 22:24
@brianV Yes...that behavior should be fixed. Is that what you are seeing now? I thought the original report was for a single Vagrantfile.

**Comment by brianV** [comment] 2020-03-06 15:39
@briancain My report is for a single Vagrant file - it appears that the mechanism is different from #4666, but the end result is the same: Duplicate lined in /etc/exports.

I was able to re-add to the test case Vagrantfile until I triggered the duplicate /etc/exports entries:

```
 Vagrant.configure(2) do |config|
    # tunables
    project     = 'clientsite'
    hostname    = "#{project}.local"
    extra_hostnames = []

  config.vm.define "test" do |box|
        box.vm.box = "palantir/drupalbox"
        box.vm.box_version = ">= 1.2.0, < 2.0"

        box.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end

        box.vm.hostname = "#{hostname}"
        box.vm.network :private_network, :auto_network => true

        box.hostmanager.aliases = extra_hostnames
        box.vm.synced_folder ".", "/vagrant", :disabled => true
        box.vm.synced_folder ".", "/var/www/#{hostname}", :nfs => true
    end
end
```

The last change was to add the `box.vm.hostname`, `box.vm.network` and `box.hostmanager.aliases` lines.

However, by the same token, the duplicate lines aren't causing the NFS failure in this use case. In fact, the original Vagrantfile and project where this was happening are no longer triggering any NFS issues like they were the other day.

At this point, my specific project is back operational, despite creating duplicate `/etc/exports` lines. If the duplicate lines are not an issue, I guess I can chalk this up to some unknown condition on my machine over the past few days and close the issue.

**Comment by briancain** [comment] 2020-05-20 22:26
Hey there! Sorry that I did not get back to you sooner. I still am unable to reproduce this issue with a handful of boxes. I'm going to go ahead and close this issue for now. However if you're still experiencing this issue with the latest version of Vagrant, please feel free to open a new issue and reference this one! Thanks.

**Closed by briancain** 2020-05-20 22:26 UTC
Labels: waiting-reply
