### ISSUE TITLE
vagrant failed to initialize early

### ISSUE THREAD

**Issue by jberas** [hashicorp/vagrant#12794] opened 2022-06-19 04:17 UTC
Running Ubuntu 20.  Will not work passing a VagrentFile either.  Previously was able to initialize several hashicorp/ubuntu boxes. 

```
➜  virtualbox --help   
Oracle VM VirtualBox VM Selector v6.1.32_Ubuntu

➜  vagrant -v            
Vagrant 2.2.19

➜  vagrant ruby -v               
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

➜  vagrant vagrant init hashicorp/bionic64
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/config/loader.rb
Line number: 0
Message: private method `load' called for nil:NilClass

```

**Comment by jmsbooth** [comment] 2022-07-11 11:02
Having the same issue. Reinstalled plugins, reinstalled Vagrant. Tried with fresh install, same issue.

"vagrant init" works fine. Adding a box worked fine. Running init after adding ubuntu/jammy64 caused the error and any init after that causes and error. Deleting the .vagrant & Vagrantfile and re-initializing works, but still the same issue when running "vagrant up".

**Comment by chrisroberts** [comment] 2022-07-12 16:25
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2022-08-29 18:29
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2022-08-29 18:29 UTC
Labels: waiting-reply
