### ISSUE TITLE
ansible_local cannot be installed on ubuntu focal64/groovy64

### ISSUE THREAD

**Issue by mhitza** [hashicorp/vagrant#11798] opened 2020-07-31 08:21 UTC
Vagrant version: 2.2.9

Guest operating system: ubuntu/focal64

Trying to provision with ansible_local fails as there are no ansible packages for the focal/groovy releases within the ansible PPA located http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/

As a workaround, I have a separate provisioning step that installs ansible via `sudo apt install ansible`

**Comment by gildegoma** [comment] 2020-07-31 13:50
@mhitza thank you for reporting this issue. We must check with Ansible project why these versions are not supported in the official PPA. 

For the moment, you can use the [`:pip` installation mode](https://www.vagrantup.com/docs/provisioning/ansible_local#install_mode) as well (if you don't want to stick to ubuntu's ansible packages).

**Comment by albers** [comment] 2020-11-10 21:02
Do you have any updates on this issue?

**Comment by soapy1** [comment] 2021-03-12 20:46
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by soapy1** 2021-03-12 20:46 UTC
Labels: guest/ubuntu, provisioner/ansible_local, upstream

**Comment by albers** [comment] 2021-03-18 19:39
I can confirm that the ansible_local provisioner now works with Ubuntu 20.04 (focal).
The ppa now supports focal: http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/focal/ but still not groovy (which is a minor problem because groovy is not an LTS version).
