### ISSUE TITLE
Haiku guest looks up SSH keys in the wrong folder

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9553] opened 2018-03-10 22:37 UTC
Haiku applications have somewhat of a convention for placing configuration files in `$(finddir B_USER_DIRECTORY)/config/settings)`, though sshd continues to look for SSH keys by default in `$(finddir B_USER_DIRECTORY)/.ssh`, rather than `$(findstr B_USER_DIRECTORY)/config/settings/ssh`). In short, the current Haiku guest plugin implementation code for managing SSH keys interacts with a different SSH directory than sshd actually looks for keys. This causes `vagrant up` to break.

### Vagrant version

Vagrant 2.0.2

### Host operating system

macOS 10.13 High Sierra

### Guest operating system

Haiku alpha4

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/haiku"

  config.ssh.sudo_command = "su user -c '%c'"
end
```

Packer source:

https://github.com/mcandre/packer-templates/tree/d05dd87442e316c771217bfe57c90ec8cafcd00b/haiku

### Steps to reproduce

1. `vagrant up`

As a workaround, I'm storing the actual `authorized_keys` file in `$(findstr B_USER_HOME_DIRECTORY)/.ssh`, and creating a soft link for `$(findstr B_USER_HOME_DIRECTORY/config/settings/ssh` that points to `$(findstr B_USER_HOME_DIRECTORY)/.ssh`.

You might be wondering why I'm using `$(findstr B_USER_HOME_DIRECTORY)` rather than `$HOME` or `~`. It's because Haiku (version alpha4) doesn't update `$HOME` nor `~` correctly. C'est le vie.

**Comment by kallisti5** [comment] 2020-07-03 21:24
this one can likely be closed.   Vagrant puts the ssh keys into the correct folder and picks up on them.  The latest haiku-os images at vagrant feature the insecure vagrant public key which gets swapped successfully.

**Comment by jbonhag** [comment] 2020-07-06 18:35
Thanks for jumping in, @kallisti5 -- I confirmed that Vagrant performed the insecure key replacement in `./config/settings/ssh/authorized_keys` in the nightly release I was testing (v54142).

I'm going to close this issue because it appears to be working correctly.

**Closed by jbonhag** 2020-07-06 18:35 UTC
Labels: enhancement, guest/haiku, help-wanted, task-small
