### ISSUE TITLE
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

### ISSUE THREAD

**Issue by fendo8888** [hashicorp/vagrant#9843] opened 2018-05-16 13:18 UTC
a78.780: Log file opened: 5.2.12r122591 g_hStartupLog=0000000000000194 g_uNtVerCombined=0xa042ee00
a78.780: \SystemRoot\System32\ntdll.dll:
a78.780:     CreationTime:    2018-04-11T23:34:22.383017500Z
a78.780:     LastWriteTime:   2018-04-11T23:34:22.383017500Z
a78.780:     ChangeTime:      2018-05-16T00:20:21.342640800Z
a78.780:     FileAttributes:  0x20
a78.780:     Size:            0x1db2c0
a78.780:     NT Headers:      0xe8
a78.780:     Timestamp:       0x207580e2
a78.780:     Machine:         0x8664 - amd64
a78.780:     Timestamp:       0x207580e2
a78.780:     Image Version:   10.0
a78.780:     SizeOfImage:     0x1e1000 (1970176)
a78.780:     Resource Dir:    0x174000 LB 0x6b338
a78.780:     [Version info resource found at 0xd8! (ID/Name: 0x1; SubID/SubName: 0x409)]
a78.780:     [Raw version resource data: 0x1740f0 LB 0x380, codepage 0x0 (reserved 0x0)]
a78.780:     ProductName:     Microsoft® Windows® Operating System
a78.780:     ProductVersion:  10.0.17134.1
a78.780:     FileVersion:     10.0.17134.1 (WinBuild.160101.0800)
a78.780:     FileDescription: NT Layer DLL
a78.780: \SystemRoot\System32\kernel32.dll:
a78.780:     CreationTime:    2018-04-11T23:34:40.510607900Z
a78.780:     LastWriteTime:   2018-04-11T23:34:40.510607900Z
a78.780:     ChangeTime:      2018-05-16T00:20:21.092674900Z
a78.780:     FileAttributes:  0x20
a78.780:     Size:            0xafef8
a78.780:     NT Headers:      0xe8
a78.780:     Timestamp:       0x5f488a51
a78.780:     Machine:         0x8664 - amd64
a78.780:     Timestamp:       0x5f488a51
a78.780:     Image Version:   10.0
a78.780:     SizeOfImage:     0xb2000 (729088)
a78.780:     Resource Dir:    0xb0000 LB 0x520
a78.780:     [Version info resource found at 0x90! (ID/Name: 0x1; SubID/SubName: 0x409)]
a78.780:     [Raw version resource data: 0xb00b0 LB 0x3a4, codepage 0x0 (reserved 0x0)]
a78.780:     ProductName:     Microsoft® Windows® Operating System
a78.780:     ProductVersion:  10.0.17134.1
a78.780:     FileVersion:     10.0.17134.1 (WinBuild.160101.0800)
a78.780:     FileDescription: Windows NT BASE API Client DLL
a78.780: \SystemRoot\System32\KernelBase.dll:
a78.780:     CreationTime:    2018-04-11T23:34:20.976649600Z
a78.780:     LastWriteTime:   2018-04-11T23:34:20.976649600Z
a78.780:     ChangeTime:      2018-05-16T00:20:21.373853400Z
a78.780:     FileAttributes:  0x20
a78.780:     Size:            0x2731d0
a78.780:     NT Headers:      0xf8
a78.780:     Timestamp:       0x701ca188
a78.780:     Machine:         0x8664 - amd64
a78.780:     Timestamp:       0x701ca188
a78.780:     Image Version:   10.0
a78.780:     SizeOfImage:     0x273000 (2568192)
a78.780:     Resource Dir:    0x251000 LB 0x548
a78.780:     [Version info resource found at 0x90! (ID/Name: 0x1; SubID/SubName: 0x409)]
a78.780:     [Raw version resource data: 0x2510b0 LB 0x3bc, codepage 0x0 (reserved 0x0)]
a78.780:     ProductName:     Microsoft® Windows® Operating System
a78.780:     ProductVersion:  10.0.17134.1
a78.780:     FileVersion:     10.0.17134.1 (WinBuild.160101.0800)
a78.780:     FileDescription: Windows NT BASE API Client DLL
a78.780: \SystemRoot\System32\apisetschema.dll:
a78.780:     CreationTime:    2018-04-11T23:34:44.042150700Z
a78.780:     LastWriteTime:   2018-04-11T23:34:44.042150700Z
a78.780:     ChangeTime:      2018-05-16T00:06:08.545079700Z
a78.780:     FileAttributes:  0x20
a78.780:     Size:            0x1bd98
a78.780:     NT Headers:      0xd0
a78.780:     Timestamp:       0xd02ff418
a78.780:     Machine:         0x8664 - amd64
a78.780:     Timestamp:       0xd02ff418
a78.780:     Image Version:   10.0
a78.780:     SizeOfImage:     0x1c000 (114688)
a78.780:     Resource Dir:    0x1b000 LB 0x408
a78.780:     [Version info resource found at 0x48! (ID/Name: 0x1; SubID/SubName: 0x409)]
a78.780:     [Raw version resource data: 0x1b060 LB 0x3a8, codepage 0x0 (reserved 0x0)]
a78.780:     ProductName:     Microsoft® Windows® Operating System
a78.780:     ProductVersion:  10.0.17134.1
a78.780:     FileVersion:     10.0.17134.1 (WinBuild.160101.0800)
a78.780:     FileDescription: ApiSet Schema DLL
a78.780: NtOpenDirectoryObject failed on \Driver: 0xc0000022
a78.780: supR3HardenedWinFindAdversaries: 0x0
a78.780: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox'
a78.780: Calling main()
a78.780: SUPR3HardenedMain: pszProgName=VBoxHeadless fFlags=0x0
a78.780: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox'
a78.780: SUPR3HardenedMain: Respawn #1
a78.780: System32:  \Device\HarddiskVolume4\Windows\System32
a78.780: WinSxS:    \Device\HarddiskVolume4\Windows\WinSxS
a78.780: KnownDllPath: C:\WINDOWS\System32
a78.780: '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
a78.780: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe)
a78.780: supR3HardNtEnableThreadCreation:
a78.780: supR3HardNtDisableThreadCreation: pvLdrInitThunk=00007ffcdff230e0 pvNtTerminateThread=00007ffcdff4a9e0
a78.780: supR3HardenedWinDoReSpawn(1): New child 28d4.13b0 [kernel32].
a78.780: supR3HardNtChildGatherData: PebBaseAddress=000000000114a000 cbPeb=0x388
a78.780: supR3HardNtPuChFindNtdll: uNtDllParentAddr=00007ffcdfeb0000 uNtDllChildAddr=00007ffcdfeb0000
a78.780: supR3HardenedWinSetupChildInit: uLdrInitThunk=00007ffcdff230e0
a78.780: supR3HardenedWinSetupChildInit: Start child.
a78.780: supR3HardNtChildWaitFor: Found expected request 0 (PurifyChildAndCloseHandles) after 1 ms.
a78.780: supR3HardNtChildPurify: Startup delay kludge #1/0: 259 ms, 29 sleeps
a78.780: supHardNtVpScanVirtualMemory: enmKind=CHILD_PURIFICATION
a78.780:  *0000000000000000-0000000000f0ffff 0x0001/0x0000 0x0000000
a78.780:  *0000000000f10000-0000000000f2ffff 0x0004/0x0004 0x0020000
a78.780:  *0000000000f30000-0000000000f48fff 0x0002/0x0002 0x0040000
a78.780:   0000000000f49000-0000000000f4ffff 0x0001/0x0000 0x0000000
a78.780:  *0000000000f50000-0000000000f53fff 0x0002/0x0002 0x0040000
a78.780:   0000000000f54000-0000000000f5ffff 0x0001/0x0000 0x0000000
a78.780:  *0000000000f60000-0000000000f60fff 0x0004/0x0004 0x0020000
a78.780:   0000000000f61000-0000000000ffffff 0x0001/0x0000 0x0000000
a78.780:  *0000000001000000-0000000001149fff 0x0000/0x0004 0x0020000
a78.780:   000000000114a000-000000000114cfff 0x0004/0x0004 0x0020000
a78.780:   000000000114d000-00000000011fffff 0x0000/0x0004 0x0020000
a78.780:  *0000000001200000-00000000012fafff 0x0000/0x0004 0x0020000
a78.780:   00000000012fb000-00000000012fdfff 0x0104/0x0004 0x0020000
a78.780:   00000000012fe000-00000000012fffff 0x0004/0x0004 0x0020000
a78.780:   0000000001300000-000000007ffdffff 0x0001/0x0000 0x0000000
a78.780:  *000000007ffe0000-000000007ffe0fff 0x0002/0x0002 0x0020000
a78.780:   000000007ffe1000-00007ff576b4ffff 0x0001/0x0000 0x0000000
a78.780:  *00007ff576b50000-00007ff576b82fff 0x0002/0x0002 0x0040000
a78.780:   00007ff576b83000-00007ff66a98ffff 0x0001/0x0000 0x0000000
a78.780:  *00007ff66a990000-00007ff66a990fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66a991000-00007ff66aa01fff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa02000-00007ff66aa02fff 0x0080/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa03000-00007ff66aa48fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa49000-00007ff66aa49fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa4a000-00007ff66aa4afff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa4b000-00007ff66aa4ffff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa50000-00007ff66aa50fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa51000-00007ff66aa51fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa52000-00007ff66aa55fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa56000-00007ff66aa9dfff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
a78.780:   00007ff66aa9e000-00007ffcdfeaffff 0x0001/0x0000 0x0000000
a78.780:  *00007ffcdfeb0000-00007ffcdfeb0fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffcdfeb1000-00007ffcdffbffff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffcdffc0000-00007ffce0005fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffce0006000-00007ffce0010fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffce0011000-00007ffce001efff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffce001f000-00007ffce001ffff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffce0020000-00007ffce0022fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffce0023000-00007ffce0090fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume4\Windows\System32\ntdll.dll
a78.780:   00007ffce0091000-00007ffffffeffff 0x0001/0x0000 0x0000000
a78.780: VBoxHeadless.exe: timestamp 0x5af2c2c3 (rc=VINF_SUCCESS)
a78.780: '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
a78.780: '\Device\HarddiskVolume4\Windows\System32\ntdll.dll' has no imports
a78.780: supR3HardNtChildPurify: Done after 315 ms and 0 fixes (loop #0).
a78.780: supR3HardNtEnableThreadCreation:
28d4.13b0: Log file opened: 5.2.12r122591 g_hStartupLog=0000000000000008 g_uNtVerCombined=0xa042ee00
28d4.13b0: supR3HardenedVmProcessInit: uNtDllAddr=00007ffcdfeb0000 g_uNtVerCombined=0xa042ee00
28d4.13b0: ntdll.dll: timestamp 0x207580e2 (rc=VINF_SUCCESS)
28d4.13b0: New simple heap: #1 0000000001510000 LB 0x400000 (for 1970176 allocation)
28d4.13b0: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox'
28d4.13b0: System32:  \Device\HarddiskVolume4\Windows\System32
28d4.13b0: WinSxS:    \Device\HarddiskVolume4\Windows\WinSxS
28d4.13b0: KnownDllPath: C:\WINDOWS\System32
28d4.13b0: supR3HardenedVmProcessInit: Opening vboxdrv stub...
28d4.13b0: supR3HardenedWinReadErrorInfoDevice: 'Found executable memory at 0000000000010000 (0000000000010000 LB 0x3000): type=0x20000 prot=0x40 state=0x1000 aprot=0x10000 abase=0000000000000040'
28d4.13b0: Error -5619 in supR3HardenedWinReSpawn! (enmWhat=3)
28d4.13b0: NtCreateFile(\Device\VBoxDrvStub) failed: Unknown Status -5619 (0xffffea0d) (rcNt=0xe986ea0d)
VBoxDrvStub error: Found executable memory at 0000000000010000 (0000000000010000 LB 0x3000): type=0x20000 prot=0x40 state=0x1000 aprot=0x10000 abase=0000000000000040
a78.780: supR3HardenedWinCheckChild: enmRequest=2 rc=-5619 enmWhat=3 supR3HardenedWinReSpawn: NtCreateFile(\Device\VBoxDrvStub) failed: Unknown Status -5619 (0xffffea0d) (rcNt=0xe986ea0d)
VBoxDrvStub error: Found executable memory at 0000000000010000 (0000000000010000 LB 0x3000): type=0x20000 prot=0x40 state=0x1000 aprot=0x10000 abase=0000000000000040
a78.780: Error -5619 in supR3HardenedWinReSpawn! (enmWhat=3)
a78.780: NtCreateFile(\Device\VBoxDrvStub) failed: Unknown Status -5619 (0xffffea0d) (rcNt=0xe986ea0d)
VBoxDrvStub error: Found executable memory at 0000000000010000 (0000000000010000 LB 0x3000): type=0x20000 prot=0x40 state=0x1000 aprot=0x10000 abase=0000000000000040

**Comment by briancain** [comment] 2018-05-16 20:20
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by chrisroberts** [comment] 2018-06-26 22:30
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2018-06-26 22:30 UTC
Labels: waiting-reply
