### ISSUE TITLE
"File Provisioner" always run even if run: "never" option is specified

### ISSUE THREAD

**Issue by eliu** [hashicorp/vagrant#9271] opened 2017-12-14 10:56 UTC
### Vagrant version

`Vagrant 2.0.1`

### Host operating system

`macOS High Sierra (10.13.2)`

### Guest operating system

CentOS 7 (1710.01)

### Vagrantfile
```ruby
NETWORK_BASE = '192.168.101'
INTEGRATION_START_SEGMENT = 101
Vagrant.configure("2") do |config|
  config.vm.box = "centos-7-1710.01"
  config.vm.provision "shell", inline: <<-SHELL
    sudo bash -c 'echo "export TZ=Asia/Shanghai" > /etc/profile.d/tz.sh'
    # sudo yum -y update && sudo yum -y upgrade
    # sudo yum -y install docker
    mkdir -p /home/vagrant/.ssh
  SHELL

  config.vm.define "master", primary: true do |node|
    node.vm.network "private_network", ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT}"
    node.vm.hostname = "master.example.com"
    node.hostmanager.aliases = %w(etcd.example.com nfs.example.com)

  node.vm.provision "copy-key-master", type: "file", run: "never", source: ".vagrant/machines/master/virtualbox/private_key", destination: "/home/vagrant/.ssh/master.key"
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior

The provisioner with `file` type and optioned with `run: never` should never run unless the `vagrant provision --provision-with name` is called.

### Actual behavior

The provisioner with `file` type and optioned with `run: never` ALWAYS run.

### Steps to reproduce
1. cd /path/to/vagrant/workdir
2. vagrant up

**Comment by briancain** [comment] 2017-12-14 17:54
Hi @eliu - I could not reproduce this with this Vagrantfile. Do you have a debug log that you could share?

```
brian@localghost:vagrant-sandbox % be vagrant up bork                                                   ±[●●][master]
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'bork' up with 'virtualbox' provider...
==> bork: Importing base box 'bento/ubuntu-16.04'...
==> bork: Matching MAC address for NAT networking...
==> bork: Checking if box 'bento/ubuntu-16.04' is up to date...
==> bork: Setting the name of the VM: vagrant-sandbox_bork_1513272537199_2951
==> bork: Clearing any previously set network interfaces...
==> bork: Preparing network interfaces based on configuration...
    bork: Adapter 1: nat
==> bork: Forwarding ports...
    bork: 22 (guest) => 2222 (host) (adapter 1)
==> bork: Booting VM...
==> bork: Waiting for machine to boot. This may take a few minutes...
    bork: SSH address: 127.0.0.1:2222
    bork: SSH username: vagrant
    bork: SSH auth method: private key
    bork: Warning: Remote connection disconnect. Retrying...
    bork: Warning: Connection reset. Retrying...
    bork: Warning: Remote connection disconnect. Retrying...
    bork:
    bork: Vagrant insecure key detected. Vagrant will automatically replace
    bork: this with a newly generated keypair for better security.
    bork:
    bork: Inserting generated public key within guest...
    bork: Removing insecure key from the guest if it's present...
    bork: Key inserted! Disconnecting and reconnecting using new SSH key...
==> bork: Machine booted and ready!
==> bork: Checking for guest additions in VM...
==> bork: Mounting shared folders...
    bork: /vagrant => /Users/brian/code/vagrant-sandbox
```

```ruby
  config.vm.define "bork" do |b|
    b.vm.box = "bento/ubuntu-16.04"
    b.vm.provider :virtualbox
    b.vm.provision "hello", type: "file", run: "never", source: "box.json", destination: "/home/vagrant/box.json"
  end
```

**Comment by eliu** [comment] 2017-12-14 18:09
I can still reproduce it ... when that file currently unavailable
![image](https://user-images.githubusercontent.com/831707/34007455-c34ece5e-e13c-11e7-9478-9d0c028bd0e2.png)

**Comment by briancain** [comment] 2017-12-14 18:16
If the file exists, does it still produce the behavior you described? And if so, please provide a gist link to the debug log. Thanks!

**Comment by eliu** [comment] 2017-12-14 18:21
i confirm it works normally when the file exists.

**Comment by eliu** [comment] 2017-12-14 18:24
i found that point just now...about the file existance. anyways, this behavior should not happen since it was marked as never run. maybe file will be available after vagrant is up

**Comment by briancain** [comment] 2017-12-14 18:33
What you described is expected behavior for the file provisioner. A file must exist on disk for it to be a valid config option. If you'd like it to be apart of the config conditionally based on if that file exists on your host machine, you'll want to use an if statement:

```ruby
# pseudocode...
if File.exist?("/path/to/file")
  node.vm.provision "copy-key-master" .... etc ....
end
```

I'm going to go ahed and close this since you said it works normally when the file exists. Thanks!

**Closed by briancain** 2017-12-14 18:33 UTC
Labels: waiting-reply

**Comment by eliu** [comment] 2017-12-14 18:55
ok, thanks for help.
