### ISSUE TITLE
Vagrant setup issue

### ISSUE THREAD

**Issue by nupursingh11** [hashicorp/vagrant#9474] opened 2018-02-16 13:39 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.0

### Host operating system
windows 8.1

### Guest operating system
ubuntu

### Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :
file_root = File.dirname(File.expand_path(__FILE__)) + "/tmp"
file_to_disk = File.join(file_root, "large_disk.vdi")
swap_disk = File.join(file_root, "swap_disk.vdi")
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  # set our global virtualbox items
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
  end

  # config main vm, this is autostarted
  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/trusty64"
  end

  # config additional vm 1, this is NOT autostarted
  config.vm.define "addl1" do |addl1|
    addl1.vm.box = "ubuntu/trusty64"
  end

  # config additional vm 2, this is NOT autostarted
  config.vm.define "addl2" do |addl2|
    addl2.vm.box = "ubuntu/trusty64"
  end

  # config vm for local eXaLink deployment. this is NOT autostarted
  config.vm.define "exalink" do |exalink|
    exalink.vm.box = "ubuntu/trusty64"
    exalink.vm.network "private_network", ip: "192.168.233.3"
    # provision vm via ansible playbook.
    # replace playbook with your ansible playbook.
    # https://www.vagrantup.com/docs/provisioning/ansible.html
    # web.playbook = "playbook.yml"
    # peristant docker store
    # vagrant plugin install vagrant-persistent-storage
    if Vagrant.has_plugin?("vagrant-persistent-storage")
        exalink.persistent_storage.enabled = true
        exalink.persistent_storage.location = file_to_disk
        exalink.persistent_storage.size = 75000
        exalink.persistent_storage.mountname = 'docker'
        exalink.persistent_storage.filesystem = 'ext4'
        exalink.persistent_storage.mountpoint = '/docker_images'
    end
    exalink.vm.provider :virtualbox do |vb|
      vb.memory = 8096
      if !File.exist?(swap_disk)
        vb.customize ['createhd', '--filename', swap_disk, '--size', 12 * 1024]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', swap_disk]
    end
    exalink.vm.provision "shell", path: "scripts/drives.sh", privileged: false
    exalink.vm.provision "shell", path: "scripts/virtualenv.sh", privileged: false
  end

  #vagrant plugin install vagrant-cachier
  if Vagrant.has_plugin?("vagrant-cachier")
      # Configure cached packages to be shared between instances of the same base box.
      # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
      config.cache.scope = :box

      # OPTIONAL: If you are using VirtualBox, you might want to use that to enable
      # NFS for shared folders. This is also very useful for vagrant-libvirt if you
      # want bi-directional sync
      config.cache.synced_folder_opts = {
        type: :nfs,
        # The nolock option can be useful for an NFSv3 client that wants to avoid the
        # NLM sideband protocol. Without this option, apt-get might hang if it tries
        # to lock files needed for /var/cache/* operations. All of this can be avoided
        # by using NFSv4 everywhere. Please note that the tcp option is not the default.
        mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      }
      # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end

  # set our network type do public, pulls a 10.x.x.x address
  config.vm.network "private_network", type: "dhcp"

  # map our users document directory
  # uncomment if using PyCharm
  #config.vm.synced_folder "~/PyCharmProjects/", "/code", create: false
  config.vm.synced_folder "E:/code/", "/code", create: false

  # copy over the td-agent.conf configuration
  config.vm.provision "file", source: "td-agent.conf", destination: "/tmp/td-agent.conf"

  # inline shell provisioning
  $shell = <<-SHELL
    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /tmp/docker.list
    sudo cp /tmp/docker.list /etc/apt/sources.list.d/docker.list
    rm /tmp/docker.list
    sudo apt-get update
    sudo apt-get install -y --force-yes htop lsof iotop zip unzip gcc libev4 emacs24 python-pip python3-pip git build-essential libssl-dev libffi-dev python-dev python-psycopg2 docker-engine=1.12.3-0~trusty zsh
    sudo apt-get autoremove
    sudo sed -i -e 's/#DOCKER_OPTS=\"--dns 8.8.8.8 --dns 8.8.4.4\"/DOCKER_OPTS=\"--insecure-registry 10.12.228.6\"/g' /etc/default/docker
    sudo sh -c "$(curl -fsSL https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh)"
    sudo rm -f install-ubuntu-trusty-td-agent2.sh
    sudo td-agent-gem install fluent-plugin-elasticsearch
    sudo td-agent-gem install fluent-plugin-kafka
    sudo td-agent-gem install fluent-plugin-forest
    sudo td-agent-gem install fluent-plugin-out-http

    sudo usermod -aG docker vagrant
    sudo service docker restart
    sudo sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    sudo chsh -s /bin/zsh vagrant
    sudo chown vagrant.vagrant -R ~/.oh-my-zsh
    sudo chown vagrant.vagrant ~/.zshrc
    sudo chown vagrant.vagrant /home/vagrant/
    sudo mv /tmp/td-agent.conf /etc/td-agent/td-agent.conf
    sudo service td-agent restart
    sudo sed -i -e 's/ZSH_THEME=\"robbyrussell\"/ZSH_THEME=\"steeef\"/' ~/.zshrc
    sudo pip install pyopenssl ndg-httpsclient pyasn1 docker-py==1.10.6
    sudo pip install --upgrade pip
    sudo pip3 install --upgrade pip
  SHELL

  # provision our vm
  config.vm.provision "shell", inline: $shell, privileged: false

  # autstart "dev", DO NOT autostart "addl1", "addl2 or web"
  config.vm.define "dev"
  config.vm.define "addl1", autostart: false
  config.vm.define "addl2", autostart: false
  config.vm.define "exalink", autostart: false

  # force vagrant reload after provisioning
  config.trigger.after :provision, :execute => "vagrant reload"
  config.trigger.before :destroy, :force => true do
    run_remote "docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)"
  end
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
Vagrant image created

### Actual behavior
Bringing machine 'exalink' up with 'virtualbox' provider...
==> exalink: Box 'ubuntu/trusty64' could not be found. Attempting to find and in
stall...
    exalink: Box Provider: virtualbox
    exalink: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error: The requested URL returned error: 404 Not Found

### References
NO
![vagrantissue](https://user-images.githubusercontent.com/36538547/36310509-437791b8-134e-11e8-8c25-200101f997fd.png)

- ...

**Comment by briancain** [comment] 2018-02-16 19:27
Duplicate of https://github.com/hashicorp/vagrant/issues/9442

**Comment by briancain** [comment] 2018-02-16 19:28
Please see the duplicate issue for more information @nupursingh11

**Closed by briancain** 2018-02-16 19:27 UTC
