### ISSUE TITLE
Upstream: Having a dir named `c` causes rubygems error

### ISSUE THREAD

**Issue by kou0179** [hashicorp/vagrant#10800] opened 2019-04-19 15:49 UTC
### Vagrant version
2.2.4

### Host operating system
Windows 10 Pro version 1809 build 17763.437

### Provider
VirtualBox 6.0.6

### Guest operating system
Cent OS 7
The box is [centos/7](https://app.vagrantup.com/centos/boxes/7)

### Vagrantfile

```Ruby

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network",ip: "192.168.10.1"
  config.vm.synced_folder ".", "/vagrant",type:"virtualbox"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
  end
end

```

### Debug output
[https://gist.github.com/kou0179/cca71862a3520c3e019ff73480efb0a5](https://gist.github.com/kou0179/cca71862a3520c3e019ff73480efb0a5)

`Error message given during initialization: Is a directory @ rb_sysopen - C`

### Behavior
`vagrant up`
`vagrant halt`
`vagrant plugin repair` ...etc

An error occurred with most vagrant commands.

### Cause & Steps to reproduce
**Because a directory named "C" exists in the same location as `Vagrantfile`.**

1.  `vagrant init`
2. Setup `Vagrantfile`
3. `mkdir c`
4. `vagrant up`

### P.S.
I am Japanese. So I am not good at English.
Thank you for reading this to the end.

**Comment by briancain** [comment] 2019-04-19 16:19
Hi @kou0179 - Have you tried running the vagrant command:

```ruby
vagrant plugin expunge --reinstall
```

What happens when you do? And what plugins have you installed?

Thanks!

**Comment by kou0179** [comment] 2019-04-19 16:28
Hello @briancain . Thank you for reply.

I tried it. However, I did not have any plugins from the beginning.

`vagrant plugin repair`
`vagrant plugin update`
Also, running them did not solve the problem.

Thank you for taking your time.

**Comment by briancain** [comment] 2019-04-19 16:41
Hello @kou0179 - I was able to reproduce the bug. Thanks for the report!

**Comment by briancain** [comment] 2019-04-19 17:00
Just a book keeping note: this looks like this issue might be a duplicate of https://github.com/hashicorp/vagrant/issues/9148

**Comment by kou0179** [comment] 2019-04-20 02:08
I'm sorry I couldn't find the issue.
Thank you for getting back to me so quickly and carefully considering my request.
You've done a great job. Thanks @briancain !

**Closed** 2019-05-08 16:12 UTC
Labels: bug, confirmed, core, host/windows
