### ISSUE TITLE
vagrant box outdated --global doesn't take into account provider

### ISSUE THREAD

**Issue by tas50** [hashicorp/vagrant#11245] opened 2019-12-10 06:41 UTC
### Vagrant version
Vagrant 2.2.6

### Host operating system
macOS 10.15

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
When running `vagrant box outdated --global` you should receive a list of outdated boxes when there is a newer version available for *your* provider *not* any provider.

### Actual behavior
If there is a newer version available for any provider the system will show as outdated even if you are running the latest version for your specific provider

### Steps to reproduce
1. Install bento/ubuntu-18.04 for virtualbox
2. Run: vagrant box outdated --global
3. ubuntu-18.04 will show as outdated as there is a newer version available for parallels/vmware

**Comment by jbonhag** [comment] 2019-12-10 15:01
Hi there, and thanks for opening an issue with Vagrant! This issue has been fixed in https://github.com/hashicorp/vagrant/pull/11192, which has been merged into master -- it should be out in the next release.

I'm going to close this issue as a duplicate of https://github.com/hashicorp/vagrant/issues/11163, but feel free to reopen it if you don't feel like the issue is fully resolved.

Cheers and have a great day!

**Closed by jbonhag** 2019-12-10 15:01 UTC
Labels: duplicate

**Comment by tas50** [comment] 2019-12-10 17:25
Nice. Thanks!
