### ISSUE TITLE
'vagrant suspend' error

### ISSUE THREAD

**Issue by acho-bacho** [hashicorp/vagrant#8231] opened 2017-01-26 16:42 UTC
When I do a "vagrant suspend" command that is in a bash script I get the following error:

> 17:37:10  INFO interface: error: There was an error while executing `VBoxManage`, a CLI used by Vagrant
17:37:10 for controlling VirtualBox. The command and stderr is shown below.
17:37:10 
17:37:10 Command: ["controlvm", "69bdb455-cd27-4117-931b-72def0e17ef4", "savestate"]
17:37:10 
17:37:10 Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...
17:37:10 Progress state: NS_ERROR_FAILURE
17:37:10 VBoxManage: error: Failed to save machine state
17:37:10 VBoxManage: error: Code NS_ERROR_FAILURE (0x80004005) - Operation failed (extended info not available)
17:37:10 VBoxManage: error: Context: "RTEXITCODE handleControlVM(HandlerArg*)" at line 276 of file VBoxManageControlVM.cpp
17:37:10 
17:37:10 There was an error while executing `VBoxManage`, a CLI used by Vagrant
17:37:10 for controlling VirtualBox. The command and stderr is shown below.
17:37:10 
17:37:10 Command: ["controlvm", "69bdb455-cd27-4117-931b-72def0e17ef4", "savestate"]
17:37:10 
17:37:10 Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...
17:37:10 Progress state: NS_ERROR_FAILURE
17:37:10 VBoxManage: error: Failed to save machine state
17:37:10 VBoxManage: error: Code NS_ERROR_FAILURE (0x80004005) - Operation failed (extended info not available)
17:37:10 VBoxManage: error: Context: "RTEXITCODE handleControlVM(HandlerArg*)" at line 276 of file VBoxManageControlVM.cpp
17:37:10  INFO interface: Machine: error-exit ["Vagrant::Errors::VBoxManageError", "There was an error while executing `VBoxManage`, a CLI used by Vagrant\nfor controlling VirtualBox. The command and stderr is shown below.\n\nCommand: [\"controlvm\", \"69bdb455-cd27-4117-931b-72def0e17ef4\", \"savestate\"]\n\nStderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...\nProgress state: NS_ERROR_FAILURE\nVBoxManage: error: Failed to save machine state\nVBoxManage: error: Code NS_ERROR_FAILURE (0x80004005) - Operation failed (extended info not available)\nVBoxManage: error: Context: \"RTEXITCODE handleControlVM(HandlerArg*)\" at line 276 of file VBoxManageControlVM.cpp\n"]

When the command is run from command line the issue is not observed.
### Vagrant version
Vagrant 1.9.1

### Host operating system
CentOS Linux release 7.2.1511 (Core)

### Guest operating system
Ubuntu 14.04.4 LTS

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'cloudfoundry/bosh-lite'

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_version = '9000.137.0' # ci:replace
    v.gui = false

    # To use a different IP address for the bosh-lite director, uncomment this line:
    # override.vm.network :private_network, ip: '192.168.59.4', id: :local
  end

  config.vm.provider :aws do |v, override|
    override.vm.box_version = '9000.137.0' # ci:replace
    # To turn off public IP echoing, uncomment this line:
    # override.vm.provision :shell, id: "public_ip", run: "always", inline: "/bin/true"

    # To turn off CF port forwarding, uncomment this line:
    # override.vm.provision :shell, id: "port_forwarding", run: "always", inline: "/bin/true"

    # Following minimal config is for Vagrant 1.7 since it loads this file before downloading the box.
    # (Must not fail due to missing ENV variables because this file is loaded for all providers)
    v.access_key_id = ENV['BOSH_AWS_ACCESS_KEY_ID'] || ''
    v.secret_access_key = ENV['BOSH_AWS_SECRET_ACCESS_KEY'] || ''
    v.ami = ''
  end

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box = 'cloudfoundry/no-support-for-bosh-lite-on-fusion'
    #we no longer build current boxes for vmware_fusion
    #ensure that this fails. otherwise the user gets an old box
  end

  config.vm.provider :vmware_workstation do |v, override|
    override.vm.box = 'cloudfoundry/no-support-for-bosh-lite-on-workstation'
    #we no longer build current boxes for vmware_workstation
    #ensure that this fails. otherwise the user gets an old box
  end
end
```

### Debug output
https://gist.github.com/acho-bacho/056ce446e78a91220e3a4013dc801a69

### Expected behavior
vagrant should be suspended

### Actual behavior
The error from the output is shown
In virtualbox I observe that the machine state is "saved" or "aborted"

### Steps to reproduce
1. create a bash script with 'vagrant up' and 'vagrant suspend' commands and run the script

**Comment by acho-bacho** [comment] 2017-01-30 16:06
Hello,

can I get some input on this issue? 

Thanks a lot!

**Comment by kikitux** [comment] 2017-01-31 22:54
can you try to reproduce using `hashicorp/precise64` and provide us with instructions to reproduce ?

in the meantime, can you share how are you calling this script?

its under a interactive shell session, or its by cron or some tool ie CI/CD ?

Try to set in your script before the vagrant commands:
```
VAGRANT_HOME=<path_to_home_user>/.vagrant.d
```

Thanks

**Comment by acho-bacho** [comment] 2017-02-02 08:56
@kikitux thanks a lot for the reply. 
The issue is not reproducible with `hashicorp/precise64`
I run the script in a interactive shell session.
Here's the script: [https://gist.github.com/acho-bacho/126f96bcfa95ffc65da679a47b73954e](url)

**Comment by chrisroberts** [comment] 2018-12-21 23:02
I was unable to reproduce this behavior using the latest version of Vagrant. It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2018-12-21 23:02 UTC
Labels: bug, needs-repro, provider/virtualbox
