### ISSUE TITLE
vagrant share --ssh hangs

### ISSUE THREAD

**Issue by ronmcmillian** [hashicorp/vagrant#11323] opened 2020-01-14 20:44 UTC
### Vagrant version
Vagrant 2.2.6

### Host operating system
Ubuntu 18.04

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
   config.vm.network "public_network",
     use_dhcp_assigned_default_route: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output
https://gist.github.com/ronmcmillian/5e15c0e4927df9a44d27bbf063d98be0

### Expected behavior
vagrant share --ssh should have completed successfully.

### Actual behavior
vagrant share --ssh hangs on "share: Machine booted and ready!"

### Steps to reproduce
1. vagrant share --ssh

**Comment by ronmcmillian** [comment] 2020-01-14 20:52
Maybe the same issue? #10328

**Comment by ronmcmillian** [comment] 2020-01-14 22:18
According to the logs, it looks to be an issue with ngrok finding the configuration file generated by vagrant share. Not sure if this is an issue with file creation though.

**Comment by jbonhag** [comment] 2020-01-15 14:55
Hi @ronmcmillian, and thanks for opening an issue with Vagrant.  This definitely seems like a duplicate of that other issue, as I see the following error in both debug logs:

```
 WARN share: Failure handling ngrok process output line: JSON::ParserError - 751: unexpected token at 'ERROR:  Failed to read configuration: Error reading configuration file '/tmp/vagrant-share20181025-5899-14kp8ac': open /tmp/vagrant-share20181025-5899-14kp8ac: no such file or directory' (`ERROR:  Failed to read configuration: Error reading configuration file '/tmp/vagrant-share20181025-5899-14kp8ac': open /tmp/vagrant-share20181025-5899-14kp8ac: no such file or directory`)
```

I'm going to go ahead and close your issue as a duplicate, but we'll see if we can figure out what's going on here.  Cheers!

**Closed by jbonhag** 2020-01-15 14:55 UTC
Labels: duplicate
