### ISSUE TITLE
Vagrant up not start stack (undefined method `downcase' for nil:NilClass)

### ISSUE THREAD

**Issue by weyderfs** [hashicorp/vagrant#10802] opened 2019-04-22 16:58 UTC
### Vagrant version
Vagrant 2.2.4
### Plugins
Hostmanager 1.2.2
Vbguest
### Host operating system
macOS Mojave 10.14.4
Kernel: Darwin Kernel Version 18.5.0
### Guest operating system
ubuntu/bionic64
### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.vbguest.auto_update = false
  #config.vbguest.no_remote = true

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "base"
  config.vm.define :srvub01, primary: true do |c|
    c.vm.box = "ubuntu/bionic64"
    c.vm.network "private_network", ip: "192.168.200.200"
    c.vm.hostname = "Kube01"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end

  config.vm.define :srvubu02 do |ds|
    ds.vm.box = "ubuntu/bionic64"
    ds.vm.network "private_network", ip: "192.168.200.202"
    ds.vm.hostname = "Kube02"
    ds.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2" 
    end
  end

  config.vm.define :srvubu03 do |ub|
    ub.vm.box = "ubuntu/bionic64"
    ub.vm.network "private_network", ip: "192.168.200.201"
    ub.vm.hostname = "Kube03"
    ub.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
end

```
### Debug output
https://gist.github.com/weyderfs/0c31469126219e64323c5cdf388c5df6

Anyone can help how solve this?

**Comment by briancain** [comment] 2019-04-22 17:03
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by weyderfs** [comment] 2019-04-22 19:31
@briancain thanks for feedback. I run again using `--debug` and update the Gist.

**Comment by briancain** [comment] 2019-04-23 20:29
@weyderfs thanks for the debug gist! As I thought, this seems to be a duplicate of issue https://github.com/hashicorp/vagrant/issues/10733. It was fixed via https://github.com/hashicorp/vagrant/pull/10745, however that fix is not out yet! It should be out in the next release, which will be version 2.2.5, hopefully released soon. Thanks for the report!

For now while you wait for the fix, it sounds like you can downgrade to version 2.2.2 and it should not have this bug. Thanks!

**Closed by briancain** 2019-04-23 20:29 UTC
Labels: duplicate
