### ISSUE TITLE
vagrant cloud publish exits with exit code: 52 when uploading the box

### ISSUE THREAD

**Issue by ruzickap** [hashicorp/vagrant#12026] opened 2020-11-07 05:37 UTC
I'm trying to upload the created box file using `vagrant cloud publish`, but the upload process ends with error:

```
exit code: 52
Empty reply from server
An error occurred while uploading the file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

The box is successfully uploaded, but not released and the command ends with the error code.  

### Vagrant version

`2.2.10`

### Host operating system

MacOS Catalina

### Debug output

I'm using this command to upload the box to Vagrant Cloud:

```bash
vagrant cloud publish --force --description "${LONG_DESCRIPTION}" --version-description "${LONG_DESCRIPTION}" --release --short-description "${SHORT_DESCRIPTION}" --checksum-type sha256 --checksum "${CHECKSUM_BOX_FILE}" "${VAGRANT_CLOUD_USER}/${NAME}" "${BOX_VERSION}" "${VAGRANT_PROVIDER}" "${VAGRANT_CLOUD_BOX_FILE}"
```

Here is the debug ouput:

```text
INFO global: Vagrant version: 2.2.10
 INFO global: Ruby version: 2.6.6
 INFO global: RubyGems version: 3.0.3
 INFO global: VAGRANT_LATEST_VERSION="${VAGRANT_LATEST_VERSION}"
 INFO global: VAGRANT_PROVIDER="libvirt"
 INFO global: VAGRANT_CLOUD_USER="peru"
 INFO global: VAGRANT_LOG="debug"
 INFO global: VAGRANT_CLOUD_TOKEN="***"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_INSTALLER_ENV="1"
...
Progress: 95% (Rate: 326M/s, Estimated time remaining: 0:00:02)
 INFO interface: detail: Progress: 99% (Rate: 327M/s, Estimated time remaining: 0:00:01)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   267M  0:00:30  0:00:30 --:--:--  191M
 INFO interface: info: 

Progress: 99% (Rate: 327M/s, Estimated time remaining: 0:00:01)
 INFO interface: detail: Progress: 100% (Rate: 261M/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   257M  0:00:31  0:00:31 --:--:--  126M
 INFO interface: info: 

Progress: 100% (Rate: 261M/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 191M/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   249M  0:00:32  0:00:32 --:--:-- 65.0M
 INFO interface: info: 

Progress: 100% (Rate: 191M/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 126M/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   240M  0:00:33  0:00:33 --:--:-- 9146k
 INFO interface: info: 

Progress: 100% (Rate: 126M/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 65.0M/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   232M  0:00:34  0:00:34 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 65.0M/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 9146k/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   225M  0:00:35  0:00:35 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 9146k/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   218M  0:00:36  0:00:36 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   213M  0:00:37  0:00:37 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   207M  0:00:38  0:00:38 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   202M  0:00:39  0:00:39 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   197M  0:00:40  0:00:40 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   192M  0:00:41  0:00:41 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   188M  0:00:42  0:00:42 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   183M  0:00:43  0:00:43 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   179M  0:00:44  0:00:44 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   175M  0:00:46  0:00:46 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   171M  0:00:47  0:00:47 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   167M  0:00:48  0:00:48 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   163M  0:00:49  0:00:49 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   160M  0:00:50  0:00:50 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   157M  0:00:51  0:00:51 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   154M  0:00:52  0:00:52 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   151M  0:00:53  0:00:53 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   148M  0:00:54  0:00:54 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   145M  0:00:55  0:00:55 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   142M  0:00:56  0:00:56 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   140M  0:00:57  0:00:57 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   137M  0:00:58  0:00:58 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   134M  0:00:59  0:00:59 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   132M  0:01:00  0:01:00 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   130M  0:01:01  0:01:01 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   128M  0:01:02  0:01:02 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   126M  0:01:03  0:01:03 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   124M  0:01:04  0:01:04 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   122M  0:01:05  0:01:05 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   120M  0:01:07  0:01:07 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   118M  0:01:08  0:01:08 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   116M  0:01:09  0:01:09 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   115M  0:01:10  0:01:10 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   113M  0:01:11  0:01:11 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   111M  0:01:12  0:01:12 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   109M  0:01:13  0:01:13 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   108M  0:01:14  0:01:14 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   106M  0:01:15  0:01:15 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   105M  0:01:16  0:01:16 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   103M  0:01:17  0:0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 1:17 --:--:--     0
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   102M  0:01:18  0:01:18 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0   100M  0:01:20  0:01:20 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  99.5M  0:01:21  0:01:21 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  98.2M  0:01:22  0:01:22 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  96.9M  0:01:23  0:01:23 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  95.7M  0:01:24  0:01:24 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  94.5M  0:01:25  0:01:25 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  93.3M  0:01:26  0:01:26 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  92.1M  0:01:27  0:01:27 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  91.6M  0:01:28  0:01:28 --:--:--     0
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: stderr: 
100 8080M    0     0  100 8080M      0  91.6M  0:01:28  0:01:28 --:--:--     0
curl: (52) Empty reply from server
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail: Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31912
DEBUG subprocess: Exit status: 52
 WARN uploader: Uploader exit code: 52
 INFO interface: info: 

Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: error: Failed to create box peru/windows-server-2012_r2-standard-x64-eval
Failed to create box peru/windows-server-2012_r2-standard-x64-eval
 INFO interface: error: An error occurred while uploading the file. The error
message, if any, is reproduced below. Please fix this error and try
again.

exit code: 52
Empty reply from server
An error occurred while uploading the file. The error
message, if any, is reproduced below. Please fix this error and try
again.

exit code: 52
Empty reply from server
 INFO environment: Running hook: environment_unload
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /Users/runner/work/packer-templates/packer-templates>]
DEBUG host: Trying: slackware
DEBUG host: Trying: freebsd
DEBUG host: Trying: void
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
 INFO host: Detected: darwin!
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007fe2883c3b98>
```

The full debug log can be found here: https://pastebin.com/7UpY3UPr

### Expected behavior

The upload of the box image should not end with error and the image should be "released" successfully.

### Actual behavior

The `vagrant cloud publish ... --release ...` command ends with error and the box is not released.

### Steps to reproduce

See the command with debug output above.

**Comment by soapy1** [comment] 2020-11-09 16:06
I'm unable to reproduce this issue on the latest version of Vagrant (2.2.13). So, I'm going to go ahead and close this issue, however, if the problem persists after upgrading please feel free to reopen.

**Closed by soapy1** 2020-11-09 16:06 UTC
