### ISSUE TITLE
net-ssh version requirement inconsistency

### ISSUE THREAD

**Issue by mathiashls** [hashicorp/vagrant#12837] opened 2022-08-10 19:39 UTC
### Vagrant version
Vagrant 2.3.0

### Host operating system
Linux 5.18.16-arch1-1 x86_64 GNU/Linux

### Debug output

[Gist with complete command output.](https://gist.github.com/mathiashls/408dd4afecd781fd6015be6ff93d861a)

### Expected behavior

The plugin should be installed correctly.

### Actual behavior

The execution outputs an error saying that the net-ssh version is invalid.

```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= 6.2.0.rc2)
  Activated net-ssh-6.2.0.rc2
  which does not match conflicting dependency (>= 2.6.5, < 7.0.0)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc2), 6.2.0.rc2 activated

  versus:
    net-scp (= 3.0.0), 3.0.0 activated, depends on
    net-ssh (>= 2.6.5, < 7.0.0)

  Gems matching net-ssh (>= 2.6.5, < 7.0.0):
    net-ssh-6.2.0.rc2
```

The last net-ssh version available for my system is >7.0.0, so I forced the installation of the version 6.1.0, but it doesn't effect the version vagrant use (it probably don't use the net-ssh from my system anyway).

### Steps to reproduce

1. Try to install any vagrant plugin using `vagrant plugin install plugin-name`

### References

https://github.com/hashicorp/vagrant/issues/12441

**Comment by lokihsx** [comment] 2022-08-11 03:00
face the same issue, and i got a work through: 
```mv /usr/bin/ruby /usr/bin/ruby-3.0```
and
```mv /usr/bin/ruby-2.7 /usr/bin/ruby```
may fix it temporarily.

**Comment by hstct** [comment] 2022-08-11 07:13
> face the same issue, and i got a work through: `mv /usr/bin/ruby /usr/bin/ruby-3.0` and `mv /usr/bin/ruby-2.7 /usr/bin/ruby` may fix it temporarily.

This did not work for me. As a workaround I manually downgraded the pacman package back to `2.2.19` for now.

**Comment by mathiashls** [comment] 2022-08-11 14:01
> > face the same issue, and i got a work through: `mv /usr/bin/ruby /usr/bin/ruby-3.0` and `mv /usr/bin/ruby-2.7 /usr/bin/ruby` may fix it temporarily.
> 
> This did not work for me. As a workaround I manually downgraded the pacman package back to `2.2.19` for now.

This seems to be the better workaround for now.

Just to help our fellows arch users, this can be achieved using:

```
pacman -U https://archive.archlinux.org/packages/v/vagrant/vagrant-2.2.19-2-x86_64.pkg.tar.zst
```

**Comment by chrisroberts** [comment] 2022-08-11 22:13
Hi,

Currently the net-ssh constraint cannot be relaxed to allow the 7.0 versions due to other Vagrant dependencies which currently have constraints on net-ssh set to `< 7`. Once they have been updated, we will be able to loosen this constraint as well. 

One thing that might be effective is to allow Vagrant to match on the prerelease version by setting the `VAGRANT_ALLOW_PRERELEASE` environment variable. Another option is to install our release package which provides an isolated Ruby build and also isolates the Vagrant RubyGem installation along with its direct dependencies:

```
pacman -U https://releases.hashicorp.com/vagrant/2.3.0/vagrant-2.3.0-1-x86_64.pkg.tar.zst
```

Cheers!

**Comment by leophys** [comment] 2022-08-12 12:31
Hi @chrisroberts 

> Hi,
> 
> Currently the net-ssh constraint cannot be relaxed to allow the 7.0 versions due to other Vagrant dependencies which currently have constraints on net-ssh set to `< 7`. Once they have been updated, we will be able to loosen this constraint as well.

Neither of the two proposed solutions work, unfortunately. I too had to downgrade `vagrant`.
 
> One thing that might be effective is to allow Vagrant to match on the prerelease version by setting the `VAGRANT_ALLOW_PRERELEASE` environment variable. Another option is to install our release package which provides an isolated Ruby build and also isolates the Vagrant RubyGem installation along with its direct dependencies:
> 

I set `VAGRANT_ALLOW_PRERELEASE=1` before running `vagrant plugin install vagrant-libvirt` and this produces no difference with the above issue.

> ```
> pacman -U https://releases.hashicorp.com/vagrant/2.3.0/vagrant-2.3.0-1-x86_64.pkg.tar.zst
> ```
> 

This make vagrant complain a `libvirt` library is missing.

Greetings

**Comment by mathiashls** [comment] 2022-08-12 18:04
> This make vagrant complain a libvirt library is missing.

If you are trying to install the vagrant-libvirt plugin, it will require you to install the libvirt package as well. libvirt is not a vagrant dependency so you need to install it separately (`pacman -S libvirt`).

**Comment by leophys** [comment] 2022-08-13 07:31
On August 12, 2022 8:05:09 PM GMT+02:00, Mathias Hillesheim ***@***.***> wrote:
>> This make vagrant complain a libvirt library is missing.
>
>If you are trying to install the vagrant-libvirt plugin, it will require you to install the libvirt package as well. libvirt is not a vagrant dependency so you need to install it separately (`pacman -S libvirt`).
>
I acknowledge that the internet is full of noobs, but I do not consider myself one of them :)

**Comment by Krys87** [comment] 2022-08-14 13:58
I had the same issue and downgrading the vagrant package made it work:

### error -   conflicting dependencies 

    $ vagrant plugin install virtualbox
    Vagrant failed to properly resolve required dependencies
    conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= 6.2.0.rc2)

### downgrade with pacman

    $ pacman -U https://archive.archlinux.org/packages/v/vagrant/vagrant-2.2.19-2-x86_64.pkg.tar.zst
    downgrading package vagrant (2.3.0-2 => 2.2.19-2)
    vagrant      2.3.0-2      2.2.19-2     -99,21 MiB

### install plugin

    $ vagrant plugin install virtualbox
    Installing the 'virtualbox' plugin. This can take a few minutes...
    Fetching virtualbox-0.8.6.gem
    Installed the plugin 'virtualbox (0.8.6)'!

**Comment by gnfzdz** [comment] 2022-08-15 19:14
@chrisroberts  I don't see it mentioned above, but the version being complained about is absolutely within the stated bounds. Is it possible something is instead just choking on the rc2 suffix?

> conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= **6.2.0**.rc2)

I'm running into this same issue on a freshly updated ArchLinux system. Downgrading as mentioned above resolved the issue.

**Comment by Eggbertx** [comment] 2022-08-15 19:20
Yeah, I think it's an issue with the rc2 suffix, which would mean that the real problem isn't with net-ssh itself, but with whatever is being used to parse the version.
I'm hesitant to call the issue "resolved", though, since it's just a temporary workaround that will resurface until the version parsing is improved.

**Comment by mathiashls** [comment] 2022-08-16 14:36
> I acknowledge that the internet is full of noobs, but I do not consider myself one of them :)

To imply that definitely wasn't my intention, I'm sorry. Reading again I can see that you were not quoting me, my bad.


> Yeah, I think it's an issue with the rc2 suffix, which would mean that the real problem isn't with net-ssh itself, but with whatever is being used to parse the version.
I'm hesitant to call the issue "resolved", though, since it's just a temporary workaround that will resurface until the version parsing is improved.

I did not looked at the source code, but that's what I thought when I opened the issue, it really sounds like a version parsing problem.

**Comment by electrofelix** [comment] 2022-08-16 15:51
It doesn't appear to be an issue with the rc2 suffix, I did some digging and it appears to be able to correctly resolve 6.2.0.rc2 as satisfying the dependency, but still rejects it.

I couldn't pin it down exactly what is going on, but the resolver appears to do something a little weird in that it tries to generate every version between the spec bounds and perform resolving, which means for net-ssh, it generates every version between 2.6.5 and 7.0.0 and checks whether it satisfies the constraints.

Following tweak to the gem specifications is sufficient to allow everything to work on arch:
```
diff -u /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec.orig /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec
--- /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec.orig	2022-08-16 15:47:12.928174587 +0000
+++ /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec	2022-08-16 15:46:37.998463158 +0000
@@ -27,11 +27,11 @@
   end
 
   if s.respond_to? :add_runtime_dependency then
-    s.add_runtime_dependency(%q<net-ssh>.freeze, [">= 2.6.5", "< 7.0.0"])
+    s.add_runtime_dependency(%q<net-ssh>.freeze, [">= 6.0.0", "< 7.0.0"])
     s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
     s.add_development_dependency(%q<mocha>.freeze, [">= 0"])
   else
-    s.add_dependency(%q<net-ssh>.freeze, [">= 2.6.5", "< 7.0.0"])
+    s.add_dependency(%q<net-ssh>.freeze, [">= 6.0.0", "< 7.0.0"])
     s.add_dependency(%q<test-unit>.freeze, [">= 0"])
     s.add_dependency(%q<mocha>.freeze, [">= 0"])
   end
```

Which suggests to me at least, that maybe some limit is being hit when trying to do the resolving the way that it's currently being approached rather than it not being satisfied by net-ssh-6.2.0rc2.

**Comment by electrofelix** [comment] 2022-08-16 18:14
The lowest number I could modify that dependency range to and have it work is `3.2.0`, going to `3.1.0` fails with a slightly different message:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:860:in `find_all': can't modify frozen Gem::Dependency: <Gem::Dependency type=:runtime name="net-ssh" requirements="< 7.0.0, >= 2.6.5"> (FrozenError)
	from /usr/lib/ruby/3.0.0/rubygems/resolver/composed_set.rb:54:in `block in find_all'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/composed_set.rb:53:in `map'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/composed_set.rb:53:in `find_all'
	from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:203:in `find_possible'
	from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:228:in `search_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:11:in `block in search_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `search_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:727:in `activate_new_spec'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
	from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
	from /usr/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:591:in `internal_install'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:355:in `install'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/builder.rb:180:in `call'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `block in run'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `run'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `each'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/bin/vagrant:248:in `<main>'
```

going to `2.6.0` as the lower range also works.

Enabling `DEBUG_RESOLVER=1` dumps the following for net-ssh when the constraint in net-scp is set to `>= 2.6.5, < 7.0.0`
```
:  75: Requiring nested dependencies (net-ssh (>= 2.6.5, < 7.0.0))
:  75: Creating possibility state for net-ssh (>= 2.6.5, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-2.6.5, net-ssh-2.6.6, net-ssh-2.6.7, net-ssh-2.6.8, net-ssh-2.7.0, net-ssh-2.8.0, net-ssh-2.9.0, net-ssh-2.9.1, net-ssh-2.9.2, net-ssh-2.9.4, net-ssh-3.0.1, net-ssh-3.0.2, net-ssh-3.1.0, net-ssh-3.1.1, net-ssh-3.2.0, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: Unsatisfied by existing spec ([net-ssh-6.2.0.rc2])
:  76: Unwinding for conflict: net-ssh (>= 2.6.5, < 7.0.0) to -1
```

Compared to when the lower bound is 3.2.0:
```
  75: Activated net-scp at [net-scp-3.0.0, net-scp-3.0.0]
:  75: Requiring nested dependencies (net-ssh (>= 3.2.5, < 7.0.0))
:  75: Creating possibility state for net-ssh (>= 3.2.5, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0
.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: Creating possibility state for net-scp (~> 3.0.0) (2 remaining)
```

In general it looks like there are some issues in the underlying ruby bundler around how it tries to do some filtering of the valid possibilites in /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb

Adding some debug to that file to output the filtered_set:
```
      def attempt_to_filter_existing_spec(vertex)
        filtered_set = filtered_possibility_set(vertex)
        if name == "net-ssh"
          debug(depth) { "filtered_set => #{filtered_set}" }
        end
        if !filtered_set.possibilities.empty?
          activated.set_payload(name, filtered_set)
          new_requirements = requirements.dup
          push_state_for_requirements(new_requirements, false)
        else
          create_conflict
          debug(depth) { "Unsatisfied by existing spec (#{vertex.payload})" }
          unwind_for_conflict
        end
      end
```

gives the following for the failed resolving:
```
...
:  75: Creating possibility state for net-ssh (>= 2.6.5, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-2.6.5, net-ssh-2.6.6, net-ssh-2.6.7, net-ssh-2.6.8, net-ssh-2.7.0, net-ssh-2.8.0, net-ssh-2.9.0, net-ssh-2.9.1, net-ssh-2.9.2, net-ssh-2.9.4, net-ssh-3.0.1, net-ssh-3.0.2, net-ssh-3.1.0, net-ssh-3.1.1, net-ssh-3.2.0, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: filtered_set => []
:  76: Unsatisfied by existing spec ([net-ssh-6.2.0.rc2])
:  76: Unwinding for conflict: net-ssh (>= 2.6.5, < 7.0.0) to -1

:   0: Finished resolution (76 steps) (Took 5.012015612 seconds) (2022-08-16 17:57:02 +0000)
```

and for the successful
```
...
:  75: Attempting to activate [net-scp-3.0.0, net-scp-3.0.0]
:  75: Activated net-scp at [net-scp-3.0.0, net-scp-3.0.0]
:  75: Requiring nested dependencies (net-ssh (>= 3.2.0, < 7.0.0))
:  75: Creating possibility state for net-ssh (>= 3.2.0, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-3.2.0, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: filtered_set => [net-ssh-6.2.0.rc2]
:  76: Creating possibility state for net-scp (~> 3.0.0) (2 remaining)
...
```

I don't know exactly why this is happening, but it does look like the issue is rubygems resolver rather than vagrant.

**Comment by chrisroberts** [comment] 2022-08-22 15:13
@leophys The libvirt plugin will install correctly when following the instructions defined in the [vagrant-libvirt installation instructions](https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#arch). Specifically, [setting the CONFIGURE_ARGS](https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#failure-to-find-libvirt-for-native-extensions) and [adjusting the linker](https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#failure-to-link).

**Comment by chrisroberts** [comment] 2022-08-22 16:25
The root cause of the issue is the package being built by installing the Vagrant gem using the `--prerelease` flag which is pulling in the net-ssh release client. By default prerelease versions are not used for dependency resolution unless extra steps to explicitly enable them are taken. Link to the archlinux package bug report is [here](https://bugs.archlinux.org/task/75671).

For workarounds now, you can either install our release package as described [here](https://github.com/hashicorp/vagrant/issues/12837#issuecomment-1212549600), or you can add a couple environment variables to enable prerelease versions and relax the constraint enforcement:

```
[vagrant@archlinux ~]$ VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 VAGRANT_ALLOW_PRERELEASE=1 vagrant plugin install vagrant-list
Installing the 'vagrant-list' plugin. This can take a few minutes...
Fetching vagrant-list-0.0.6.gem
Installed the plugin 'vagrant-list (0.0.6)'!
```

Cheers!

**Closed** 2022-08-23 18:03 UTC
Labels: upstream, core

**Comment by electrofelix** [comment] 2022-08-23 18:51
@chrisroberts that's great. I do think there is probably still another issue with rubygems as it should have consistently seen a conflict or consistently succeeded. Though with this resolved it's probably less important for that inconsistency to be fixed as well.

**Comment by Krys87** [comment] 2022-08-24 22:11
### I upgarded the package to 2.3.0-5 and I can also confirm it works now:

vagrant  2.2.19-2     2.3.0-5      101,13 MiB      39,66 MiB

krys@archeos:~/admin/local/vagrant]$ vagrant plugin install vagrant-scp
Installing the 'vagrant-scp' plugin. This can take a few minutes...
Fetching virtualbox-0.8.6.gem
Fetching vagrant-scp-0.5.9.gem
Installed the plugin 'vagrant-scp (0.5.9)'!
