### ISSUE TITLE
Can not use docker provider with host vm on windows

### ISSUE THREAD

**Issue by yunchuan-cumulus** [hashicorp/vagrant#11844] opened 2020-08-24 10:02 UTC
### Vagrant version

Vagrant 2.2.9

### Host operating system

Windows 10 2004

### Guest operating system

docker image

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
	config.vm.provider "docker" do |d|
	  d.force_host_vm = true
	  d.image = "hello-world"
	end
end
```

### Expected behavior

`vagrant up` should create necessary host vm.

### Actual behavior

`vagrant up` complains that

> The provider 'docker' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:
The executable 'docker' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.

### Potential Cause
file: vagrant/plugins/providers/docker/provider.rb

```ruby
      def self.usable?(raise_error=false)
        Driver.new.execute("docker", "version")
        true
      rescue Vagrant::Errors::CommandUnavailable, Errors::ExecuteError
        raise if raise_error
        return false
      end
```

the usable check above doesn't working on host vm configuration cause it default using local executor to run docker command.

**Comment by soapy1** [comment] 2020-08-24 14:59
Hey there, 
thanks for submitting an issue! It looks like this is probably a duplicate of https://github.com/hashicorp/vagrant/issues/11802. So, I'm going to go ahead and close this. Thanks again!

**Closed by soapy1** 2020-08-24 14:59 UTC
Labels: duplicate, provider/docker
