### ISSUE TITLE
Modified ~/.vimrc breaks vim

### ISSUE THREAD

**Issue by Torniojaws** [hashicorp/vagrant#9161] opened 2017-11-09 07:25 UTC
When I modified the ``~/.vimrc`` file on my Vagrant 2.0.0 on Windows 10 with ``v0rtex/xenial64`` box (Ubuntu 16.04 64-bit), I can no longer use ``vim``. It freezes (cannot write or change mode) when it opens a file to edit and you need to press ``Ctrl + C`` repeatedly for about 5-6 times before it responds.

Steps to reproduce, as user ``vagrant``:
1. ``vim ~/.vimrc`` (in my case, it did not exist yet)
2. Make the contents this:
```
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

```
3. Save with ``:wq!``
4. Now, open vim again with any file - doesn't need to exist: ``vim ~/myfile``

**Expected:** 
The file is opened normally and can be edited.

**Actual:** 
Vim freezes with just the filename in the bottom of the screen. Once it is in this frozen mode, you cannot do anything. Eg.
``Esc + i`` nothing happens.
``Esc + Esc`` the mode does not change.
``Esc + : + q!`` does not even appear in the screen and does not quit the editor
``Ctrl + C`` done once does not do anything.
``Ctrl + C`` several times in a row will eventually make the command row appear, where you can write ``:q!`` and it then works.

**Comment by Torniojaws** [comment] 2017-11-09 07:26
I modified the file with ``nano`` and then it mysteriously works again. It might be actually related to editing the vim file with ``vim``.

**Comment by briancain** [comment] 2017-11-10 21:21
@Torniojaws - What program are you using to run vagrant with? cmd.exe, powershell, cygwin...etc?

**Comment by Torniojaws** [comment] 2017-11-10 21:25
@briancain Powershell (64-bit) and then I ssh to it with PuTTY.

**Comment by briancain** [comment] 2017-11-10 21:40
Do you mean that you bring up the machine with vagrant in powershell, and then ssh into that vm with PuTTY separately outside of vim?

Also I just tried to reproduce this on windows 10 with the latest version of Vagrant. I created a .vimrc with those settings, and I didn't experience this behavior. I did use a different ubuntu box though. Perhaps try this with Vagrant 2.0.1?

**Comment by Torniojaws** [comment] 2017-11-11 17:09
``Do you mean that you bring up the machine with vagrant in powershell, and then ssh into that vm with PuTTY separately outside of vim?``
I'm not sure what you mean by outside of vim, but I assume you meant outside of Windows? Or maybe you mean a second instance where the "frozen" vim is not active?

I do the ssh from within the same guest Windows where I bring up the VM. So:

- In Windows guest, do ``vagrant up`` in Powershell
- In the same Windows guest, ssh to the box using PuTTY
- Then within that same ssh session do the steps mentioned in my first post.

So only one ssh session is active.

**Comment by briancain** [comment] 2017-11-13 16:52
If your ssh session is freezing outside of `vagrant ssh` and you're using PuTTY to ssh into the guest, that wouldn't be a vagrant bug. Sorry! It's likely something wrong with your PuTTY environment...so I recommend looking at that. I'm going to go ahead and close this issue.

**Closed by briancain** 2017-11-13 16:52 UTC

**Comment by Torniojaws** [comment] 2017-11-13 18:45
It's not SSH that is freezing, it's the vim editor itself.

**Comment by briancain** [comment] 2017-11-13 18:52
Hi @Torniojaws - I understand what you're saying, but what you described is not a bug with Vagrant.

**Comment by Torniojaws** [comment] 2017-11-13 18:58
Ok, thanks!
