### ISSUE TITLE
vmware-plugin 5.0 permission error

### ISSUE THREAD

**Issue by terion-name** [hashicorp/vagrant#9073] opened 2017-10-18 17:27 UTC
I've updated vmware plugin to 5.0, then I've updated VMWare to 10.0
After running `vagrant up` I get:
```sh
Bringing machine 'next-gen' up with 'vmware_fusion' provider...
==> next-gen: Verifying vmnet devices are healthy...
/Users/terion/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-fusion-5.0.0/lib/vagrant-vmware-fusion/helper/nat_conf.rb:169:in `initialize': Permission denied @ rb_sysopen - /Users/terion/.vagrant.d/data/vmware/vmware-nat.json.lock (Errno::EACCES)
  # trace here
```

**Comment by briancain** [comment] 2017-10-18 18:32
Hi! Thanks for opening an issue, this seems to be a duplicate of #9047 so I'm going to go ahead and close this.

**Closed by briancain** 2017-10-18 18:32 UTC

**Comment by terion-name** [comment] 2017-10-18 19:02
@briancain yes, that helped. I thought it is related to plugin update. Thank you
