### ISSUE TITLE
Vagrant precise64 url not working anymore

### ISSUE THREAD

**Issue by PragmaticEd** [hashicorp/vagrant#9616] opened 2018-03-26 07:30 UTC
* Go to vagrant web page https://www.vagrantup.com/
* See tutorial..
* Run `vagrant init hashicorp/precise64`
* Run `vagrant up`
* Get error:

```
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error: The requested URL returned error: 404 Not Found
```

This happens in Windows 10 & Ubuntu 16.04

**Comment by PragmaticEd** [comment] 2018-03-26 07:34
Found temp solution: https://github.com/hashicorp/vagrant/issues/9442#issuecomment-363080565

**Comment by briancain** [comment] 2018-03-26 16:20
Hello @PragmaticEd - this is actually a duplicate of #9442. You can fix this by upgrading to the latest version of Vagrant. Thanks!

**Closed by briancain** 2018-03-26 16:20 UTC
