### ISSUE TITLE
box-cutter/ubuntu1404-desktop hits HTTP 404 Not Found instead of 200 OK

### ISSUE THREAD

**Issue by CMoH** [hashicorp/vagrant#10236] opened 2018-09-24 23:07 UTC
This seems like a repeated issue, but well... here's my steps to reproduce:

1. Go to and search for `ubuntu desktop`
2. Pick first 16.04 hit in Downloads order, namely https://app.vagrantup.com/box-cutter/boxes/ubuntu1604-desktop
3. Paste Vagrantfile and run `vagrant up` as in this session:

```
~/src/vagrant/ubuntu1604-desktop $ cat Vagrantfile 
Vagrant.configure("2") do |config|
  config.vm.box = "box-cutter/ubuntu1604-desktop"
end
~/src/vagrant/ubuntu1604-desktop $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'box-cutter/ubuntu1604-desktop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'box-cutter/ubuntu1604-desktop'
    default: URL: https://vagrantcloud.com/box-cutter/ubuntu1604-desktop
==> default: Adding box 'box-cutter/ubuntu1604-desktop' (v2.0.26) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/box-cutter/boxes/ubuntu1604-desktop/versions/2.0.26/providers/virtualbox.box
    default: Download redirected to host: cdn.boxcutter.io
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
~/src/vagrant/ubuntu1604-desktop $ vagrant --version
Vagrant 2.1.2
```

Running with `--debug` shows that some cdn failed to replicate the box, like this:

```
...
GET http://cdn.boxcutter.io/ubuntu/virtualbox5.1.10/ubuntu1604-desktop-2.0.26.box HTTP/1.1
> Host: cdn.boxcutter.io
> User-Agent: Vagrant/2.1.2 (+https://www.vagrantup.com; ruby2.3.7)
> Accept: */*
> Proxy-Connection: Keep-Alive
> 

 INFO interface: detail: Progress: 100% (Rate: 199/s, Estimated time remaining: --:--:--)
 INFO interface: detail:     default: Progress: 100% (Rate: 199/s, Estimated time remaining: --:--:--)
    default: Progress: 100% (Rate: 199/s, Estimated time remaining: --:--:--)DEBUG subprocess: stderr: * The requested URL returned error: 404 Not Found
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 1
DEBUG subprocess: stderr: curl: (22) The requested URL returned error: 404 Not Found
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 22
 WARN downloader: Downloader exit code: 22
ERROR downloader: Exit code: 22

DEBUG box_add: Deleting temporary box: 
ERROR warden: Error occurred: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
...
```

Please either remove the box from the index if you dropped it, or add the box to the CDN (also if you dropped it :-))

**Comment by briancain** [comment] 2018-09-24 23:28
Hello there @CMoH - thanks for opening an issue on Vagrant!

Unfortunately, there isn't much we can do about that. The [boxcutter](https://github.com/boxcutter) org has configured their boxes to be externally hosted, and they have decided to no longer support providing boxes to download. As of this issue https://github.com/boxcutter/ubuntu/issues/133#issuecomment-339929663, they have stated that they no longer support pre-built boxes. You can clone their repo and build the box yourself, or find a different box on Vagrant Cloud. Closing this issue as a duplicate of https://github.com/hashicorp/vagrant/issues/10183. Thanks!

**Closed by briancain** 2018-09-24 23:28 UTC

**Comment by CMoH** [comment] 2018-09-25 12:48
So, why don't you remove them from there? They seem to be confusing to a lot of users, judging by the issues you linked.

**Comment by chrisroberts** [comment] 2018-09-25 15:02
@CMoH We do not modify the contents of user's accounts on Vagrant Cloud. If the account owner wishes to update/delete their box files, that is the responsibility of the owner.
