### ISSUE TITLE
vagrant.pkg cannot be verified on Catalina for upgrade

### ISSUE THREAD

**Issue by timcoote** [hashicorp/vagrant#11158] opened 2019-10-26 10:41 UTC
**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.
macOS 10.15 (19A583)

### Expected behaviour
Following the instructions in vagrant 2.2.5 to upgrade, download the dmg.
Open downloaded package vagrant_2.2.6_x86_64.dmg
Double click on 'vagrant.pkg'
there should be an interaction to upgrade from the previous version of vagrant

### Actual behavior
Double click on `vagrant.pkg`, get error message:
'“vagrant.pkg” can’t be opened because Apple cannot check it for malicious software."
"This software needs to be updated. Contact the developer for more information."
"This item is on the disk image “vagrant_2.2.6_x86_64.dmg”. Chrome downloaded this disk image today at 11:25 from releases.hashicorp.com."

### Steps to reproduce
1. Download package from https://www.vagrantup.com/downloads.html
2. launch downloaded file
3. double click on updater 'vagrant.pkg'

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by timcoote** [comment] 2019-10-26 10:42
Probably a dupe of #11127

**Comment by briancain** [comment] 2019-10-28 15:31
Hi @timcoote - Thanks for opening an issue! You're right, this is a duplicate of that issue. I'll go ahead and close this one.

**Closed by briancain** 2019-10-28 15:31 UTC
