### ISSUE TITLE
SMB: Causes new issues by modifying the host share settings

### ISSUE THREAD

**Issue by strarsis** [hashicorp/vagrant#8298] opened 2017-02-23 02:32 UTC
### Vagrant version
Vagrant 1.9.1

### Host operating system
Windows 10 Home Premium x64

### Guest operating system
Ubuntu 16.04 (Xenial)

After using SMB as synced folder type the first type (instead nfs), 
the new synced folder type works well in guest - but it causes now trouble 
with  CIFS (SMB) mounts of other linux clients.

sendfile (nginx) doesn't work anymore suddenly, truncated at 0.

**Comment by chrisroberts** [comment] 2017-02-23 17:39
Hi! Can you provide a simple Vagrantfile and instructions for reproducing the error you are encountering? This will be the best way to replicate and determine the underlying cause of the error. Thanks!

**Comment by strarsis** [comment] 2017-02-24 16:48
Vagrantfile is https://github.com/strarsis/trellis/blob/patch-1/Vagrantfile .

Related issue (encoding issues when using NFS): https://github.com/roots/trellis/issues/771

**Comment by chrisroberts** [comment] 2017-02-24 17:23
@strarsis thanks, but that is an extremely complex Vagrantfile to reproduce this specific issue. Can you reduce it down to include only what is required to view the error? Thanks!

**Comment by strarsis** [comment] 2017-02-24 17:28
The issue seems to be a global one, it doesn't depend on the Vagrantfile.
It appeared after using SMB for shared folders the first time on the Windows host.
Now I have issues with direct IO from linux clients, some setting of Windows has been apparently changed.

**Comment by chrisroberts** [comment] 2018-03-27 16:00
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2018-03-27 16:00 UTC
Labels: host/windows, needs-repro, synced-folders/smb
