### ISSUE TITLE
bundle --binstubs exec

### ISSUE THREAD

**Issue by vikasgubbi** [hashicorp/vagrant#9133] opened 2017-11-02 08:18 UTC
getting following error message

/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:259:in `find_spec_for_exe': can't find gem vagrant ([">= 0.a"]) with executable bundle (Gem::GemNotFoundException)
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:278:in `activate_bin_path'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'

**Comment by briancain** [comment] 2017-11-02 15:42
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by briancain** [comment] 2017-12-05 16:29
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by briancain** 2017-12-05 16:29 UTC
Labels: waiting-reply
