### ISSUE TITLE
Archlinux, many warnings and unable to configure network

### ISSUE THREAD

**Issue by raqua** [hashicorp/vagrant#11361] opened 2020-02-01 10:09 UTC
### Vagrant version
Vagrant 2.2.7

### Host operating system
Archlinux, fully up to date

### Guest operating system
Archlinux, two images:
archlinux/archlinux                       (virtualbox, 2019.10.02)
archlinux/archlinux                       (virtualbox, 2020.01.03)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

####################################################################
GUI_WANTED=false

SALT_INSTALL_TYPE='stable'
SALT_VERSION=''
####################################################################

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "archlinux/archlinux"

  config.vm.synced_folder "saltstack/states/", "/srv/salt"
  config.vm.synced_folder "saltstack/pillars/", "/srv/pillar"

  config.vbguest.auto_update = false

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.define "master" do |master|

        master.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.name = "salt-master"
            vb.cpus = 2
            vb.memory = 512
        end

        master.vm.network "public_network" , :mac => "080027111112", bridge: [ "wlan0", "eth0" ]
        master.vm.provision "shell", run: "always", inline: "sh /vagrant/arch_box_prepare.sh"
        master.vm.hostname = "salt-master"

        master.vm.provision :salt do |salt_master|
            salt_master.verbose = true
            salt_master.colorize = true
            salt_master.masterless = true
            salt_master.log_level = "debug"
            salt_master.run_highstate = true
            salt_master.install_type = "#{SALT_INSTALL_TYPE}"
            salt_master.install_args = "#{SALT_VERSION}"
        end

  end

  config.vm.define "minion1" do |minion1|

        disk_filename = "large_disk_m1.vdi"

        minion1.vm.provider "virtualbox" do |vb|
            vb.gui = GUI_WANTED
            vb.name = "salt-minion1"
            vb.cpus = 6
            vb.memory = 4096

            unless File.exist?(disk_filename)
                vb.customize ['createhd',
                             '--filename', disk_filename,
                             '--size', 10 * 1024]
                vb.customize ['storageattach', :id,
                             '--storagectl', 'IDE',
                             '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk_filename]
            end
        end

        minion1.vm.network "public_network", bridge: [ "wlan0", "eth0" ]
        minion1.vm.provision "shell", run: "always", inline: "sh /vagrant/arch_box_prepare.sh"
        minion1.vm.hostname = "minion1"

        minion1.vm.provision :salt do |salt_minion|
            salt_minion.verbose = true
            #salt_minion.log_level = "info"
            salt_minion.colorize = true
            salt_minion.masterless = true
            salt_minion.run_highstate = true
            salt_minion.install_type = "#{SALT_INSTALL_TYPE}"
            salt_minion.install_args = "#{SALT_VERSION}"
        end

        minion1.vm.provision "shell", run: "always",
                inline: "echo 'minion1' > /etc/salt/minion_id"
  end
end
```

Note, arch_box_prepare.sh has this contents only:
cp /vagrant/mirrorlist.x86 /etc/pacman.d/mirrorlist

### Debug output
https://gist.github.com/raqua/cf3a394298f32332393191d06a88ba92

### Expected behavior
Archlinux should be started and provisioned with Salt. 

### Actual behavior
I get a lot of gem (Ruby?) warnings and provisioning fails with being unable to setup networking.
This worked fine until box version 2019.10.02, since then it fails.

### Steps to reproduce
1. Run "vagrant up" on provided Vagrantfile
2.
3.

**Comment by Kenney-G** [comment] 2020-02-10 04:14
also getting errors in arch `Bringing machine 'default' up with 'virtualbox' provider...
Traceback (most recent call last):
	14: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `action'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `call'
	11: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/environment.rb:613:in `lock'
	10: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:209:in `block in action'
	 9: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:238:in `action_raw'
	 8: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
	 7: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
	 6: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
	 5: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
	 4: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
	 3: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	 2: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
`

**Comment by muhammadsalah** [comment] 2020-02-26 08:50
I have the same warnings as well on vagrant on my arch installation.
But vagrant works ok, the warnings however are so annoying.

**Comment by briancain** [comment] 2020-05-19 21:44
Hey there - These warnings are likely because arch packages vagrant differently from the official installer. The network issue should be resolved via https://github.com/hashicorp/vagrant/pull/11400. I'm going to go ahead and close this as a duplicate of https://github.com/hashicorp/vagrant/issues/11254. Thanks!

**Closed by briancain** 2020-05-19 21:44 UTC
