### ISSUE TITLE
vagrant-vmware-workstation requires vagrant-vbguest 0.13.0

### ISSUE THREAD

**Issue by doctapp** [hashicorp/vagrant#8977] opened 2017-09-15 19:06 UTC
### Vagrant version
2.0.0 (also tried with 1.9.0)

### Host operating system
Windows 10 x64

### Guest operating system
Ubuntu 16.04

### Debug output
$ vagrant plugin list
vagrant-share (1.1.9, system)
vagrant-vbguest (0.14.2)

$ vagrant plugin install vagrant-vmware-workstation
Installing the 'vagrant-vmware-workstation' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:
 
Unable to resolve dependency: user requested 'vagrant-vbguest (= 0.13.0)'

### Expected behavior
Installs with vagrant-vbguest 0.14.2 or doesn't require vagrant-vbguest at all

### Actual behavior
Fails to install

### Steps to reproduce
1. vagrant plugin install vagrant-vbguest --plugin-version 0.14.2
2. vagrant plugin install vagrant-vmware-workstation

**Comment by chrisroberts** [comment] 2017-09-15 21:10
Can you please provide the debug output from:

```
vagrant plugin install vagrant-vmware-workstation --debug
```

Thanks!

**Comment by doctapp** [comment] 2017-09-18 13:37
Can't reproduce it now even if I uninstall vagrant-vmware-workstation and
vagrant-vbguest with a re-install of vagrant-vbguest --version 0.14.2
(latest).

Any idea how I can reproduce it?

**Comment by chrisroberts** [comment] 2017-09-19 03:09
I have been unable to reproduce it locally. I'm going to close this issue up, but if you experience the behavior again, please feel free to open a new issue. Thanks!

**Closed by chrisroberts** 2017-09-19 03:09 UTC
Labels: bundler, host/windows, waiting-reply
