### ISSUE TITLE
No host IP was given to the Vagrant core NFS helper

### ISSUE THREAD

**Issue by merlinnot** [hashicorp/vagrant#8021] opened 2016-11-18 23:30 UTC
No host IP was given to the Vagrant core NFS helper. This is an internal error that should be reported as a bug.

### Vagrant version
Vagrant 1.8.7, 1.8.1 (both invoked with and without sudo)

### Host operating system
Ubuntu 16.04.1 LTS 4.4.0-47-generic

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version
Vagrant.require_version ">= 1.8.7"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# Create and configure the Docker container
Vagrant.configure("2") do |config|

  # Assign a friendly name to this host VM
  config.vm.hostname = "dev"

  # Vagrant uses vagrant user by default. Docker uses root.
  # Use root, it is a development environment anyway.
  config.ssh.username = "root"

  # Since we have all the powers of a root user, make it easy
  # to edit files on our host machine.
  config.nfs.map_uid = ENV['UID']
  config.nfs.map_gid = ENV['GROUPS']
  config.vm.synced_folder ".", "/vagrant/",
    nfs: true

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Provision ssh keys and git configuration
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/root/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/root/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/known_hosts", destination: "/root/.ssh/known_hosts"
  config.vm.provision "file", source: "~/.gitconfig", destination: "/root/.gitconfig"

  # Forwarding ports with auto-correction
  config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 8081, host: 8081, auto_correct: true
  config.vm.network "forwarded_port", guest: 8082, host: 8082, auto_correct: true

  # Docker provider
  config.vm.provider "docker" do |d|
    d.image = "merlinnot/dev"
    d.remains_running = true
    d.has_ssh = true
    d.privileged = true
  end
end
```

### Debug output
[gist](https://gist.github.com/merlinnot/21ea100fbab0a6dd2a4fabc904369a63)

### Expected behavior
Synced folders should be correctly mounted.

### Actual behavior
`vagrant up` throws an error, container is still accessible via `vagrant ssh`, there's no /vagrant folder in the container.

### Steps to reproduce
1. `vagrant up`

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
-  #4344

**Comment by rmohr** [comment] 2016-11-24 10:04
I have exactly the same problem when  using nfs with vagrant and docker provider. Tried 1.8.7 on ubuntu 14.4 and on fedora 23.

**Comment by sjsn** [comment] 2017-07-20 21:24
Any status on this bug? Were you able to get it to work? I'm encountering the same issue with 1.9.7 and ubuntu 16.04.

**Comment by merlinnot** [comment] 2017-07-21 05:52
I'm using docker-compose instead of Vagrant.

**Comment by axot** [comment] 2017-11-07 08:55
Same error in `2.0.1`,  any updates?

**Comment by nervo** [comment] 2017-11-22 13:14
I'm not a ruby specialist, anyway, having the same issue, i've tried to (kind-of) debug.
Digging into the code, i've realized that there is a "PrepareNFSSettings" class in docker provider (here: https://github.com/hashicorp/vagrant/blob/master/plugins/providers/docker/action/prepare_nfs_settings.rb) which is reponsible to inject host & machine ip to nfs settings.

Adding an ugly `puts 'Hello'` in its call method (right here: https://github.com/hashicorp/vagrant/blob/master/plugins/providers/docker/action/prepare_nfs_settings.rb#L16), it seems the this method is called during `vagrant reload`, but NOT during `vagrant up`.

Can someone confirm ?

**Comment by briancain** [comment] 2017-11-28 18:17
Closing this, as it is a duplicate of #7070. Thanks!

**Closed by briancain** 2017-11-28 18:17 UTC
Labels: synced-folders/nfs
