### ISSUE TITLE
Failed to create new device

### ISSUE THREAD

**Issue by terion-name** [hashicorp/vagrant#12052] opened 2020-11-16 20:27 UTC
I've updated to Big Sur (that was in beta for half of a year and gave plenty of time to adapt and test)

With that I was forced to update VMWare Fusion from 11 to 12, that is around for 2 months already. But thankfully it is now free for personal use.

With that I was forced to pay again for vagrant vmware provider. Third or fourth time in my usage period.

And... and it doesn't work.

I've used to permanent port forwarding issues. I can live without port forwarding that doesn't work at all by now as I see in numerios issues.

But for me it simply doesn't work at all. Multiple hours of trying to do something and nothing. Thank you, hashicorp for such "stable" and "tested" products that continiously steal my time and stopping my work. Thank you.

### Vagrant version

Vagrant 2.2.13
vmware fusion 12, freshly updated vmware provider and utility

### Host operating system

MacOS Big Sur

### Guest operating system

Ubuntu

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/laravel/homestead", File.dirname(__FILE__))

homesteadYamlPath = File.expand_path("Homestead.yaml", File.dirname(__FILE__))
homesteadJsonPath = File.expand_path("Homestead.json", File.dirname(__FILE__))
afterScriptPath = "after.sh"
customizationScriptPath = "user-customizations.sh"
aliasesPath = "aliases"

require File.expand_path(confDir + '/scripts/homestead.rb')

Vagrant.require_version '>= 2.2.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in " + File.dirname(__FILE__)
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if File.exist? customizationScriptPath then
        config.vm.provision "shell", path: customizationScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end

# https://github.com/hashicorp/vagrant/issues/12045
Vagrant.configure("2") do |config|
  config.vm.provider :vmware_desktop do |v|
    v.ssh_info_public = true
  end
end

```

### Debug output
```
terion@MBP-Terion catalog % vagrant up
Bringing machine 'catalog' up with 'vmware_fusion' provider...
==> catalog: Checking if box 'laravel/homestead' version '10.0.0' is up to date...
==> catalog: Verifying vmnet devices are healthy...
Vagrant failed to create a new VMware networking device. The following
error message was generated while attempting to create a new device:

  Failed to create new device

Please resolve any problems reported in the error message above and
try again.
```
### Expected behavior

It works

### Actual behavior

It doesn't

**Comment by soapy1** [comment] 2020-11-16 23:59
Hey there, a new version of the vmware utility (1.0.17) was [released](https://www.vagrantup.com/vmware/downloads) 🪂 that includes a fix for this issue. So, I'm going to go ahead and close this issue. Thanks for the report!

**Comment by terion-name** [comment] 2020-11-17 10:02
@soapy1 no, it doesn't

**Comment by soapy1** [comment] 2020-11-17 15:35
Oh no! In order to better understand what is going on and reproduce this issue could you provided a minimal Vagrantfile. That is, the bare minimum amount of configuration to reproduce the problem, ideally without any dependencies on external files. 
Could you also provide some logs from [vagrant](https://www.vagrantup.com/docs/other/debugging) and from the vmware utility. The vmware utility log file should be at `/Library/Application Support/vagrant-vmware-utility/service.log`

**Comment by Kryptonit3** [comment] 2020-11-23 20:28
Same exact issue. 
MacOS BigSur
Vagrant 2.2.14
vmware utility 1.0.17

My Vagrantfile is the same. It is what is required for Laravel Homestead to function.

**Comment by ignaciovazquez** [comment] 2020-12-01 17:05
I'm having the same issue

**Comment by dfox288** [comment] 2020-12-15 13:00
Same problem here. Big Sur 11.1. All plugins, utilities and VMWare are the newest versions.

**Comment by dfox288** [comment] 2020-12-16 10:49
Update: uninstalling the vmware utility and the vagrant plugin and reinstalling them seemed to have fixed the issue.

**Comment by terion-name** [comment] 2020-12-25 21:29
@dfox288 tried, didn't help

**Comment by herrbischoff** [comment] 2021-01-06 11:55
Purchased the VMware plugin yesterday, same issue here. Probably have to return it if this is not fixed very shortly.

```
# sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

```
VMware Fusion 12.1.0 (17195230)
```

**Comment by kvn1234** [comment] 2021-01-09 23:12
I am FURIOUS that this is a known issue and yet you still sold me the plugin not an hour ago.  It should be noted on the website that it doesn't work with Big Sur (or at least that there are issues.) Since there's no VirtualBox available for Big Sur ATM, this is going to be happening a lot more now that everyone will be starting to move.  I suggest you get on a fix for this. You're CHARGING MONEY FOR THIS.  This isn't some freeware hope-for-the-best open source for-the-love-of-code project. You are taking money for a product you know doesn't work. 

That's called "fraud."

**Comment by herrbischoff** [comment] 2021-01-10 21:15
Just wanted to point to to an [Ask Different question I posted](https://apple.stackexchange.com/questions/410529/virtualbox-does-not-work-after-upgrading-to-big-sur) some time ago with possible solutions to get VirtualBox going on Big Sur, although this issue is about the VMware plugin. For me, a full wipe and install from scratch did it for VirtualBox, no further tricks necessary, no messing with SIP, nothing. The OS update appears to break subtle things while a clean install works. Have seen this on multiple machines now.

VMware still does not work as expected with Vagrant though.

@kvn1234, you're upset, I was frustrated too. However, there's no need for name-calling. Breathe. I got offered a refund after an unsuccessful troubleshooting attempt with support@hashicorp.com. They answer very quickly and try their best, despite not being able to help in this case. It was a great support experience, despite the fact that it led nowhere. In truth, it's quite possibly predominantly a VMware issue.

**Comment by kvn1234** [comment] 2021-01-10 23:53
> Just wanted to point to an [Ask Different question I posted](https://apple.stackexchange.com/questions/410529/virtualbox-does-not-work-after-upgrading-to-big-sur) some time ago with possible solutions to get VirtualBox going on Big Sur, although this issue is about the VMware plugin. For me, a full wipe and install from scratch did it for VirtualBox, no further tricks necessary, no messing with SIP, nothing. The OS update appears to break subtle things while a clean install works. Have seen this on multiple machines now.
> 
> VMware still does not work as expected with Vagrant though.
> 
> @kvn1234, you're upset, I was frustrated too. However, there's no need for name-calling. Breathe. I got offered a refund after an unsuccessful troubleshooting attempt with [support@hashicorp.com](mailto:support@hashicorp.com). They answer very quickly and try their best, despite not being able to help in this case. It was a great support experience, despite the fact that it led nowhere. In truth, it's quite possibly predominantly a VMware issue.

I was able to get VirtualBox working as well. Since I can't see where I called anyone names, I stand by everything else in my post.  The fact of the matter is this is a known issue.

**Comment by soapy1** [comment] 2021-01-12 20:00
Hey there, it's clear that this is a very frustrating issue and the move to Big Sur has been pretty rocky. In order to better enable users to make informed decisions we are adding a "Known Issues" section to the VMWare landing page (check out [this PR](https://github.com/hashicorp/vagrant/pull/12136)). As a reminder, please remember to follow the [Community Guidelines](https://www.hashicorp.com/community-guidelines) when posting on public Hashicorp forums.

**Comment by kvn1234** [comment] 2021-01-12 20:59
I called no one names.  I properly named the legal term for taking money for a product you know doesn't work.  If you want to continue to allege that I did something wrong, that's fine.  It does not change the fact that I did nothing wrong. "Congratulations", I guess, on doing the absolute bare minimum 96 hours after the bare minimum was pointed out to you.

**Comment by chrisroberts** [comment] 2021-01-12 22:24
@kvn1234 I'd again refer you to review the [Community Guidelines](https://www.hashicorp.com/community-guidelines) when posting on HashiCorp forums/repositories. We maintain an expectation that users will be considerate and respectful when commenting. I understand that you are frustrated, but the tone and condescension of your comments are not helpful in resolving this issue nor are they acceptable within the framework of the guidelines. The VMware plugin also includes a 30 day refund period if it does not meet your needs. 

An update was released today for the `vagrant-vmware-utility` that resolves the original issue as best as possible. While the creation of network devices is available in Fusion on Big Sur, there are restrictions which prevent them from behaving the same as they do on Catalina and prior installations of macOS. Most notable is the lack of support for specifying subnet and mask values which removes the ability to define custom IP addresses. 

The list of known issues with Big Sur can now be seen here: https://www.vagrantup.com/docs/providers/vmware/known-issues#big-sur-related-issues

When running VMware Fusion on Big Sur, Fusion virtualization and vmnet services are no longer used. Initial releases indicated that the lacking features would be addressed in upcoming releases, but with no updates being released in the macOS virtualization and vmnet frameworks around the lacking features, it does not appear that they will be available any time in the near term future.

We have been working on supplementing the functionality as best we can where possible, and cleaning up error responses where supplementing is not possible. The Big Sur release introduced a number of changes that were compounded by Fusion's complete move to the macOS virtualization and vmnet frameworks. My apologies to everyone affected by the issues around this and my thanks for all your patience as we worked through what was missing, what we could provide, and what was no longer possible.

Cheers!

**Closed by chrisroberts** 2021-01-12 22:24 UTC
Labels: provider/vmware, waiting-reply
