### ISSUE TITLE
`vagrant plugin install` returns "SSL_connect returned=1 errno=0 state=error: unexpected message"

### ISSUE THREAD

**Issue by ndejay** [hashicorp/vagrant#12409] opened 2021-06-04 12:13 UTC
Hello,

I'm running into the following problem.  This is happening on two different machines running slightly different versions of Vagrant, OS and Kernel.

Any help would be greatly appreciated, thanks!

### Vagrant / OS / Kernel Version

Vagrant 2.2.10 / CentOS Linux 8 / 4.18.0-193.14.2.el8_2.x86_64 / OpenSSL 1.1.1g FIPS  21 Apr 2020
Vagrant 2.2.16 / CentOS Linux 7 / 3.10.0-1160.25.1.el7.x86_64 / OpenSSL 1.0.2k-fips  26 Jan 2017

### Steps to reproduce

```
$ vagrant plugin install vagrant-vbguest
$ vagrant plugin install vagrant-vbguest --plugin-clean-source --plugin-source https://rubygems.org
```

### Expected behavior

Install the plugin.

### Actual behavior

```
$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  SSL_connect returned=1 errno=0 state=error: unexpected message (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
```

### Debug output

```
$ vagrant plugin install vagrant-vbguest &> log
```
[Gist](https://gist.github.com/ndejay/4421a88fd14eef1af7798d33593a8db4)

### Additional Things

The following work:

```
$ wget -v https://gems.hashicorp.com/specs.4.8.gz
$ wget -4 https://gems.hashicorp.com/specs.4.8.gz
$ curl https://gems.hashicorp.com/specs.4.8.gz
$ wget --ca-certificate=/opt/vagrant/embedded/cacert.pem https://gems.hashicorp.com/specs.4.8.gz
```

I even tried to disable IPv6 (as explained in #8795), but it did not resolve the issue:

```
$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6
$ sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
$ ip a | grep inet6
```

I even tried to use `curl` or `wget`'s certificates instead of the one that ships with Vagrant:

```
$ export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
$ export CURL_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt

$ export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
$ export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
```

### References

- [#8795](https://github.com/hashicorp/vagrant/issues/8795)
- [#11548](https://github.com/hashicorp/vagrant/issues/11548)
- [#7780](https://github.com/hashicorp/vagrant/issues/7780)

**Comment by ndejay** [comment] 2021-06-10 17:38
Hi,

Just kindly following up on this in case it was missed!  Please let me know if there is any other information I can provide to help reproduce this error.

Thanks,
Nicolas

**Comment by chrisroberts** [comment] 2021-06-11 16:49
This error is generally encountered when a network proxy is filtering the request. If the HashiCorp RubyGem repository cannot be added to the allow list, removing it from the sources when doing an install should be sufficient. This command should allow that:

```
vagrant plugin install --plugin-clean-sources --plugin-source https://rubygems.org vagrant-vbguest
```

I did see this attempted in the original issue description, but the `--plugin-clean-sources` was missing the `s` at the end. If it still does not work, please provide the debug out in a gist of the above command and I'll see what I can find there.

Cheers!

**Comment by ndejay** [comment] 2021-06-15 20:30
Hi Chris,

Thanks for taking the time to look into this.

> This error is generally encountered when a network proxy is filtering the request. 

If a network proxy were filtering the request, then wouldn't we expect `wget` and `curl` to fail as well?  They both seem to work.  In addition, system-wide (but older) Ruby seems to work too.

```
$ yum install ruby ruby-devel
$ ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
$ gem install json
Building native extensions.  This could take a while...
Successfully installed json-2.5.1
Parsing documentation for json-2.5.1
Installing ri documentation for json-2.5.1
1 gem installed
```

In contrast, the Ruby that was embedded with Vagrant doesn't:

```
$ /opt/vagrant/embedded/bin/ruby --version
ruby 2.6.7p197 (2021-04-05 revision 67941) [x86_64-linux]
$ /opt/vagrant/embedded/bin/gem install json
ERROR:  Could not find a valid gem 'json' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: unexpected message (https://rubygems.org/specs.4.8.gz)
```

> I did see this attempted in the original issue description, but the --plugin-clean-sources was missing the s at the end. If it still does not work, please provide the debug out in a gist of the above command and I'll see what I can find there.

Good catch on the missing `s`, but it still doesn't work. [Here](https://gist.github.com/ndejay/31881e64eaf6c01a829c1a9ddb9f402b) is a link to the debug Gist.

I don't know if the following is useful, but I'm attaching it in case it is:

```
$ tree ~/.gem -L 3
/root/.gem
├── ruby
│   └── cache
│       └── io-console-0.5.9.gem
└── specs
    ├── gems.hashicorp.com%443
    ├── gems.hashicorp.com%80
    ├── rubygems.org%443
    │   ├── latest_specs.4.8
    │   ├── quick
    │   └── specs.4.8
    └── rubygems.org%80
        └── specs.4.8
```

Thanks again for your help,
Nicolas

**Comment by soapy1** [comment] 2021-06-18 22:52
Heya @ndejay I'm trying to reproduce this issue but I'm not having much success. Could you share what steps you took to install Vagrant. Additionally, could you share the debug output from the command you tried above `/opt/vagrant/embedded/bin/gem install json`.
Thanks!

**Comment by ndejay** [comment] 2021-06-20 11:42
Hey @soapy1,

Here are the steps I took to install Vagrant on CentOS 7:

```
$ yum update
$ yum install -y vim bind-utils epel-release tmux wget nc map git traceroute 
$ cd /etc/yum.repos.d
$ wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
$ yum --enablerepo=epel install dkms
$ yum install VirtualBox-6.1

$ yum install -y yum-utils
$ yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
$ yum -y install vagrant

$ yum -y install kernel-devel kernel-devel-3.10.0-1160.el7.x86_64
$ /sbin/vboxconfig
```

The output of `/opt/vagrant/embedded/bin/gem install json` can be found in this [Gist](https://gist.github.com/ndejay/cab17dd2f2b39025facb4efd9a33c1a8).

Thanks for looking into this!
Nicolas

**Comment by soapy1** [comment] 2021-06-21 16:09
I'm still unable to reproduce this issue. Taking a peek at the [Bundle docs for TLS/SSL issues](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html) it looks like there are some system level issues that might result in this kind of error. You might need to [update the system clock](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-system-clock). Or, maybe the [CA certs need to be updated](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-ca-certificates).

**Comment by chrisroberts** [comment] 2021-06-21 16:20
> If a network proxy were filtering the request, then wouldn't we expect wget and curl to fail as well?

Not necessarily. It depends on how the local system is configured. Vagrant ships with its own certificate bundle and if your system bundle includes a custom certificate for a filtering proxy, then Vagrant will not have that available and connections will fail. Can you run the gem install like this to test:

```
SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt /opt/vagrant/embedded/bin/gem install json
```

That environment variable will make the bundled Ruby use the cert bundle on your system, and not the bundle provided by Vagrant.

**Comment by ndejay** [comment] 2021-06-21 21:50
Thank you both @soapy1 @chrisroberts for your help and detailed explanations.

I was able to install the plugin with the following steps:

```
$ SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt /opt/vagrant/embedded/bin/gem install vagrant-vbguest
$ vagrant plugin list
No plugins installed.
$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Fetching micromachine-3.0.0.gem
Installed the plugin 'vagrant-vbguest (0.30.0)'!
```

I'm still stumped as to why neither of the following commands had worked in the first place (as I had described in the original post).  It's almost as if I couldn't get Vagrant to (1) detect `SSL_CERT_FILE` or (2) to pass it to the internal call to `gem install`, and needed to first pre-fetch the gem using `SSL_CERT_FILE=... gem install` so that `vagrant` could install it.

```
$ export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
$ vagrant plugin install vagrant-vbguest
```

```
$ SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt vagrant plugin install vagrant-vbguest
```

**Comment by chrisroberts** [comment] 2021-06-24 15:37
The original error was due to the failed connection to `gems.hashicorp.com`. That's my best guess for what is going on without being able to inspect the behavior on the local network you are working on. Internally Vagrant is using the RubyGems library (not the executable) for managing plugin installations, and Vagrant allows for custom cert files and ca bundles to be provided (https://github.com/hashicorp/vagrant-installers/blob/main/substrate/launcher/main.go#L181). Exporting them should allow things to work correctly, and likely you'll also need to clear the plugin sources and only include rubygems (unless the hashicorp gemstore can be included in the network's allow list).

Since you've got the plugin installed, I'm going to go ahead and close this up.

Cheers!

**Closed by chrisroberts** 2021-06-24 15:37 UTC
Labels: bundler, waiting-reply
