### ISSUE TITLE
vagrant ssh -c <command> broken for Windows guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9479] opened 2018-02-17 00:39 UTC
I can `vagrant ssh` directly into a Command Prompt session for Windows boxes. However, when I try to run a one-off command like `vagrant ssh -c "echo howdy"`, Vagrant shows a bunch of blank lines and stalls. This stinks, because this makes it much harder to script commands to Windows guests.

When the tty is disabled with `vagrant ssh --no-tty -c "echo howdy"`, then this returns an error, complaining about a missing `bash` application. Vagrant knows that the guest OS is Windows, and correctly loads a Command Prompt shell for `vagrant ssh`. And yet `vagrant ssh --no-tty -c` defaults to bash shell for some reason, even though bash is absent from many operating systems. If anything, the shell should default to `sh` for `*nix` guest, and cmd.exe or powershell.exe for Windows guests.

### Vagrant version

Vagrant 2.0.1

### Host operating system

macOS High Sierra 10.13.3

### Guest operating system

Windows 10 Evaluation x86_64

### Vagrantfile template for packer

```ruby
Vagrant.configure("2") do |config|
  config.vm.communicator = "winrm"
  config.vm.synced_folder ".", "/cygdrive/c/vagrant", type: "rsync"
end
```

Packer source: https://github.com/mcandre/packer-templates/tree/0d1a203e20332a0ee56245f2b0ea7a91be8642ad/windows

### Expected behavior

When I run `vagrant ssh -c "echo howdy"`, then the Windows box yields output like `howdy`.

### Actual behavior

```
$ vagrant ssh -c "echo howdy"
















(prints a bunch of blank lines and then stalls)
(does not respond to Control+C, Control+D, etc. to kill)
(requires intercession with Activity Monitor, closing terminal tab, etc.)
```

And with tty disabled:

```
$ vagrant ssh --no-tty -c "echo howdy"
'bash' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to reproduce

1. Clone mcandre/packer-templates.
2. Checkout the `windows` branch.
3. `cd windows`, pack the Windows box.
4. Import the Windows box.
5. `cd test && vagrant up`
6. Test out different `vagrant ssh -c` invocations.

Does anyone know of a good `Vagrantfile` configuration to fix `vagrant ssh -c` for Windows guests? Since `vagrant ssh` launches Command Prompt, ideally `vagrant ssh -c <command>` also evaluates commands in Command Prompt interpreter as well.

### Workaround

One workaround is to install bash, which has around six installation candidates, between Git Bash, cygwin bash, MSYS bash, MinGW bash, and bash on Ubuntu on Windows AKA the Windows Linux Subsystem. These are necessary for some environments, but for a basic Windows VM, I should think that this is not necessary, especially since a `vagrant ssh` REPL appears to basically work.

Another potential workaround would involve carefully sending appropriate characters to `vagrant ssh`, such as with an `expect` script. This is not trivial, and requires the host to have the `expect` tool installed. More preferably would be for `vagrant ssh -c` to work out of the box for Windows guests.

**Comment by mcandre** [comment] 2018-02-17 20:26
Addressing this with https://github.com/hashicorp/vagrant/pull/9483

I'm having a hard time building Vagrant from source, but if other users find this patch useful, then I'd love to test a new release with this included, hopefully fixing a bunch of oddities with Windows guests!

**Comment by mloskot** [comment] 2023-05-22 11:05
It's been almost five years and the Vagrant bug is still there, apparently, as the semantic of `vagrant ssh -c <cmd>` gets broken for every Windows box with installed OpenSSH due to the `bash -l` being hard-wired.

Having no `config.ssh.shell` in Vagrantfile, I've tried `vagrant --debug ssh -c dir`, here are the logs showing `bash -l`

1. [vagrant-ssh-bug-with-defaultshell-powershell.txt](https://github.com/hashicorp/vagrant/files/11530244/vagrant-ssh-bug-with-defaultshell-powershell.txt) with  `New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force`
2. [vagrant-ssh-bug-without-defaultshell.txt](https://github.com/hashicorp/vagrant/files/11530250/vagrant-ssh-bug-without-defaultshell.txt) without `DefaultShell` property

The only way to get the `vagrant ssh` execute a (simple!) command is https://github.com/hashicorp/vagrant/pull/9483#issuecomment-367410236 which is not a solution https://github.com/hashicorp/vagrant/pull/9483#issuecomment-368198472

**Comment by chrisroberts** [comment] 2023-06-15 22:52
@mloskot Hi there!

Thanks for surfacing this again. The issue being described here has been resolved (which is why I'm going to close this issue), but I wanted to know why you were running into the same sort of issue. I ran through how the command is getting built and then executed and think I see where the problem is surfacing. The shell gets assigned [here](https://github.com/hashicorp/vagrant/blob/main/lib/vagrant/action/builtin/ssh_run.rb#L40-L56). Vagrant will use the Vagrantfile configuration [`ssh.shell`](https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings#config-ssh-shell) value by default. If the communicator is configured to use winssh, then it will use the [`winssh.shell`](https://developer.hashicorp.com/vagrant/docs/vagrantfile/winssh_settings#config-winssh-shell). 

Now, this works fine _if_ your communicator is configured for winssh. However, if it's using winrm, then it will just use the `ssh.shell` value which will be `bash -l`. This can be addressed by setting the `ssh.shell` value to cmd or powershell:

```ruby
Vagrant.configure("2") do |config|
  ...
  config.ssh.shell = "cmd.exe"
  ...
end
```

I'm going to look at how this can be surfaced better in the documentation so that it's more obvious. Changing the behavior, unfortunately, isn't really viable. Even if we checked that the guest was Windows, swapping over to the `winssh.shell` configuration value would likely cause issues where users were running OpenSSH on Windows provided by msys2. So in this case, the best option is to just adjust the `ssh.shell` value to what you need for the guest.

I'm going to close this issue, but if you run into issues or still feel there's a bug here, please feel free to open a new issue and we can look into it further.

Cheers!

**Closed by chrisroberts** 2023-06-15 22:52 UTC
Labels: enhancement, guest/windows

**Comment by mloskot** [comment] 2023-06-29 16:05
@chrisroberts Thank you for the detailed answer and apologies for late response. I had to switch to other topics, but I should be able to give detailed update soon.
