### ISSUE TITLE
Vagrant 2.3.4 fails with VirtualBox 7.0.8r156879 when Virtuabox has any virtual machine whose name has non ASCII characters

### ISSUE THREAD

**Issue by javierpuche** [hashicorp/vagrant#13148] opened 2023-05-12 05:45 UTC
### Debug output
https://gist.github.com/javierpuche/0719d035f911a9b8c4266e4a4bb1f8d7

### Expected behavior
Vagrant should continue renaming VirtualBox machine and do not abort

### Actual behavior
Vagrant creates box and imports in VirtualBox with a name alike box_1683869871460_75571 and then breaks with this error:
The VM import failed! Try running `VBoxManage import` on the box file
manually for more verbose error output.

#### Vagrant version
Vagrant 2.3.4
VirtualBox 7.0.8r156879 

#### Host operating system
Linux Mint 21.1 (Ubuntu 22.04 based) but I guess this is not the issue

#### Guest operating system
any

#### Steps to reproduce
1.- VBoxManage createvm  --name="Programación"  --register
2- vagrant init “debian/bullseye64”
3.- vagrant up

Changing other virtual machines' names in VirtualBox to avoid any non-ASCII character solves the issue.

**Comment by chrisroberts** [comment] 2023-05-18 19:47
Hi there,

I believe this issue has been resolved in #13160, and I'm unable to reproduce the behavior with that changeset applied. [This development build](https://github.com/hashicorp/vagrant/releases/tag/2.3.6.dev%2B5009580690-66edc80) includes that pull request. If it's possible for you to confirm that this build resolves your issue it would be greatly appreciated. Thanks!

**Comment by javierpuche** [comment] 2023-05-20 07:33
Yes, I confirm it works fine with that devolopment build. Issue fixed.
Thanks a lot. Let's hope it will be soon in the production
repositories.

**Comment by chrisroberts** [comment] 2023-05-22 20:30
Closing as the underlying issue has been fixed. This is included in the current 2.3.6 release. Thank you for the report!

**Closed by chrisroberts** 2023-05-22 20:30 UTC
Labels: waiting-reply, provider/virtualbox, encoding
