### ISSUE TITLE
Git commands not working without sudo in vagrant machine

### ISSUE THREAD

**Issue by KakarN** [hashicorp/vagrant#11282] opened 2019-12-23 14:42 UTC
I have a project on my vagrant machine that I would like to push into my github repository. But I cannot add objects without using `sudo`.

I have initialized git
```
vagrant@vagrant:/vagrant/testDir$ git init
Initialized empty Git repository in /vagrant/testDir/.git/`
```
After that if I run the command to add contents
```vagrant@vagrant:/vagrant/testDir$ git add .```
Then I am getting this error:

> error: insufficient permission for adding an object to repository database .git/objects
> error: file1: failed to insert into database
> error: unable to index file file1
> fatal: adding files failed

Although I can run the command without any errors if I run with `sudo`, i.e., `sudo git add .`.

I have confirmed the permission inside the project, and they are are okay:

```
vagrant@vagrant:/vagrant/testDir$ ls -al
total 0
drwxr-xr-x 1 vagrant vagrant 160 Dec 23 10:33 .
drwxr-xr-x 1 vagrant vagrant 160 Dec 23 10:33 ..
drwxr-xr-x 1 vagrant vagrant 352 Dec 23 10:33 .git
-rw-r--r-- 1 vagrant vagrant   0 Dec 23 10:33 file1
-rw-r--r-- 1 vagrant vagrant   0 Dec 23 10:33 file2.txt
```

Also, the permission on `.git/` directory are fine

```
vagrant@vagrant:/vagrant/testDir/.git$ ls -al
total 12
drwxr-xr-x 1 vagrant vagrant 320 Dec 23 10:52 .
drwxr-xr-x 1 vagrant vagrant 160 Dec 23 04:12 ..
-rw-r--r-- 1 vagrant vagrant  23 Dec 23 04:12 HEAD
drwxr-xr-x 1 vagrant vagrant  64 Dec 23 04:12 branches
-rw-r--r-- 1 vagrant vagrant 111 Dec 23 04:12 config
-rw-r--r-- 1 vagrant vagrant  73 Dec 23 04:12 description
drwxr-xr-x 1 vagrant vagrant 416 Dec 23 04:12 hooks
drwxr-xr-x 1 vagrant vagrant  96 Dec 23 04:12 info
drwxr-xr-x 1 vagrant vagrant 160 Dec 23 04:12 objects
drwxr-xr-x 1 vagrant vagrant 128 Dec 23 04:12 refs
```
Even the permission inside the `.git/objects` directory are also okay.

```
vagrant@vagrant:/vagrant/testDir/.git/objects$ ls -al
total 0
drwxr-xr-x 1 vagrant vagrant 160 Dec 23 11:06 .
drwxr-xr-x 1 vagrant vagrant 320 Dec 23 11:06 ..
drwxr-xr-x 1 vagrant vagrant  96 Dec 23 11:06 e6
drwxr-xr-x 1 vagrant vagrant  64 Dec 23 11:06 info
drwxr-xr-x 1 vagrant vagrant  64 Dec 23 11:06 pack
```

I have ubuntu 18.04 on my vagrant machine running on macOS High Sierra. 
Vagrant = 2.2.2
Virtual box = 6.0.8 r130520

Could you please help me out?

**Comment by dragetd** [comment] 2020-01-06 16:20
vagrant is the tool for spinning up the virtual machines. What is actually running inside the virtual machine is completely out of scope of vagrant.

You obviously have a permission issue that you can fix like any other permission issue by adjusting the permissions of the directory.

-> Should be closed.

**Comment by jbonhag** [comment] 2020-01-06 16:21
Hi there,

Sorry to hear that you're having an issue with Vagrant!  I couldn't reproduce this issue on the latest version of Vagrant (2.2.6) with the following Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider :virtualbox
end
```

In general, if you're using synced folders with VirtualBox we recommend using a guest VM with the VirtualBox guest additions installed (like `bento/ubuntu-18.04`).

I'm going to close this issue as it does not appear to be reproducible on the latest version of Vagrant.  Feel free to re-open it if it's still an issue for you after upgrading.

Cheers! 😄

**Closed by jbonhag** 2020-01-06 16:21 UTC

**Comment by KakarN** [comment] 2020-01-10 07:11
These are the steps I took to solve my problem:

1. I downgraded the virtualbox on my macOS from 6.0.8 r130520 to 6.0.4 r128413.
2. Installed vagrant-vbguest plugin

`$ vagrant plugin install vagrant-vbguest
`
3. Reload the vagrant machine.

```
user@MacBook-Pro vagrant-project-machine $ vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'bento/ubuntu-18.04' is up to date...
...
...
==> default: Machine booted and ready!
...
[default] GuestAdditions versions on your host (6.0.4) and guest (6.0.8) do not match.
...
...
The following additional packages will be installed:
  linux-headers-4.15.0-51
...
...
```

Finally you can confirm it by running this command:

```
user@MacBook-Pro vagrant-project-machine $ vagrant vbguest --status
...
...
[default] GuestAdditions 6.0.4 running --- OK.
```
You can also confirm inside the vagrant machine by running this command:

```
vagrant@vagrant:/vagrant/testDir$ modinfo vboxguest
filename:       /lib/modules/4.15.0-51-generic/misc/vboxguest.ko
version:        6.0.4 r128413
license:        GPL
description:    Oracle VM VirtualBox Guest Additions for Linux Module
author:         Oracle Corporation
srcversion:     95F53B9B95BC6E03156A1D8
alias:          pci:v000080EEd0000CAFEsv00000000sd00000000bc*sc*i*
depends:        
retpoline:      Y
name:           vboxguest
vermagic:       4.15.0-51-generic SMP mod_unload 
```

Now I can run the git commands without using `sudo`.
