### ISSUE TITLE
[Improvement] Support .env file natively so VAGRANT_DOTFILE_PATH can be set per vagrantfile directory

### ISSUE THREAD

**Issue by Yivan** [hashicorp/vagrant#11246] opened 2019-12-10 20:53 UTC
Hello,

This issue is to submit a combined improvement.

Actually we are struggling because of the .vagrant folder being nested inside the same directory of the Vagrantfile.
This pose a problem because:

- We don't want metadatas in this directory, because the directory is hard to move/delete/reinstall if needed.
A classic case is "git clone my-repo-with-vargantfile && vagrant up"
Hyper create the VM harddrive in .vagrant in the same folder. And this is hard to move or rename the folder after (or even delete to reclone the repo) because you need to move the VM harddrive manually and hyperv, etc...
So purpose is to be able to set VAGRANT_DOTFILE_PATH for this project in another place and only this one.
Because we cannot ask to an user to change all its systemwide .vagrant directory by setting manually VAGRANT_DOTFILE_PATH (will impact already existing projects).

- It lead us to the second combined improvement: having a `.env` file (like docker do it and many others) at the same level of the Vagrantfile which could be parsed and injected in environment before vagrant begin to process the Vagrantfile.

This way we could set VAGRANT_DOTFILE_PATH properly by project, without any dirty hacks (see: https://github.com/hashicorp/vagrant/issues/3705).

In the same times, it would allow to make proper env initialisation instead those form of hacks in the Vagrantfile:

```
if File.file?('.env')
	open('.env', 'r').readlines.each {|l| kv = l.split('='); ENV[kv[0]] = kv[1];}
end
vm_memory = ENV["VM_MEMORY"] || "4096"
```

I don't think it is difficult to implement, just parse the .env and inject the variables before parsing the Vagrantfile. Maybe I am wrong but seems a small modification (without any BC break) and which will make so more flexible vagrant ! Really a good improvement for many users. It will improve distribution of vagrantfile from repo, configurable at the user needs without touching the Vagrantfile.

---

For those waiting for this, actully we resolve the problem of the VAGRANT_DOTFILE_PATH with a shell alias command which do:
```
alias vagrant="my_vagrant"
```

And my_vagrant do:
```
if [ (here we parse vagrantfile of the current directory to extract, VAGRANT_DOTFILE_PATH defined somewhere) ]; then
    VAGRANT_DOTFILE_PATH=value_extracted vagrant "$@"
fi
```

This is a always a hack, but I think it is better than https://github.com/hashicorp/vagrant/issues/3705 as it prevent double initialization (making vagrant ssh slow for instance and problem with git bash, see details here please: https://github.com/hashicorp/vagrant/issues/3705#issuecomment-564254997). And work with Git Bash on Windows.

Thanks for reading me

**Comment by chrisroberts** [comment] 2019-12-12 16:03
Duplicate of #11110 (https://github.com/hashicorp/vagrant/issues/11110#issuecomment-540033452)

**Closed by chrisroberts** 2019-12-12 16:03 UTC

**Comment by Yivan** [comment] 2019-12-12 17:08
@chrisroberts Thanks a lot for your return.

I was thinking it was a good and simple way to improve greatly vagrant, but maybe it is a strategic choice or difficult to implement.
I hope really one day it will be implemented natively. I will go on comment on https://github.com/hashicorp/vagrant/issues/3705 so.
Best regards.
