### ISSUE TITLE
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

### ISSUE THREAD

**Issue by atulanandnitt** [hashicorp/vagrant#9831] opened 2018-05-12 02:51 UTC
### Vagrant version
vagrant 2.1.1

### Host operating system
This is the operating system that you run locally.

### Guest operating system
I have used this cmd to get guest OS.
git clone https://github.com/oracle/vagrant-boxes

### Expected behavior
once this cmd is executed:
 $ vagrant ssh
It should go fine.

### Actual behavior
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

### Steps to reproduce
1. install windows 7 as host OS.
2   cd  /vagrant-boxes/Kubernetes (master)
3: execute :    vagrant up master
Bringing machine 'master' up with 'virtualbox' provider...
==> master: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> master: flag to force provisioning. Provisioners marked to run always will still run.

main Issue
step4: $ vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

### References
similar to issue: https://github.com/hashicorp/vagrant/issues/9433.
Only difference is I am using Windows 7 as host instead of win10 in that issue.

**Comment by leem32** [comment] 2018-05-12 19:33
I had the same issue on a Windows 7 Host every time I tried to `vagrant ssh`. For me the problem was caused by `openssh` installed on the host. Once I uninstalled  I could `vagrant ssh` no problem. I didn't figue out how to get it working along with `openssh` though because I didn't need it anymore anyway.

**Comment by atulanandnitt** [comment] 2018-05-13 01:32
But I dont have openssh installed.What may be the reason of error in my case ?

Note: I have PuTTy and TigerVNC installed.

**Comment by chrisroberts** [comment] 2018-05-15 14:45
Would you please provide a gist of the debug output. Thanks.

```
vagrant ssh --debug
```

**Comment by JuPlutonic** [comment] 2018-06-01 16:37
Win7ProSP1 x64 Vagrant 2.1.1
Problems was always pursued me with newly initiated **ununtu/xenial64** and when I tried some tricks: 
```In VM box I did:
 pasted raw from https://github.com/mitchellh/vagrant/tree/master/keys
vagrant.pub into /home/vagrant/.ssh/authorized_sites (created with **touch**)
chmod 700 /home/vagrant/.ssh/
chmod 600 /home/vagrant/.ssh/authorized_keys
chown -R vagrant: /home/vagrant/.ssh```
output of vagrant ssh -debug:
[1.txt](https://github.com/hashicorp/vagrant/files/2063448/1.txt)
output of  ssh-config
```
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile F:/pyth/dockercompose_heating-analyser/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```
[Vagrantfile.txt](https://github.com/hashicorp/vagrant/files/2063452/Vagrantfile.txt)
[ubuntu-xenial-16.04-cloudimg-console.log](https://github.com/hashicorp/vagrant/files/2063453/ubuntu-xenial-16.04-cloudimg-console.log)

**Comment by JuPlutonic** [comment] 2018-06-04 11:00
icacls F:/pyth/dockercompose_heating-analyser/.vagrant/machines/default/virtualbox/private_key 
```(I)(F) for ALL```

**Comment by JuPlutonic** [comment] 2018-06-04 13:51
vagrant ssh -- -vvv gives better information
RE @atulanandnitt Note: I have PuTTy and TigerVNC installed.
prereq.: use private_key.ppk generated by PUTTYGEN
steps: 1)delete private_key file from VAGRANT_FILE_PLACED_IN_DIRECTORY\.vagrant\blah\blah\blah\
2) change Vagrantfile delete all lines except one ssh related record: `config.ssh.insert_key = false`
if you have `vm.synced_folder  "PATH_DOT_SSH", "/home/vagrant/.ssh"` don't remove this line
3)open Ora...VirtualBox in list of VMs right click on the machine and choose **Show** login vagrant password vagrant
4) next you should write this:
`curl https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub > ~/.ssh/authorized_keys`
[Enter]? then right click to get out from VM
5. Finally restart VM, and you cat use puuty to login over ssh

**Comment by JuPlutonic** [comment] 2018-06-04 14:36
I had the same environment and sitation/bug. I think it happend (`Permission denied (publickey)`) because of `config.vm.synced_folder "/../root_projects/.ssh", "/home/vagrant/.ssh"`. After I long way of chmoding chowning and in changing rights in Win7 (adding only Adimistrators and my user, using icacls as ls -l analog) I found what actionally it seems to be **synced_folders** bug.

**Comment by John3** [comment] 2018-08-06 22:49
Hi! win10 has include a ssh client. You just need to remove it from "apps and features => Optional features". I not see this as a real issue from vagrant.

**Comment by chrisroberts** [comment] 2018-10-22 17:41
Generated private key permissions should be fixed in the latest Vagrant release (updated in 2.1.2). You can also tell vagrant to prefer the embedded tools using an environment variable:

https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_prefer_system_bin

Cheers!

**Closed by chrisroberts** 2018-10-22 17:41 UTC
Labels: communicator/ssh, waiting-reply

**Comment by dvgamerr** [comment] 2018-11-26 04:44
> Hi! win10 has include a ssh client. You just need to remove it from "apps and features => Optional features". I not see this as a real issue from vagrant.

Where is "apps and features => Optional features"???

**Comment by munkiepus** [comment] 2018-11-28 12:08
If you're on windows 10 powershell. Just set the environment variable like this:
` $Env:VAGRANT_PREFER_SYSTEM_BIN += 0`
This will tell vagrant to use the builtin vagrant ssh rather than using C:\\WINDOWS\\System32\\OpenSSH\\/ssh.EXE

**Comment by emayssat** [comment] 2019-09-10 17:08
What is probably happening is that you cannot ssh in the box because you deleted the vagrant entry ~/.ssh/authorized_keys for the vagrant used in the vagrant box.
On your host, the private_key you use (vagrant ssh --debug) should have the corresponding public key in the authorized_keys in the vagrant box.

So if somehow you still have a session open, modify the authorized_key accordingly (or cut and past a private key from vagrant box to host)
