### ISSUE TITLE
  // , Logic Error: A Mistake in shell Provisioning path prevents vagrant destroy -f

### ISSUE THREAD

**Issue by v6** [hashicorp/vagrant#10010] opened 2018-07-11 22:01 UTC
### Vagrant version
```
$ vagrant -v
Vagrant 2.1.2
```

### Host operating system
Ubuntu 16.04

### Guest operating system
bento/centos-7.5

### Vagrantfile
```ruby
$ cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  ##  Note: can be used with either VMWare or Virtualbox
  ##  This example uses three boxes. instance5, instance6, and instance7. 
    (5..7).each do |i|
        config.vm.define "instance#{i}" do |server|
              ##  consul-replicate is optional.
            server.vm.box = "bento/centos-7.5"
            server.vm.box_version = "201805.15.0"
            server.vm.hostname = "instance#{i}"
            server.vm.network :private_network, ip: "192.168.13.3#{i}"
            server.vm.provision "shell", path: "account.sh", args: "vault"
            server.vm.provision "shell", path: "account.sh", args: "consul"
            server.vm.provision "shell", path: "account.sh", args: "consul-replicate"
            server.vm.provision "shell", path: "prereqs.sh"
            server.vm.provision "shell", path: "consulsystemd.sh"
            server.vm.provision "shell", path: "vaultsystemd.sh"
            server.vm.provision "shell", path: "consuldownload.sh"
            server.vm.provision "shell", path: "configureconsul.sh"
            server.vm.provision "shell", path: "vaultdownload.sh", args: "0.10.3"
            server.vm.provision "shell", path: "configurevault.sh"
            server.vm.provision "shell", path: "demonstrations/consul-replicatedownload.sh", args: "0.4.0"
            server.vm.provision "shell", inline: "sudo systemctl enable consul.service"
            server.vm.provision "shell", inline: "sudo systemctl start consul"
            server.vm.provision "shell", inline: "sudo systemctl enable vault.service"
            server.vm.provision "shell", inline: "sudo systemctl start vault"
        end
    end

  ##  I have added a variable here in case you want to try out Vault's
  ##  DB Secret backend.
  ##  It's false by default.
  ##  If set to true, Vagrant will add a machine called db when you run vagrant up.
  db = true

  if db == true
    config.vm.define "db" do |db|
          ##  Setup VM for Secret Engine testing:
          ##  https://www.vaultproject.io/docs/secrets/databases/index.html
          ##  
        db.vm.box = "bento/centos-7.5"
        db.vm.box_version = "201805.15.0"
        db.vm.hostname = "db"
        db.vm.network :private_network, ip: "192.168.133.7"
          ##  Install and run DB
        db.vm.provision "shell", path: "account.sh", args: "mariadb"
        db.vm.provision "shell", path: "prereqs.sh"
        db.vm.provision "shell", path: "mariadb.sh", args: ["errydayimSHUFFLIN", "true", "false"]
        db.vm.provision "shell", inline: "sudo systemctl enable mariadb.service"
        db.vm.provision "shell", inline: "sudo systemctl start mariadb"
    end
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output
https://gist.github.com/v6/b1b727248f5a116ebfcf4c93f5745c50

### Expected behavior
```bash
$ vagrant destroy -f
==> db: Destroying VM and associated drives...
==> instance7: Destroying VM and associated drives...
==> instance6: Destroying VM and associated drives...
==> instance5: Destroying VM and associated drives...
```

Vagrant destroy -f does not usually need to know whether a box was provisioned correctly to destroy it, right? 

Especially since incorrect provisioning may be the reason to destroy the box in the first place.

Anyway, this might be a "it's not a bug it's a feature" type of situation if Vagrant is doing this sort of check by design, or if it's to prevent other behavior. Still, it seemed strange enough to me to be worth a bug report.

### Actual behavior
```bash
$ vagrant destroy -f
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* `path` for shell provisioner does not exist on the host system: /home/nb/proj/vault/hashicorpcert/super-duper-vault-train/mariadb.sh
```

### Steps to reproduce
1. Create a Vagrant box, and start it up
2. Introduce an error into its provisioning definition that does not affect how it is destroyed
3. Attempt vagrant destroy -f

**Comment by briancain** [comment] 2018-07-12 16:29
Hi there @v6 - what you are seeing is not a message about a guest being provisioned, but a Vagrantfile validation error. Before Vagrant runs any commands or actions, it first validates your Vagrantfile and checks for any errors. In this case, a path `"mariadb.sh"` does not exist locally on your host for your defined shell provisioner and Vagrant sees this as an invalid configuration and exits.

This might seem a little strange when running the `destroy` command since you probably don't care that it exists just to destroy a guest, but that's what is going on.

This can either be fixed by making sure the paths you have defined for your shell provisioners exist, or you can comment out the shell provisioner if it's not in use and the script doesn't exist locally.

Hopefully that makes senes! I'm going to go ahead and close this issue since this is expected behavior, but if you have any more questions or suggestions feel free to ask it here or on the mailing list. Thanks!

**Closed by briancain** 2018-07-12 16:29 UTC

**Comment by v6** [comment] 2018-07-13 20:45
// , 

> This might seem a little strange when running the destroy command since you probably don't care that it exists just to destroy a guest, but that's what is going on.

Yeah, I knew that was what's going on. Why is that the expected behavior, though? 

I'll move this to the mailing list.
