### ISSUE TITLE
Cant get VM (Hyper-V) up on Windows 10. Stuck on vagrant up

### ISSUE THREAD

**Issue by Prale** [hashicorp/vagrant#9414] opened 2018-01-30 08:58 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.01

### Host operating system
Windows 10

### Vagrantfile
$ vagrant up
Bringing machine 'homestead-7' up with 'hyperv' provider...
==> homestead-7: Verifying Hyper-V is enabled...
==> homestead-7: Importing a Hyper-V instance
    homestead-7: Please choose a switch to attach to your Hyper-V instance.
    homestead-7: If none of these are appropriate, please open the Hyper-V manager
    homestead-7: to create a new virtual switch.
    homestead-7:
    homestead-7: 1) Internal Switch
    homestead-7: 2) New External Switch
    homestead-7:
    homestead-7: What switch would you like to use? 1
    homestead-7: Cloning virtual hard drive...
    homestead-7: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Compare-VM : Failed to import a virtual machine.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.1\plugins\providers\hyperv\scripts\impo rt_vm_vmcx.ps1:33 char:14
+ $vmConfig = (Compare-VM -Copy -GenerateNewID @VmProperties)
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM

### Expected behavior
Virtual machine should have started

### Actual behavior
The above error

### Steps to reproduce
vagrant up

### References
None to my knowledge

**Comment by briancain** [comment] 2018-01-30 17:56
Closing this because it seems to be a duplicate of #9317. Thanks!

**Closed by briancain** 2018-01-30 17:56 UTC
