### ISSUE TITLE
debug1: key_load_public: No such file or directory

### ISSUE THREAD

**Issue by sharanraj124** [hashicorp/vagrant#12087] opened 2020-11-30 08:23 UTC
Hi, I try to up my vagrant today I faced below issue. past 6 months vagrant is working fine but why this problems hapen, could you please help me for solve. I search most of links but anything not helping solve the issue.

```
○ → vagrant ssh -- -vvv
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/apple/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "127.0.0.1" port 2222
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2222.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /Users/apple/development/tools/vagrant/ubuntu-18/.vagrant/machines/default/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/apple/development/tools/vagrant/ubuntu-18/.vagrant/machines/default/virtualbox/private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
ssh_exchange_identification: Connection closed by remote host
```

**Comment by chrisroberts** [comment] 2021-02-04 16:41
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by soapy1** [comment] 2023-02-28 00:14
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by soapy1** 2023-02-28 00:14 UTC
Labels: needs info, waiting-reply, needs-debug-gist
