### ISSUE TITLE
vagrant plugin failed when download plugins

### ISSUE THREAD

**Issue by evopen** [hashicorp/vagrant#10373] opened 2018-11-05 13:56 UTC
### Vagrant version
Vagrant 2.2.0

### Host operating system
Manjaro Linux

### Expected behavior
What should have happened?
vagrant download plugins successfully

### Actual behavior
What actually happened?
vagrant stuck at downloading.

**Comment by briancain** [comment] 2018-11-05 17:02
Hi @evopen - You need to export them as environment variables:

```bash
export http_proxy='http://127.0.0.1:12333'
vagrant blah blah
```

If that doesn't work feel free to comment with a full debug log using `--debug` and we can take another look. Thanks!

**Comment by evopen** [comment] 2018-11-05 17:12
@briancain hello.
The log is here.
[https://gist.github.com/evopen/d75660d59784b26356a2fee9945899ea](vagrant log)

`⋊> ~ env | grep 'proxy\|PROXY'                                                                                                         01:05:17
FTP_PROXY=http://127.0.0.1:12333                                                                                                              
HTTPS_PROXY=http://127.0.0.1:12333                                                                                                            
HTTP_PROXY=http://127.0.0.1:12333                                                                                                             
ftp_proxy=http://127.0.0.1:12333                                                                                                              
http_proxy=http://127.0.0.1:12333                                                                                                             
https_proxy=http://127.0.0.1:12333`

and the variable are exported
and my wget is working through the proxy
`
![image](https://user-images.githubusercontent.com/1773234/48014115-ee8b0b80-e160-11e8-80e4-180558b038a8.png)
`

**Comment by evopen** [comment] 2018-11-06 06:20
@briancain 
Sorry, I made a mistake. Vagrant plugin does use my proxy to download plugin. It just failed.
Here's my [log](https://gist.github.com/evopen/d75660d59784b26356a2fee9945899ea).
I don't know why.

If I wget it.Wget finished downloading instantly.
![image](https://user-images.githubusercontent.com/1773234/48046348-11ec9f80-e1cf-11e8-96c1-1d15d12a69dd.png)

**Comment by evopen** [comment] 2018-11-06 07:30
I'm pretty sure it's connected to the proxy.
![image](https://user-images.githubusercontent.com/1773234/48049030-4d3f9c00-e1d8-11e8-8f6f-f329fc52eb1e.png)
This this the image after turning the proxy off.

And this is the last part of the log of command `env VAGRANT_LOG=info vagrant plugin install vagrant-libvirt`
` INFO cli: CLI: [] "plugin" ["install", "vagrant-libvirt"]                                                                                    
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/dhh/.vagrant.d/gems/2.5.3/cache>]                                      
 INFO host: Detected: arch!                                                                                                                   
 INFO runner: Preparing hooks for middleware sequence...                                                                                      
 INFO runner: 1 hooks defined.                                                                                                                
 INFO runner: Running action:  #<Vagrant::Action::Builder:0x0000556b47ba2900>                                                                 
 INFO warden: Calling IN action: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000556b479f1980>                                      
 INFO interface: info: Installing the 'vagrant-libvirt' plugin. This can take a few minutes...                                                
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...                                                                       
Building native extensions. This could take a while...                                                                                        
ERROR warden: Error occurred: Bundler, the underlying system Vagrant uses to install plugins,                                                 
reported an error. The error is shown below. These errors are usually                                                                         
caused by misconfigured plugin installations or transient network                                                                             
issues. The error from Bundler is:                                                                                                            
                                                                                                                                              
fatal error (https://api.rubygems.org/gems/ruby-libvirt-0.7.1.gem)                                                                            
 INFO warden: Beginning recovery process...                                                                                                   
 INFO warden: Calling recover: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000556b479f1980>                                        
 INFO warden: Recovery complete.                                                                                                              
 INFO environment: Running hook: environment_unload                                                                                           
 INFO runner: Preparing hooks for middleware sequence...                                                                                      
 INFO runner: 1 hooks defined.                                                                                                                
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000556b4bea3768>                                               
ERROR vagrant: Vagrant experienced an error! Details:                                                                                         
ERROR vagrant: #<Vagrant::Errors::BundlerError: Bundler, the underlying system Vagrant uses to install plugins,                               
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

fatal error (https://api.rubygems.org/gems/ruby-libvirt-0.7.1.gem)>
ERROR vagrant: Bundler, the underlying system Vagrant uses to install plugins,                                                                
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:


fatal error (https://api.rubygems.org/gems/ruby-libvirt-0.7.1.gem)
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:172:in `rescue in install_plugin'                  
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:116:in `install_plugin'                                           
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/plugins/commands/plugin/action/install_gem.rb:30:in `call'                                      
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'                                                       
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'                                                     
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'                                               
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'                                                           
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'                                                        
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/plugins/commands/plugin/command/base.rb:14:in `action'                                          
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/plugins/commands/plugin/command/install.rb:70:in `block in execute'                             
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/plugins/commands/plugin/command/install.rb:69:in `each'                                         
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/plugins/commands/plugin/command/install.rb:69:in `execute'                                      
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/plugins/commands/plugin/command/root.rb:66:in `execute'                                         
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/cli.rb:54:in `execute'                                                              
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/lib/vagrant/environment.rb:291:in `cli'                                                         
/opt/vagrant/embedded/gems/gems/vagrant-2.2.0/bin/vagrant:164:in `<main>'                                                                     
 INFO interface: error: Bundler, the underlying system Vagrant uses to install plugins,                                                       
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

fatal error (https://api.rubygems.org/gems/ruby-libvirt-0.7.1.gem)
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

fatal error (https://api.rubygems.org/gems/ruby-libvirt-0.7.1.gem)
 INFO interface: Machine: error-exit ["Vagrant::Errors::BundlerError", "Bundler, the underlying system Vagrant uses to install plugins,\nreport
ed an error. The error is shown below. These errors are usually\ncaused by misconfigured plugin installations or transient network\nissues. The
 error from Bundler is:\n\nfatal error (https://api.rubygems.org/gems/ruby-libvirt-0.7.1.gem)"] `

And when I manually download the gem using wget into gem cache folder I get:
![image](https://user-images.githubusercontent.com/1773234/48049221-ea9ad000-e1d8-11e8-84c3-70df7e6d5c2d.png)

**Comment by chrisroberts** [comment] 2018-11-06 15:36
@evopen I'm curious if there is an issue with the proxy you are using. In the output you have provided the errors are not consistent. It seems as though on the first request an error is being received, yet on the next request it succeeds. I'm basing this on the fact that when fetching the dependencies for installation, fog-xml will be fetched prior to ruby-libvirt and in the first error message we see it failing on fog-xml, but in the second it succeeds with it failing on ruby-libvirt.

I would suggest validating the configuration of the proxy you are using. If everything looks fine and you are still encountering errors, please provide information on the proxy you are using, and the configuration you have for the proxy. I'll see if I can repro the environment locally and spot the issue.

Cheers!

**Comment by evopen** [comment] 2018-11-07 02:40
I don't think my http proxy has any problem. The http proxy setting is in my .profile. I've been using it daily for years. It's converted from socks5 to http proxy using privoxy.
![image](https://user-images.githubusercontent.com/1773234/48107141-4fa60280-e279-11e8-81c0-646db217b53f.png)
This screenshot. Why bundler tried to download fog-xml-0.1.3.gem in the building phrase? Shouldn't all gems get downloaded in the `Fetching: ` part?

**Comment by chrisroberts** [comment] 2018-11-07 15:48
Vagrant uses RubyGems internally for managing plugins. RubyGems will fetch the gem, then install the gem, and proceed to the next. A simple way to validate if the proxy is causing the problem is to disable the proxy and see if you experience the same errors when connecting directly.

**Comment by evopen** [comment] 2018-11-07 15:55
@chrisroberts Yes I did. See the post above.
Porxy indeed works in fetching step, but failed in building step.

**Comment by chrisroberts** [comment] 2018-11-07 17:15
Okay, I assume the firewall is preventing you from accessing https://rubygems.org ? Can you please disable your proxy and try this command:

```
$ vagrant plugin install vagrant-libvirt --plugin-clear-sources --plugin-source https://gems.ruby-china.org
```

Thanks!

**Comment by evopen** [comment] 2018-11-08 10:39
No I didn't setup any firewall rule. You can see there are two posts downloading gems manually using wget from rubygems.org. Also I can access https://rubygems.org/ via browser.

Btw, using the command above I got error `bad response Not Found 404 (https://gems.ruby-china.org/specs.4.8.gz) `

**Comment by evopen** [comment] 2018-11-08 10:47
I think this issue is largely not a vagrant issue since the error happened in the ruby gem building process. 
How about we just drop it.

**Comment by chrisroberts** [comment] 2018-11-08 15:28
My mistake on the domain. It is `https://gems.ruby-china.com/`. Apologies, but I'll just close this issue per request.

Cheers!

**Closed by chrisroberts** 2018-11-08 15:28 UTC
Labels: waiting-reply
