### ISSUE TITLE
vagrant up does not work with windows 1909 and wsl on bento/centos

### ISSUE THREAD

**Issue by MichaBub** [hashicorp/vagrant#12085] opened 2020-11-30 07:51 UTC
### Vagrant version

Vagrant 2.2.14

### Host operating system

Win10 Pro, Build 1909

### Guest operating system

"bento/centos-7.8"

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.8"

  # config.vm.boot_timeout = 240

  config.proxy.http             = "http://10.0.2.2:3128"
  config.proxy.https            = "http://10.0.2.2:3128"
  config.proxy.no_proxy         = "localhost,127.0.0.1"

  config.vm.provider "virtualbox" do |v|
      v.name = "my_centos7_64"
      v.memory = 18000
      v.cpus = 8
      v.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = true
  
end
```

### Debug output

https://gist.github.com/MichaBub/56e0d9318377ec70ee769822fd70552e

### Expected behavior

Should start up

### Actual behavior

Hangs infinite and then aborts

### Steps to reproduce

1. vagrant up --debug

**Comment by soapy1** [comment] 2020-11-30 15:52
This seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/12081. In order to consolidate conversation to only one issue, I'm going to close this one as a duplicate.

**Closed by soapy1** 2020-11-30 15:52 UTC
