### ISSUE TITLE
SSH connection always errors out: Connection errored, not re-using. Will reconnect. <Timeout::Error: execution expired>

### ISSUE THREAD

**Issue by henrykuijpers** [hashicorp/vagrant#8772] opened 2017-07-11 20:19 UTC
### Vagrant version
Vagrant 1.9.6

### Host operating system
Windows 10 with latest updates

### Guest operating system
CentOS 7.2 (jhcook/centos7 v3.10.0.514.21.2)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search
    config.vm.box = "jhcook/centos7"
    config.vm.box_version = "3.10.0.514.21.2"
    config.vm.boot_timeout = 300000
    config.ssh.pty = true

    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
     config.vm.provision "shell", binary: true, inline: <<-SHELL
       rpm -ivh --replacepkgs http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
       yum -yt install puppet-3.8.7 wget screen policycoreutils-python
       puppet module install puppetlabs-stdlib
       puppet module install bstopp-aem
       puppet module install maestrodev-maven
       puppet module install puppetlabs-apache
       puppet module install puppetlabs-firewall
       puppet module install crayfishx/firewalld
       cp /usr/share/zoneinfo/Europe/Brussels /etc/localtime
     SHELL

    # Mount local mvn repo to expected location
    config.vm.synced_folder ".m2", "/opt/install_files/.m2", create: true

    config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "{CLIENT}/manifests"
      puppet.manifest_file = "sites.pp"
      puppet.module_path = [ "aem/modules", "{COMPANY}/modules","{CLIENT}/modules"]
      puppet.hiera_config_path = "{CLIENT}/manifests/hiera.yaml"
      puppet.options = "--parser future --verbose --debug"
      ## custom facts provided to Puppet
      ##puppet.facter = {
          ## tells puppet.manifest_file that we're running in Vagrant
        ##  "is_vagrant" => true,
      ##}
    end

    config.vm.define :aem do |aem|
      aem.vm.provider "virtualbox" do |vb|
        vb.name = "{CLIENT}"
        vb.gui = true
        vb.customize ["modifyvm", :id, "--memory", 8192]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
        #vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        #vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
      end
      aem.vm.hostname = "{CLIENT}.localhost.com"
	  # Any IP in the private IPv4 range https://www.arin.net/knowledge/address_filters.html
      aem.vm.network :private_network, ip: "10.1.1.20", :netmask => "255.255.255.0"
      
      aem.vm.network :forwarded_port, guest: 80, host: 80
    end


end
```

### Debug output
https://gist.github.com/henrykuijpers/d2f13b1e31f86c9de5fb30c626e2ecd5

### Expected behavior
I should be able to make normal SSH connections and reuse them, without them timing out all the time.

### Actual behavior
The SSH connections keep timing out and it keeps on creating new connections, creating immense slowdowns.

### Steps to reproduce
This only seems to happen on certain networks?

### References
This has been reported quite some times already. I never found a solution in all the issues / posts though.

**Comment by chrisroberts** [comment] 2018-04-24 23:38
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2018-04-24 23:38 UTC
Labels: communicator/winssh, host/windows

**Comment by ustm** [comment] 2018-09-05 08:16
hey! have you found the cause?
