### ISSUE TITLE
Embedded curl on Linux causes more problems than solves

### ISSUE THREAD

**Issue by laranzu** [hashicorp/vagrant#8966] opened 2017-09-13 01:44 UTC
Just spent two hours trying to figure out why 'vagrant up' didn't work. Eventually fixed by deleting /opt/vagrant/embedded/bin/curl to force vagrant to fall back to system version of curl.

Seriously, why is Vagrant shipping with its own version of curl on Linux? Apt/yum/dnf etc have dependency checkers for just this.

I'd even suggest that it isn't worth shipping your own on MacOS/MSWin either. People who want to use Vagrant have reasonable technical skills and know how to download and install stuff that isn't in an App Store.

### Vagrant version
Vagrant 1.9.7

### Host operating system
Ubuntu 16.04 - but same issue for other platforms

### Guest operating system
Irrelevant, because issue breaks Vagrant up

### Expected behavior"
Vagrant up with conv.vm.box = "nrclark/xenial64-minimal-libvirt" should download the box image.

### Actual behavior
Error: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### References
Are there any other GitHub issues (open or closed) that should be linked here?
A quick scan through the closed issues list shows curl being responsible for some of them. Any Google search for being unable to download box will return a long list of Mac/MSWin hits which were solved by deleting the Vagrant version of curl.

**Comment by chrisroberts** [comment] 2017-09-13 16:09
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by laranzu** [comment] 2017-09-13 23:39
Didn't make myself clear.

The bug is that Vagrant ships with its own version of curl. The fix is not to ship /opt/vagrant/embedded/bin/curl on Linux, and I would recommend not shipping an embedded curl on MacOS X or MS Windows either.

I provided host OS and Vagrant version. Guest info is irrelevant: it didn't matter what box I tried to download, it always failed. I could have provided a long list of debugging output but again it would be irrelevant: the problem occurs because Vagrant does not use the system version of curl. As soon as I deleted /opt/vagrant/embedded/bin/curl, Vagrant started working.

It's not something you can fix in code. My Google search for the error turned up similar incidents reported on StackOverflow, Laravel, and other forums; for MacOS X, MS Windows, and various Linux versions. They dated at least as far back as 2011, and the number one solution was deleting the curl that came with Vagrant.

If Vagrant uses the system curl, less code to maintain and package and an intermittent cross-platform problem that's been happening for at least six years goes away. (Or at least it won't be your fault.)

**Closed** 2017-09-14 07:29 UTC
Labels: waiting-reply

**Comment by kikitux** [comment] 2017-09-14 07:30
@laranzu if you can provide us with reproducible steps so we can check why our embedded curl is failing, we can review and work on make things better.

the tone in your updates is not very constructive, so we don't help you there

happy to help if you want us to help.

**Comment by raclepoulpe** [comment] 2017-09-25 09:51
Hi,
removing the "embedded curl" did the trick for me.
Ubuntu 16.04 (x64) - Vagrant 2.0.0
Just after a fresh install of Vagrant : 

```
$ vagrant up
 INFO dcos-vagrant: Validating Plugins...
 INFO dcos-vagrant: Validating User Config...
 INFO dcos-vagrant: Downloading DC/OS 1.10.0 Installer...
 INFO dcos-vagrant: Source: https://downloads.dcos.io/dcos/stable/1.10.0/commit/e38ab2aa282077c8eb7bf103c6fff7b0f08db1a4/dcos_generate_config.sh
 INFO dcos-vagrant: Destination: installers/dcos/dcos_generate_config-1.10.0.sh
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```
ps : The installed curl is preferred because behind a http proxy
```
$ cat ~/.vagrant.d/Vagrantfile 
Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://127.0.0.1:3128/"
    config.proxy.https    = "http://127.0.0.1:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end
  # ... other stuff
end
```

**Comment by mreali** [comment] 2017-09-27 16:53
I had the same problem. In my case the proposed solution of removing curl also worked. I suspect that it could be related to the fact that I'm accessing the Internet through a proxy server.
It would be desirable to take the suggestion of rethinking how the dependencies are distributed.

**Comment by yashrsharma44** [comment] 2017-10-11 07:52
Similar problem was faced by me. I am using my computer under my college proxy. I was getting the similar error. After removing the above curl file from the respective file, I was able to proceed. Thanks

**Comment by tstuber** [comment] 2017-10-19 09:01
We are also using a proxy service and faced the same issue. I tried every thinkable combination of parameters in vagrant, but nothing worked. In the end, renaming the `curl` file made it work!

**Comment by lalloni** [comment] 2017-11-21 16:35
Same problem here.

Solution of getting embedded curl out of the way worked as a charm.

**Comment by tlc** [comment] 2018-03-14 14:29
I'm also behind a corporate proxy.  These are the errors I'm seeing.

> $ vagrant init ubuntu/xenial64
> A `Vagrantfile` has been placed in this directory. You are now
> ready to `vagrant up` your first virtual environment! Please read
> the comments in the Vagrantfile as well as documentation on
> `vagrantup.com` for more information on using Vagrant.
> $ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'ubuntu/xenial64' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> The box 'ubuntu/xenial64' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Vagrant Cloud, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://vagrantcloud.com/ubuntu/xenial64"]
> Error: An unknown option was passed in to libcurl

> troy@potamus:~/VAGRANT/mycroft$ /opt/vagrant/bin/../emb*/bin/curl https://atlas.hashicorp.com
> curl: (48) An unknown option was passed in to libcurl

Removing the embedded curl worked. Thanks for the tip, OP!

**Comment by tlc** [comment] 2018-03-14 14:46
If I put _/opt/vagrant/embedded/lib_ in my LD_LIBRARY_PATH

> $ /opt/vagrant/bin/../emb*/bin/curl.old https://atlas.hashicorp.com
> <html><body>You are being <a href="https://app.terraform.io/">redirected</a>.</body></html>
> 

instead of the error above.  I suspect that vagrant should be setting LD_LIBRARY_PATH when it uses its embedded curl.
