### ISSUE TITLE
Issue installing plugins.

### ISSUE THREAD

**Issue by corporealsoul** [hashicorp/vagrant#13530] opened 2024-11-03 17:47 UTC
PS D:\GITRepos\Aleph-vitatha-Research-Lab\YEAR2024\Automation-Lab\Vagrant>  vagrant plugin install vagrant-vmware-desktop
Installing the 'vagrant-vmware-desktop' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0

**Comment by efussi** [comment] 2024-11-03 20:33
Seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/13527

**Comment by chrisroberts** [comment] 2024-11-04 17:28
Closing as duplicate of #13527

**Closed by chrisroberts** 2024-11-04 17:28 UTC
Labels: waiting-intake
