### ISSUE TITLE
Occasional freeze on Configuring network interfaces

### ISSUE THREAD

**Issue by marek-obuchowicz** [hashicorp/vagrant#10316] opened 2018-10-18 16:32 UTC
### Vagrant version
`v2.1.2` - `2.2.0`

### Provider
VirtualBox 5.2.20r125813

### Host operating system
Mac OS X 10.14

### Guest operating system
Debian Linux 9, 64-bit

### Vagrantfile
```ruby
VM_IP='10.10.0.191'
VM_PROJECT='suite-nonsplit'
VM_MEMORY='3200'
VM_CPUS='4'
VM_NAME='Spryker Dev VM (suite-nonsplit)'

Vagrant.configure("2") do |config|
config.vm.box = "debian95_15"
  config.vm.box_url = "debian95.box"
  config.vm.hostname = "vm-#{VM_PROJECT}"
  config.vm.boot_timeout = 300

  # Enable SSH agent forwarding
  config.ssh.forward_agent = true

  # Set the VirtualBox IP address for the browser
  config.vm.network :private_network, ip: VM_IP, nic_type: "virtio"

  # Port forwarding for services running on the VM
  config.vm.network "forwarded_port", guest: 1080,  host: 1080,  auto_correct: true
  config.vm.network "forwarded_port", guest: 3306,  host: 3306,  auto_correct: true
  config.vm.network "forwarded_port", guest: 5432,  host: 5432,  auto_correct: true
  config.vm.network "forwarded_port", guest: 5601,  host: 5601,  auto_correct: true
  config.vm.network "forwarded_port", guest: 10007, host: 10007, auto_correct: true

  # Configure VirtualBox VM resources (CPU and memory)
  config.vm.provider :virtualbox do |vb|
    vb.name = VM_NAME
    vb.customize([
      "modifyvm", :id,
      "--memory", VM_MEMORY,
      "--cpus", VM_CPUS,
      "--nictype1", "virtio",
      "--nictype2", "virtio",
    ])
end
```

note: it's extract, our `Vagrantfile` embedded in the .box file is pretty complex, can be seen on: https://github.com/spryker/devvm/blob/develop/Vagrantfile-quick

### Debug output
https://gist.github.com/marek-obuchowicz/af3c4dbec255b0f28a8e8d5182f9cc56

### Expected behavior
It should setup networking and continue with other vagrant up steps to setup to VM.

### Actual behavior
It froze. It freezes occasionally among many users in our company. That happens usually a few times a week, on various machines. After hitting Ctrl+C, then `vagrant halt;vagrant up` (usually once, 
sometimes a few times needed) - issue disappears and VM starts correctly.

It happens on various vagrant versions, from ca. 2.1.0 to 2.2.0. As it happens only from time to time, it was difficult to get the debug output of the crash - it took us several weeks to be able to get it and it happened to be the output of `2.1.2`, not the latest release. However same problem happens on latest as well.

One of our developers suggested that he manually deleted/re-created interfaces in VirtualBox and it solved the issue permanently for him.

### Steps to reproduce
Issue happens occasionally and we haven't been able to figure out how to reproduce it yet.

### References
https://github.com/hashicorp/vagrant/issues/6234

**Comment by marek-obuchowicz** [comment] 2018-10-19 09:06
If we manage to reproduce it locally, is there any step we should do in order to provide additional information?

**Comment by marek-obuchowicz** [comment] 2018-10-19 09:09
Snippet from the end of debug lot - i'm not sure how to interpret it, was it hang on the long command `ifdown enp0s8; (...) ifup enp0s8` or does it mean that this command succeeded and freeze happened afterwards?

```
(...)
/sbin/ifup 'enp0s8' (sudo=true)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo; printf $SSH_AUTH_SOCK (sudo=false)
DEBUG ssh: stderr: mesg: 
DEBUG ssh: stderr: ttyname failed
DEBUG ssh: stderr: : 
DEBUG ssh: stderr: Inappropriate ioctl for device

DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
 INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-LuQVTXgvAv/agent.1745
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Sending SSH keep-alive...
```

**Comment by anton-kiva** [comment] 2018-10-23 16:12
```mount.nfs: Connection timed out

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,nolock,fsc,noatime,async 10.10.0.1:/.../project /data/shop/development/current

Stdout from the command:



Stderr from the command:

mount.nfs: Connection timed out```

**Comment by tvaleriy** [comment] 2018-11-06 10:42
This is my debug output about the same issue.

If you need steps to reproduce, they are simple: just try to follow this instruction - http://academy.spryker.com/getting_started/installation_guide.html.

[vagrant up failed on configuring network interfaces.txt](https://github.com/hashicorp/vagrant/files/2552764/vagrant.up.failed.on.configuring.network.interfaces.txt)

**Comment by richard-scott** [comment] 2019-02-18 10:23
Change your NIC type to something other than virtio....

```
vb.customize ["modifyvm", :id, "--nictype1", "82540EM"]
```

**Comment by OZZlE** [comment] 2019-10-08 12:11
Seems like it only works in VirtualBox v6.0.2 for Mojave/Catalina! (+vagrant 2.2.2 - not sure it matters though!)

**Comment by chrisroberts** [comment] 2020-06-18 15:33
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2020-06-18 15:33 UTC
Labels: host/darwin, needs-repro, networking, provider/virtualbox
