### ISSUE TITLE
Vagrant uses a different SSH username which fails

### ISSUE THREAD

**Issue by JayMaree** [hashicorp/vagrant#10381] opened 2018-11-07 14:07 UTC
### Vagrant version
Vagrant 2.2.0

### Host operating system
MacOS Mojave 10.14

### Guest operating system
ubuntu/xenial64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ansible_inventory_dir = "./ansible/src"

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"

    db.vm.network "private_network", ip: "192.168.25.25"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    db.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "db.devenv.nl"
      ansible.playbook = "#{ansible_inventory_dir}/database.yml"
      ansible.verbose = false
    end

    db.vm.synced_folder "db.devenv.nl", "/vagrant_data"
  end

  config.vm.define "mail", autostart: false do |mail|
    mail.vm.box = "ubuntu/xenial64"

    mail.vm.network "private_network", ip: "192.168.25.33"

    mail.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    mail.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "mail.devenv.nl"
      ansible.playbook = "#{ansible_inventory_dir}/mail.yml"
      ansible.verbose = false
    end

    mail.vm.synced_folder "mail.devenv.nl", "/vagrant_data"
  end

  config.vm.define "port_flap", autostart: false do |port_flap|
    port_flap.vm.box = "ubuntu/xenial64"

    port_flap.vm.network "private_network", ip: "192.168.25.26"

    port_flap.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    port_flap.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "flap.devenvbit.portdev"
      ansible.playbook = "#{ansible_inventory_dir}/ports.yml"
      ansible.verbose = false
    end

    port_flap.vm.synced_folder "flap.devenv.portdev", "/vagrant_data"
  end

  config.vm.define "port_auto", autostart: false do |port_auto|
    port_auto.vm.box = "ubuntu/xenial64"

    port_auto.vm.network "private_network", ip: "192.168.25.27"

    port_auto.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "auto.devenv.portdev"
      ansible.playbook = "#{ansible_inventory_dir}/ports.yml"
      ansible.verbose = false
    end

    port_auto.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    port_auto.vm.synced_folder "auto.devenv.portdev", "/vagrant_data"
  end

  config.vm.define "port_xvg", autostart: false do |port_xvg|
    port_xvg.vm.box = "ubuntu/xenial64"

    port_xvg.vm.network "private_network", ip: "192.168.25.35"

    port_xvg.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "xvg.devenv.portdev"
      ansible.playbook = "#{ansible_inventory_dir}/ports.yml"
      ansible.verbose = false
    end

    port_xvg.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    port_xvg.vm.synced_folder "xvg.devenv.portdev", "/vagrant_data"
  end

  config.vm.define "port_vliegtuig", autostart: false do |port_vliegtuig|
    port_vliegtuig.vm.box = "ubuntu/xenial64"

    port_vliegtuig.vm.network "private_network", ip: "192.168.25.32"

    port_vliegtuig.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "vliegtuig.devenv.portdev"
      ansible.playbook = "#{ansible_inventory_dir}/ports.yml"
      ansible.verbose = false
    end

    port_vliegtuig.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    port_vliegtuig.vm.synced_folder "vliegtuig.devenv.portdev", "/vagrant_data"
  end


  config.vm.define "port_devenv", autostart: false do |port_devenv|
    port_devenv.vm.box = "ubuntu/xenial64"

    port_devenv.vm.network "private_network", ip: "192.168.25.31"

    port_devenv.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    port_devenv.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "devenv.portdev.devenv"
      ansible.playbook = "#{ansible_inventory_dir}/ports.yml"
    end

    port_devenv.vm.synced_folder "devenv.portdev.devenv", "/vagrant_data"
  end

  config.vm.define "website" do |website|
    website.vm.box = "ubuntu/xenial64"

    website.vm.network "private_network", ip: "192.168.25.28"

    website.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    website.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "www.devenv.nl"
      ansible.playbook = "#{ansible_inventory_dir}/devenv.yml"
      ansible.verbose = false
    end

    #website.vm.synced_folder "www.devenv.nl/pluto", "/var/www", owner: "devenv", group: "devenv"
    website.vm.synced_folder "www.devenv.nl/pluto", "/var/www", mount_options: ["dmode=777", "fmode=666"]
    #website.vm.synced_folder "www.devenv.nl/website-repository/src", "/var/www/html", owner: "devenv", group: "devenv"
    website.vm.synced_folder "www.devenv.nl/website-repository/src", "/var/www/html", mount_options: ["dmode=777", "fmode=666"]
    #website.vm.synced_folder "www.devenv.nl/website-repository", "/git", mount_options: ["dmode=777", "fmode=666"]
  end

  config.vm.define "masty" do |masty|
    masty.vm.box = "ubuntu/xenial64"

    masty.vm.network "private_network", ip: "192.168.25.29"

    masty.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    masty.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "www.sterdev.nl"
      ansible.playbook = "#{ansible_inventory_dir}/masty.yml"
      ansible.verbose = false
    end

    #masty.vm.synced_folder "www.sterdev.nl/masty-repository/src", "/var/www/html", owner: "devenv", group: "devenv"
    masty.vm.synced_folder "www.sterdev.nl/masty-repository/src", "/var/www/html", mount_options: ["dmode=777", "fmode=777"]
  end

  config.vm.define "tools", autostart: false do |tools|
    tools.vm.box = "ubuntu/xenial64"

    tools.vm.network "private_network", ip: "192.168.25.30"

    tools.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end

    tools.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "tools.devenv.nl"
      ansible.playbook = "#{ansible_inventory_dir}/tools.yml"
    end

    tools.vm.synced_folder "tools.sterdev.nl/kliko-mock-server-repository/src", "/var/www/kliko-api/html", mount_options: ["dmode=777", "fmode=666"]
  end

  config.vm.define "moon_processes", autostart: false do |moon_processes|
    moon_processes.vm.box = "ubuntu/xenial64"

    moon_processes.vm.network "private_network", ip: "192.168.25.34"

    moon_processes.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    moon_processes.vm.provision "ansible" do |ansible|
      ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
      ansible.inventory_path = "#{ansible_inventory_dir}/develop"
      ansible.limit = "devenv.moondev.processes"
      ansible.playbook = "#{ansible_inventory_dir}/moon.yml"
    end
  end

  config.vm.define "app-api" do |api|
    api.vm.box = "ubuntu/xenial64"

    api.vm.network "private_network", ip: "192.168.25.36"

     api.vm.provider "virtualbox" do |vb|
       vb.memory = 1024
     end

    api.vm.provision "ansible" do |ansible|
        ansible.config_file = "#{ansible_inventory_dir}/ansible.cfg"
        ansible.inventory_path = "#{ansible_inventory_dir}/develop"
        ansible.limit = "app-api.devenv.nl"
        ansible.playbook = "#{ansible_inventory_dir}/app-api.yml"
        ansible.verbose = false
      end

      api.vm.synced_folder "app-api.devenv.nl/app-api-repository", "/var/www/html", mount_options: ["dmode=777", "fmode=666"]
    end
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

The debug output could be found at https://gist.github.com/JayMaree/34e23973de50294564f5af04e5461d01

### Expected behavior
Vagrant should login with SSH username **vagrant** and a private key.

The vm should execute ansible scripts to install different kinds of packages.

### Actual behavior
It logs in with username **ubuntu** and a **password**. Then it tries to execute the ansible playbook which gives us the following error:

````
Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    db: Running ansible-playbook...
Vault password:
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and
make sure become_method is 'sudo' (default). This feature will be removed in
version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

PLAY [all] *********************************************************************

TASK [Install Python2] *********************************************************
fatal: [db.dev.nl]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '192.168.25.25' (ECDSA) to the list of known hosts.\r\nvagrant@192.168.25.25: Permission denied (publickey,password).\r\n", "unreachable": true}
````

I have enabled the Vagrant verbose output within the Vagrantfile which gave me the following errors:
````
Failed to connect to the host via ssh: OpenSSH_7.7p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/user/.ssh/config
debug1: /Users/user/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: resolve_canonicalize: hostname 192.168.25.25 is address
debug1: auto-mux: Trying existing master
debug1: Control socket \"/Users/user/.ansible/cp/5dfd5f05df\" does not exist
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.25.25 [192.168.25.25] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug3: timeout: 29995 ms remain after connect
debug1: key_load_public: No such file or directory
debug1: identity file /Users/user/Projects/dev/vagrant/.vagrant/machines/db/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/user/Projects/dev/vagrant/.vagrant/machines/db/virtualbox/private_key-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file .vagrant/machines/db/virtualbox/private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file .vagrant/machines/db/virtualbox/private_key-cert type -1
debug1: identity file /Users/user/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file /Users/user/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.7
````

### Steps to reproduce
1. I have tried the same configuration (files/repo clone etc.) on different machines, which worked.
2. I have tried to force Vagrant to login with **vagrant** and the **private key**.
3. I have tried to force ansible to use **vagrant** as username.

### References
None, yet.

**Comment by chrisroberts** [comment] 2018-11-07 15:31
Hi there. Please provide a gist of the debug output from the failing command. Thanks.

**Comment by JayMaree** [comment] 2018-11-13 09:45
> Hi there. Please provide a gist of the debug output from the failing command. Thanks.

I have updated the original issue > added the GitHub Gist.

**Comment by chrisroberts** [comment] 2018-11-13 17:09
@JayMaree Thanks for the update. The output in the gist doesn't seem to line up correctly with the configuration shown in the provided Vagrantfile. Would you please ensure that your local Vagrantfile matches what you have provided in the issue, and then provide a gist of a `vagrant up --debug` so the full debug log is available.

Thanks!

**Comment by JayMaree** [comment] 2018-11-14 08:43
> @JayMaree Thanks for the update. The output in the gist doesn't seem to line up correctly with the configuration shown in the provided Vagrantfile. Would you please ensure that your local Vagrantfile matches what you have provided in the issue, and then provide a gist of a `vagrant up --debug` so the full debug log is available.
> 
> Thanks!

Hi Chris. Thanks for the reply.

I removed a part of the Vagrantfile because in my opinion it is irrelevant for this particular issue. Vagrant fails while configuring the db VM. Am I correct?

**Comment by chrisroberts** [comment] 2018-11-16 17:01
@JayMaree The output provided does not seem to match with the current state of the Vagrantfile provided in the original description. There is also extra information provided at the debug level that will help to determine the underlying cause and if there is an error.

**Comment by JayMaree** [comment] 2018-11-20 10:44
> @JayMaree The output provided does not seem to match with the current state of the Vagrantfile provided in the original description. There is also extra information provided at the debug level that will help to determine the underlying cause and if there is an error.

Updated both of them.

**Comment by chrisroberts** [comment] 2018-11-20 18:46
@JayMaree Thanks. The issue is caused by the ubuntu box you are using. That box includes configuration which sets the `config.ssh.username` and `config.ssh.password` to `"ubuntu"`. These boxes generally include a `vagrant` user with the expected public key configured, so you will likely be able to resolve the issue by overriding the ssh configuration in your Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"
  config.ssh.password = nil
end
```

**Comment by chrisroberts** [comment] 2018-12-07 21:31
Going to assume this fixed this issue so closing this up. Cheers!

**Closed by chrisroberts** 2018-12-07 21:31 UTC
Labels: needs-debug-gist, provisioner/ansible, waiting-reply
