### ISSUE TITLE
Vagrant not properly setting mount point for VirtualBox synced folders

### ISSUE THREAD

**Issue by perezd** [hashicorp/vagrant#11725] opened 2020-06-28 20:10 UTC
### Vagrant version

Vagrant 2.2.9

### Host operating system

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

### Guest operating system

VirtualBox version:
Version 6.0.22 r137980 (Qt5.12.8)

Also tried:
Version 6.1.10 r138449 (Qt5.12.8)

https://app.vagrantup.com/generic/boxes/alpine312

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine312"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/code", automount: true, create: true, 
    owner: "vagrant", group: "vagrant"
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apk add virtualbox-guest-additions virtualbox-guest-modules-virt
    reboot
  SHELL
end
```
### Debug output

N/A

### Expected behavior

What should have happened?

Given

 ```
==> default: Mounting shared folders...
    default: /code => /home/derek/src/bcpilot
```
`ls /code` would return the root of my project as a synced folder.

### Actual behavior

What actually happened?

`/code` is present but not mounted to anything.

I noticed that this doesn't seem configured properly:
![image](https://user-images.githubusercontent.com/20598/85957124-9f9a7700-b93f-11ea-914f-fdd5ea2fb284.png)

On the guest OS, I ran the following command:
```
alpine312:~$ sudo VBoxControl sharedfolder list
Oracle VM VirtualBox Guest Additions Command Line Management Interface Version 6.0.14
(C) 2008-2020 Oracle Corporation
All rights reserved.

Shared Folder mappings (1):

01 - code [idRoot=0 writable auto-mount create-symlink host-icase guest-icase]
```
If I type `/code` into the `mount point:` text field in that settings UI screenshot and reboot, it works fine, and the command I ran above changes to this:

```
alpine312:~$  sudo VBoxControl sharedfolder list
Oracle VM VirtualBox Guest Additions Command Line Management Interface Version 6.0.14
(C) 2008-2020 Oracle Corporation
All rights reserved.

Shared Folder mappings (1):

01 - code [idRoot=1 writable auto-mount create-symlink host-icase guest-icase mnt-pt=/code]
```

I can confirm that the mount actually works, just the mount point never gets configured properly:

```
alpine312:~$ mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,relatime,size=10240k,nr_inodes=254345,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on / type ext4 (rw,relatime)
tmpfs on /run type tmpfs (rw,nodev,relatime,size=204476k,mode=755)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
/dev/sda1 on /boot type ext4 (rw,relatime)
code on /media/sf_code type vboxsf (rw,nodev,relatime,iocharset=utf8,uid=0,gid=101,dmode=0770,fmode=0770,tag=VBoxAutomounter)
```

### Steps to reproduce

1. Run that vagrant file
2. Observe lack of sync'd contents.
3. Change UI setting manually and reboot.
4. Observe mount is present with root:vboxsf permissions (also wrong).

### References

N/A

**Comment by perezd** [comment] 2020-06-29 00:38
As a workaround, I had to fall back to manually managing my sync folders:

```ruby
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/code", "1"]
    v.customize ["sharedfolder", "add", :id, "--name", "code", "--hostpath", File.dirname(__FILE__)]
  end
  config.vm.provision :shell, privileged: true, run: 'always', inline: <<-SHELL
    mkdir -p /home/vagrant/src
    mount.vboxsf -o "uid=1000,gid=1000" code /home/vagrant/src
  SHELL
```

This works as intended.

**Comment by soapy1** [comment] 2020-06-29 14:56
It looks like this issue may be surfacing because of the `reboot` step at the end of the provisioner in your original Vagrantfile

```
config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apk add virtualbox-guest-additions virtualbox-guest-modules-virt
    reboot
  SHELL
```

The root of the issue is [VBox mounts not being persisted after reboot](https://github.com/hashicorp/vagrant/issues/11368). A fix for this has recently been [merged](https://github.com/hashicorp/vagrant/pull/11570). So, this issue should be resolved in the next release of Vagrant.

ref:
https://github.com/hashicorp/vagrant/issues/11368
https://github.com/hashicorp/vagrant/pull/11570

**Closed by soapy1** 2020-06-29 14:56 UTC
