### ISSUE TITLE
Error on vagrant commands

### ISSUE THREAD

**Issue by harlangray** [hashicorp/vagrant#12949] opened 2022-10-11 11:37 UTC
running a vagrant command on Windows (eg vagrant up) throws the following error. I just installed version 2.3.1
I get a similar error on Mac OS too. 

C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'bcrypt_pbkdf' (~> 1.1) - did find: [bcrypt_pbkdf-1.1.0-x86-mingw32] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=C:/HashiCorp/Vagrant/embedded/gems/2.3.1', execute `gem env` for more information
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/dependency.rb:320:in `to_spec'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:95:in `block (2 levels) in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:94:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:94:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:105:in `<main>'

**Comment by bandilepdlamini** [comment] 2022-10-21 09:08
I am running into the same issue.

**Comment by Lumixx09** [comment] 2022-10-21 15:06
I'm caught in one as well

**Comment by Lumixx09** [comment] 2022-10-21 15:07
Traceback (most recent call last):                                                                                                                                              6: from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:105:in `<main>'                                                                         5: from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:94:in `block in <main>'                                                                 4: from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:94:in `each'                                                                            3: from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:95:in `block (2 levels) in <main>'                                                      2: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'                                                                1: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'                                                            C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'bcrypt_pbkdf' (~> 1.1) among 94 total gem(s) (Gem::MissingSpecError)                                                                                                                                                             Checked in 'GEM_PATH=C:/HashiCorp/Vagrant/embedded/gems/2.3.1', execute `gem env` for more information

**Comment by chrisroberts** [comment] 2022-11-18 01:19
Hi there. Is this still be encountered on the latest Vagrant release (2.3.3)? If so, would you please provide what version of Windows you are on. Thanks!

**Comment by ramsesrom** [comment] 2022-12-06 01:22
still having issue with 2.3.3 version

**Comment by soapy1** [comment] 2023-01-11 21:42
Hey there, I'm trying to reproduce this issue from windows Vagrant installers from [2.3.1 - 2.3.3](https://releases.hashicorp.com/vagrant/). However, I'm unable to reproduce this issue. Could you share:

- where you downloaded the installer
- install steps
- system information (eg. what version of windows, are you running WSL, etc.)

thanks!

**Comment by soapy1** [comment] 2023-02-15 22:51
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by soapy1** 2023-02-15 22:51 UTC
Labels: installer, waiting-reply, host/windows
