### ISSUE TITLE
Error in gems/net-sftp-2.1.2 after upgrading Vagrant 2.2.3 to 2.2.4

### ISSUE THREAD

**Issue by catalinux** [hashicorp/vagrant#10767] opened 2019-04-01 06:44 UTC
### Vagrant version
Vagrant 2.2.4

### Host operating system
Windows 8.1

### Guest operating system
 box 'bento/ubuntu-16.04' version '201812.27.0'

### Debug output
https://gist.github.com/catalinux/118a0d3500abef83bc439cccfb874f36
### Expected behavior
The machine should have started

### Actual behavior

The machine did not start

### Steps to reproduce

This error appeared after I upgraded from Vagrant 2.2.3 to 2.2.4

**Comment by chrisroberts** [comment] 2019-04-01 16:43
Duplicate of #10745

**Closed by chrisroberts** 2019-04-01 16:43 UTC
Labels: bug, duplicate, upstream
