### ISSUE TITLE
can't check for updates( The requested URL returned error: 404 Not Found )

### ISSUE THREAD

**Issue by YousefSaber** [hashicorp/vagrant#9539] opened 2018-03-05 20:31 UTC
![image](https://user-images.githubusercontent.com/33742499/36998107-7e383482-20c4-11e8-8ed7-f6e0660abf16.png)

![image](https://user-images.githubusercontent.com/33742499/36998136-9b0581fa-20c4-11e8-9e31-c12d6f32dac0.png)

does anyone knows why Ubuntu/trusty64 can't check for updates ???

I'm running the latest version of Vagrant and Oracle Virtual Machine 
![image](https://user-images.githubusercontent.com/33742499/36998215-d181047a-20c4-11e8-8b31-c3d86d5a6194.png)

**Comment by briancain** [comment] 2018-03-05 21:45
Duplicate of https://github.com/hashicorp/vagrant/issues/9442

Please see this post for more information on how to fix this. Thanks! https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vagrant-up/H8C68UTkosU/qz4YUmAgBAAJ

**Closed by briancain** 2018-03-05 21:45 UTC
