### ISSUE TITLE
The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by rinu** [hashicorp/vagrant#9458] opened 2018-02-08 16:00 UTC
### Vagrant version
Vagrant 1.8.1

### Host operating system
Ubuntu 16.04

I already have the box 'ubuntu/xenial64' but updates fail. This started to fail today, never had this issue before.

**Comment by briancain** [comment] 2018-02-08 18:11
Closing as a duplicate of #9442. Thanks!

**Closed by briancain** 2018-02-08 18:11 UTC
