### ISSUE TITLE
Vagrant up (1.9.x) does not work on Windows Creators Update (WSL installed)

### ISSUE THREAD

**Issue by ajaykagrawal** [hashicorp/vagrant#8542] opened 2017-04-30 03:09 UTC
### Vagrant version
1.9.4 (this is true for 1.9.0, 1.9.1, 1.9.2 also)

### Host operating system
Windows 10 pro (Version 10.0.15063 - Creators Update with WSL installed)

### Guest operating system
Ubuntu 16.04 Server

### Expected behavior
vagrant up should have launched VM

### Actual behavior
'vagrant up' on (1.9.0 - 1.9.2) returned this error: 1.9.2/lib/vagrant/batch_action.rb:126:in `join': No live threads left. Deadlock? (fatal)

'vagrant up' on 1.9.4 just hangs. When run with --debug it acquires a machine lock and then simply hangs

Note vagrant 1.8.7 works without any issues

**Comment by chrisroberts** [comment] 2017-05-01 21:17
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by ajaykagrawal** [comment] 2017-05-04 05:57
Hi I have included most of the above information - host (Windows 10 version 10.0.15063 with Windows Subsystem for Linux), guest (Ubuntu 16.04 Server - x64), vagrant version 1.9.4.

Here is the link to "vagrant up --debug": https://gist.github.com/ajaykagrawal/cfa60b692cae4a9c4852181517e84922

**Comment by ajaykagrawal** [comment] 2017-05-06 03:57
Hi let me know if you need additional information. This is reproducible on at least 2 different Windows machines

**Comment by TonyKelly12** [comment] 2017-05-17 05:47
Hi Guys,
It seems im having the same problem. vagrant up gets stuck on SSH auth method 
My Specs:

Windows 10 Home 
version 1703
os build 15063.296
processor Intel(R) Core(TM) i7-4510U CPU @ 2.00GHZ 2.60GHZ
Installed RAM 8.00 GB
System Type 64-bit operating system, x64 based processor



![vagrant up error](https://cloud.githubusercontent.com/assets/19878189/26139993/f6db44c2-3a99-11e7-937b-2da1857ff884.JPG)

**Comment by harrystaley** [comment] 2017-05-17 05:57
I can confirm that the VM is hanging when being prompted for the login of Ubuntu.

**Comment by girlandhercode** [comment] 2017-05-25 16:42
This is also true for Vagrant 1.9.5.  I can ``Ctrl+C`` the login errors and then successfully log in if I just use ``ssh``:

```bash
ssh vagrant@127.0.0.1 -p 2222
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is 65:45:30:fe:f6:72:ce:3e:cd:a2:d5:85:85:f2:2a:7d.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
vagrant@127.0.0.1's password:
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-55-generic x86_64)
```

### Vagrant version

1.9.5

### Host operating system

Windows 10 Home (Version 1703, OS Build 15063.296 - Creators Update with WSL 14.04 i did not upgrade WSL to 16.04)

### Guest operating system

Scotch Box based on Ubuntu 14.04


Vagrant command used: ``vagrant up``


Vagrantfile:
```Ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "scotch/box"
end
```


Errors in console:
```bash
==> default: Successfully added box 'scotch/box' (v2.5) for 'virtualbox'!
==> default: Importing base box 'scotch/box'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'scotch/box' is up to date...
==> default: Setting the name of the VM: VagrantWSLtest_default_1495729249321_45492
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
```

**Comment by briancain** [comment] 2017-12-19 19:26
@ajaykagrawal - does this still happen if you upgrade to the latest version of Vagrant? Thanks!

**Comment by chrisroberts** [comment] 2018-03-27 15:52
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2018-03-27 15:52 UTC
Labels: guest/ubuntu, host/windows, waiting-reply
