### ISSUE TITLE
Vagrant up is not working

### ISSUE THREAD

**Issue by sandipansen** [hashicorp/vagrant#9723] opened 2018-04-25 02:43 UTC
Guys, I am trying to install Linux VM since 2 hours. Installed 3 times, still not working. Please help
### Vagrant version
2.0.4

### Host operating system
Windows 10

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /D:/test/base
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment] 2018-04-25 14:11
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by lCHECHOl** [comment] 2018-04-25 21:25
chech@DESKTOP-QJGFHQ1 MINGW64 ~/homestead-6.1.0
$ vagrant up
==> vagrant: A new version of Vagrant is available: 2.0.4!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Bringing machine 'homestead-7' up with 'virtualbox' provider...
The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3

**Comment by chrisroberts** [comment] 2018-04-25 21:36
@lCHECHOl Hi. The problem you are experiencing is not related to this issue. It is likely that you do not have the powershell executable available in your PATH. If you still feel that Vagrant is not working correctly after fixing your local environment, please create a new issue and provide all the information requested by the template. Thanks!

**Comment by lCHECHOl** [comment] 2018-04-25 21:44
@chrisroberts jajaj Sorry it was my mistake, I'm wrong about this issue

**Comment by chrisroberts** [comment] 2018-05-03 20:31
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2018-05-03 20:31 UTC
Labels: host/windows, waiting-reply
