### ISSUE TITLE
Not detecting VirtualBox

### ISSUE THREAD

**Issue by MilesHart** [hashicorp/vagrant#9128] opened 2017-10-31 18:35 UTC
I've been following getting started guide... and I'm unable to proceed.

Vagrant version 2.0.0
Windows 10 pro
VirtualBox 5.2.0 r118431 (Qt5.6.2)

VBOX_INSTALL_PATH is set
VBOX_MSI_INSTALL_PATH is set

When bring a machine up...

C:\Users\admin>vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

Vagrant file

Vagrant.configure("2") do |config|
  config.vm.box = "hasicorp/precise64"
end

**Comment by twelch555** [comment] 2017-10-31 23:13
Running the vagrant up --provider=virtualbox command will get you to a further error indicating that virtualbox 5.2 is not the lists of supported versions of virtualbox. (4.0, 4.1, 4.2, 4.3, 5.0, 5.1).

I guess the short term solution is to pull out virtualbox 5.2 and replace it with 5.1. Although, I haven't done this yet, I'm hoping to find a kinder and gentler solution.

**Comment by briancain** [comment] 2017-11-01 15:40
@MilesHart - Hey there! I'm closing this as a duplicate of #9090. We're working on the final steps to get the next release out the door, which includes support for VirtualBox 5.2. Thank you for your patience! For now, you should be just fine using VirtualBox 5.1.x. Thanks!

**Closed by briancain** 2017-11-01 15:40 UTC

**Comment by MilesHart** [comment] 2017-11-03 10:16
Thanks guys.
