### ISSUE TITLE
Vagrant Timeout on Windows 10 build 19042.662

### ISSUE THREAD

**Issue by jason-migz** [hashicorp/vagrant#12089] opened 2020-12-01 09:07 UTC
### Vagrant version

Vagrant 2.2.14

### Host operating system

Windows 10 Pro Version 20H2 (OS Build 19042.662)

### Guest operating system

Ubuntu 18.04 LTS

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "base"
    config.vm.boot_timeout = 600
    config.vm.define "laravel_envoy" do |laravel_envoy|
      laravel_envoy.vm.hostname = "192.168.12.12"
      laravel_envoy.vm.box = "bento/ubuntu-18.04"
      laravel_envoy.vm.network :private_network, ip: "192.168.12.12"
      laravel_envoy.vm.provider "virtualbox" do |bionicv|
        bionicv.memory = 4096
        bionicv.cpus = 4
      end
      laravel_envoy.vm.synced_folder "C:/Users/jjmigz-win10/Code/laravel_gitlab_ci_cd_with_envoy","/home/vagrant/Code/gcp-home"
    end
    config.vm.network "forwarded_port", guest: 8992, host: 8991, host_ip: "127.0.0.1"
  end
```

### Debug output
![image](https://user-images.githubusercontent.com/21366028/100719497-b0bc4800-33f7-11eb-85be-add3a884d205.png)

### Expected behavior

`vagrant up` command should up the box

### Actual behavior

I encountered a timeout, i already extend timeout in vagrant config but it does not fix the issue

### Steps to reproduce
1.) open Windows Powershell
2.)  run command `vagrant up`

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/microsoft/WSL/issues/6295

**Comment by soapy1** [comment] 2020-12-01 19:01
This seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/12081. In order to consolidate conversation to only one issue, I'm going to close this one as a duplicate.

**Closed by soapy1** 2020-12-01 19:01 UTC

**Comment by jason-migz** [comment] 2020-12-02 02:16
> This seems to be a duplicate of #12081. In order to consolidate conversation to only one issue, I'm going to close this one as a duplicate.

@soapy1 i use Ubuntu 18.04 as my guest OS and latest Windows 10 Build, i think it is not duplicate, can you look at it again? thank you
