### ISSUE TITLE
Unable to ssh into Vagrant Box when more than two private_network entries defined

### ISSUE THREAD

**Issue by softabout** [hashicorp/vagrant#8835] opened 2017-07-31 10:47 UTC
After defining three private_network entries in our Vagrantfile it is not possible to ssh into the box via vagrant ssh. vagrant up shows the following output:

Vagrantfile (excerpt):

```
 config.vm.network "private_network", ip: "192.168.42.10", netmask: "255.255.255.0"
 config.vm.network "private_network", ip: "192.168.42.20", netmask: "255.255.255.0"
 config.vm.network "private_network", ip: "192.168.42.30", netmask: "255.255.255.0"
```

OUTPUT:

```
Bringing machine 'default' up with 'virtualbox' provider...                          
==> default: Importing base box 'bento/centos-7.3'...                                
==> default: Matching MAC address for NAT networking...                              
==> default: Checking if box 'bento/centos-7.3' is up to date...                     
==> default: Setting the name of the VM: mrm_centos7_64                              
==> default: Clearing any previously set network interfaces...                       
==> default: Preparing network interfaces based on configuration...                  
    default: Adapter 1: nat                                                          
    default: Adapter 2: hostonly                                                     
    default: Adapter 3: hostonly                                                     
    default: Adapter 4: hostonly                                                     
==> default: You are trying to forward to privileged ports (ports <= 1024). Most     
==> default: operating systems restrict this to only privileged process (typically   
==> default: processes running as an administrative user). This is a warning in case 
==> default: the port forwarding doesn't work. If any problems occur, please try a   
==> default: port higher than 1024.                                                  
==> default: Forwarding ports...                                                     
    default: 22 (guest) => 1022 (host) (adapter 1)                                   
==> default: Running 'pre-boot' VM customizations...                                 
==> default: Booting VM...                                                           
==> default: Waiting for machine to boot. This may take a few minutes...             
    default: SSH address: 127.0.0.1:1022                                             
    default: SSH username: root                                                      
    default: SSH auth method: password                                               
    default: Warning: Connection reset. Retrying...                                  
    default: Warning: Connection aborted. Retrying...                                

...

    default: Warning: Connection aborted. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

vagrant ssh-config shows, that no public key was imported:

Host default
  HostName 127.0.0.1
  User root
  Port 1022
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentitiesOnly yes
  LogLevel FATAL

```

After removing the third private_network entry: 

 config.vm.network "private_network", ip: "192.168.42.10", netmask: "255.255.255.0"
 config.vm.network "private_network", ip: "192.168.42.20", netmask: "255.255.255.0"

vagrant up shows

```
.....
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
```

and vagrant ssh-config shows:

Host default
  HostName 127.0.0.1
  User root
  Port 1022
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile C:/Develop/proj/acx/dev/devenv/vagrant/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL

We use:
Vagrant 1.9.7
Provider Virtual Box, 5.1.26
Host-OS: Win7
Guest-OS: bento/centos-7.3, 2.3.8

Any ideas?

Thx

**Comment by briancain** [comment] 2017-08-01 16:57
@softabout - this might be an issue with the `bento/centos-7.3` box you are using. I attempted to reproduce this with `bento/centos-7.3` and `bento/ubuntu-16.04` and the ubuntu box was able to handle three private networks with no problems. Here's my test Vagrant block:

```ruby
  config.vm.define "basic" do |b|
    #b.vm.box = "bento/ubuntu-16.04" # this works
    b.vm.box = "bento/centos-7.3" # this doesn't work
    b.vm.provider :virtualbox

    b.vm.network "private_network", ip: "192.168.42.10", netmask: "255.255.255.0"
    b.vm.network "private_network", ip: "192.168.42.20", netmask: "255.255.255.0"
    b.vm.network "private_network", ip: "192.168.42.30", netmask: "255.255.255.0"
  end
```

**Comment by softabout** [comment] 2017-08-01 17:47
Thx.
The bento/centos-7.3 is able to handle three private networks, but not during initial provisioning.
This means, if I comment the last line of the private networks and initially only use two of them, I get the machine up and running and vagrant ssh works as usual.
vagrant halt, uncommenting the third private network and vagrant up leads to a fully functioning vm with all three private network ips functioning.

**Comment by chrisroberts** [comment] 2018-12-22 00:00
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2018-12-22 00:00 UTC
Labels: needs info, networking
