### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by ksclarke** [hashicorp/vagrant#8499] opened 2017-04-19 19:44 UTC
VMWare boxes are not starting and error message says to report this as a bug.

Vagrant version:
* Vagrant 1.9.3

Vagrant plugins:
* vagrant-share (1.1.7, system)
* vagrant-vmware-workstation (4.0.18)

VMWare:
* VMware Workstation 12.5.5 build-5234757

Host:
* Linux kevin-oryx 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Guest operating system:
* RHEL 6.8 and/or CentOS 6.8

Vagrantfile:

    Vagrant.configure("2") do |config|
      config.ssh.insert_key = false
    
      config.vm.define "basebox-rhel6" do |vmware|
        vmware.vm.hostname = "basebox-rhel6"
        vmware.vm.box = "ksclarke/basebox-rhel6"
    
        vmware.vm.network :private_network, type: "dhcp"
    
        config.vm.provider :vmware_fusion do |v, override|
          v.gui = false
          v.vmx["memsize"] = 1024
          v.vmx["numvcpus"] = 1
        end
    
        config.vm.provider :vmware_workstation do |v, override|
          v.gui = false
          v.vmx["memsize"] = 1024
          v.vmx["numvcpus"] = 1
        end
      end
    end

Debug output:
  https://gist.github.com/ksclarke/fb772b752245f0fe2c6f27e439388bce

Expected behavior:
  Vagrant box would start up

Actual behavior:
  Vagrant box reports: `Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.`

Steps to reproduce:
1. mkdir testdir
2. cd testdir
3. vagrant init ksclarke/basebox-centos6
4. vagrant up --provider vmware_workstation

There are various other closed tickets with the generic "Guest-specific operations" message but none of them looked relevant to me.

**Comment by ksclarke** [comment] 2017-04-20 19:16
I should clarify my first statement. The problem isn't that the box isn't starting. It does start and I can login to it, it's just that I see that error after "Configuring network adapters within the VM"  on `up` which might lead someone to believe they can't SSH into it.

**Comment by brandonsoto** [comment] 2017-04-25 13:51
I'm experiencing this issue as well.

Vagrant version:
Vagrant 1.9.3

Vagrant plugins:
vagrant-share 1.1.7
vagrant-vmware-workstation 4.0.18

VMWare:
VMware Workstation 11.1.4 build-3848939

Host:
Linux bsoto 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 
GNU/LinuxGNU/Linux

Guest operating system:
CentOS 6.8 (bento/centos-6.8)

**Comment by chrisroberts** [comment] 2017-04-28 23:40
Hi there.

**Comment by chrisroberts** [comment] 2017-04-28 23:41
Hi there. I have identified the source of the error and have implemented a fix in the vagrant-vmware plugins. I am planning to release the update on Monday, and will leave this issue open until the plugins have been released. Thanks for the report and extra information to help track this down. Cheers!

**Comment by ksclarke** [comment] 2017-05-18 18:15
Should this still be open? I tried using vagrant-vmware-workstation 4.0.19 but had the same error so I'm guessing the fix hasn't been published yet. Is that correct?

**Comment by Ghostavio** [comment] 2018-03-20 13:15
@chrisroberts was this fixed?

**Comment by Ghostavio** [comment] 2018-03-20 13:15
I'm having this very same issue with VirtualBox.

**Comment by Healthcare-IT** [comment] 2018-03-21 15:17
I'm having this very same issue with VirtualBox; it just started today.

**Comment by chrisroberts** [comment] 2018-12-21 23:00
The fix for this issue was released in the plugin. The root cause is due to the network reset after applying port forwards. It causes DHCP configured devices to drop their address and re-acquire a new lease which leads to the "Guest-specific operations..." error. The fix adds a pause after applying the forwards before continuing. If you find that the pause is not long enough, it can be configured using a provider configuration option: https://www.vagrantup.com/docs/vmware/configuration.html#port_forward_network_pause

Cheers!

**Closed by chrisroberts** 2018-12-21 23:00 UTC
Labels: confirmed, guest/redhat, networking, provider/vmware
