### ISSUE TITLE
Vagrant 2.3.2 and Virtualbox 7.0.2 - Private Network Interface

### ISSUE THREAD

**Issue by Yagoor** [hashicorp/vagrant#12967] opened 2022-10-21 20:53 UTC
### Debug output

https://gist.github.com/Yagoor/66ca6861f57e2c2b09f34c0821bbb0e7

### Expected behavior

The machine is started with a private network interface

### Actual behavior

The vagrant up fails

### Reproduction information 

Reproducible with the Vagrantfile and vagrant up

#### Provider version

Virtual box: Version 7.0.2 r154219 (Qt5.15.2)

#### Vagrant version

Vagrant 2.3.2

#### Host operating system

macOS 11.7

#### Guest operating system

bento/ubuntu-20.04

#### Steps to reproduce

1. Create Vagrantfiles as follows
2. vagrant up

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.network "private_network", ip: "192.168.50.4"
end
```

**Comment by identifysun** [comment] 2022-10-24 02:42
I have same question,

# Vagrant and Virtualbox Version

```shell
$ vagrant --version
Vagrant 2.3.2

$ vboxmanage --version
7.0.2r154219
```

I guess running the following command is caused by a failure

```shell
$ VBoxManage hostonlyif create
0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp
```

Refer to the workaround on the internet, but I can't find the following file or command

-  /Library/StartupItems/VirtualBox/VirtualBox restart
- /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart

**Comment by identifysun** [comment] 2022-10-24 02:44
I tried reinstalling Vagrant and Virtualbox, but it still doesn't fix

```shell
$ brew reinstall virtualbox vagrant
```

**Comment by jav-12** [comment] 2022-10-24 07:45
Same issue here. I downgraded VirtualBox to v6.1 problem is gone. For now, I will keep it this way till 7 gets fixed.

**Comment by f3l1x** [comment] 2022-10-24 18:45
Same issue here. 

```
❯ vagrant up debian11
Bringing machine 'debian11' up with 'virtualbox' provider...
==> debian11: Checking if box 'debian/bullseye64' version '11.20220912.1' is up to date...
==> debian11: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp
```


```
vagrant --version
Vagrant 2.3.2

vboxmanage --version
7.0.2r154219
```

**Comment by JackSzwergold** [comment] 2022-10-24 22:14
Adding my voice to the choir here. Worked fine prior to this VirtualBox 7.0.2 update when I was using  VirtualBox 6.1.40. Might just downgrade VirtualBox 6.1.40 if need be.

```
vagrant --version
Vagrant 2.3.2
```

 ```
 vboxmanage --version
 7.0.2r154219
 ```

This is the output I get when running `vagrant up` on my setup:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "f74b9e88-7ff6-402f-92fe-f7d195d6d890", "--type", "headless"]

Stderr: VBoxManage: error: Host-only adapters are no longer supported!
VBoxManage: error: For your convenience a host-only network named 'Legacy vboxnet0 Network' has been created with network mask '255.255.255.0' and IP address range '192.168.56.101' - '192.168.56.254'.
VBoxManage: error: To fix this problem, switch to 'Host-only Network' attachment type in the VM settings.
VBoxManage: error:  (VERR_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by splunkenizer** [comment] 2022-10-25 12:33
Same problem here on OSX:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "ab1ae5b6-0789-4cbe-8421-b43ed2f280c1", "--type", "headless"]

Stderr: VBoxManage: error: Host-only adapters are no longer supported!
VBoxManage: error: For your convenience a host-only network named 'Legacy vboxnet0 Network' has been created with network mask '255.255.255.0' and IP address range '192.168.56.101' - '192.168.56.254'.
VBoxManage: error: To fix this problem, switch to 'Host-only Network' attachment type in the VM settings.
VBoxManage: error:  (VERR_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by MacCracken** [comment] 2022-10-25 23:09
encountering the same; issue attempted a fix for virtualbox driver 7_0... replaced hostonlyifs with hostonlynets as a host only network works with 7.x base machines.  Only thing is not familiar with the code base to know if there needs to be a os specific switch added as I'm not sure if windows users experience the same issue.

**Comment by DeanWronowski** [comment] 2022-10-27 10:23
Same issue here as well

**Comment by alexpotter** [comment] 2022-10-27 11:29
Anyone facing this issue do the following:

1) Downgrade to 6.1.32 https://download.virtualbox.org/virtualbox/6.1.32/VirtualBox-6.1.32-149290-OSX.dmg
2) On the installer uninstall the current version, chances are you will need to go into settings and allow it to run
3) Run the following
```

**Comment by mgascoyne** [comment] 2022-10-27 11:56
> Anyone facing this issue do the following:
> 
> 1. Downgrade to 6.1.32 https://download.virtualbox.org/virtualbox/6.1.32/VirtualBox-6.1.32-149290-OSX.dmg
> 2. On the installer uninstall the current version, chances are you will need to go into settings and allow it to run
> 3. Run the following

Thanks, works for me!

**Comment by JackSzwergold** [comment] 2022-10-27 13:41
While to VirtualBox 6.1 — unsure why @alexpotter is recommending 6.1.32 when 6.1.40 is [the latest in the 6.1.x releases](https://www.virtualbox.org/wiki/Download_Old_Builds) — will “solve” the issue but that his not really a solution: Changes need to be made in Vagrant to handle VirtualBox 7.0.2.

**Comment by alexpotter** [comment] 2022-10-27 13:47
That version did not work for me @JackSzwergold 🤷‍♂️ not that a minor bump should be of significant difference to anyone so does not matter anyway

**Comment by EnSabanNur** [comment] 2022-10-27 19:38
Same issue on this end:

#### Guest operating system
bento/ubuntu-20.04
#### Host Machine
Macbook pro - M1 Max
#### Host operating system
macOS 11.7
#### Provider version
Virtual box: Version 7.0.2 r154219 (Qt5.15.2)
#### Vagrant version
Vagrant 2.3.2

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp
```

**Comment by trevor** [comment] 2022-10-27 22:11
```
VirtualBox 7.0.2 (released October 20 2022)
[...]
macOS hosts: Re-introduced support for internal networking, this is considered a bit experimental still

[...]

VirtualBox 7.0.0 (released October 10 2022)
[...]
macOS host: Dropped all kernel extensions. VirtualBox relies fully on the hypervisor and vmnet frameworks provided by Apple now. At the moment the implementation lacks "Internal Networking" functionality. This will be provided at a later date.
```

- https://www.virtualbox.org/wiki/Changelog-7.0

**Comment by csherrell** [comment] 2022-10-28 22:48
Compiling what I have found. I have not tried this. Think I'll wait for the official solution, but have heard the following works.

1. [Disable SIP.](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)
2.  Then run the
```
sudo kextload -b org.virtualbox.kext.VBoxDrv;
sudo kextload -b org.virtualbox.kext.VBoxNetFlt;
sudo kextload -b org.virtualbox.kext.VBoxNetAdp;
sudo kextload -b org.virtualbox.kext.VBoxUSB;
```

I updated VirtualBox and Vagrant when I updated to macOS Ventura.

```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.0
BuildVersion:		22A380

$ vboxmanage --version
7.0.2r154219

$ vagrant --version
Vagrant 2.3.2
```

**Comment by mintplo** [comment] 2022-10-31 07:32
same problem here.

**Comment by mmihalev** [comment] 2022-10-31 12:45
Any news on this?

**Comment by walznet** [comment] 2022-10-31 14:33
same problem here.

**Comment by skabrits** [comment] 2022-11-01 15:21
same problem

**Comment by barryhughes** [comment] 2022-11-01 20:50
Same; Ventura 13.0 | Vagrant 2.3.2 | Virtual Box 7.0.2.

**Comment by Phally** [comment] 2022-11-02 15:00
Same problem here, with the same versions as mentioned above.

**Comment by JakubSzczerba** [comment] 2022-11-03 08:19
Find some solution.
![ss](https://user-images.githubusercontent.com/81684662/199673042-7b3f7bf9-256c-4145-9fda-30008cbf54c1.png)

Few steps:
1)
`sudo su
  csrutil clear`
2) Unistall from official unistaller andre-install Vbox
3) If prompted, go to System Preferences - Privacy - General and accept the extensions
4) Reebot
5) Add at Vagrant file `virtualbox__intnet: true` to your config.vm.network -> https://discuss.hashicorp.com/t/vagrant-up-fails-on-macos-13-x-ventura-with-latest-2-3-2-vagrant-release/46043/13
6) 
`VirtualBoxVM --startvm vagrant
vagrant up
`

This works for me.

**Comment by identifysun** [comment] 2022-11-03 09:10
> I found some solution. ![ss](https://user-images.githubusercontent.com/81684662/199673042-7b3f7bf9-256c-4145-9fda-30008cbf54c1.png)
> 
> **Few steps:** (https://apple.stackexchange.com/questions/408154/macos-big-sur-virtualbox-error-the-virtual-machine-has-terminated-unexpectedly-d) 1) `sudo su` ` csrutil clear` 2) Unistall from official unistaller andre-install Vbox 3) If prompted, go to System Preferences - Privacy - General and accept the extensions 4) Reebot 5) Add at Vagrant file `virtualbox__intnet: true` to your config.vm.network -> https://discuss.hashicorp.com/t/vagrant-up-fails-on-macos-13-x-ventura-with-latest-2-3-2-vagrant-release/46043/13 6) `VirtualBoxVM --startvm vagrant` `vagrant up`
> 
> This works for me.

Thanks @JakubSzczerba , It 's Ok for me.

**Comment by chrisroberts** [comment] 2022-11-03 18:16
Duplicate of #12959

**Closed by chrisroberts** 2022-11-03 18:16 UTC
Labels: bug

**Comment by Jos-de-Boss** [comment] 2022-11-04 08:53
> Anyone facing this issue do the following:
> 
> 1. Downgrade to 6.1.32 https://download.virtualbox.org/virtualbox/6.1.32/VirtualBox-6.1.32-149290-OSX.dmg
> 2. On the installer uninstall the current version, chances are you will need to go into settings and allow it to run
> 3. Run the following
> 
> ```shell
> sudo kextload -b org.virtualbox.kext.VBoxDrv
> sudo kextload -b org.virtualbox.kext.VBoxNetFlt
> sudo kextload -b org.virtualbox.kext.VBoxNetAdp
> sudo kextload -b org.virtualbox.kext.VBoxUSB
> ```
> 
> 4. This will trigger a permissions issue, go into settings and allow Oracle to run, then reboot, it should ask you to
> 5. On startup run 3) again and then `vagrant up` this works for me. 3) will need to be ran on every boot

This workaround is working for me with version 6.1.40. I wasn't getting the the notice to grant the permissions on version 6.1.32. Not sure if it's mandatory but I rebooted between uninstalling the old version and installing the new version as well.

It's a bit of a hassle having to run the kexload commands every time after boot but at least this works for now.

**Comment by Gekko0114** [comment] 2022-11-04 14:30
same problem
Can't we solve this problem without downgrading VM?

**Comment by JackSzwergold** [comment] 2022-11-05 05:00
@Gekko0114 Please look at this comment at the linked/related issue:

> “Currently the only workaround is to not configure a private network for your guest. Work is currently in progress to handle the new way host only networks are configured and used in macOS.”

The reality is the kernel extension hacks are a complete hack. There is no need for the kernel extensions for host only access in macOS 13 (Ventura) and the solution is to wait for Vagrant and possibly VirtualBox to be patched. Nothing more and nothing less.

**Comment by BodoHuber** [comment] 2022-11-05 11:55
I am having the same issue but it started with Mac OS Ventura.  I tried all things described here (turn SIP off, downgrade, reinstall, ...).  After all, I turned SIP on again and installed the latest and greatest Vagrant 2.3.2 because nothing solved the problem.  

Right now I believe the issue is because of this:

![image](https://user-images.githubusercontent.com/12612476/200114335-d7d72c73-bc91-4d29-84c5-79d16317336d.png)

mentioned [here](https://www.virtualbox.org/manual/ch06.html).

Even the latest Vagrant 2.3.2 uses the **hostonlyif** command to setup a host-only adapter for the guest VM.  But I think this needs to be changed for most recent Mac OS into some other commands to end up with a host-only network instead of a host-only adapter.  Because if I manually configure a host-only network, everything works like a charm again.  

The only way I could bypass the error is adding the _virtualbox__intnet: true_ statement to my private network config.  At least this keeps all my static ip settings and the VM boots with an internal network instead of a private network.  Since the internal network is not accessible by the host at all, I have to manually modify the network settings within the VirtualBox UI after successful boot of the VM to convert the internal network back into a private network.  I also had to manually add a host-only network with my preferred ip range which I have to use at the network "name" setting at the NIC configuration.  

After that, everything works like expected.  So no kernel extension issue at all with me, but non-working and legacy host-only adapter config by Vagrant on recent Mac OS.

**Comment by d4n3sh** [comment] 2022-11-05 14:09
I am just using innet (inter network) as a workaround for now.
```
  config.vm.define "n2" do |n2|
      n2.vm.hostname = "n2"
      n2.vm.network "private_network", ip: "192.168.56.11",
        virtualbox__intnet: true
  end
```

**Comment by Kolesar** [comment] 2022-11-07 14:54
When I use `virtualbox__intnet: true`, my vagrant machine is up and running. I can connect via SSH, but I have no public IP address, and I cannot ping or connect to any port directly via IP. So, my machine is useless :/

Any idea?

**Comment by BodoHuber** [comment] 2022-11-07 18:28
> When I use `virtualbox__intnet: true`, my vagrant machine is up and running. I can connect via SSH, but I have no public IP address, and I cannot ping or connect to any port directly via IP. So, my machine is useless :/
> 
> Any idea?

I did add the same flag to my private network config to be able to run „vagrant up“.  Then I use the VirtualBox GUI to manually modify the running machine and set its NIC to „host-only network“ instead of „internal network“.  In advance, you might want to manually add a host-only network in VirtualBox which fits your IP address range needs.  You want to refer to an existing network in the field „name“.  

The „host-only network“ is accessible from your host other than the internal network which is a guest-only network.  This might solve your situation…

This is a pretty unfortunate workaround, but the only one which worked for me…

**Comment by d4n3sh** [comment] 2022-11-08 02:00
> When I use `virtualbox__intnet: true`, my vagrant machine is up and running. I can connect via SSH, but I have no public IP address, and I cannot ping or connect to any port directly via IP. So, my machine is useless :/
> 
> Any idea?

using the `vagrant ssh` command to get in is not an option that works for you? 

I build an extra vagrant box that I use as a jump host. I `vagrant ssh` into that VM and then ssh to all the other vagrant boxes :)

**Comment by tallandtree** [comment] 2022-11-17 09:47
I seem to have the same issue with Vagrant 2.3.2 and VirtualBox 6.1.40 on Fedora 36: vagrant up doesn't work anymore. I've downgraded to 6.1.36 and my vagrant boxes work again. I've tried the workaround with the virtualbox_intnet: true, but that didn't work for me. So, maybe not quite the same issue, but it seemed network related. I couldn't find any real errors in the logging. It just didn't boot properly.

**Comment by identifysun** [comment] 2022-11-17 11:59
> I seem to have the same issue with Vagrant 2.3.2 and VirtualBox 6.1.40 on Fedora 36: vagrant up doesn't work anymore. I've downgraded to 6.1.36 and my vagrant boxes work again. I've tried the workaround with the virtualbox_intnet: true, but that didn't work for me. So, maybe not quite the same issue, but it seemed network related. I couldn't find any real errors in the logging. It just didn't boot properly.

Please use the latest versions of vagrant and virtualbox

```bash
$ vagrant --version
Vagrant 2.3.3

$ VBoxManage --version
7.0.2r154219
```

**Comment by JackSzwergold** [comment] 2022-11-17 16:12
Yes! Vagrant 2.3.3 solves the issue cleanly! I can start up my Vagrant boxes now and host-only works.
