### ISSUE TITLE
Vagrant Cloud API Box Create does not respect "is_private": false optional setting

### ISSUE THREAD

**Issue by laurenblackfox** [hashicorp/vagrant#9123] opened 2017-10-29 11:09 UTC
```
curl \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $token" \
  https://app.vagrantup.com/api/v1/boxes \
  --data '{ "box": { "username": "UserName",
    "name": "BoxName",
    "short_description": "ShortDescription",
    "description": "LongDescription",
    "is_private": false } }'
```
When the box is created, the private flag is always set to true. I want my boxes to be created as public.

**Comment by justincampbell** [comment] 2017-10-30 16:26
Thanks for the report, looking into this now.

**Comment by justincampbell** [comment] 2017-10-30 17:29
@laurenblackfox I wasn't able to reproduce this:

```
curl \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v1/boxes \
  --data '
    {
      "box": {
        "username": "justin_hashicorp",
        "name": "test-public",
        "is_private": false
      }
    }
  '

curl \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v1/boxes \
  --data '
    {
      "box": {
        "username": "justin_hashicorp",
        "name": "test-private",
        "is_private": true
      }
    }
  '
```

Created these boxes:

![](http://c.justincampbell.me/0o0B3b421G0R/Screen%20Shot%202017-10-30%20at%201.28.21%20PM.png)

**Comment by justincampbell** [comment] 2017-10-30 17:31
@laurenblackfox Can you post the output with `curl -i` (obscuring the token), as well as the JSON response from creating the box? Feel free to email support+vagrantcloud@hashicorp.com too if you prefer and I can take the ticket.

**Comment by briancain** [comment] 2017-12-07 18:10
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by jghalam** [comment] 2018-01-18 18:11
I know this issue may have been closed already. But I thought to add to it, just in case. I ran into the similar issue and I was able to resolve it. When I try to create a public box and include description and short_description, the "is_private" is ignored.
curl \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v1/boxes \
  --data '{ "box": { "username": "test_name",
    "name": "MyBox",
    "short_description": "short desc",
    "description": "extended description",
    "is_private": false } }'

Based on the posting on this page, then I tried to create a box without "short_description" and "description" params. This time worked as expected.

curl \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v1/boxes \
  --data '{ "box": { "username": "test_name",
    "name": "MyBox",
    "is_private": false } }'

I'm not sure if that's a bug, or if it is an expected behavior.

**Comment by justincampbell** [comment] 2018-01-18 20:21
@jghalam I'm not able to reproduce this. Are you sure that the only thing changed was the removal of description/short_description?

```
$ curl --header "Content-Type: application/json" --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/boxes --data '{
  "box": {
    "username": "justin_hashicorp",
    "name": "test-20180118",
    "short_description": "short description",
    "description": "description",
    "is_private": false
  }
}'

{"created_at":"2018-01-18T20:17:16.066Z","updated_at":"2018-01-18T20:17:16.066Z","tag":"justin_hashicorp/test-20180118","name":"test-20180118","short_description":"","description_html":
null,"username":"justin_hashicorp","description_markdown":null,"private":false,"current_version":null,"versions":[]}

$ curl --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/justin_hashicorp/test-20180118 | jq .private
false

$ curl -X DELETE --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/justin_hashicorp/test-20180118

$ curl --header "Content-Type: application/json" --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/boxes --data '{
  "box": {
    "username": "justin_hashicorp",
    "name": "test-20180118",
    "is_private": false
  }
}'

{"created_at":"2018-01-18T20:18:01.454Z","updated_at":"2018-01-18T20:18:01.454Z","tag":"justin_hashicorp/test-20180118","name":"test-20180118","short_description":"","description_html":null,"username":"justin_hashicorp","description_markdown":null,"private":false,"current_version":null,"versions":[]}

$ curl --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/justin_hashicorp/test-20180118 | jq .private
false

$ curl -X DELETE --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/justin_hashicorp/test-20180118
```

**Comment by jghalam** [comment] 2018-01-18 22:05
@justincampbell reposting the Python method (it didn't come out right in the last post):

def createBox(user, boxname, token, s_desc="Short Description", desc="Main Description"):
    import requests, json
    headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer '+token}
    url = 'https://app.vagrantup.com/api/v1/boxes'
    data = { "box": { "username": user, 
                      "name": boxname, 
                      "short_description": "%s" % s_desc,
                      "is_private": False,
                      }
             }
    r = requests.post(url, data=json.dumps(data), headers=headers)
    print r.text

**Comment by jghalam** [comment] 2018-01-18 22:18
I tried created 4 different boxes using the same python code, and here is the result:

<img width="1196" alt="vagrant" src="https://user-images.githubusercontent.com/6125899/35124281-5f88145a-fc5a-11e7-9c05-7253fbf2151f.png">

**Comment by justincampbell** [comment] 2018-01-23 17:31
I was able to reproduce this. The issue is if the box was created with the same name and `is_private: true` (the default), then deleted, if created again the `is_private` argument is ignored. We'll get this fixed internally shortly.

**Comment by jghalam** [comment] 2018-01-23 17:35
Thats great. Also, based on my observations, I think the same issue exists for other fields also. At least, I can see “short_description” behaves similarly.
Thanks,
Joe

**Comment by justincampbell** [comment] 2018-01-24 16:38
This was auto-closed via a commit message, but not deployed yet. Will let you all know when it’s fixed.

**Comment by justincampbell** [comment] 2018-01-24 22:02
We fixed an issue where deleting a box did not clean up all database models, which caused future boxes of the same name to inherit some attributes. The deletion code has been fixed, and any dangling models were cleaned up. Please let us know if you run into this again in the future, and thanks for your patience and help debugging it!

**Closed by justincampbell** 2018-01-24 22:02 UTC
Labels: vagrant cloud, waiting-reply
