### ISSUE TITLE
When running vagrant up on an already existing VM it fails to load json from samba share

### ISSUE THREAD

**Issue by tallen1983** [hashicorp/vagrant#9636] opened 2018-03-29 18:05 UTC
### Vagrant version
2.0.2 and 2.0.3

### Host operating system
Windows
### Guest operating system
Irrelevant

### metadata_url file in ~/.vagrant.d/boxes/< some string >/
file:////somesmbshare/foo-bar.json

### Debug output
Providing a snippet of the relevant debug log instead of a gist:
```
 INFO interface: output: ==> default: Checking if box 'FOO/bar' is up to date...
==> default: Checking if box 'FOO/bar' is up to date...
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: file://somesmbshare/foo-bar.json
 INFO downloader:   -- Destination: C:/Users/abcdefg/AppData/Local/Temp/vagrant-load-metadata20180329-10476-dwhheh

...

DEBUG subprocess: stderr: * Invalid file://hostname/, expected localhost or 127.0.0.1 or none
* Closing connection -1
curl: (3) Invalid file://hostname/, expected localhost or 127.0.0.1 or none
```

### Expected behavior
The json file is pulled from the network share

### Actual behavior
The json file is not pulled from the network share.

### Steps to reproduce
1. Put a json descriptor on an smbshare.
2. Point the metadata_url file at this smbshare
3. Run `vagrant up`

### Alternative Steps to reproduce
1. Put a json descriptor on an smbshare.
2. Run `vagrant up` to bring up a new box

### Attempted Workaround
If you use 6 forwardslashes (file://////somesmbshare/foo-bar.json) it gets you past the error above, however it then errors with the following:
```
 INFO interface: output: ==> default: Checking if box 'FOO/bar' is up to date...
==> default: Checking if box 'FOO/bar' is up to date...
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: file:////somesmbshare/foo-bar.json
 INFO downloader:   -- Destination: C:/Users/abcdefg/AppData/Local/Temp/vagrant-load-metadata20180329-10476-dwhheh

...

DEBUG subprocess: stderr: * SMB shares are not supported in file: URLs.
* Closing connection -1
curl: (3) SMB shares are not supported in file: URLs.
```

It appears the update from curl 7.56.0 to 7.57.0 has broken smb support in file URLs. The offending commit in curl is https://github.com/curl/curl/commit/25634611f983824503cd708f0b65dddf028c3026
Unfortunately, vagrant appends "file:" in front of virtually anything you give it that isn't a web url, so we can't use whatever curl expects an smb share to look like ("//somesmbshare/foo-bar.json" perhaps?)

### Working Workaround
Go back to 2.0.1 where it worked to use an smb share in a file: URL.

**Comment by The4thLaw** [comment] 2018-04-06 12:52
I can confirm this.

Attempting to ceate a new Vagrant from scratch also fails with the following error:

`SMB shares are not supported in file: URLs`

I could replicate this error by calling the embedded curl manually.

**Comment by TomaszDom** [comment] 2018-04-25 10:54
This is basic functionality for us, we keep our boxes on a network share and Vagrantfile configurations point to them, now everything is broken. It's easily reproducible on Windows 10, had to roll back to version 2.0.1.

**Comment by chrisroberts** [comment] 2018-04-25 14:13
This was due to a bug in curl and Vagrant 2.0.4 ships with a patched version of curl to fix the file:// protocol usage. Please upgrade to 2.0.4 and let me know if you are still experiencing issues. Thanks!

**Comment by datosh** [comment] 2018-04-25 14:45
Thanks for the reply! Updating to Vagrant 2.0.4 works for me when using
```
config.vm.box_url = "file://////<share>/<catalogue>.json
```
and in the catalogue .json file
```
"url": "file://////<share>/<base>.box
```

**Comment by tallen1983** [comment] 2018-04-25 14:51
@chrisroberts correct, it is now fixed, however you have to use 6 forward slashes instead of the previous 4. That leaves all existing boxes broken (as the metadata_url file for existing boxes overrides what is in the Vagrantfile, which I still don't understand). I'd rather not have to tell all of our box consumers to destroy/create or manually edit that file...

**Comment by chrisroberts** [comment] 2018-04-25 19:14
@tallen1983 @datosh Thanks for the confirmation that 2.0.4 fixed the underlying issue.

@tallen1983 With regards to the requirement of the extra `//`, I will investigate this a bit more within the curl code base. My assumption is that the behavior being exhibited now will be the behavior of the protocol going forward. If I can validate that, I will see if it's reasonable to add detection and auto-modification where applicable.

**Comment by tallen1983** [comment] 2018-04-25 19:18
@chrisroberts the remaining 6 forward slashes issue isn't a curl issue. That one is a vagrant issue. You guys recently changed how you parse urls. You rip stuff off the front, then put some back on. It just isn't done correctly 😄.

I'll try to find the offending code in vagrant again. I'm not 100% familiar with the vagrant codebase so it may take me a few minutes.

**Comment by tallen1983** [comment] 2018-04-25 19:27
@chrisroberts ok I can't find the vagrant code that I was referring to. But what I can tell you is the curl binary you guys ship with works with 4 slashes when I call it directly. If I pass it 6 slashes directly it will not download the file.
So somewhere along the way Vagrant is stripping the slashes down from 6 to 4, or from 4 to 2, which is causing issues.

**Comment by chrisroberts** [comment] 2018-04-25 19:29
@tallen1983 Okay then I'll go dig for that. Thanks!

**Comment by chrisroberts** [comment] 2018-04-25 23:28
Thanks for pointing out the SMB path issue. The fix will be included in the next release.

Cheers!

**Closed** 2018-04-26 21:44 UTC
Labels: host/windows, installer

**Comment by chrisroberts** [comment] 2018-06-29 20:08
@sparris9 can you create a new issue and include a debug gist for inspection? Thanks!
