### ISSUE TITLE
vagrant up command config.vm.boot_timeout issue

### ISSUE THREAD

**Issue by chetansatasiya** [hashicorp/vagrant#9938] opened 2018-06-15 15:44 UTC
I am using vagrant 2.2.1 on windows 10, now when I run the command `vagrant up` I got this below error.

![image](https://user-images.githubusercontent.com/7081284/41408740-4fc51cd8-6ff1-11e8-8825-759b24ab9942.png)

### Actions I have taken so far.
1. I've re-installed the vagrant and virtual box.
2. Tried on the different system. ( win10 )
3. I've searched for the solution on the google, GitHub, and StackOverflow.

**Tried all the possible solutions, nothing was so much helpful. :(**

## Expected Behavior
The command should run properly without having any error. 

## Current Behavior
Getting timeout error (see screenshot)

## Steps to Reproduce (for bugs)
1. Run `vagrant up` command

## Context
I think this happened when I have added an ssh key to the system.

## Your Environment
* VVV version: 2.2.1
* VVV Git Branch: `master`
* Vagrant version: 2.1.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.12
* Operating System and version: Windows 10 64bit

**Comment by chetansatasiya** [comment] 2018-06-15 15:46
Also, I am using VVV for the WordPress and I am following this steps https://varyingvagrantvagrants.org/docs/en-US/installation/software-requirements/ to install VVV on my machine.

**Comment by drujd** [comment] 2018-06-21 08:37
We have been facing a similar problem on some machines, which we resolved by downgrading Vagrant version to 2.0.1. Maybe caused by #9676 ?

**Comment by briancain** [comment] 2018-06-21 18:49
Hey! This _should_ be fixed in this pull request #9923 which will be out in the next release. I'll leave this open until that gets shipped to track the issue. Thanks!

**Comment by oussaka** [comment] 2018-06-24 10:37
it's a bug that made me waste a lot of time. I am waiting with imapatience the new version.

**Comment by chrisroberts** [comment] 2018-06-27 22:28
This is resolved in the 2.1.2 release.

Cheers!

**Closed by chrisroberts** 2018-06-27 22:28 UTC
Labels: host/windows
