### ISSUE TITLE
Windows 10 (1709), vagrant stopped working after windows update. Installed latest vagrant 2.0.2 & Virtualbox 5.2.8 and it just hangs...

### ISSUE THREAD

**Issue by stijlfigurant** [hashicorp/vagrant#9579] opened 2018-03-15 16:36 UTC
### Vagrant version
2.0.2 + Virtualbox 5.2.8

### Host operating system
Windows 1709

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 443
  
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.ssh.username = 'REDACTED'
  config.ssh.password = 'REDACTED'
  
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "_vagrant/puppet/manifests"
    puppet.module_path = "_vagrant/puppet/modules"
    puppet.manifest_file = "default.pp"
  end
end
```

### Debug output
https://gist.github.com/stijlfigurant/84949f2e2989950a04a1fea4f731b2e2

### Expected behavior
Just run

### Actual behavior
Gets stuck at `aqcuired process lock`

### Steps to reproduce
1. Start with a broken vagrant
2. Uninstall vagrant
3. Uninstall virtualbox
4. Remove .vagrant.d
5. Install latest vagrant
6. Install latest virtualbox
7. Practice patience

**Comment by samriddhi** [comment] 2018-03-20 00:01
This is happening to me as well. 
Vagrant 2.0.3 
Virtualbox 5.2.8
Windows 1709

`# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end`

After running vagrant up it hangs for the default amount of time 300 and then pops an error 

![image](https://user-images.githubusercontent.com/5325345/37628541-1bafd77e-2b97-11e8-9590-fa849bb34155.png)

Is there a fix for this?

**Comment by samriddhi** [comment] 2018-03-20 00:28
@stijlfigurant I figured it out, if you update your machine then you have to turn your virtualization from UFEI settings 

setting ==> Update&Security ==> Recovery ==> Advance startup ==> Click(restart now)

after restart 

Troubleshoot ==> Advanced options ==> Select UEFI Firmware Settings ==> Click 
Restart. 

Turn on your virtualization to enabled.

**Comment by briancain** [comment] 2018-04-24 22:00
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2018-04-24 22:00 UTC
Labels: waiting-reply

**Comment by jpruiz114** [comment] 2018-06-21 12:16
Hello,

This is still an issue. After every Windows update, my vagrant machines keep breaking. Mine is stuck at the SSH step. Any workaround for it?

Thanks.
