### ISSUE TITLE
2.2.10 fails with vagrant up in WSL 1

### ISSUE THREAD

**Issue by jamus-cambium** [hashicorp/vagrant#11855] opened 2020-08-26 20:32 UTC
Vagrant 2.2.10 is not working for us when we run it from WSL 1.  This is happening on multiple systems.  Vagrant 2.2.9 works fine.

### Vagrant version
WSL: 2.2.10
Windows: 2.2.10

### Host operating system
Windows 10
WSL Version: 1
WSL OS: Ubuntu 18.04.1

### Guest operating system
Linux (Ubuntu)

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
end
```

### Expected behavior

`vagrant up` should succeed with starting and provisioning  the virtual machine.

### Actual behavior

`vagrant up` fails with:
```/opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:1213:in `__connect_nonblock': Operation already in progress - connect(2) for 127.0.0.1:2222 (Errno::EALREADY)```

Full debug log is here: https://gist.github.com/jamus-cambium/37785ee5f5f7dae46b4ed747eee07441.

### Steps to reproduce

1. `vagrant up`

### Workaround

Running `vagrant up` from a command prompt outside of WSL works.  We can then use other vagrant commands (like `vagrant ssh`) from WSL.

**Comment by evilprophet** [comment] 2020-09-04 09:24
I have the same issue :/

**Comment by Stefan075** [comment] 2020-09-06 13:13
[vagrant.log](https://github.com/hashicorp/vagrant/files/5179683/vagrant.log)

Same issue here, except that `vagrant up` outside WSL is not available. Upgrading from vagrant 2.2.9 to 2.2.10 lead to the same error message.
Vagrantfile:
```
Vagrant.configure("2") do |config|

  config.vm.box_check_update = true
  config.vm.synced_folder '/mnt/c/shared/vagrant', '/vagrant'

  ## 2 ubuntu VMs 
  (10..11).each do |i|
    config.vm.define "ubuntu#{i}" do | ubuntu |
      ubuntu.vm.box = "bento/ubuntu-18.04"
#      ubuntu.vm.name = "ubuntu#{i}"
      ubuntu.vm.hostname = "ubuntu#{i}"
      ubuntu.vm.network "private_network", ip: "192.168.50.#{i}"
      ubuntu.vm.provision "shell", path: "provision-ubuntu.sh"
    end
  end 

  ## 2 centos VMs
  (20..21).each do |i|
    config.vm.define "centos#{i}" do | centos |
      centos.vm.box = "bento/centos-8"
#      centos.vm.name = "centos#{i}"
      centos.vm.hostname = "centos#{i}"
      centos.vm.network "private_network", ip: "192.168.50.#{i}"
      centos.vm.provision "shell", path: "provision-centos.sh"
    end
  end

  config.vm.provider "virtualbox" do |v|
    # add vboxmanage customizations here:
    # https://www.vagrantup.com/docs/virtualbox/configuration.html
    # "convenience shortcuts for memory and CPU settings:" (per link above), tweak to your machine's capabilities to speed up VMs:
    v.memory = 2048
    v.cpus = 2
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
```

**Comment by jakauppila** [comment] 2020-09-09 17:29
I'm having this issue as well on WSL1 with CentOS 7.

Works fine on 2.2.10 on Windows 10.

**Comment by AsharLohmar** [comment] 2020-09-13 21:25
I confirm the same issue.
### Host operating system
Windows 10 2004  19041.508
WSL Version: 1
WSL OS: Ubuntu 18.04.5 LTS

### Vagrant installed versions
WSL: 2.2.10

### Guest operating system
Alpine Linux 3.12.0

### Workaround
I've got rid of the issue by reverting to 2.2.9.

**Comment by shed-00** [comment] 2020-09-21 20:31
Same here.

**Host**
Windows 10.0.18363
WSL 1

**Guest OS**
Linux (Ubuntu)

**Vagrant Versions**
`vagrant -v`
WSL1: 2.2.10
Windows: 2.2.10

Expected / Actual Behavior matches description from original poster.

**Comment by thangnqs** [comment] 2020-09-27 07:45
How fix error with version 2.2.10?

**Comment by gardart** [comment] 2020-10-08 11:31
same issue here with 2.2.10

**Comment by phillashworth** [comment] 2020-10-26 05:02
Me too with 2.2.10

**Comment by mattabdou** [comment] 2020-10-26 21:01
Had the same issue with 2.2.10 on Ubuntu 20.04 in WSLv1. Downgraded to 2.2.9 and `vagrant up` works again from WSLv1.

**Comment by jamieburchell** [comment] 2020-10-28 14:46
> Had the same issue with 2.2.10 on Ubuntu 20.04 in WSLv1. Downgraded to 2.2.9 and `vagrant up` works again from WSLv1.

Same. Hoping that this is a bug and not something that is going to get dropped in light of what it says in the docs:

> Vagrant must be installed within the Linux distribution used with WSL. While the vagrant.exe executable provided by the Vagrant Windows installation is accessible from within the WSL, it will not function as expected.

**Comment by AsharLohmar** [comment] 2020-10-28 15:27
It's been a (relatively) long time since that is no longer valid/required.
I mean I work with vagrant installed only within the linux distro, I have `VBoxManage.exe`  in my PATH, actually `/mnt/c/Program Files/Oracle/VirtualBox`, and I've created 2 aliases
```
alias vboxmanage="VBoxManage.exe"
alias VBoxManage="VBoxManage.exe"
``` 
and everything works fine, at least with the 2.2.9 (and previous).

**Comment by jamieburchell** [comment] 2020-10-28 16:47
> It's been a (relatively) long time since that is no longer valid/required.

Good to know. I too have a similar setup with some aliases pointing to `vagrant.exe`

**Comment by Stefan075** [comment] 2020-11-14 08:59
I've updated Vagrant to version 2.2.13 on the WSL1 Ubuntu 18.04 yesterday. The vagrant machines starts now without any problems. I don't have any other Vagrants implementations yet to test version 2.2.13 but it seems to be that this issue can be closed.

**Comment by AsharLohmar** [comment] 2020-11-16 09:12
Thanks @Stefan075 for the news. I confirm that the issue is no longer present after upgrading to the 2.2.13.

**Comment by soapy1** [comment] 2021-03-12 20:05
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by soapy1** 2021-03-12 20:05 UTC
Labels: WSL, needs-investigation
