### ISSUE TITLE
ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by EthanLXGu** [hashicorp/vagrant#9798] opened 2018-05-07 15:19 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.1.0
VirtualBox Manager 5.2.10

### Host operating system
Centos7.0

### Guest operating system
Centos7.0

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```
### Expected behavior
I just follow the documentation, vagrant up works, but stuck in 
```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
```
And also vagrant ssh will connection time out, 
```
vagrant ssh
ssh_exchange_identification: read: Connection reset by peer
```

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: vagrant_getting_started_default_1525704353463_72622
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

I already checked some closed issues, but still cannot figure out how to make it work. Thanks.

**Comment by briancain** [comment] 2018-05-07 16:27
Hi there @EthanLXGu - I recommend trying to use the [bento/centos-7.2](https://app.vagrantup.com/bento/boxes/centos-7.2) box instead. This issue is often caused by a misconfiguration in the vagrant box. Thanks!

**Comment by EthanLXGu** [comment] 2018-05-08 00:56
@briancain Hi, I tired [bento/centos-7.2](https://app.vagrantup.com/bento/boxes/centos-7.2), still got same issue, i installed virtual box and vagrant by yum in my centos box, is there some special setting for vagrant with virtual box?

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7.2' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/centos-7.2'
    default: URL: https://vagrantcloud.com/bento/centos-7.2
==> default: Adding box 'bento/centos-7.2' (v2.3.1) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/centos-7.2/versions/2.3.1/providers/virtualbox.box
==> default: Successfully added box 'bento/centos-7.2' (v2.3.1) for 'virtualbox'!
==> default: Importing base box 'bento/centos-7.2'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7.2' is up to date...
==> default: Setting the name of the VM: vagrant_getting_started_default_1525740673124_93458
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by briancain** [comment] 2018-05-08 16:11
@EthanLXGu - If you open the VirtualBox gui after running `vagrant up` is the machine running? Can you log in, see if it has networking with `ip addr` and check if sshd is running? Are there any errors in syslog? Firewall running? Can you ssh into it outside of the Vagrant cli? Thanks!

**Comment by EthanLXGu** [comment] 2018-05-09 12:41
@briancain @kikitux Hi, Thanks. My linux box cannot open any GUI, so directly use command
```
VBoxManage controlvm "vagrant_getting_started_default_1525740673124_93458" poweroff
can poweroff the vm

BoxManage startvm "vagrant_getting_started_default_1525740673124_93458" --type headless
Waiting for VM "vagrant_getting_started_default_1525740673124_93458" to power on...
VM "vagrant_getting_started_default_1525740673124_93458" has been successfully started.
```
But still got vagrant ssh
ssh_exchange_identification: read: Connection reset by peer this error when i want to vagrant ssh.

**Comment by briancain** [comment] 2018-05-09 21:16
If you bring up the same vm with vboxmanage can you ssh into it outside of the vagrant cli tool?

**Comment by EthanLXGu** [comment] 2018-05-10 00:36
@briancain Hi, Thanks. I run ```ssh -p 2222 vmname@localhost
ssh_exchange_identification: read: Connection reset by peer`` still cannot access, this is the vm setting.

```
    <Hardware>
      <CPU>
        <PAE enabled="true"/>
        <LongMode enabled="true"/>
        <X2APIC enabled="true"/>
        <HardwareVirtExLargePages enabled="false"/>
      </CPU>
      <Memory RAMSize="512"/>
      <Display VRAMSize="16"/>
      <BIOS>
        <IOAPIC enabled="true"/>
      </BIOS>
      <Network>
        <Adapter slot="0" enabled="true" MACAddress="5254005F9478" type="82540EM">
          <NAT>
            <DNS use-proxy="true" use-host-resolver="true"/>
            <Forwarding name="ssh" proto="1" hostip="127.0.0.1" hostport="2222" guestport="22"/>
          </NAT>
        </Adapter>
        <Adapter slot="1" enabled="true" MACAddress="080027E21656" type="82540EM">
          <DisabledModes>
            <InternalNetwork name="intnet"/>
            <NATNetwork name="NatNetwork"/>
          </DisabledModes>
          <HostOnlyInterface name="vboxnet1"/>
        </Adapter>
      </Network>
      <AudioAdapter driver="ALSA" enabled="true" enabledIn="false" enabledOut="false"/>
      <RTC localOrUTC="UTC"/>
    </Hardware>
```

**Comment by briancain** [comment] 2018-05-10 16:03
Hi there @EthanLXGu - thanks for checking on that for me. Unfortunately that's something outside of Vagrant. If you can't ssh into the VM directly then Vagrant won't be able to either :( You might be able to get more help on the mailing list, but otherwise I'm going to close the issue since it isn't an issue with Vagrant.

**Closed by briancain** 2018-05-10 16:03 UTC
Labels: waiting-reply

**Comment by HR555** [comment] 2018-06-06 09:43
@EthanLXGu Did you find the reason for the issue, I am getting the same issue when I try to ssh in.

**Comment by ManFromEast** [comment] 2018-06-29 02:34
I have the same problem,

**Comment by chetanyachopra** [comment] 2018-08-01 05:59
@EthanLXGu facing same issue did you find any fix for this !!
