### ISSUE TITLE
vagrant up fails for  `module_eval': stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by bashartwal** [hashicorp/vagrant#10641] opened 2019-02-03 12:26 UTC
Good Day Everyone,

I have installed Vagrant on fresh Windows 10. Vagrant installed successfully an its working fine on global box like centos/7, however, im trying to run a box for a colleague of mine but it failed for the below error (after vagrant up)

C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:54:in `module_eval': stack level too deep (SystemStackError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:54:in `module_eval'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:54:in `unset_log'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:26:in `block in undefine_methods'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:24:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:24:in `undefine_methods'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:16:in `define_methods'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/log4r-1.1.10/lib/log4r/logger.rb:37:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/kernel_v2/config/push.rb:11:in `new'
         ... 707 levels...
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/up/command.rb:87:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/cli.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:291:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/bin/vagrant:182:in `<main>'

The same box is working fine on my other machine which is running vagrant on windows 7, can someone advice what could be the issue.

Current Machine:
Windows 10
Vagrant 2.2.3
Virtualbox 5.2.16

Old Machine:
Windows 7
Vagrant 1.9.6
virtualbox 5.0.18

Im more than happy to share the box with anyone who would like to test it.

**Comment by chrisroberts** [comment] 2019-02-04 16:45
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by briancain** [comment] 2019-02-26 20:49
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2019-02-26 20:49 UTC
Labels: waiting-reply

**Comment by KSym04** [comment] 2020-03-27 04:34
Is there a fix already regarding this? got same issues, thanks
