### ISSUE TITLE
"URL using bad/illegal format or missing URL" when adding box with a relative path

### ISSUE THREAD

**Issue by truhlikfredy** [hashicorp/vagrant#12359] opened 2021-05-11 17:31 UTC
This is similar to existing issue GH-12320, but it's different as the invalid URL is generated by Vagrant itself.
When I'm running `vagrant add box` with a relative path (the box file is exactly where my CWD is), yet the Vagrant will generate an invalid URL.

```
$ vagrant box add --name my-box my-box.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'my-box' (v0) for provider:
    box: Unpacking necessary files from: file://D/work/vagrant-extras/my-box.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

So I have to explicitly make the absolute path for it
`$ vagrant box add --name renode-builder-windows10-v3 file:///d:/work/vagrant-extras/my-box.box`

Should the tool when is generating the absolute path, to generate it in the format it excepts it?

### Vagrant version

Vagrant 2.2.16

### Host operating system

Windows 10 64-bit 1809

### Guest operating system

Windows 10 64-bit (don't think it's relevant)

### Vagrantfile

Didn't even got to the Vagrantfile yet.

### References

- GH-12320

**Comment by countzero** [comment] 2021-05-19 07:52
I am also encountering this bug in Vagrant v2.2.16.

If you are running the `--debug` option you can see that Vagrant utilizes `curl` to load the box:

```
INFO subprocess: Starting process: [
    "C:\\HashiCorp\\Vagrant\\embedded\\bin/curl.EXE", 
    "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", 
    "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.7) ", "--continue-at", "-", 
    "--output", "C:/Users/USERNAME/.vagrant.d/tmp/boxc7e428cd76569427a4bcbf540530d5d390690593", 
    "file://D/work/vagrant-extras/my-box.box"
]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: * Closing connection -1
curl: (3) URL using bad/illegal format or missing URL
```
The problem lies in the missing colon (:) in the generated file protocol URI!

Try opening `file://D/work/vagrant-extras/my-box.box` in your browser and it will also fail. 

The correct syntax is `file://D:/work/vagrant-extras/my-box.box`!

@soapy1 I think this bug is caused somewhere prior to the `curl` invocation in the Vagrant codebase. I think the Bug was not present in v2.2.14!

**Comment by countzero** [comment] 2021-05-19 08:15
**Note:** The three slashes of the file URI are correct. The schema is `file://host/path` and if the host part is omitted `localhost` is assumed, but the slash must stay. i.e.:

`file:///my-box.box` === `file://localhost/my-box.box`

@soapy1 Perhaps the bugfix can include the fully quallified name with a speaking `localhost` to avoid misunderstandings?

**Comment by soapy1** [comment] 2021-05-20 14:25
@countzero, very true! I believe that is part of [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986). 

> @soapy1 Perhaps the bugfix can include the fully quallified name with a speaking localhost to avoid misunderstandings?

Since this kind of behavior is defined in that RFC, I think sticking to `///` is fine.

> @soapy1 I think this bug is caused somewhere prior to the curl invocation in the Vagrant codebase. I think the Bug was not present in v2.2.14!

Yep, seems to be!

**Comment by kmbgit** [comment] 2021-05-25 12:10
I tested on Windows 10 with Vagrant versions 2.2.10, 2.2.14, 2.2.15 and 2.2.16.  The first 2 were reported by colleagues as working, the last is the one I had the problem with, and 2.2.15 is there to see where the error was introduced.  My observation is that versions up to 2.2.15 inclusive work correctly, with `vagrant box add --name my-vm mv-vm.box` run from directory `C:/HashiCorp/my-vm` reporting **box: Unpacking necessary files from: file://C:/HashiCorp/my-vm/my-vm.box**.  Note that the successful URL is technically invalid because it begins **file://C:** rather than **file:///C:** - there's a missing "/".

The problem is only seen in version 2.2.16, and it can be corrected by reverting `embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb` to its previous version...

`$ diff -U0 box_add.rb.orig box_add.rb
--- box_add.rb.orig     2021-04-29 18:37:46.000000000 +0100
+++ box_add.rb  2021-05-25 12:46:59.247976200 +0100
@@ -129 +129 @@
-            add_direct(authed_urls, env)
+            add_direct(url, env)
`

...so something in the magic that creates `authed_urls` is removing the crucial colon from the drive letter.

**Comment by sp1icer** [comment] 2021-05-26 19:18
For what it's worth, I can also confirm what @kmbgit mentions with absolute paths being correctly changed to the correct URI. Windows 10 with 2.2.16 here. If needed, I can provide more info on my setup, but seems to me that the answers in the above thread have already pretty much nailed it down.

**Comment by breisig** [comment] 2021-05-26 21:00
This issue is happening for us in Vagrant 2.2.16

**Comment by mdepot** [comment] 2021-05-27 12:02
As countzero mentions above, I agree the problem is the missing colon.  Here is a test to show this.

```
vagrant box add --name centos-79 centos-7.9.virtualbox.box --debug

...
 INFO interface: detail: Unpacking necessary files from: file://C/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box
 INFO interface: detail:     box: Unpacking necessary files from: file://C/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box
    box: Unpacking necessary files from: file://C/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box
 INFO downloader: Downloader starting download:
 INFO downloader:   -- Source: file://C/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box
 INFO downloader:   -- Destination: C:/Users/Mike/.vagrant.d/tmp/box507dafe8deff1d87c86381aa559c5c34c97e3b67
 INFO subprocess: Starting process: ["C:\\HashiCorp\\Vagrant\\embedded\\bin/curl.EXE", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.7) ", "--continue-at", "-", "--output", "C:/Users/Mike/.vagrant.d/tmp/box507dafe8deff1d87c86381aa559c5c34c97e3b67", "file://C/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: * Closing connection -1
curl: (3) URL using bad/illegal format or missing URL
...

```
In the debug output above, at the end of the curl command you can see that vagrant built an absolute path file:// url using the  just a supplied filename in the current dir, and then called curl with this file:// url.

According to the curl docs here: [https://github.com/curl/curl/blob/master/docs/URL-SYNTAX.md](https://github.com/curl/curl/blob/master/docs/URL-SYNTAX.md)
you will find that on windows a colon or a pipe is required in file:// urls when using a drive letter:

_"curl accepts that the FILE URL's path starts with a "drive letter". That's a
single letter `a` to `z` followed by a colon or a pipe character (`|`)."_

The debug output from vagrant does not include the colon.

So let's try a test to see if this is the actual problem:

First try a simple curl call using the exact file:// url from the debug output above:

```
C:\Users\Mike\Desktop\builds>C:/HashiCorp/Vagrant/embedded/bin/curl.exe --output delete-me file://C/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box
curl: (3) URL using bad/illegal format or missing URL
```

Now try the same command again, but with the colon added:

```
C:\Users\Mike\Desktop\builds>C:/HashiCorp/Vagrant/embedded/bin/curl.exe --output delete-me file://C:/Users/Mike/Desktop/builds/centos-7.9.virtualbox.box
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  329M  100  329M    0     0  1214M      0 --:--:-- --:--:-- --:--:-- 1285M
```

So it would seem to fix this, vagrant should add a colon when it builds the absolute path file:// url on windows.

**Comment by soapy1** [comment] 2021-06-23 17:41
This issue is resolved by https://github.com/hashicorp/vagrant/pull/12419 🎉

**Closed by soapy1** 2021-06-23 17:41 UTC
Labels: core, host/windows
