### ISSUE TITLE
Vagrant port forward dosen't work on External IP Address on Google Compute Engine

### ISSUE THREAD

**Issue by CodeFarmer1995** [hashicorp/vagrant#10231] opened 2018-09-24 14:38 UTC
Here is the network status:

```
ens4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
        inet 10.146.0.2  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::4001:aff:fe92:2  prefixlen 64  scopeid 0x20<link>
        ether 42:01:0a:92:00:02  txqueuelen 1000  (Ethernet)
        RX packets 284259  bytes 2249676951 (2.2 GB)
        RX errors 0  dropped 0  overruns 0  frame 6
        TX packets 282598  bytes 245643368 (245.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 47611  bytes 6105239 (6.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 47611  bytes 6105239 (6.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lxcbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.3.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::216:3eff:fe00:0  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 51007  bytes 4351349 (4.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 57232  bytes 545587526 (545.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethGKC7RL: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc6c:dff:fe81:8e94  prefixlen 64  scopeid 0x20<link>
        ether fe:6c:0d:81:8e:94  txqueuelen 1000  (Ethernet)
        RX packets 271  bytes 30520 (30.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 260  bytes 27379 (27.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Name | Network | Subnetwork | Primary internal IP | Alias IP ranges | External IP | Network Service Tier | IP forwarding
-- | -- | -- | -- | -- | -- | -- | --
nic0 | default | default | 10.146.0.2 | — | static-ip-jp (35.200.75.125) | Premium | Off

Here is the ports forward:

```
default: 9991 (guest) => 9991 (host) (adapter eth0)
default: 9994 (guest) => 9994 (host) (adapter eth0)
```
I can access the port `9991` and `9994` from the `localhost` and the internal ip `10.146.0.2`,but I can't access from  external IP 35.200.75.125.

```
root@chat:~/zulip# telnet 35.200.75.125 9991
Trying 35.200.75.125...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by CodeFarmer1995** [comment] 2018-09-24 14:42
```
root@chat:~/zulip# lsof -i:9991
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
redir   29152 root    4u  IPv4 894227      0t0  TCP localhost:9991 (LISTEN)
```
It seems that it only listens on localhost. I tried to set the [host_ip ](https://www.vagrantup.com/docs/networking/forwarded_ports.html#host_ip) with the external IP,but it did't work.

**Comment by briancain** [comment] 2018-09-24 16:06
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by briancain** [comment] 2018-10-08 21:13
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2018-10-08 21:13 UTC
Labels: needs info, waiting-reply
