### ISSUE TITLE
$HOME/.vagrant.d/tmp grows arbitrarily large

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9751] opened 2018-04-30 16:18 UTC
When `vagrant package` exports a box, this often leaves behind junk files in `$HOME/.vagrant.d/tmp` that grow quite large over time. After working with some boxes for a few months, I ended up with over 100GiB wasted here. As a workaround, I carefully deleted the child files and folders there, but I would rather Vagrant intelligently clean up this junk as a TRAPEXIT or such for `vagrant package`, or perhaps place these files at `/tmp` rather than `$HOME/.vagrant.d/tmp`, so that the host OS has a chance to clean these up. Computers exist to automate, not to create additional manual labor!

### Vagrant version

Vagrant 2.0.2

### Host operating system

Multiple hosts affected: macOS High Sierra and Windows 10 Professional

### Guest operating system

Multiple guests affected: Linux, BSD, macOS, Windows, Solaris, Haiku, MINIX, ...

**Comment by chrisroberts** [comment] 2018-04-30 16:26
Duplicate of #9593

**Closed by chrisroberts** 2018-04-30 16:26 UTC
