### ISSUE TITLE
No guest IP was given to the Vagrant core NFS helper.

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9118] opened 2017-10-28 16:58 UTC
### Vagrant version

2.0.0

### Host operating system

macOS Sierra

### Guest operating system

NetBSD 7

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "kja/netbsd-7-amd64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
end
```

### Expected behavior

Vagrant ideally sets up a working /vagrant mount for NetBSD via NFS. Or, Vagrant reports an error with how the NetBSD guest OS has difficulty integrating with NFS.

### Actual behavior

```console
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'kja/netbsd-7-amd64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'kja/netbsd-7-amd64' is up to date...
==> default: Setting the name of the VM: vagrant-netbsd-cpp_default_1509209664494_18896
==> default: Fixed port collision for 22 => 2222. Now on port 2201.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2201 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...
==> default: Checking if machine supports zones: no
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

### Steps to reproduce
1. `vagrant up`

**Comment by briancain** [comment] 2017-10-30 16:54
@mcandre  Could you please provider a gist to the debug output for this error? Thanks!

**Comment by briancain** [comment] 2017-11-28 18:17
Closing this, as it is a duplicate of #7070. Thanks!

**Closed by briancain** 2017-11-28 18:17 UTC
Labels: waiting-reply
