### ISSUE TITLE
Vagrant-aws plugin installation fails due to required "Ruby version >= 2.5" from dependency

### ISSUE THREAD

**Issue by rkl3ss** [hashicorp/vagrant#11518] opened 2020-04-14 16:32 UTC
As from object: our team need to install the _Vagrant AWS_ plugin, but the command **vagrant plugin install vagrant-aws** terminates with the following error:
```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ovirt-engine-sdk requires Ruby version >= 2.5.
```
We tried to install some depencies with separate commands, but we faced the same issue.
We also tried to manually install the last Roìuby version on the local machine, but it didn't help (I'm not familiar with Ruby language and framework, but I suspect that this is a dependency issue unrelated to my local environment).
I work on a Windows environment, Windows 10 x64 (build 17763), and I installed Vagrant 2.2.7, which should be the last version.

Can you please help us to address this problem?
If you need any further information, I will be glad to gather them for you.

Below the complete command output, as reference:
```
PS C:\> vagrant -v
Vagrant 2.2.7
PS C:\> vagrant plugin install vagrant-aws
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Fetching: iniparse-1.5.0.gem (100%)
Fetching: xmlrpc-0.3.0.gem (100%)
Fetching: formatador-0.2.5.gem (100%)
Fetching: excon-0.73.0.gem (100%)
Fetching: fog-core-1.45.0.gem (100%)
Fetching: mini_portile2-2.4.0.gem (100%)
Fetching: nokogiri-1.10.9-x64-mingw32.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.10, libxslt-1.1.34, zlib-1.2.11, libiconv-1.15.
Fetching: fog-xml-0.1.3.gem (100%)
Fetching: fog-xenserver-1.0.0.gem (100%)
Fetching: optimist-3.0.0.gem (100%)
Fetching: rbvmomi-2.4.1.gem (100%)
Fetching: fog-vsphere-3.3.0.gem (100%)
Fetching: fog-voxel-0.1.0.gem (100%)
Fetching: CFPropertyList-2.3.6.gem (100%)
Fetching: fission-0.5.0.gem (100%)
Fetching: fog-vmfusion-0.1.0.gem (100%)
Fetching: fog-terremark-0.1.0.gem (100%)
Fetching: fog-json-1.2.0.gem (100%)
Fetching: fog-storm_on_demand-0.1.1.gem (100%)
Fetching: fog-softlayer-1.1.4.gem (100%)
Fetching: fog-serverlove-0.1.2.gem (100%)
Fetching: fog-sakuracloud-1.7.5.gem (100%)
Fetching: fog-riakcs-0.1.0.gem (100%)
Fetching: fog-radosgw-0.0.5.gem (100%)
Fetching: ipaddress-0.8.3.gem (100%)
Fetching: fog-rackspace-0.1.6.gem (100%)
Fetching: fog-profitbricks-4.1.1.gem (100%)
Fetching: fog-powerdns-0.2.0.gem (100%)
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ovirt-engine-sdk requires Ruby version >= 2.5.
```

**Comment by jbonhag** [comment] 2020-04-14 17:33
Hi there,

Thanks for opening an issue with Vagrant! We've got good news -- the next Vagrant release (v2.2.8) will include Ruby 2.6.5 or higher. That should resolve the issue you're seeing currently.

Cheers and have a great day! :smile:

**Comment by jbonhag** [comment] 2020-04-14 17:34
Duplicate of #11516

**Closed by jbonhag** 2020-04-14 17:33 UTC

**Comment by rkl3ss** [comment] 2020-04-15 09:44
> 
> 
> Hi there,
> 
> Thanks for opening an issue with Vagrant! We've got good news -- the next Vagrant release (v2.2.8) will include Ruby 2.6.5 or higher. That should resolve the issue you're seeing currently.
> 
> Cheers and have a great day! 😄

Thank you very much for your feedback!
Just one more question: is there an ETA for the next release? When it'll be available approximately?
