### ISSUE TITLE
platform.rb:115:in `cygwin_path': undefined method `gsub!' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by starrychloe** [hashicorp/vagrant#9037] opened 2017-10-07 01:41 UTC
I was running this from a Windows command line for `vagrant up`. Although I do have Cygwin, I wasn't in a Cygwin shell. 

### Vagrant version
C:\Users\Chloe\workspace\vps>vagrant -v
Vagrant 2.0.0

### Host operating system
Windows 8.1

### Guest operating system
==> default: Checking if box 'centos/7' is up to date...
==> default: A newer version of the box 'centos/7' is available! You currently
==> default: have version '1702.01'. The latest is version '1708.01'. Run

### Vagrantfile
```
C:\Users\Chloe\workspace\vps>grep -v ^# Vagrantfile | grep -v "^\s*$"
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 43110, host: 43110
  config.vm.network "forwarded_port", guest: 15441, host: 15441
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
  config.vm.provision "shell", run: "always", inline: <<-SHELL
                mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant
                mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` dash
/dash
                mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` zeronet /home/vagrant/ZeroBundle/ZeroNet
                service tor start
                mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` ipfs
/ipfs
  SHELL
end
```

### Debug output
https://gist.github.com/starrychloe/622bcd5638b84e95ee0ea66ea6f41c8a

### Expected behavior
It should have brought the box up without an exception.

### Actual behavior
It crashed with a stack trace.

### Steps to reproduce
1. `vagrant up`

**Comment by rschuetzler** [comment] 2017-10-09 14:20
I have the same with the base `Vagrantfile` from `vagrant init centos/7`. Also with Vagrant 2.0.0 on Windows 10.

**Comment by briancain** [comment] 2017-10-09 17:36
Hi @starrychloe - I see the gist you provided is saying that vagrant is using rsync, but I do not see a synced_folder config option in your Vagrantfile.

**Comment by rschuetzler** [comment] 2017-10-13 02:35
I was able to get it running just fine with Vagrant 1.9.8 on another machine.

**Comment by shakman9999** [comment] 2017-10-16 18:09
Same problem here using Win10 and a vanilla Vagrantfile using Vagrant 2.0.0.

**Comment by briancain** [comment] 2017-10-16 18:19
This is still likely a duplicate of #8960 and has already been fixed and will be released in the next version of Vagrant. If this is still occurring when we release the next version with the fix, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by briancain** 2017-10-16 18:19 UTC
