### ISSUE TITLE
Port Vagrant to Go

### ISSUE THREAD

**Issue by XVilka** [hashicorp/vagrant#10649] opened 2019-02-05 15:33 UTC
Ruby is not very popular nowadays and harder to port/deploy to a new platforms.
Obviously you already know this since your all other services written in Go. Maybe it is time to ditch the last barrier and port Vagrant to Go too?

https://github.com/golang/go/wiki/FromXToGo#ruby

**Comment by chrisroberts** [comment] 2019-02-05 16:39
Duplicate of #10431

**Closed by chrisroberts** 2019-02-05 16:39 UTC
