### ISSUE TITLE
hyperv: "default switch" is invalid

### ISSUE THREAD

**Issue by kopfpilot** [hashicorp/vagrant#9787] opened 2018-05-04 23:10 UTC
It is not possible to select the defautl switch with Hyper-V on windows 10.

The changelogs for 2.1.0 indicate that config.vm.network will require the ID instead of the name now.
Anyway, I tried both:
- config.vm.network "Standardswitch"
- config.vm.network 69 (which is the result of `(Get-NetAdapter -Name "vEthernet (Standardswitch)").ifIndex`

output:
* Network type '69' is invalid. Please use a valid network type.

When I try with the name, of course 'Stadardswith' is displayed instead of '69'.

**Comment by chrisroberts** [comment] 2018-05-04 23:30
Duplicate of #9774

**Closed by chrisroberts** 2018-05-04 23:30 UTC
