### ISSUE TITLE
No host IP was given to the Vagrant core NFS helper.

### ISSUE THREAD

**Issue by utkonos** [hashicorp/vagrant#9203] opened 2017-11-18 08:59 UTC
### Vagrant version
Vagrant 2.0.1

### Host operating system
macOS 10.13.1 (17B48)

### Guest operating system
Ubuntu Server 17.10 x64 (DigitalOcean)

### Vagrantfile
https://gist.github.com/utkonos/a1d2f3d0a021580ef3e3636f40b09ea8

### Debug output
https://gist.github.com/utkonos/5d51009f034359cb3850c632f68b2d49

### Expected behavior
Normal vagrant up

### Actual behavior
Error: No host IP was given to the Vagrant core NFS helper.

### Steps to reproduce
Use the above Vagrantfile and run `vagrant up`

**Comment by utkonos** [comment] 2017-11-18 09:00
If I add the following to the Vagrantfile, the VM boots normally:

```
override.vm.synced_folder '.', '/vagrant', :disabled => true
```

**Comment by briancain** [comment] 2017-11-28 18:17
Closing this, as it is a duplicate of #7070. Thanks!

**Closed by briancain** 2017-11-28 18:17 UTC
