### ISSUE TITLE
vagrant failed to create a new vmware networking device - the services doesn't seem to have a PID associated with it

### ISSUE THREAD

**Issue by parviijedi** [hashicorp/vagrant#12163] opened 2021-01-31 05:36 UTC
I'm using Big Sur 11.1, Fusion 12.1.0, Vagrant Plugin 2.2.14, Vagrant VMWare Utility 1.0.18.

**Comment by chrisroberts** [comment] 2021-02-04 18:23
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment] 2021-03-08 19:16
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by chrisroberts** 2021-03-08 19:16 UTC
Labels: host/darwin, needs info, needs-debug-gist, provider/vmware, waiting-reply
