### ISSUE TITLE
Multiple Nic support ?

### ISSUE THREAD

**Issue by kujinke** [hashicorp/vagrant#11240] opened 2019-12-07 00:04 UTC
### Vagrant version
Vagrant 2.2.6

### Host operating system
Windows 10 pro.

### Guest operating system
Centos 7.6

### Vagrantfile
```ruby
    config.vm.provider "hyperv" do |hv|
	  config.vm.network "private_network", bridge: "internal"
	  config.vm.network "public_network", bridge: "external"
		
        hv.vmname = config.vm.hostname
        hv.memory = 4096
        hv.cpus = 4
        hv.vm_integration_services = {
            guest_service_interface: true,
            time_synchronization: true
        }    
    end
```

### Expected behavior
Create the second external nic.

### Actual behavior
Only creates one nic.

### Steps to reproduce
recreate vm with vagrant up.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
none.

Can this issue be addressed?

Not only its not possible to add a secondary nic, which makes hyper-v provider useless if you want to also have an external network access nic, its also not possible to hack a way to get this to work somehow. if I create an external script and run it using a trigger, every time the Configure class kicks in it will run over any secondary nic I have added, and change it to the internal one.

**Comment by kujinke** [comment] 2019-12-07 15:44
OK, I have managed to fix the code myself.

So I created my own fork for the hyperv provider with multiple nics support, is there a requirement that I share it here? Or are you going to add this type of support later?

**Comment by jerinrajan23** [comment] 2020-04-01 12:57
@kujinke can you share the code for multiple nic or selecting a newly created VNIC(internal) in hyperv in Vagrantfile ?

**Comment by briancain** [comment] 2020-05-19 21:46
Hey there, I am going to close this issue as it is a duplicate of https://github.com/hashicorp/vagrant/issues/8849. Cheers!

**Closed by briancain** 2020-05-19 21:46 UTC
