### ISSUE TITLE
Checksup fail despite correct value

### ISSUE THREAD

**Issue by bristol-d** [hashicorp/vagrant#13369] opened 2024-03-20 16:02 UTC
Trying to download a vagrant box:

    vagrant box add zenshade/mint64-xfce-20

Gets me this error:

    ==> box: Loading metadata for box 'zenshade/mint64-xfce-20'
    box: URL: https://vagrantcloud.com/api/v2/vagrant/zenshade/mint64-xfce-20
    ==> box: Adding box 'zenshade/mint64-xfce-20' (v1.0.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/zenshade/boxes/mint64-xfce-20/versions/1.0.0/providers/virtualbox/unknown/vagrant.box
    box:
    box: Calculating and comparing box checksum...
    The checksum of the downloaded box did not match the expected
    value. Please verify that you have the proper URL setup and that
    you're downloading the proper file.
    
    Expected: 5cdefeacdd0259ea666f1112211af306  package.box
    Received: 5cdefeacdd0259ea666f1112211af306

I'm not sure what's happening here, but those two hash values are the same.

If it helps,

    vagrant --version
    Vagrant 2.4.1

Both vagrant and virtualbox freshly installed on a Win10/intel i7-8700 machine.

**Comment by chrisroberts** [comment] 2024-07-15 17:22
Closing as duplicate of #13470

**Closed by chrisroberts** 2024-07-15 17:22 UTC
Labels: waiting-intake
