### ISSUE TITLE
Vagrant 1.9.4: mount.nfs: access denied by server while mounting 33.33.33.1

### ISSUE THREAD

**Issue by giancarloandroid** [hashicorp/vagrant#8540] opened 2017-04-29 14:51 UTC
### Vagrant version
Vagrant 1.9.4

### Host operating system
Ubuntu 16.10 x86_64

### Guest operating system
Ubuntu 13.10 x64

### Vagrantfile
```ruby
Vagrant::Config.run do |config|

    # Configure the VM box to use
    config.vm.box = 'ubuntu-server'
#    config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box'
  	config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-1310-x64-virtualbox-puppet.box'

# Configure VM Ram usage
   config.vm.customize ["modifyvm", :id,
        "--memory", "1024",
        "--cpus", "2"
        ]

    # Configure network and port forwarding
    config.vm.network :hostonly, "33.33.33.10"
    config.vm.forward_port 80, 8080,      :auto => true  # HTTP
    config.vm.forward_port 5433, 5433,  :auto => true  # Postgresql
	config.vm.forward_port 9000, 9000,  :auto => true  # FPM

    #config.vm.forward_port 27017, 27017 # MongoDB

    # Configure shared folders
    config.vm.share_folder "vagrant-root", "/vagrant", ".", :nfs => true
    config.vm.share_folder "www", "/var/www", "..", :nfs => true
	config.vm.share_folder "puppet", "/tmp/vagrant-puppet", "puppet", :nfs => true

    # Configure provisioning
    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.module_path = "puppet/modules"
    end
end
```

### Debug output
https://gist.github.com/giancarloandroid/f27cfad52c4b8a9f26b9e354caa52452

### Expected behavior
Virtual machine started with success

### Actual behavior
```ruby
mount.nfs: access denied by server while mounting 33.33.33.1:/home/giancarlo/Documentos/Programacao/Vagrant/vagrant-symfony-psql
 INFO interface: Machine: error-exit ["Vagrant::Errors::NFSMountFailed", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\nmount -o vers=3,udp 33.33.33.1:/home/giancarlo/Documentos/Programacao/Vagrant/vagrant-symfony-psql /vagrant\n\nStdout from the command:\n\n\n\nStderr from the command:\n\nmount.nfs: access denied by server while mounting 33.33.33.1:/home/giancarlo/Documentos/Programacao/Vagrant/vagrant-symfony-psql\n"]
```
### Steps to reproduce
1. git clone https://github.com/giancarloandroid/vagrant-symfony-psql.git
2. cd vagrant-symfony-psql
3. vagrant up

**Comment by zkanda** [comment] 2017-05-02 04:44
Happening to me as well, it seems like the last it's trimming the ip address from your `Vagrantfile`

You have `33.33.33.10` but the mount command is using `33.33.33.1`

**Comment by tauil** [comment] 2017-05-15 21:52
Same here.

**Comment by UmanShahzad** [comment] 2017-05-27 17:35
Same.

**Comment by tauil** [comment] 2017-05-27 19:23
I "fixed" my problem by removing the nfs option.

**Comment by vipinroy** [comment] 2017-11-02 15:36
Same problem here. please help.

**Comment by AyumuKasuga** [comment] 2018-01-01 14:04
same problem

**Comment by JustBlackBird** [comment] 2018-01-07 18:16
Same here

**Comment by NHellFire** [comment] 2018-01-10 20:31
I've just had this with an Ubuntu 14.04 guest. It seems some versions default to sec=krb5. Adding `sec=sys` to `mount_options` fixed it for me. See [Specifying NFS Arguments](https://www.vagrantup.com/docs/synced-folders/nfs.html#specifying-nfs-arguments). Might not be your issue, but worth a try.

**Comment by chrisroberts** [comment] 2018-03-27 15:53
This should be resolved in recent versions of Vagrant. If you are still experiencing this issue after upgrading, please create a new issue and I will investigate further.

Cheers!

**Closed by chrisroberts** 2018-03-27 15:53 UTC
Labels: synced-folders/nfs

**Comment by GolubovicM** [comment] 2018-10-08 09:45
Can it be caused by this issue: https://stackoverflow.com/questions/20726248/vagrant-error-nfs-is-reporting-that-your-exports-file-is-invalid
