### ISSUE TITLE
Commands Not in Installer of VMWare Fusion 8.5.8 Pro

### ISSUE THREAD

**Issue by JackTiber** [hashicorp/vagrant#8916] opened 2017-08-25 02:05 UTC
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant v1.9.8

### Host operating system
macOS Sierra 10.12.6

### Guest operating system
Ubuntu 16.04 Server LTS

### Vagrantfile
Vagrant.configure("2") do |config|
  config.ssh.insert_key = 'false'
  config.ssh.password = 'vagrant'
  config.ssh.port = '22'
  config.ssh.keys_only = 'false'
  config.vm.box = "test"
  ["vmware_workstation", "vmware_fusion"].each do |vmware_provider|
    config.vm.provider(vmware_provider) do |vmware|
      vmware.whitelist_verified = true
    end
  end
  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
  end
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/JackTiber/ab3614029cbc2f7dcd1ac131484018aa

### Expected behavior
Vagrant should be able to connect to VM. 

### Actual behavior
Vagrant hangs on trying to resolve IP of VM while running vmrun list or getIpAddress commands, which return as not in installer, restoring original environment...

### Steps to reproduce
1. I am trying to boot a vmx build that is made into a box with the post-processor. It has minimal libraries / items provisioned, and from the debug log this looks to be more in the vagrant VMware plugin than in the box itself. I have tried editing the path and it failed the up command. I can call the vmrun list by running ' /Applications/VMware\ Fusion.app/Contents/Library/vmrun list' in a shell.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
Not that I have found. LOT of Googling going on over here.

**Comment by william-voyek** [comment] 2017-08-25 23:08
I'm experiencing the same issue. I get it running again with:
`sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --stop && sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --start`

It seems like the networking isn't getting taken care of properly.

**Comment by chrisroberts** [comment] 2017-08-28 16:38
Are you able to reproduce this behavior with any publicly available boxes?

**Comment by JackTiber** [comment] 2017-08-28 17:34
Honestly have not tried a ton of public vagrant boxes, but it did reproduce itself using the below packer template repo by @geerlingguy.

https://github.com/geerlingguy/packer-ubuntu-1604 - if you are trying this, you will need to update the iso url and checksums, otherwise the template is fine. 

He has another thread running that it looks like to be on the same subject that goes a bit deeper into why vagrant hangs at Waiting to Boot, but I didn't discover that until yesterday. Looks like this has been an open issue since last Oct. and has to do with VMware's systemd processes.

https://github.com/geerlingguy/packer-ubuntu-1604/issues/13

Using Virtualbox, the custom box boots easily, so I have resigned myself to using VB for the time being and waiting till someone at Hasicorp or VMware address this in an update.

**Comment by william-voyek** [comment] 2017-08-28 19:26
I'm using Laravel Homestead: https://github.com/laravel/homestead. It's the only vagrant box I'm using.

**Comment by JackTiber** [comment] 2017-08-30 15:36
Makes sense. We need to have some custom boxes setup for repetitive development environments. I managed to get this working, although tracking down the exact reason to why it is working is minimal as I only changed the preseed.cfg to allow for full-update to the installed packages on the box. Amazingly, this either corrected an issue that was keeping VMware from listing the IPv4 of the box or fixed something in Ubuntu that was causing that as well. 

No idea, but zero edits to the actual template for that exception.

**Comment by chrisroberts** [comment] 2018-03-27 15:39
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Closed by chrisroberts** 2018-03-27 15:39 UTC
Labels: provider/vmware
