### ISSUE TITLE
Ansible provisioner unable to run on Vagrant 2.1.5

### ISSUE THREAD

**Issue by pkaramol** [hashicorp/vagrant#10281] opened 2018-10-10 09:03 UTC
### Vagrant version

```
(master)$ vagrant --version
Vagrant 2.1.5
```

### Host operating system

```
(master)$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
/home/pkara/Workspace/gitlab/awx-mesos-inf-update
(master)$ uname -a
Linux pkara-pc01 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
### Hypervisor
Virtualbox Version 5.2.18 r124319 (Qt5.6.1)

### Guest operating system
`ubuntu/xenial64`

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = true

  config.vm.network "private_network", ip: "192.168.33.10"

 
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "4096"
  end

  config.vm.provision "ansible" do |ansible|
   ansible.limit = "all"
   ansible.compatibility_mode = "2.0"
   ansible.playbook = "ansible/install.yml"
  end
end

```

### Debug output
[gist](https://gist.github.com/pkaramol/f07567cb3b0d442555ff18456610e69b)

### Expected behavior
vagrant box should be provisioned with `ansible`

### Actual behavior
Provisioning fails as follows:

```
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
ImportError: No module named site
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I even tried to execute the command shown in the debug output via an explicit call to `subprocess` as I guess it is done in `vagrant` if I can infer correctly from the gist pasted above and it seems to run

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> 
>>> subprocess.call(["/usr/bin/ansible-playbook", "--connection=ssh", "--timeout=30", "--limit=all", "--inventory-file=/home/pkara/Workspace/gitlab/mdr-deployment/.vagrant/provisioners/ansible/inventory", "ansible/install.yml"])


PLAY [all] *****************************************************************************************************************************************************************************************************

TASK [Install python2 for Ansible] *****************************************************************************************************************************************************************************
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is SHA256:fRxTUZ9v+nYrRsuSv0LOYRwFy7Jxq6rpuDu5n2SN3AA.
Are you sure you want to continue connecting (yes/no)? yes
changed: [default]

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [default]

```

I also tried to downgrade `ansible` from `2.7.0` to `2.4` but the end result was the same.

currently:

```
$ ansible --version
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

**Comment by chrisroberts** [comment] 2018-10-10 14:08
Duplicate of #10276. Using the `.deb` package should resolve the issue for now. There is a problem with appimage finding the correct things on the host which I should have resolved in the next release. Cheers!

**Closed by chrisroberts** 2018-10-10 14:08 UTC

**Comment by chrisroberts** [comment] 2018-10-10 23:36
Issue has been identified and resolved. The fix will be available in the next release. Cheers!
