### ISSUE TITLE
Vagrant box add fails

### ISSUE THREAD

**Issue by sayanganguly-97** [hashicorp/vagrant#9278] opened 2017-12-15 12:41 UTC
I am trying to install open edx ginkgo release on a machine running Windows Server 2008. But, vagrant box add --name BOX command fails to add the box. I have tried it with ficus release box file, and the result is same.

### Vagrant version
Vagrant 2.0.1. I downgraded to Vagrant 1.9.6. but the problem is not solved.

### Host operating system

Windows Server 2008

### Guest operating system

Open edx ginkgo fullstack
http://files.edx.org/vagrant-images/ginkgo-fullstack-2017-08-14.box

### Vagrantfile
```ruby
Vagrant.require_version ">= 1.8.7"
unless Vagrant.has_plugin?("vagrant-hostsupdater")
  raise "Please install the vagrant-hostsupdater plugin by running `vagrant plugin install vagrant-hostsupdater`"
end

VAGRANTFILE_API_VERSION = "2"

MEMORY = 6144
CPU_COUNT = 2

# map the name of the git branch that we use for a release
# to a name and a file path, which are used for retrieving
# a Vagrant box from the internet.
openedx_releases = {
  "open-release/ginkgo.1rc1" => "ginkgo-fullstack-2017-07-14",
  "open-release/ginkgo.1" => "ginkgo-fullstack-2017-08-14",

  "open-release/ficus.1rc3" => "ficus-fullstack-2017-02-07",
  "open-release/ficus.1rc4" => "ficus-fullstack-2017-02-15",
  "open-release/ficus.1" => "ficus-fullstack-2017-02-15",
  "open-release/ficus.2" => "ficus-fullstack-2017-03-28",
  "open-release/ficus.3" => "ficus-fullstack-2017-04-20",

  "open-release/eucalyptus/1rc1" => "eucalyptus-fullstack-1rc1",
  "open-release/eucalyptus.1rc2" => "eucalyptus-fullstack-2016-08-19",
  "open-release/eucalyptus.1" => "eucalyptus-fullstack-2016-08-25",
  "open-release/eucalyptus.2" => "eucalyptus-fullstack-2016-09-01",

  "named-release/dogwood" => {
    :name => "dogwood-fullstack-rc2", :file => "20151221-dogwood-fullstack-rc2.box",
  },
  "named-release/dogwood.1" => {
    :name => "dogwood-fullstack-rc2", :file => "20151221-dogwood-fullstack-rc2.box",
  },
  "named-release/dogwood.2" => {
    :name => "dogwood-fullstack-rc2", :file => "20151221-dogwood-fullstack-rc2.box",
  },
  "named-release/dogwood.3" => {
    :name => "dogwood-fullstack-rc2", :file => "20151221-dogwood-fullstack-rc2.box",
  },
  "named-release/dogwood.rc" => {
    :name => "dogwood-fullstack-rc2", :file => "20151221-dogwood-fullstack-rc2.box",
  },
  # Cypress is deprecated and unsupported
  # Birch is deprecated and unsupported
}
openedx_releases.default = "ginkgo-fullstack-2017-08-14"

openedx_release = ENV['OPENEDX_RELEASE']
boxname = ENV['OPENEDX_BOXNAME']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  boxfile = ""
  if not boxname
    reldata = openedx_releases[openedx_release]
    if Hash == reldata.class
      boxname = openedx_releases[openedx_release][:name]
      boxfile = openedx_releases[openedx_release].fetch(:file, "")
    else
      boxname = reldata
    end
  end
  if boxfile == ""
    boxfile = "#{boxname}.box"
  end

  # Creates an edX fullstack VM from an official release
  config.vm.box     = boxname
  config.vm.box_url = "http://files.edx.org/vagrant-images/#{boxfile}"
  config.vm.box_check_update = false

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder  ".", "/vagrant", disabled: true
  config.ssh.insert_key = true

  config.hostsupdater.aliases = ["preview.localhost"]

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_s]
    vb.customize ["modifyvm", :id, "--cpus", CPU_COUNT.to_s]

    # Virtio is faster, but the box needs to have support for it.  We didn't
    # have support in the boxes before Ficus.
    if !(boxname.include?("dogwood") || boxname.include?("eucalyptus"))
      vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    end
  end
end

```

### Debug output

https://gist.github.com/sayanganguly-97/df7e1d65e7bd23251d4dc7b8ae81791d

**Comment by briancain** [comment] 2017-12-19 17:19
@sayanganguly-97 - Are you able to add other boxes just fine, or does this happen with every vagrant box you try? Thanks!

**Comment by sayanganguly-97** [comment] 2017-12-20 09:59
No, I could not add other boxes. I tried with precise64 box file, but it gave the same error.

**Comment by iNode** [comment] 2018-02-17 06:17
I'm experiencing similar issue on linux (vagrant 2.0.2). Investigation shows that server responds by html page instead of image file and as result it can't uncompressed by bsdtar. 

This issue seems to be related to server infrastructure rather than client side.

I've experienced this issue with each image I've tried and updated from 1.8.1 to 2.0.2 as part of troubleshooting, both are failing in the same way.

Examples of images tried last times:
generic/arch
hashicorp/precise64
ubuntu/trusty64

Example of curl command from debug file:
 INFO subprocess: Starting process: ["/opt/vagrant/embedded/bin/curl", "-I", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/2.0.2 (+https://www.vagrantup.com; ruby2.4.3)", "--continue-at", "-", "-H", "Accept: application/json", "https://vagrantcloud.com/generic/arch"]

**Comment by briancain** [comment] 2018-02-20 17:47
@iNode - you are probably experiencing this issue https://github.com/hashicorp/vagrant/issues/9442. Thanks!

**Comment by iNode** [comment] 2018-03-09 11:48
Thanks you for the suggestion, but issue was resolved without any changes on client side so this was probably server a side issue. May be some record from DNS cache to misconfigured server was refreshed. And there initially was no 404 exit code. But thank you anyway.

**Comment by chrisroberts** [comment] 2018-05-03 22:58
Hi there,

Are you still encountering this issue with the latest Vagrant release?

**Comment by briancain** [comment] 2018-10-08 21:18
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2018-10-08 21:18 UTC
Labels: core, host/windows, needs-repro, waiting-reply
