### ISSUE TITLE
Vagrant 2.2.13 (.10?) breaks working NFS shared folders on Windows

### ISSUE THREAD

**Issue by AsgeirSH** [hashicorp/vagrant#12059] opened 2020-11-19 22:36 UTC
Repo exhibiting issue available at https://github.com/ukmnorge/servere

### Vagrant version
Working: 2.2.5
Broken: 2.2.13 (latest) - relevant code changed in 2.2.10 afaics

### Host operating system
Windows 10 Pro (Note: No extra NFS-support turned on in "Turn Windows Features on or off", although enabling them did not make the setup work on 2.2.13)
Provider: VirtualBox version 6.0

### Guest operating system
Ubuntu Bionic64, box 20190508.0.0
Guest Additions 6.0.6

### Vagrantfile

```ruby
# Share UKMlib folder
share(main, 'main/ukmlib', '/etc/php-includes/UKM/')

[..]

# Share folder between vm and host
def share(box, localpath, serverpath)   
    localpath = requireServerDataFolder(localpath)
    box.vm.synced_folder localpath, serverpath, type: "nfs", create: true
    puts '    mount point: '+ localpath +' => '+ serverpath
end
```

### Expected behavior
On vagrant 2.2.5, the mount is created without issue and is working as expected from the Windows host. 🥳

### Actual behavior
On vagrant 2.2.13, vagrant complains that the machine does not support NFS, and halts booting the VM.

```
It appears your machine doesn't support NFS, or there is not an adapter to enable NFS on this machine for Vagrant. Please verify that `nfsd` is installed on your machine, and try again. If you're on Windows, NFS isn't supported. If the problem persists, please contact Vagrant support.
``` 

### Steps to reproduce

1. Create a Vagrantfile with a Ubuntu or other NFS-capable linux box, on a Windows 10 Pro host
2. Configure an NFS share with type: "nfs" as above
3. Run vagrant up

This has been tested on two different machines, one a completely fresh install on a Win10 Pro system, another upgraded from older versions.

[Link to boot log](https://gist.github.com/AsgeirSH/3df2748d538146adf9ae31e5fd3ae34d)

### References
- GH-9909 - says Vagrant ignores nfs and uses vboxsf. In my testing, 2.2.5 does seem to be using nfs, though I don't know if there's a way to verify that no fallback has been used. No info in boot log about that.
- EDIT: See also [GH-9463](https://github.com/hashicorp/vagrant/issues/9463) - where the conclusion was that the optional NFS Services Feature of Win10 was for an NFS client and not a server and the issue then closed. However, for mounting shares, that's all we need and so it should not disable NFS functionality completely.

### Debugging measures taken

As far as I can tell, the relevant change is in bc898e385, included from 2.2.10 and onwards. It changes the check for NFS, and raises `NFSNotSupported`, which stops the vagrant up process.

It seems like [synced_folders/nfs/synced_folder.rb#L33](https://github.com/hashicorp/vagrant/blob/main/plugins/synced_folders/nfs/synced_folder.rb#L33) returns false, based on [plugins/hosts/windows/cap/nfs.rb](https://github.com/hashicorp/vagrant/blob/main/plugins/hosts/windows/cap/nfs.rb).

That check is the same for all editions of Windows as far as I can tell, although an NFS Client now seems to be working by default in Win10 Pro. Can we update the check somehow to consider this?

**Comment by chrisroberts** [comment] 2020-11-19 23:25
Closing as duplicate of: #11986 (https://github.com/hashicorp/vagrant/issues/11986#issuecomment-722038330)

**Closed by chrisroberts** 2020-11-19 23:25 UTC
