### ISSUE TITLE
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long

### ISSUE THREAD

**Issue by Tusshu** [hashicorp/vagrant#10196] opened 2018-09-08 18:30 UTC
Using MacOs High Sierra 10.13.6
Downloaded and installed Vagrant 2.1.4
Downloaded coreos-vagrant
vagrant up output is as below:

Installing plugins: vagrant-ignition
Installing the 'vagrant-ignition' plugin. This can take a few minutes...
Installed the plugin 'vagrant-ignition (0.0.3)'!
Installing plugins: vagrant-ignition
Installing the 'vagrant-ignition' plugin. This can take a few minutes...
Installed the plugin 'vagrant-ignition (0.0.3)'!
Installing plugins: vagrant-ignition
Installing the 'vagrant-ignition' plugin. This can take a few minutes...
Installed the plugin 'vagrant-ignition (0.0.3)'!
Installing plugins: vagrant-ignition

... above message appears more than 50 times.... and finally...

Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
Installation of one or more plugins has failed. Aborting.

Help please!

**Comment by briancain** [comment] 2018-09-10 15:24
This looks to be a duplicate of #10178 which is a bug. If you downgrade to a previous version of Vagrant it should fix the errors you're seeing. Thanks!

**Closed by briancain** 2018-09-10 15:24 UTC

**Comment by niccoX** [comment] 2018-09-12 08:45
The downgrade to 2.1.2 didn't help now instead of the install loop of:

```
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.16.0)'!
```
which ends with:

```
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long
```

now I just get a loop of these error lines.
