### ISSUE TITLE
Error after vagrant upgrade to 2.0.1

### ISSUE THREAD

**Issue by michaelknurr** [hashicorp/vagrant#9165] opened 2017-11-09 11:05 UTC
### Vagrant version
$ vagrant -v
Vagrant 2.0.1

### Host operating system
Windows 7

### Guest operating system
Centos

### Vagrantfile
plain vagrantfile

### Debug output
$ vagrant up
C:/Programme/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- log4r (LoadError)
        from C:/Programme/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Programme/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:61:in `<main>'

$ vagrant plugin list
C:/Programme/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- log4r (LoadError)
        from C:/Programme/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Programme/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:61:in `<main>'

### Expected behavior
start of vm / list of plugins

### Actual behavior
error messsage

### Steps to reproduce
1. install vagrant 2.0.1
2. open shell
3. type: vagrant up

**Comment by michaelknurr** [comment] 2017-11-09 14:17
Installing vagrant 1.9.8 showed the same problem. I now rolled back to vagrant 1.9.4 which is working for me.

**Comment by janview** [comment] 2017-11-21 10:06
This seems to be a problem with the installation path. We also changed it at installation to `C:/Programme/~` wich is not the default path vagrant would use. When using the default `C:/HashiCorp/~` everything works fine...

**Comment by Simran-B** [comment] 2018-03-28 11:58
I can confirm that the error does not occur if the default path is used to install Vagrant 2.0.3.

**Comment by cardillos** [comment] 2018-05-03 00:43
Any other fix on this problem? I am facing the same issue
Vagrant version: 2.0.4
Operating system: Windows 10 OS
Installation path:  C:\HashiCorp\Vagrant

**Comment by soapy1** [comment] 2020-04-17 20:33
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by soapy1** 2020-04-17 20:33 UTC
Labels: host/windows, installer, needs-repro
