### ISSUE TITLE
error after update to vagrant 2.3.6 on rhel 8.8 with libvirt

### ISSUE THREAD

**Issue by gentooise** [hashicorp/vagrant#13190] opened 2023-05-31 16:09 UTC
### Debug output

https://gist.github.com/gentooise/7ed3e521c71a2eb590a3368b3199517d

Of course libvirt is installed:

```
sudo rpm -q libvirt
libvirt-8.0.0-19.module+el8.8.0+18453+e0bf0d1d.x86_64
```

### Expected behavior

`vagrant up` should bring VM up without issues.

### Actual behavior

`vagrant up` and `vagrant plugin install vagrant-libvirt` are failing

#### Vagrant version

Vagrant 2.3.6

#### Host operating system

RHEL 8.8

#### Guest operating system

Any.

https://app.vagrantup.com/generic/boxes/ubuntu2004

#### Steps to reproduce

1. vagrant up
2. vagrant plugin install vagrant-libvirt

#### Vagrantfile

https://app.vagrantup.com/generic/boxes/ubuntu2004

**Comment by chrisroberts** [comment] 2023-05-31 16:14
I believe this is a duplicate of #13184. Can you please confirm if you have the libvirt development package installed?

**Comment by gentooise** [comment] 2023-05-31 16:21
Yes I have libvirt-devel installed. I was using vagrant every day before update.

```
sudo rpm -q libvirt-devel
libvirt-devel-8.0.0-19.module+el8.8.0+18453+e0bf0d1d.x86_64
```

**Comment by chrisroberts** [comment] 2023-05-31 16:45
Looks related to/duplicate of #11020. [This comment](https://github.com/hashicorp/vagrant/issues/11020#issuecomment-974222044) includes some likely relevant information. However, I'm going to spin up some guests to run some install tests on and see if we can fix some of this on the installer side.

**Comment by gentooise** [comment] 2023-05-31 20:46
I think the exact problem is stated in this comment: https://github.com/openssl/openssl/issues/11471#issuecomment-609645505

**Comment by chrisroberts** [comment] 2023-05-31 22:21
Yes, that appears to be very relevant. However, an unrelated [change](hashicorp/vagrant-installers#278) in the package generation recently (updating to openssl 3) looks like it might resolve this issue currently. Would you mind trying the recent [nightly build](https://github.com/hashicorp/vagrant/releases/tag/2.3.7.dev%2B000016-1b63ba85) and see if that works for you?

**Comment by gentooise** [comment] 2023-06-01 07:21
I removed 2.3.6 and all the files, and then picked the `vagrant-2.3.7.dev-1.x86_64.rpm`:

```
sudo dnf remove vagrant
sudo rm -rf /opt/vagrant
sudo rpm -i vagrant-2.3.7.dev-1.x86_64.rpm 
vagrant plugin install vagrant-libvirt
```

and it worked like a charm!

```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Fetching formatador-1.1.0.gem
Fetching fog-core-2.3.0.gem
Fetching fog-xml-0.1.4.gem
Fetching fog-json-1.2.0.gem
Fetching fog-libvirt-0.11.0.gem
Fetching diffy-3.4.2.gem
Fetching vagrant-libvirt-0.12.1.gem
Installed the plugin 'vagrant-libvirt (0.12.1)'!
```

The only thing, I needed to recreate my machine since it gave this error on vagrant up:

```
==> generic-ubuntu20: Updating domain definition due to configuration change
==> generic-ubuntu20: Error when updating domain settings: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
Error while creating domain: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
```

**Comment by mthbrown** [comment] 2023-06-10 09:16
@gentooise Doesn't work on Fedora 37. The first parts work including the ```vagrant plugin install vagrant-libvirt``` but trying any other command after that such as ```vagrant destroy``` or ```vagrant up``` results in:

```
<internal:/opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0 - /home/o/.vagrant.d/gems/3.1.4/gems/ruby-libvirt-0.8.0/lib/_libvirt.so (LoadError)
```

**Comment by chrisroberts** [comment] 2023-06-13 22:28
@mthbrown Thanks for reporting the issue you encountered. I've been able to adjust the build in hashicorp/vagrant-installers#282 to get things linking correctly.

**Closed** 2023-06-13 22:29 UTC
Labels: installer, duplicate
