### ISSUE TITLE
Vagrant Cloud Web UI no longer shows provider dropdown menu when submitting boxes

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10466] opened 2018-11-29 23:01 UTC
Vagrant Cloud recently stopped presenting a dropdown menu for provider name when uploading boxes via the Web UI. So it's hard to get the provider name exactly right.

Safari / macOS Mojave.

**Comment by briancain** [comment] 2019-07-08 21:28
Hey there,

I am going to close this as I cannot reproduce it. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by briancain** 2019-07-08 21:28 UTC
Labels: vagrant cloud, website
