### ISSUE TITLE
Trigger does not run inline script

### ISSUE THREAD

**Issue by sparris9** [hashicorp/vagrant#10105] opened 2018-08-09 14:38 UTC
### Vagrant version
2.1.2

### Host operating system
Windows 10

### Guest operating system
hashicorp/precise64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

MESSAGE='Hi, Mom!'

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise64"
  
    config.trigger.before :up do |trigger|
        trigger.info = "Unmounting Samba share..."
        trigger.run = {:inline => "echo #{MESSAGE}"}
    end
end
```

### Debug output
https://gist.github.com/sparris9/8c86d567e66daf2754bc680089f66662

### Expected behavior
Vagrant should successfully run the command.

### Actual behavior
Some message about `Unable to find type`

### Steps to reproduce
1. `vagrant up`

### References
Are there any other GitHub issues (open or closed) that should be linked here?

I did not search.

**Comment by briancain** [comment] 2018-08-09 16:02
This is a duplicate of #10099. Thanks for opening an issue!

**Closed by briancain** 2018-08-09 16:02 UTC
