### ISSUE TITLE
 master: curl: (22) The requested URL returned error: 500 The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.

### ISSUE THREAD

**Issue by abdelghanimeliani** [hashicorp/vagrant#13099] opened 2023-02-27 13:02 UTC
i m trying now up my vagrant envirement using the **2.3.4** and im geting the folowing message 

![image](https://user-images.githubusercontent.com/62490938/221567750-aef2a8a1-4a2d-49da-b912-bd102f61c917.png)
im using the following repo config and scripts : https://github.com/techiescamp/vagrant-kubeadm-kubernetes 

**NB : the cluster was working fine yesterday with an older version **

the complete output is the folowing : 

``` log
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node01' up with 'virtualbox' provider...
==> master: Box 'bento/ubuntu-22.04' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
==> master: Loading metadata for box 'bento/ubuntu-22.04'
    master: URL: https://vagrantcloud.com/bento/ubuntu-22.04
==> master: Adding box 'bento/ubuntu-22.04' (v202212.11.0) for provider: virtualbox
    master: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-22.04/versions/202212.11.0/providers/virtualbox.box
==> master: Successfully added box 'bento/ubuntu-22.04' (v202212.11.0) for 'virtualbox'!
==> master: Importing base box 'bento/ubuntu-22.04'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'bento/ubuntu-22.04' version '202212.11.0' is up to date...
==> master: Setting the name of the VM: pfecluster_master_1677501656717_50498
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2222 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: vagrant
    master: SSH auth method: private key
    master: Warning: Remote connection disconnect. Retrying...
    master: Warning: Connection reset. Retrying...
    master: 
    master: Vagrant insecure key detected. Vagrant will automatically replace
    master: this with a newly generated keypair for better security.
    master: 
    master: Inserting generated public key within guest...
    master: Removing insecure key from the guest if it's present...
    master: Key inserted! Disconnecting and reconnecting using new SSH key...
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
    master: The guest additions on this VM do not match the installed version of
    master: VirtualBox! In most cases this is fine, but in rare cases it can
    master: prevent things such as shared folders from working properly. If you see
    master: shared folder errors, please make sure the guest additions within the
    master: virtual machine match the version of VirtualBox you have installed on
    master: your host and reload your VM.
    master: 
    master: Guest Additions Version: 6.1.40
    master: VirtualBox Version: 7.0
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Mounting shared folders...
    master: /vagrant => /home/abdelghani/Bureau/pfe_projects/pfecluster
==> master: Running provisioner: shell...
    master: Running: inline script
    master: Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
    master: Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
    master: Get:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [107 kB]
    master: Get:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
    master: Get:5 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [899 kB]
    master: Get:6 http://us.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [197 kB]
    master: Get:7 http://us.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [624 kB]
    master: Get:8 http://us.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [96.3 kB]
    master: Get:9 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [856 kB]
    master: Get:10 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [164 kB]
    master: Get:11 http://us.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [9,672 B]
    master: Get:12 http://us.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [3,260 B]
    master: Get:13 http://us.archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [40.7 kB]
    master: Get:14 http://us.archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [9,800 B]
    master: Get:15 http://us.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [19.5 kB]
    master: Get:16 http://us.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [14.0 kB]
    master: Get:17 http://us.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [644 kB]
    master: Get:18 http://us.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [134 kB]
    master: Get:19 http://us.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [582 kB]
    master: Get:20 http://us.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [90.4 kB]
    master: Get:21 http://us.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [678 kB]
    master: Get:22 http://us.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [105 kB]
    master: Get:23 http://us.archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4,960 B]
    master: Get:24 http://us.archive.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [996 B]
    master: Fetched 5,509 kB in 5s (1,094 kB/s)
    master: Reading package lists...
==> master: Running provisioner: shell...
    master: Running: /tmp/vagrant-shell20230227-98393-p5cc2n.sh
    master: + sudo mkdir /etc/systemd/resolved.conf.d/
    master: + cat
    master: + sudo tee /etc/systemd/resolved.conf.d/dns_servers.conf
    master: [Resolve]
    master: DNS=8.8.8.8 1.1.1.1
    master: + sudo systemctl restart systemd-resolved
    master: + sudo swapoff -a
    master: + crontab -l
    master: + crontab -
    master: + echo '@reboot /sbin/swapoff -a'
    master: + sudo apt-get update -y
    master: Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
    master: Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
    master: Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
    master: Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
    master: Reading package lists...
    master: ++ echo 1.26.1-00
    master: ++ grep -oE '[0-9]+\.[0-9]+'
    master: + VERSION=1.26
    master: + sudo tee /etc/modules-load.d/crio.conf
    master: + cat
    master: overlay
    master: br_netfilter
    master: + sudo modprobe overlay
    master: + sudo modprobe br_netfilter
    master: + cat
    master: + sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
    master: net.bridge.bridge-nf-call-iptables  = 1
    master: net.ipv4.ip_forward                 = 1
    master: net.bridge.bridge-nf-call-ip6tables = 1
    master: + sudo sysctl --system
    master: * Applying /etc/sysctl.d/10-console-messages.conf ...
    master: kernel.printk = 4 4 1 7
    master: * Applying /etc/sysctl.d/10-ipv6-privacy.conf ...
    master: net.ipv6.conf.all.use_tempaddr = 2
    master: net.ipv6.conf.default.use_tempaddr = 2
    master: * Applying /etc/sysctl.d/10-kernel-hardening.conf ...
    master: kernel.kptr_restrict = 1
    master: * Applying /etc/sysctl.d/10-magic-sysrq.conf ...
    master: kernel.sysrq = 176
    master: * Applying /etc/sysctl.d/10-network-security.conf ...
    master: net.ipv4.conf.default.rp_filter = 2
    master: net.ipv4.conf.all.rp_filter = 2
    master: * Applying /etc/sysctl.d/10-ptrace.conf ...
    master: kernel.yama.ptrace_scope = 1
    master: * Applying /etc/sysctl.d/10-zeropage.conf ...
    master: vm.mmap_min_addr = 65536
    master: * Applying /usr/lib/sysctl.d/50-default.conf ...
    master: kernel.core_uses_pid = 1
    master: net.ipv4.conf.default.rp_filter = 2
    master: net.ipv4.conf.default.accept_source_route = 0
    master: sysctl: setting key "net.ipv4.conf.all.accept_source_route": Invalid argument
    master: net.ipv4.conf.default.promote_secondaries = 1
    master: sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
    master: net.ipv4.ping_group_range = 0 2147483647
    master: net.core.default_qdisc = fq_codel
    master: fs.protected_hardlinks = 1
    master: fs.protected_symlinks = 1
    master: fs.protected_regular = 1
    master: fs.protected_fifos = 1
    master: * Applying /usr/lib/sysctl.d/50-pid-max.conf ...
    master: kernel.pid_max = 4194304
    master: * Applying /etc/sysctl.d/99-kubernetes-cri.conf ...
    master: net.bridge.bridge-nf-call-iptables = 1
    master: net.ipv4.ip_forward = 1
    master: net.bridge.bridge-nf-call-ip6tables = 1
    master: * Applying /usr/lib/sysctl.d/99-protect-links.conf ...
    master: fs.protected_fifos = 1
    master: fs.protected_hardlinks = 1
    master: fs.protected_regular = 2
    master: fs.protected_symlinks = 1
    master: * Applying /etc/sysctl.d/99-sysctl.conf ...
    master: * Applying /etc/sysctl.conf ...
    master: + cat
    master: + sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    master: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /
    master: + sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.26.list
    master: + cat
    master: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/ /
    master: + curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/Release.key
    master: + sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add -
    master:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    master:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  1093  100  1093    0     0   2271      0 --:--:-- --:--:-- --:--:--  2267
    master: OK
    master: + sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add -
    master: + curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key
    master:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    master:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  1093  100  1093    0     0   5951      0 --:--:-- --:--:-- --:--:--  5972
    master: OK
    master: + sudo apt-get update
    master: Get:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04  InRelease [1,632 B]
    master: Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease
    master: Get:3 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  InRelease [1,639 B]
    master: Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
    master: Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
    master: Get:6 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04  Packages [1,796 B]
    master: Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
    master: Get:8 https://downloadcontent2.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  Packages [7,901 B]
    master: Fetched 13.0 kB in 1s (17.2 kB/s)
    master: Reading package lists...
    master: + sudo apt-get install cri-o cri-o-runc -y
    master: Reading package lists...
    master: Building dependency tree...
    master: Reading state information...
    master: The following additional packages will be installed:
    master:   conmon containers-common
    master: Suggested packages:
    master:   containernetworking-plugins
    master: The following NEW packages will be installed:
    master:   conmon containers-common cri-o cri-o-runc
    master: 0 upgraded, 4 newly installed, 0 to remove and 67 not upgraded.
    master: Need to get 36.6 MB of archives.
    master: After this operation, 149 MB of additional disk space will be used.
    master: Get:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04  cri-o 1.26.1~0 [33.5 MB]
    master: Get:2 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  conmon 100:2.1.2~0 [34.3 kB]
    master: Get:3 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  containers-common 100:1-22 [52.5 kB]
    master: Get:4 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  cri-o-runc 1.0.1~2 [2,955 kB]
    master: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    master: Fetched 36.6 MB in 24s (1,538 kB/s)
    master: Selecting previously unselected package conmon.
(Reading database ... 44068 files and directories currently installed.)
    master: Preparing to unpack .../conmon_100%3a2.1.2~0_amd64.deb ...
    master: Unpacking conmon (100:2.1.2~0) ...
    master: Selecting previously unselected package containers-common.
    master: Preparing to unpack .../containers-common_100%3a1-22_all.deb ...
    master: Unpacking containers-common (100:1-22) ...
    master: Selecting previously unselected package cri-o.
    master: Preparing to unpack .../cri-o_1.26.1~0_amd64.deb ...
    master: Unpacking cri-o (1.26.1~0) ...
    master: Selecting previously unselected package cri-o-runc.
    master: Preparing to unpack .../cri-o-runc_1.0.1~2_amd64.deb ...
    master: Unpacking cri-o-runc (1.0.1~2) ...
    master: Setting up cri-o-runc (1.0.1~2) ...
    master: Setting up conmon (100:2.1.2~0) ...
    master: Setting up containers-common (100:1-22) ...
    master: Setting up cri-o (1.26.1~0) ...
    master: Processing triggers for man-db (2.10.2-1) ...
    master: 
    master: Running kernel seems to be up-to-date.
    master: 
    master: No services need to be restarted.
    master: 
    master: No containers need to be restarted.
    master: 
    master: No user sessions are running outdated binaries.
    master: 
    master: No VM guests are running outdated hypervisor (qemu) binaries on this host.
    master: + sudo systemctl daemon-reload
    master: + sudo systemctl enable crio --now
    master: Created symlink /etc/systemd/system/cri-o.service → /lib/systemd/system/crio.service.
    master: Created symlink /etc/systemd/system/multi-user.target.wants/crio.service → /lib/systemd/system/crio.service.
    master: CRI runtime installed susccessfully
    master: + echo 'CRI runtime installed susccessfully'
    master: + sudo apt-get update
    master: Get:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04  InRelease [1,632 B]
    master: Get:2 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  InRelease [1,639 B]
    master: Hit:3 http://us.archive.ubuntu.com/ubuntu jammy InRelease
    master: Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
    master: Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
    master: Hit:6 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
    master: Fetched 3,271 B in 1s (5,827 B/s)
    master: Reading package lists...
    master: + sudo apt-get install -y apt-transport-https ca-certificates curl
    master: Reading package lists...
    master: Building dependency tree...
    master: Reading state information...
    master: ca-certificates is already the newest version (20211016ubuntu0.22.04.1).
    master: ca-certificates set to manually installed.
    master: The following NEW packages will be installed:
    master:   apt-transport-https
    master: The following packages will be upgraded:
    master:   curl libcurl4
    master: 2 upgraded, 1 newly installed, 0 to remove and 65 not upgraded.
    master: Need to get 484 kB of archives.
    master: After this operation, 169 kB of additional disk space will be used.
    master: Get:1 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.8 [1,506 B]
    master: Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.7 [193 kB]
    master: Get:3 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.7 [289 kB]
    master: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    master: Fetched 484 kB in 2s (290 kB/s)
    master: Selecting previously unselected package apt-transport-https.
(Reading database ... 44146 files and directories currently installed.)
    master: Preparing to unpack .../apt-transport-https_2.4.8_all.deb ...
    master: Unpacking apt-transport-https (2.4.8) ...
    master: Preparing to unpack .../curl_7.81.0-1ubuntu1.7_amd64.deb ...
    master: Unpacking curl (7.81.0-1ubuntu1.7) over (7.81.0-1ubuntu1.6) ...
    master: Preparing to unpack .../libcurl4_7.81.0-1ubuntu1.7_amd64.deb ...
    master: Unpacking libcurl4:amd64 (7.81.0-1ubuntu1.7) over (7.81.0-1ubuntu1.6) ...
    master: Setting up apt-transport-https (2.4.8) ...
    master: Setting up libcurl4:amd64 (7.81.0-1ubuntu1.7) ...
    master: Setting up curl (7.81.0-1ubuntu1.7) ...
    master: Processing triggers for man-db (2.10.2-1) ...
    master: Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
    master: 
    master: Running kernel seems to be up-to-date.
    master: 
    master: No services need to be restarted.
    master: 
    master: No containers need to be restarted.
    master: 
    master: No user sessions are running outdated binaries.
    master: 
    master: No VM guests are running outdated hypervisor (qemu) binaries on this host.
    master: + sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    master: curl: (22) The requested URL returned error: 500
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.```

**Comment by soapy1** [comment] 2023-02-27 16:08
Hey there, taking a look at the error it looks like the problem is in the script being used to provision the machine. Trying to follow the link to https://packages.cloud.google.com/apt/doc/apt-key.gpg on my browser I also get a 500 error. It looks like the offending line in the provision script is https://github.com/techiescamp/vagrant-kubeadm-kubernetes/blob/f9fd18e1b6dd8e97c71758ff6da25d4f2f558813/scripts/common.sh#L69. 

Since this isn't a bug with Vagrant, I'm going to go ahead and close this issue. For general usage question please check out our discuss forum https://discuss.hashicorp.com/c/vagrant/24. Thanks!

**Closed by soapy1** 2023-02-27 16:08 UTC
Labels: waiting-intake
