### ISSUE TITLE
Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by phpSign110** [hashicorp/vagrant#12229] opened 2021-03-11 07:43 UTC
C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/childprocess-4.0.0/lib/childprocess/windows/process_builder.rb:44:in `encode!': "\xE5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE (Encoding::UndefinedConversionError)

**Comment by soapy1** [comment] 2021-03-11 20:51
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by phpSign110** [comment] 2021-03-12 10:12
电脑系统：window10 
vagrant version 2.2.14
E:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/childprocess-4.0.0/lib/childprocess/windows/process_builder.rb:44:in `encode!': "\xE5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE (Encoding::UndefinedConversionError)

**Comment by soapy1** [comment] 2021-03-12 16:14
This looks like it might be a duplicate of https://github.com/hashicorp/vagrant/issues/11431.
As mentioned in that issue, are you able to set `VAGRANT_HOME` to a path that does not have special characters as a workaround?

**Comment by soapy1** [comment] 2021-03-18 17:34
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Closed by soapy1** 2021-03-18 17:34 UTC
