### ISSUE TITLE
No docker-compose found on `force_host_vm` and `compose` options set to true

### ISSUE THREAD

**Issue by weynhamz** [hashicorp/vagrant#8823] opened 2017-07-26 19:10 UTC
The documentation of the docker provider states it will start a boot2docker vm when under Mac/Win if `force_host_vm` set to true, but when it sets to true on Win and with `compose` option also true, it just dies with no docker-compose found, should docker-compose be automatically installed at this situation, or is there a way to make it work?

**Comment by setpill** [comment] 2018-06-22 14:24
Getting the same error on vagrant 2.1.1.

Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.force_host_vm = true
    d.compose = true
  end
end
```

Error:
```
Vagrant has been instructed to use to use the Compose driver for the
Docker plugin but was unable to locate the `docker-compose` executable.
Ensure that `docker-compose` is installed and available on the PATH.
```

Seems the merged PR did not catch the combination of options correctly (or there has been a regression since).

In either case, would love to see this combination actually work.

**Comment by jbonhag** [comment] 2020-04-03 20:47
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Closed by jbonhag** 2020-04-03 20:47 UTC
Labels: enhancement, provider/docker

**Comment by setpill** [comment] 2020-04-06 08:10
How is this a feature request? It does not work as documented, that's a bug, no?
