### ISSUE TITLE
virtualbox provider not working

### ISSUE THREAD

**Issue by rememberthebear** [hashicorp/vagrant#11275] opened 2019-12-20 15:28 UTC
After updating my virtualbox application to the latest version, the vagrant virtualbox provider has stopped working.  For some reason, when attempting to spin up a box using the virtualbox provider, the output from vagrant seems to indicate that vagrant is attempting to use the hyper-v provider instead, despite the fact that the vagrantfile specifically specifies using the virtualbox provider.

![image](https://user-images.githubusercontent.com/52605714/71265101-84f1a080-2313-11ea-8e1d-86db2c4d71b2.png)

### Vagrant version
vagrant -v
Vagrant 2.2.6

### Host operating system
Windows 10 1909 x64

### Guest operating system
windows server 2012 R2

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
config.vm.provider :virtualbox do |v, override|
    # Show the GUI
    v.gui = true
    # 4GB RAM
    v.customize ["modifyvm", :id, "--memory", "4096"]
    # 2 CPUs
    v.customize ["modifyvm", :id, "--cpus", "2"]
    # Video RAM is 32 MB
    v.customize ["modifyvm", :id, "--vram", 32]
    # For better DNS resolution
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # No audo
    v.customize ["modifyvm", :id, "--audio", "none"]
    # Clipboard enabled
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
    # For performance
    v.customize ["modifyvm", :id, "--usb", "off"]
    # Huge performance gain here
    v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
  end
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.box_check_update = true
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 500
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 5985, host: 55985
  config.vm.synced_folder ".", "C:/vagrant", type: "smb"
end
```

### Debug output

https://gist.githubusercontent.com/rememberthebear/ee23f3cf5cfde1b055923c87168ec83c/raw/bc8cb20c6357a8320f247c85547d8ccc57b5b28b/debug.log

### Expected behavior
Vagrant should build the vm using the virutalbox provider

### Actual behavior
Vagrant tries to build the vm using the hyper-v provider, but since the hyper-v feature is not installed on the computer, it fails.

### Steps to reproduce
1. make sure you have the latest version of virtualbox installed
2. run vagrant up against a vagrantfile which uses the virtualbox provider

**Comment by KayakinKoder** [comment] 2019-12-20 15:45
Try this:

`vagrant up --provider=virtualbox`

**Comment by rememberthebear** [comment] 2019-12-20 15:51
@KayakinKoder I have no problem trying this, but, considering the fact that, as you can see in the posted vagrantfile, the virtualbox provider is the only defined provider, shouldn't vagrant automatically default to the virtualbox provider?

**Comment by KayakinKoder** [comment] 2019-12-20 15:53
Probably. Why not try it and see if you get any new info, instead of asking another question first?

**Comment by rememberthebear** [comment] 2019-12-20 15:56
I will, but take a look at this snippet from the gist file I have linked to.  According to this, it looks like vagrant does actually try to use the virtualbox provider, but I am not sure how to interpret this:

```
DEBUG base: Windows, checking for VBoxManage on PATH first

DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage

DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\

 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe

 INFO subprocess: Starting process: ["C:/Program 
Files/Oracle/VirtualBox/VBoxManage.exe", "--version"]

 INFO subprocess: Command not in installer, restoring original environment...

DEBUG subprocess: Selecting on IO

DEBUG subprocess: stdout: 6.1.0r135406

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0

DEBUG meta: Finding driver for VirtualBox version: 6.1.0

DEBUG environment: Initial usable provider list: [[4, :hyperv]]

DEBUG environment: Priority sorted usable provider list: [:hyperv]

DEBUG environment: Preferred provider list: []

DEBUG environment: Using provider `hyperv` as it is the highest priority in 
the usable list.

DEBUG base: Windows, checking for VBoxManage on PATH first

DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage

DEBUG base: VBOX_INSTALL_PATH value: C:\Program Files\Oracle\VirtualBox\

 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe

DEBUG meta: Finding driver for VirtualBox version: 6.1.0

DEBUG environment: Initial usable provider list: [[4, :hyperv]]

DEBUG environment: Priority sorted usable provider list: [:hyperv]

DEBUG environment: Preferred provider list: []

DEBUG environment: Using provider `hyperv` as it is the highest priority in 
the usable list.

 INFO loader: Set "43687320_machine_default" = []

 INFO loader: Loading configuration in order: [:home, :root, 
"43687320_machine_default"]

DEBUG loader: Loading from: root (cache)

DEBUG loader: Configuration loaded successfully, finalizing and returning

DEBUG push: finalizing

 INFO box_collection: Box not found: mwrock/Windows2012R2 (hyperv)

 WARN vagrantfile: Failed to locate mwrock/Windows2012R2 with version 
 WARN vagrantfile: Performing lookup with inital values mwrock/Windows2012R2 
with version 

 INFO box_collection: Box not found: mwrock/Windows2012R2 (hyperv)

 INFO box_collection: Box not found: mwrock/Windows2012R2 (hyperv)

```

The part that I found the most interesting was the part that says **DEBUG environment: Using provider `hyperv` as it is the highest priority in the usable list.**

**Comment by rememberthebear** [comment] 2019-12-20 16:00
So, specifically specifying the provider does actually work.  But that is more of a workaround than a fix.  I know that vagrant used to be able to correctly determine and use the provider defined in the vagrantfile.  Now, as far as virtualbox is concerned, that is no longer the case.  But, to be clear, specifically designating the provider in the console when calling vagrant up DOES work,

**Comment by KayakinKoder** [comment] 2019-12-20 16:06
What's the output of the command I suggested you run?

**Comment by chrisroberts** [comment] 2019-12-20 16:31
Support for VirtualBox 6.1 has not shipped yet and will be included in the next release. Downgrading VirtualBox to 6.0.x until the next release is available will resolve this issue.

Cheers!

Duplicate of #11249

**Closed by chrisroberts** 2019-12-20 16:31 UTC

**Comment by zensunni** [comment] 2019-12-23 17:30
Do we know when the new release will be available? Even a rough granularity such as days/weeks/months is helpful.

**Comment by chrisroberts** [comment] 2020-01-09 22:28
@zensunni https://github.com/hashicorp/vagrant/issues/11276#issuecomment-572786139
