### ISSUE TITLE
ansible_local's pip installer has a hardcoded curl get_pip.py piped to python

### ISSUE THREAD

**Issue by chadswen** [hashicorp/vagrant#9584] opened 2018-03-16 17:11 UTC
When the `ansible_local` provisioner configures `ansible.install_mode = pip` this command is invoked: https://github.com/hashicorp/vagrant/blob/cb61497ad61873653a8042da4293dea06dffc545/plugins/provisioners/ansible/cap/guest/pip/pip.rb#L23

Piping curl into python with a static command prevents me from setting [get_pip.py args](https://pip.pypa.io/en/stable/installing/#get-pip-py-options). In my case I need to set a proxy, but I don't want to set a proxy for the entire provisioner as that causes issues when running certain playbooks. As far as I can tell there's no way to set a proxy for only the ansible install phase of the provisioner.

As a workaround, I use a shell provisioner to install pip manually with my custom get_pip.py args before `ansible_local` runs, but I still have to wait for `ansible_local`'s static curl | python command to timeout on every install which is fairly annoying. I would use the package manger ansible install_mode, but my ansible playbooks require specific ansible versions and you can only target an ansible version with the pip install_mode.

### Vagrant version
Vagrant 2.0.2

**Comment by gildegoma** [comment] 2018-03-19 07:51
@chadswen Thank you for reporting this use case. The (Ansible) provisioners are not aiming at supporting any use case, and for "advanced/complex" situations we need try to find the [adequate balance](https://github.com/hashicorp/vagrant/issues/3396) (code complexity, ROI, Vagrant flexibility for customization, etc.).

> In my case I need to set a proxy, but I don't want to set a proxy for the entire provisioner as that causes issues when running certain playbooks.

Running behind a proxy is typically subject to variance and somehow hard to fully cover by relying on standard configuration capabilities (for instance the Docker provisioner also installs with hardcoded `curl` commands).

So, you did the right thing with implementing your own ansible setup via a shell provisioner:

> As a workaround, I use a shell provisioner to install pip manually with my custom get_pip.py args before ansible_local runs, but I still have to wait for ansible_local's static curl | python command to timeout on every install which is fairly annoying.

Now, to avoid this useless and annoying wait, you can configure the `ansible_local` provisioner to **not install** ansible by setting the [install option](https://www.vagrantup.com/docs/provisioning/ansible_local.html#install) to `false`. The provisioner will then only verify that the expected version is available.

Please let me know if this solution works for you and if you agree to close this issue (i.e. no feature request). Thanks!

**Comment by chadswen** [comment] 2018-03-19 22:30
@gildegoma I am actually using the ansible installer as it is working just fine with `ansible.pip_args` configured. It installs the specific version of ansible as required by my playbook and I'd hate to stop using that feature.

My only problem is that there is no way to set args when ansible_local installs *pip*, not when it installs ansible.

**Comment by gildegoma** [comment] 2018-03-20 14:01
The issue is quite clear to me, and I do appreciate that the existing features are used ;-)

> that feature saves me from rewriting a fair amount of code with a shell provisioner

I guess it shouldn't be that large (e.g. `pip install ...`), but I ear your "frustration" to be _so close_.

@chadswen what would be your proposal to resolve this?

I would propose to introduce a new `pip_install_command` option, with 
`"curl https://bootstrap.pypa.io/get-pip.py | sudo python"` as default. 
What do you think? Interested to work on it?

**Comment by chadswen** [comment] 2018-03-21 00:09
@gildegoma That solution would work quite well. I can't volunteer to work on it right now, but perhaps in the future if it isn't picked up.

Thanks!

**Closed** 2019-04-09 22:12 UTC
Labels: enhancement, needs-community-help, provisioner/ansible_local, task-small, thinking
