### ISSUE TITLE
wrong entry in /etc/hosts file

### ISSUE THREAD

**Issue by dthpulse** [hashicorp/vagrant#11317] opened 2020-01-13 16:38 UTC
since Vagrant version 2.2.6 vagrant creates wrong entry on very first line in /etc/hosts:

> 127.0.0.1  myserver1.domain myserver1

**Comment by briancain** [comment] 2020-01-13 17:17
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by dthpulse** [comment] 2020-01-13 18:51
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

Vagrant 2.2.6

### Host operating system
NAME="openSUSE Tumbleweed"
VERSION="20200107"

### Guest operating system
NAME="SLES"
VERSION="15-SP2"

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = 'kvm'
        libvirt.host = 'localhost'
        libvirt.uri = 'qemu:///system'
        libvirt.memory = '2048'
        libvirt.cpus = '1'
        libvirt.storage_pool_name = 'default'
        libvirt.memory = '4096'
        libvirt.cpus = '2'
    end
    config.vm.hostname = 'tester'
    config.vm.box = 'sle15sp1'
    config.vm.network :private_network, :ip => "192.168.122.110"
end
```

### Debug output
https://gist.github.com/dthpulse/71790e4d51c82596738197fcf73b062c

### Expected behavior
VM is created. 
There shouldn't be entry 
> 127.0.0.1       tester  tester

in /etc/hosts file


### Actual behavior
Command `head -1 /etc/hosts` will return

> 127.0.0.1       tester  tester


### Steps to reproduce
1. use Vagrantfile I provided
2. deploy VM by command `vagrant up`

**Comment by briancain** [comment] 2020-01-13 18:54
Hey there @dthpulse - Thanks for the information.

According to the debug gist you shared, your `/etc/hosts` file is being updated because you have installed a third party plugin, `vagrant-hostsupdater`, which is updating that file for you. From the debug log:

```
INFO warden: Calling IN action: #<VagrantPlugins::HostsUpdater::Action::UpdateHosts:0x00007fb108144310>
INFO interface: info: [vagrant-hostsupdater] Checking for host entries
INFO interface: info: ==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Checking for host entries
INFO interface: info: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
INFO interface: info: ==> default: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> default: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
INFO interface: info: [vagrant-hostsupdater]   192.168.122.110  tester  # VAGRANT: 48854fa53ce91216dbaa9354ddedf2b7 (default) / a756a37f-765c-4bdc-837c-681a5846f244
INFO interface: info: ==> default: [vagrant-hostsupdater]   192.168.122.110  tester  # VAGRANT: 48854fa53ce91216dbaa9354ddedf2b7 (default) / a756a37f-765c-4bdc-837c-681a5846f244
==> default: [vagrant-hostsupdater]   192.168.122.110  tester  # VAGRANT: 48854fa53ce91216dbaa9354ddedf2b7 (default) / a756a37f-765c-4bdc-837c-681a5846f244
INFO interface: info: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
INFO interface: info: ==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
```

Uninstalling that third party plugin will resolve your issue. If you think there's a bug with that plugin, I recommend opening an issue with that repo instead. Thanks!

**Comment by dthpulse** [comment] 2020-01-13 19:28
Have you read carefully my report? 
I was speaking about entry in /etc/hosts file in VM (guest) not on host. Vagrant-hostupdater is updating hosts file on host not on VM (guest).
Also I quoted exact line from hosts file 

> 127.0.0.1 tester tester

and as you can see in the debug.log this line is not created by vagrant-hostupdater plugin.

Please reopen this bug report and investigate again.

Thank you

**Comment by dthpulse** [comment] 2020-01-13 19:31
here is the issue:

> INFO interface: info: ==> default: Setting hostname...
==> default: Setting hostname...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: change_host_name
DEBUG guest: Checking in: suse
DEBUG guest: Found cap: change_host_name in suse
INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>, "tester"] (suse)
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: getent hosts 'tester' (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 2
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: hostnamectl set-hostname 'tester'
Prepend ourselves to /etc/hosts
grep -w 'tester' /etc/hosts || {
 sed -i'' '1i 127.0.0.1\ttester\ttester' /etc/hosts
}
(sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0

**Comment by dthpulse** [comment] 2020-01-13 19:47
this file is the cause:

/usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/guests/suse/cap/change_host_name.rb


```module VagrantPlugins
  module GuestSUSE
    module Cap
      class ChangeHostName
        def self.change_host_name(machine, name)
          comm = machine.communicate

          if !comm.test("getent hosts '#{name}'", sudo: false)
            basename = name.split(".", 2)[0]
            comm.sudo <<-EOH.gsub(/^ {14}/, '')
              hostnamectl set-hostname '#{basename}'

              # Prepend ourselves to /etc/hosts
              grep -w '#{name}' /etc/hosts || {
                sed -i'' '1i 127.0.0.1\\t#{name}\\t#{basename}' /etc/hosts
              }
            EOH
          end
        end
      end
    end
  end
end
```

**Comment by briancain** [comment] 2020-01-13 19:53
I see, looks to be an issue isolated to SUSE guests. Thanks for the extra info :+1:

**Comment by dthpulse** [comment] 2020-01-13 19:54
It's not only for suse, I see it in the files for all other distros also

**Closed** 2020-06-15 19:29 UTC
Labels: core, enhancement, networking
