### ISSUE TITLE
Missing support for Virtualbox 6.1.0

### ISSUE THREAD

**Issue by myaylaci** [hashicorp/vagrant#11264] opened 2019-12-17 20:21 UTC
### Vagrant version
Vagrant 2.2.6

### VirtualBox version
6.1.0r135406

### Expected behavior
Vagrant should recognize Virtualbox 6.1.0 and start the Vagrant box.

### Actual behavior
An error is raised that the version is not supported and the start is terminated.

### Steps to reproduce
1. Install vagrant 2.2.6
2. Install VirtualBox 6.1.0
3. `vagrant up` any Vagrantfile.

**Comment by chrisroberts** [comment] 2019-12-17 20:46
Duplicate of #11249

**Closed by chrisroberts** 2019-12-17 20:46 UTC

**Comment by myaylaci** [comment] 2019-12-18 08:17
Sorry, I missed that one. I did a search and was surprised that i couldn't find an open issue regarding this topic.

Since I can't comment on #11249 I am writting my comment regarding the changed --clipboard parameter here:

> A customization command failed:
["modifyvm", :id, "--clipboard", "bidirectional"]
The following error was experienced:
#<Vagrant::Errors::VBoxManageError: There was an error while executing VBoxManage, a CLI
used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["modifyvm", "ce8a3576-201c-11ea-978f-2e728ce88125", "--clipboard",
"bidirectional"]

If present, the configuration is also inherited from the basebox's Vagrantfile (~/.vagrant.d/boxes/{group}-VAGRANTSLASH-{repo}/{version}/virtualbox/Vagrantfile). All Baseboxes prepackaged with this config will be broken - a manual fix can be done in the basebox's Vagrantfile though.

**Comment by briancain** [comment] 2019-12-18 15:38
Hi @myaylaci - Vagrant does not use that flag at all any where. That is an issue with the box you are using, not an issue with Vagrant. Thanks!
