### ISSUE TITLE
WinRM error Digest initialization failed.

### ISSUE THREAD

**Issue by salderma** [hashicorp/vagrant#13216] opened 2023-06-22 16:10 UTC
I did a system, VirtualBox, Vagrant update, and vagrant box update (which I tend to do quarterly) on our Vagrant machines which perform CI/CD operations.  I have been using this particular box for quite some time in this manor with no issues.  I have also confirmed the issue arises on a similar machine which uses the libvirt provider instead of virtualbox with a different windows server box that is available for the the libvirt provider.  According to #13076, enabling OpenSSL Legacy Providers should resolve the issue as the newer Default Providers do not include MD4.  This has been done on both host systems, but the results persist.  Below are the full details.

### Debug output

https://gist.github.com/salderma/c56b768868344c27c5e2d930074d224a

### Expected behavior

Vagrant should start the VM with out error, and in more complex cases move on to provisioning and such.

### Actual behavior

Running `vagrant up` produces the following error after booting the VM:
```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:2201
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
An error occurred executing a remote WinRM command.

Shell: Cmd
Command: hostname
Message: Digest initialization failed: initialization error
```

#### Vagrant version

2.3.7-1

Vagrant Source:
- `https://apt.releases.hashicorp.com jammy/main amd64 Packages`

VM Provider:
- VirtualBox 7.0.8r156879

#### Host operating system

Ubuntu 22.04.2 LTS
OpenSSL Providers (per #13076):
```
$ openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.0.2
    status: active
  legacy
    name: OpenSSL Legacy Provider
    version: 3.0.2
    status: active
```

#### Guest operating system

[gusztavvargadr/windows-server (v2102.0.2306)
](https://app.vagrantup.com/gusztavvargadr/boxes/windows-server)

#### Steps to reproduce

1. `vagrant init gusztavvargadr/windows-server`
2. `vagrant up`

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
end
```

**Comment by hedocode** [comment] 2023-06-22 16:12
Same here

**Comment by chrisroberts** [comment] 2023-06-22 16:23
Closing as duplicate of #13211 

See [this comment](https://github.com/hashicorp/vagrant/issues/13211#issuecomment-1601665940) for more information.

Cheers!

**Closed by chrisroberts** 2023-06-22 16:23 UTC
Labels: communicator/winrm, duplicate
