### ISSUE TITLE
Sign /opt/vagrant/embedded/bin/ruby

### ISSUE THREAD

**Issue by envygeeks** [hashicorp/vagrant#9849] opened 2018-05-18 17:20 UTC
* Vagrant version: v2.1.1
* Host operating system: macOS 10.13.4
* Guest operating system: Non-relevant

### Debug output

<img width="862" alt="image" src="https://user-images.githubusercontent.com/99763/40248024-29fffba2-5a94-11e8-9361-2b69cb0ad2c8.png">

```
jordon@Doctor mvp 🐯 (master * u+3) vagrant plugin install vagrant-vmware-desktop 
Installing the 'vagrant-vmware-desktop' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:871:in `send': Host is down - send(2) (Errno::EHOSTDOWN)
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:871:in `send'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:673:in `request'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:529:in `block in fetch_resource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1133:in `block (3 levels) in resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1131:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1131:in `block (2 levels) in resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1130:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1130:in `block in resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1128:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1128:in `resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:520:in `fetch_resource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source.rb:183:in `load_specs'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/bundler.rb:351:in `block in validate_configured_sources!'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/bundler.rb:349:in `validate_configured_sources!'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/bundler.rb:285:in `internal_install'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/bundler.rb:106:in `install'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/action/install_gem.rb:29:in `call'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:275:in `cli'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/bin/vagrant:156:in `<main>'
```

### Expected behavior

Works.

### Actual behavior

The binary is unsigned so LittleSnitch and other tools that are not manually configured will reject the connection, because the Ruby binary provided by Vagrant is unsigned, when it should really be signed if the whole of the app goes through that binary, or even part of it does.

### Steps to reproduce

1. Install Vagrant
1. Install LittleSnitch
1. Watch connection fail
1. Cry a bit 😢

### Notes

I don't know hot Brew does it, but their binaries don't warn for some reason, but I believe just signing the binary will also stop the issue, as the reason for the rejection is the lack of a signature for `/opt/vagrant/embedded/bin/ruby`

**Comment by chrisroberts** [comment] 2018-06-26 22:29
Duplicate of #8278

**Closed by chrisroberts** 2018-06-26 22:29 UTC
Labels: duplicate
