### ISSUE TITLE
SMB mounts

### ISSUE THREAD

**Issue by FarahBoudabous** [hashicorp/vagrant#12360] opened 2021-05-12 07:40 UTC
Hi,
I want to share and mount folders with type SMB but I got this problem:
Vagrant version: 2.2.14
Host OS: Windows
Box: ubuntu/bionic64
And this is the line in the vagrant file of SMB mounts :
config.vm.synced_folder ".", "/var/farah", type: "smb" , smb_password: "vagrant", smb_username: "vagrant", mount_options: ["mfsymlinks","vers=2.0"]
This is the debug output:
==> default: Checking for guest additions in VM...
==> default: Mounting SMB shared folders...
default: C:/Users/boudabou/Desktop/*****/box2 => /var/www/test
Vagrant is currently configured to mount SMB folders with the
mfsymlink option enabled. This is equivalent to adding the
following to your Vagrantfile:

config.vm.synced_folder '/host/path', '/guest/path', type: "smb", mount_options: ['mfsymlink']

This option may be globally disabled with an environment variable:

VAGRANT_DISABLE_SMBMFSYMLINKS=1
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o vers=2.0,credentials=/etc/smb_creds_vgt-96fa08f743a95a0db5af7a30854059c6-cb426b02ca9dbcd1a5e7bb7b4985d549,uid=1000,gid=1000,mfsymlinks,_netdev //10.131.225.244/vgt-96fa08f743a95a0db5af7a30854059c6-cb426b02ca9dbcd1a5e7bb7b4985d549 /var/www/test

The error output from the last command was:

mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)[](url)

**Comment by soapy1** [comment] 2021-05-17 15:24
duplicate of https://github.com/hashicorp/vagrant/issues/12357

**Closed by soapy1** 2021-05-17 15:24 UTC
