### ISSUE TITLE
Vagrant Powershell - cannot exit session

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10085] opened 2018-08-02 23:46 UTC
After running `vagrant powershell`, there's no apparent way to exit the session, short of restarting the host.  There's no documentation on ending the interactive session either.

### Vagrant version
Vagrant 2.1.2
Virtual Box 5.2.16r123759

### Host operating system
Windows 8.1

### Guest operating system
Windows 2016

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "my/windows2016"
end
```

### Expected behavior

Have a way to exit the session.

### Actual behavior

Cannot exit the session.

### Steps to reproduce
1. `vagrant init my/windows2016`
2. `vagrant up`
3. `vagrant powershell`

**Comment by briancain** [comment] 2018-08-06 15:53
Duplicate of #10087. I'm going to go ahead and close this since it looks very similar to the other issue you created. Thanks!

**Closed by briancain** 2018-08-06 15:53 UTC
