### ISSUE TITLE
Vagrent could not detected please rectify my issue

### ISSUE THREAD

**Issue by deva9017** [hashicorp/vagrant#11291] opened 2020-01-04 07:56 UTC
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by deva9017** [comment] 2020-01-04 07:57
$ vagrant up --provider virtualbox
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.

**Comment by dragetd** [comment] 2020-01-06 16:18
VirtualBox 6.1 is not yet supported. Next version will.

And please READ the text that is pre-entered in the issue box and ACT accordingly. Do not simply submit an issue WITH said text!

-> Should be closed.

**Comment by jbonhag** [comment] 2020-01-06 18:13
Hi there,

Support for VirtualBox 6.1 has not shipped yet and will be included in the next release. Downgrading VirtualBox to 6.0.x until the next release is available will resolve this issue.

Cheers!

Duplicate of #11249

**Closed by jbonhag** 2020-01-06 18:13 UTC

**Comment by deva9017** [comment] 2020-01-08 08:12
> VirtualBox 6.1 is not yet supported. Next version will.
> 
> And please READ the text that is pre-entered in the issue box and ACT accordingly. Do not simply submit an issue WITH said text!
> 
> -> Should be closed.

yeah vagrant6.1 not yet released how can you say that i am using 6.1

**Comment by deva9017** [comment] 2020-01-08 08:12
> Hi there,
> 
> Support for VirtualBox 6.1 has not shipped yet and will be included in the next release. Downgrading VirtualBox to 6.0.x until the next release is available will resolve this issue.
> 
> Cheers!
> 
> Duplicate of #11249

i tried with before versions also getting same error

**Comment by dragetd** [comment] 2020-01-08 10:03
Please post the output of the following command:
> vagrant --version ; virtualbox --help ; cat /etc/lsb-release /etc/debian_version ; uname -a

I am unable to help you without this information.

**Comment by DonRichards** [comment] 2020-01-08 12:58
When is the next release scheduled?
