### ISSUE TITLE
Hi.... just I have the same error..  vagrant version: 2.2.3 virtual box version: 6.0  error upon installing: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054 in vagrant version: 2.2.3

### ISSUE THREAD

**Issue by anonymouse703** [hashicorp/vagrant#10672] opened 2019-02-15 01:51 UTC
error upon installing: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

vagrant version: 2.2.3
virtual box version: 6.0

Tried to follow the steps from the same issue but still the problem occurred.

**Comment by briancain** [comment] 2019-02-15 16:25
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by hiralthaker** [comment] 2019-03-02 06:41
Hello all,

I try to install vagrant on my machine from command prompt with command vagrant up and I got this error.

error upon installing: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

vagrant version: 2.2.3
virtual box version: 6.0

Can any one let me know, what is the cause of this?

**Comment by briancain** [comment] 2019-03-26 20:23
Typically when I see this issue it is just a random transient issue connecting to AWS or where ever the box is hosted (potentially related to flaky connections too). Usually retrying fixes it from my experience. Without any more reproduction information from the original reporter I'm going to go ahead and close this issue. If you encounter this issue again please open a new one and be sure to properly fill out all of the information we ask so that we can help you. Thanks!

**Closed by briancain** 2019-03-26 20:23 UTC
Labels: waiting-reply
