### ISSUE TITLE
vagrant up fails on Windows with Virtualbox

### ISSUE THREAD

**Issue by dangerousHobo** [hashicorp/vagrant#12897] opened 2022-09-14 18:39 UTC
### Vagrant version

2.3.0

### Host operating system

Windows 10

### Guest operating system

Ubuntu, box generic/ubuntu2004

### Vagrantfile

```ruby
$default_network_interface = `ip route | awk '/^default/ {printf "%s", $5}'`

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.network "forwarded_port", guest: 9000, host: 9001
  config.vm.network "forwarded_port", guest: 514, host: 9514

  config.vm.network "public_network", bridge: "#$default_network_interface"

  config.vm.synced_folder "data", "/vagrant"
  config.vm.synced_folder "utils", "/utils"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-graylog"
    vb.memory = 2048
    vb.cpus = 2
  end
end
```

### Debug output
https://gist.github.com/dangerousHobo/85c894c713fdf877c83796831c90d3da

### Expected behavior

To boot Ubuntu

### Actual behavior

See gist for error

### Steps to reproduce

1. vagrant up

**Comment by dangerousHobo** [comment] 2022-09-15 13:46
VirtualBox version is 6.1.38

**Comment by dangerousHobo** [comment] 2022-09-22 11:39
I found if I run the VM without the headless option it starts successfully. It seems Windows doesn't like the `--type` to be `headless`.

Fails:
```
C:/Program Files/Oracle/VirtualBox/VBoxManage.exe startvm 5eff5f98-c7f2-4370-a5cf-d5ffd21c1211 --type headless
```

Starts:
```
C:/Program Files/Oracle/VirtualBox/VBoxManage.exe startvm 5eff5f98-c7f2-4370-a5cf-d5ffd21c1211
```

**Comment by skeeith** [comment] 2022-10-02 17:39
I'm having this issue, also 5 of my colleagues too.

Vagrant: `v.2.3.0`
Virtual Box: `v6.1.38`

**Comment by skeeith** [comment] 2022-10-02 17:55
@dangerousHobo have you found any solution? besides on `removing the --type headless`?

This is really a disturbing bug

**Comment by chrisroberts** [comment] 2022-10-03 17:48
Hi there. This issue has come up in the past and is generally related to antivirus software or a bad install of virtualbox on the host.

**Comment by skeeith** [comment] 2022-10-04 04:16
@chrisroberts that's really weird cause I've been using this for the past 5 years and I haven't encountered this before in the last few years. I've also been using the same anti-virus software `(Eset)` for the past 7 years too. I'm also sure that `Virtual Box` is installed properly too, but maybe could you take a look at this? just to be sure?

Is it possible does the have an issues? my box is `Laravel/Homestead v12.2.0`, since I was using `v12.0.0` I didn't have this issue before, it only came up when I upgraded my box to `v12.2.0`

Also, maybe the is  `Virtual Box v6.1.38`? I recall upgrade my `Virtual Box` the same time I upgraded my `box Laravel/Homestead`, BUT I also had a fresh OS installed and fresh `Vagrant` and `Vagrant Box` and still have the same issue.

so I'm guessing the issue is actually `Virtual Box v6.1.38`

**Comment by skeeith** [comment] 2022-10-04 04:25
@chrisroberts btw I can also recall `enabling` `Windows Security` -> `Device Security` -> `Core Isolation`

### Core Isolation - Security features available on your device that use virtualization-based security.
##### Memory Integrity - Prevents attacks from inserting malicious code into high-security processes `ON`.

Does this affect it?

**Comment by skeeith** [comment] 2022-10-07 03:19
@dangerousHobo have you tried downgrading `Virtual Box`? I'm planning to downgrade Virtual Box to see if this fixes the issue

**Comment by skeeith** [comment] 2022-10-16 09:42
@chrisroberts I uninstalled my Eset Anti-virus application and uninstalled Virtual Box v6.1.40 and Vagrant v2.3.1

Restarted my laptop and installed Virtual Box v6.1.40 and Vagrant v2.3.1, still not working properly.

something is really wrong here.

**Comment by skeeith** [comment] 2022-10-16 10:15
> @chrisroberts btw I can also recall `enabling` `Windows Security` -> `Device Security` -> `Core Isolation`
> 
> ### Core Isolation - Security features available on your device that use virtualization-based security.
> ##### Memory Integrity - Prevents attacks from inserting malicious code into high-security processes `ON`.
> Does this affect it?

@chrisroberts @dangerousHobo confirmed this is the configuration that's causing the issue, can you guys look into this one?

turning this `ON` will cause issues on booting up your VM.

**Comment by chrisroberts** [comment] 2022-11-18 01:28
Closing this to track underlying issue in #12955

**Closed by chrisroberts** 2022-11-18 01:28 UTC
Labels: bug, upstream, host/windows, needs-investigation
