### ISSUE TITLE
Timed out while waiting for tha machine to boot.

### ISSUE THREAD

**Issue by fr0ster** [hashicorp/vagrant#11772] opened 2020-07-16 19:15 UTC
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

Vagrant 2.2.7 & VirtualBox 6.1

### Host operating system

Debian 10

### Guest operating system

Debian 10, Ubuntu Bionic/Focal

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
end
```

### Debug output

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/focal64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/focal64' version '20200714.0.0' is up to date...
==> default: Setting the name of the VM: c-c_prj_default_1594925637102_89114
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

### Expected behavior

I hope after vagrant init ubuntu/focal64 && vagrant up && vagrant ssh I got  littlle sandbox with /vagrant synchronized with my project dir

### Actual behavior

I got error about timeout

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### Steps to reproduce

1. vagrant init ubuntu/focal64
2. vagrant up

**Comment by soapy1** [comment] 2020-07-16 19:19
It looks like this is a duplicate of https://github.com/hashicorp/vagrant/issues/11769. There is a [solution](https://github.com/hashicorp/vagrant/issues/11769#issuecomment-659057971) in the issue too 🎉 

>They add this customize command that breaks the box from booting vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]

**Closed by soapy1** 2020-07-16 19:19 UTC

**Comment by fr0ster** [comment] 2020-07-20 08:49
Thanks for respond.
Sorry for steeled time
